### ISSUE TITLE
How do I deploy to server?

### ISSUE THREAD

**Issue by aryanxk02** [potree/potree#1000]
I have set up potree locally and need guidance in the next step.
I am stuck at this point. 

**Deploy to a server**
Simply upload the Potree folderm with all your point clouds, the build directory, and your html files to a web server.
It is not required to install node.js on your webserver. All you need is to host your files online.

**Comment by midnight-dev** [comment]
Can you explain what has you stumped? Uploading files to a server is usually very simple. If you don't have a server, then you do not need to upload anything. Just use it locally.

**Comment by aryanxk02** [comment]
How do I perform the instructions as described under **Deploy to a server**
What it the meaning of point clouds ?? I haven't understood a single thing ;(

**Comment by midnight-dev** [comment]
Point clouds are groups of points that represent spatial data. The points can have X, Y, and Z coordinates and other attributes like color. This data is usually captured with LiDAR scans. 

If you don't know what point clouds are or how to upload files to a server, this project may be too advanced for you.

**Comment by aryanxk02** [comment]
@midnight-dev is there a documentation for potree?? if yes, please send me the link.

**Comment by midnight-dev** [comment]
Unfortunately, there are no longer any docs as far as I know. The readme file visible on the project page is all that there is. It's useful for demos and instructions to get started, but if you want to learn about the inner workings, you'll have to look at the existing example files and search for relevant methods in the JavaScript files.If you use an editor like VS Code, you can open the repo as a workspace and use functions like _find in all files_ to get a better understanding of where some code exists.

There are plenty of issues and pull requests that discuss parts of the codebase. Could always search for specifics like the renderer or area measurement.

@m-schuetz Are any of the older pieces of documentation still relevant for 1.8?
