### ISSUE TITLE
how to reference added object (OBJ/PLY/Mesh) from toolbar - possible?

### ISSUE THREAD

**Issue by azithinkiam** [potree/potree#1006]
Apologies if this is documented somewhere I can't find, but I'm trying to use the toolbar to change the material for an object rather than a point cloud.  

`			for(const pointcloud of viewer.scene.pointclouds){
				pointcloud.material.activeAttributeName = selectedValue;
			}`

is there a similar container for viewer.scene.meshes or can i reference the object directly via viewer.scene.mesh1/mesh2/etc?  over-simplification referencing your examples: I'd effectively like to be able to toggle the bunny color via toolbar.

initial testing has been unsuccessful, but i can't find a reference for these anywhere...

thanks in advance!

-t.

**Comment by mikepianka** [comment]
Sure, try something like this:

![image](https://user-images.githubusercontent.com/47948499/113045290-a8d5a000-916c-11eb-8478-dbef044815a8.png)

**Comment by azithinkiam** [comment]
TY!  traverse/console have been invaluable.
