### ISSUE TITLE
How to modify geometry of potree points

### ISSUE THREAD

**Issue by adoug** [potree/potree#1026]
Hi,

I would like to know if its possible to modify the actuall points geometry. I need to offset each point a certain amount on initial load and also each time the points are updated. I am assuming that I would need to walk the tree structure and for each node update its geometry. I've explored a couple of ways: through pcoGeometry.root.traverse, PointCloudOctree.children, pcoGeometry.root.geometry.setAttribute but not getting the points to update for some reason. What would be the correct approach for doing this?

**Comment by HeadLessHUN** [comment]
do you need to translate specific points or just a whole point cloud?

because you can translate,rotate, apply translation matrix/quaternion on different levels for example you can translate the whole point cloud scene.
https://threejs.org/docs/#api/en/core/Object3D

viewer.scene.scenePointCloud.translate....
viewer.scene.scenePointCloud.rotation.set....

You can do that on loaded pointclouds like below it will translate along z axis 25m and rotate around Z axis by 2 radian 
viewer.scene.pointclouds[0].translateZ(25)
viewer.scene.pointclouds[0].rotateZ(2)

**Comment by adoug** [comment]
Hi,

Thanks, I've tried translation and it works but its not quite what I am after. 

I need to be able to offset each point in Z direction only, like in this example on plas.io

![exaggerate_z](https://user-images.githubusercontent.com/2123392/116540255-43bcc800-a92d-11eb-97ba-cfd4e5ceeef9.gif)

**Comment by HeadLessHUN** [comment]
For me it seems like just a scale on Z axis which can be done similarily...

for example scene wide increase the Z scale by 10.
viewer.scene.scenePointCloud.scale.setZ(10)

**Comment by adoug** [comment]
That would seem like it should do it, but in my case the point cloud points are in ecef coordinates and I need to scale in elevation only, scaling Z in the ecef just pushed them out from the center out. It seems like I need to figure out how to get access to all the points and reproject them to lat long elevation, update elevation then back to ecef then update the geometry.

**Comment by HeadLessHUN** [comment]
It does not that hard. 

firstly translate it to  Z=0 (you can get the current Z coordinate by point picking.) then scale it up.

if you have to keep somewhat real ground coordination then scale it up and calculate the amount needed to translate...

**Comment by adoug** [comment]
Thanks @HeadLessHUN I'll give that a go

**Comment by adoug** [comment]
Modifed vertex position in the vertex shader.

**Comment by midnight-dev** [comment]
Ya know, now that you say it, that seems like the simplest and most efficient method, especially for linear scaling. It's easy to get stuck in a JavaScript-only mindset sometimes. 

Thanks for sharing the update @adoug
