### ISSUE TITLE
Volume Measurement

### ISSUE THREAD

**Issue by SebastianKasan** [potree/potree#1044]
Hi, 

are there any planned updates for volume measurement functions? 

I am looking for a solution to measuring stockpile volumes with irregular shapes. I don't see any sort of this funtionality yet implemented.

I am happy to chip in a few bucks if that helps with development.
Thank you

**Comment by HeadLessHUN** [comment]
Could you show us some example what you really mean, how you would like it to works? do you want to create meshes and then calculate volume of that? 

But i don't think there is any roadmap to implement this type of things currently, because mark is busy doing the new Webgpu based potree which will have far more better performance, then web gl.

**Comment by SebastianKasan** [comment]
Sorry for not being more specific. Think of a pile of gravel on an even or uneven surface. You draw a polygon around the bottom of the pile and calculate the volume above the polygon .
This, I think, requires some sort of mesh calulation beforehand.

I think this has been asked for before and it is a really important feature for anyone doing drone survey.

**Comment by HeadLessHUN** [comment]
I think potree is not meant to do such thing like meshing point cloud, these tasks takes times (not real time calculation), and different configurations, I can only see a version if you click all the points around the pile and then on the (local/global) top of the pile...

But this will need triangulation and a robust calculation. I don't think will be done in the near future.

**Comment by SebastianKasan** [comment]
That is unfortunate, but I understand. Would it be feasible, if a mesh is uploaded by the user? That is a standard of any photogrammetry ouptut anyways....

**Comment by CorentinStauder** [comment]
Hey Sebastian, I need the same tool as you described, have you any kind of additional information? Or maybe are you in the development of it? Any collaboration would be greatly appreciated! ;)

**Comment by SebastianKasan** [comment]
I think I will end up with some sort of tif-viewer.... but I am not pursuing this at the moment. I think Virtual Surveyor offers an online thing....
Other than that, I know there are Caesium-based applications that do that (Trimble has one, Komatsu....) but I dont know of any open-source ones...

**Comment by CorentinStauder** [comment]
Thanks for your help, I’ll watch all this and maybe come up with a solution in a while!
