### ISSUE TITLE
WebGL context lost on Firefox/Chrome in Linux Ubuntu (kernel 5.4)

### ISSUE THREAD

**Issue by h4k1m0u** [potree/potree#1045]
When I manipulate a pointcloud with 73 million points (or even less sometimes) in Potree, Firefox v89 (and also on Chrome) loses WebGL context on Linux Ubuntu (never on Windows, so I suspect it's the drivers) and Potree eventually crashes. This message then appears on the firefox console tab:

`bindVertexArrayOES: Extension is `invalidated``

I'm Ubuntu 20.04 with kernel 5.4 and the GPU driver used is i915.

I was having a GPU hang error (and the computer completely freezing) when I had recent versions of the kernel (5.8 or 5.11) with CloudCompare/meshlab, but it's not happening anymore now with kernel 5.4. However, CloudCompare does freeze temporarily sometimes (though it's not critical). So, I suspect that when the GPU freezes, it causes the webgl context to be lost in the browser and potree web application to crash - [isContextLost](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/isContextLost)

Is there a way to fix that?

**Comment by HeadLessHUN** [comment]
how about memory usage before/during the crash? I think this is more like a memory leak. And the context is lost when the op system run out of memory.

**Comment by h4k1m0u** [comment]
Thanks for your response. I don't think an excessive memory usage has caused it since I have enough RAM (64G) on this machine, and I was looking at htop's graph bars when it happened and didn't see a lot of memory being used there either.

**Comment by geeknik** [comment]
Try going into Firefox's `about:config` and changing `webgl.can-lose-context-in-foreground` from true to false and make sure that `webgl.lose-context-on-memory-pressure` is set to false (default).  Since you have the RAM, you could experiment with increasing `webgl.max-contexts`.  Good luck!

**Comment by h4k1m0u** [comment]
I suspect this issue was caused by faulty drivers on linux (for my Intel's gpu), since it was fixed once a Nvidia GPU was installed on the computer.
