### ISSUE TITLE
PotreeConverter "--List-of-files"

### ISSUE THREAD

**Issue by Cellnator** [potree/potree#1046]
I have a question.
With the Converter 1.6/1.7 it was possible to create a list with data paths from the pointclouds. 
For Example: 
I have one project, but 5 LAS-Pointclouds. For the PotreeWebsite i just want to convert it as one cloud.

In 1.6 it was easy --> --list-of-files "ListPointclouds.txt"

Does it work in 2.1 also?

**Comment by HeadLessHUN** [comment]
no it does not have the list of files, but you can add multiple input or you can add a directory for input.

**Comment by midnight-dev** [comment]
Might not be exactly the same thing, but multiple clouds in an input directory will do the trick and combine into one. Just make sure they are either LAS or LAZ files. 

By the by, can you close the duplicate issue when you get a chance? Seems GitHub made a double post in the repository when you submitted your question.

Edit: It was a duplicate in the converter repo actually. But not the accidental double post that I thought. The one for the converter is more relevant but I guess this one would catch more attention. Up to you if you wanna leave it open.

**Comment by Cellnator** [comment]
THanks :)
