### ISSUE TITLE
Uniform Adaptive Point Sizing Issue

### ISSUE THREAD

**Issue by timodwhit** [potree/potree#1062]
Adaptive point sizes seems to be based on the max depth of the current node you are looking at, this causes problems because the node that you are looking at could have a max depth of 8 where the one next to it might have a max depth of 2. I believe this is considered the Level of Detail or LOD... However, that is a bit of misnomer, as it is is not the actual level of detail, it is the amount of points in the section. The two are distinct since the node might have a large intended empty swath, and be at the same level of detail as another node with a lot points

Issue: 
- Level of Detail should not be the same as the depth of the node
- Level of Detail for a node should be the max-depth of the whole dataset minus the depth of the current node. Example: the dataset has a max-depth of 8, if the current node only has a depth of 6 and has no children, then it would have a LOD of 8, and all parents of the node would increment by the same offset 2.

![image](https://user-images.githubusercontent.com/2761203/128399151-a96bb1b5-df5f-4dc0-a6e6-b4704d450911.png)
![image](https://user-images.githubusercontent.com/2761203/128399286-e06c53cd-31ac-429c-8813-26345f00d887.png)

Here is an example of the logic working using some custom code. I'll try and get a generic PR here soon.

**Comment by timodwhit** [comment]
The example above is not quite right... depth 1 would only be adjusted if depth 6 is the only child

**Comment by m-schuetz** [comment]
Hi, yes, this is quite a bit of an issue. In Potree 2, holes will likely be filled entirely differently with a post-processing pass, which won't have worst-case behaviour as bad as this. Analyzing the density of the neighborhood of each point is also a consideration that could fix this issue.  Thanks for considering a PR, but Potree 2 will be a rewrite so current Potree won't get many more updates.

**Comment by timodwhit** [comment]
Closing this for now.
