### ISSUE TITLE
360 images and sidebar

### ISSUE THREAD

**Issue by Matthieu-Fontaine** [potree/potree#1063]
hi, on my project I have pretty 360 images as in the photo
![Capture](https://user-images.githubusercontent.com/73833231/128717043-2e97e2e0-5895-44fb-bf98-32523d7ffab5.PNG)

![Capture](https://user-images.githubusercontent.com/73833231/128717335-e0e694ae-6a6e-4232-b21c-a4e436990102.PNG)
But in the sidebar, the images do not appear you would have any ideas? I would like which ones to appear to activate or not their display

**Comment by PierreSerpe** [comment]
Hello,

Did you get a solution to solve this problem?

**Comment by Matthieu-Fontaine** [comment]
Hi, in the Image360Loader class you can add it's lines to add the nodes but I'm not sure it's the right one =) Tell me if you find anything else.
`let tree = $(`#jstree_scene`);

this.SideBarPicture = tree.jstree('create_node', "images", { 	 
				"text": "Images360",
				"icon": "../resstruth3d/icons/Picture360.png",
				"data": images360,
			}, "last", false, false);
			
tree.jstree(images.visible ? "uncheck_node" : "check_node", this.SideBarPicture);`

**Comment by PierreSerpe** [comment]
Hi, thanks for comming back to me!
As you can see in the printscreen, there is no submenu with an extra checkbox under "Objects sidebar"
![PotreeViewer-panorama_NoCheckbox](https://user-images.githubusercontent.com/102526566/183486667-eb687e5a-8cb8-4cf9-8f80-6f80d45aeed9.PNG)
 I m not sure where to put the code to get the ability to check/uncheck the 360spheres in the viewer...

Here is the last part of my code:

	async function run(){
			proj4.defs("WGS84", "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs");
			proj4.defs("pointcloud", "+proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 +lon_0=4.367486666666666 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +towgs84=-106.869,52.2978,-103.724,0.3366,-0.457,1.8422,-1.2747 +units=m +no_defs ");
			let transform = proj4("WGS84", "pointcloud");

			let params = {
				transform: transform
			};

			// this file contains coordinates, orientation and filenames of the images:
			// http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/360/Drive2_selection/coordinates.txt
			Potree.Images360Loader.load("../panoramas/carrefour", viewer, params).then( images => {
				viewer.scene.add360Images(images);
			});
			

			viewer.mapView.showSources(false);
		}

			
		
	</script>
	
	
  </body>
</html>

J espere que tu as compris mon message?

**Comment by Matthieu-Fontaine** [comment]
The lines I wrote are to be placed in potree.js or in the Images360Loader file and allows to hide all the images with a node

![image](https://user-images.githubusercontent.com/73833231/183496387-b68d48a4-c704-45a0-8100-75bdd7eecd66.png)

**Comment by PierreSerpe** [comment]
Thank you for showing me the results. It is exactly what I am looking for.
I did try to insert your code at different places in potree.js (under Image360Loader class). However the page do not load anymore (I only see the the loading image with the cat). May I ask you show me where, in code below, i should insert it to make it work?

```
class Images360Loader{

		static async load(url, viewer, params = {}){

			if(!params.transform){
				params.transform = {
					forward: a => a,
				};
			}
			
			let response = await fetch(`${url}/coordinates.txt`);
			let text = await response.text();

			let lines = text.split(/\r?\n/);
			let coordinateLines = lines.slice(1);

			let images360 = new Images360(viewer);

			for(let line of coordinateLines){

				if(line.trim().length === 0){
					continue;
				}

				let tokens = line.split(/\t/);

				let [filename, time, long, lat, alt, course, pitch, roll] = tokens;
				time = parseFloat(time);
				long = parseFloat(long);
				lat = parseFloat(lat);
				alt = parseFloat(alt);
				course = parseFloat(course);
				pitch = parseFloat(pitch);
				roll = parseFloat(roll);

				filename = filename.replace(/"/g, "");
				let file = `${url}/${filename}`;

				let image360 = new Image360(file, time, long, lat, alt, course, pitch, roll);

				let xy = params.transform.forward([long, lat]);
				let position = [...xy, alt];
				image360.position = position;

				images360.images.push(image360);
			}

			Images360Loader.createSceneNodes(images360, params.transform);

			return images360;

		}

		static createSceneNodes(images360, transform){

			for(let image360 of images360.images){
				let {longitude, latitude, altitude} = image360;
				let xy = transform.forward([longitude, latitude]);

				let mesh = new Mesh(sg, sm);
				mesh.position.set(...xy, altitude);
				mesh.scale.set(1, 1, 1);
				mesh.material.transparent = true;
				mesh.material.opacity = 0.75;
				mesh.image360 = image360;
				
				{ // orientation
					var {course, pitch, roll} = image360;
					mesh.rotation.set(
						MathUtils.degToRad(+roll + 90),
						MathUtils.degToRad(-pitch),
						MathUtils.degToRad(-course + 90),
						"ZYX"
					);
				}

				images360.node.add(mesh);

				image360.mesh = mesh;
			}
		}

		

	};
```

**Comment by Jaumen90** [comment]
> Hi, the error is in the _apostrophe_ character.  Because function _add code_ in this forum uses the same character it was removed after adding code in the post. Finally _apostrophe_ character was removed from the right place in the code. This character must be before and after `#jstree_scene` and removed from the end of this part of code: `tree.jstree(images.visible ? "uncheck_node" : "check_node", this.SideBarPicture);`

**Comment by PierreSerpe** [comment]
@Matthieu-Fontaine @Jaumen90 
Thanks for this code. 
However, if i click on the pointcloud to adjust the view, it will focus on the image like if the spheres were visible (Altough spheres a hidden).
![image](https://github.com/potree/potree/assets/102526566/9cfeeb5b-0620-4517-b35e-e7bf2d0acfc3)
