### ISSUE TITLE
PointCloudMaterial problem

### ISSUE THREAD

**Issue by davijo** [potree/potree#107]
Hi,

I'm trying to figure out why I cannot get the different material types to work.
Every time updateShaderSource is called the pointcloud color turns complete black regardless whether I try to use height coloring or intensity/etc. I am experiencing the same problem with the demosets also so it is not because of the pointcloud. 

The default RGB right after loading works fine. The problem occurs when the updateShaderSource is called.
If there are any ideas why this is happening It would be really interesting to hear about them!

Anyways while digging into the code I noticed there is a missing semicolon:
https://github.com/potree/potree/blob/master/src/materials/PointCloudMaterial.js#L555

Though this did not affect the problem itself...

**Comment by m-schuetz** [comment]
Is it also black when you switch to height and back to RGB?
Do you get any errors in the developer tools console? (ctrl + shift + i)
What kind of system do you use? (browser, os, graphics card)

The semicolon at the end of the line is actually optional in javascript but I add them anyway out of habbit. Thanks for pointing it out.

**Comment by davijo** [comment]
Yes, it remains black even after switching back to rgb.

Also while opacity is anything else than 1 the coloring is completely black, but I haven't found the relation to this problem out of this.

System specs: Win7 Pro 64b, Chrome 39, Nvidia K2000m.

**Comment by davijo** [comment]
Mystery solved:
dat.gui value was a string instead of an int and thus the getDefines did not return the correct string.

Thanks for the prompt reply!

Cheers

**Comment by m-schuetz** [comment]
Oh, I see. Is this something that occured with the standard examples? If so, how can I replicate the issue?

**Comment by davijo** [comment]
Not in the standard examples. I don't quite see how dat.gui interprets the value as a string in my code as it is from Potree.PointColorType, but once coverting back to int it seems to be working.
