### ISSUE TITLE
How do I get the original coordinates of the point from point cloud ?

### ISSUE THREAD

**Issue by Shekhrozx** [potree/potree#1073]
I am trying to get the original position information (coordinates) of a point from point cloud data. I have converted the point cloud data of the PLY using Potreeconverter to render the Potree Viewer. But when I try to get the coordinates of a point, it gives a different position from the PLY file. How can I get original positions as same as PLY?

**Comment by Shekhrozx** [comment]
Here are more details about my question.
There are samples rendered by other viewers like Colmap, CloudCompare, Meshlab. The point coordinates are the same for all viewers. But Potree viewer gives different numbers. 

### COLMAP
` coordinates (-14.7601, -8.31308, 17.5154) `
` color (127, 153, 85) `

![colmap](https://user-images.githubusercontent.com/21998080/131072831-6b85915a-f673-48ff-a95f-16eb834bb889.png)

----
### MeshLab
` coordinates (-14.7601, -8.31308, 17.5154) `
` color (127, 153, 85, 255) `

![meshlab](https://user-images.githubusercontent.com/21998080/131072253-286934c7-4932-453c-b43f-548fcc2809ed.png)

----
### CloudCompare
` coordinates (-14.760057, -8.313084, 17.515413) `
` color (127, 153, 85) `

![cc](https://user-images.githubusercontent.com/21998080/131072423-93fba23b-455e-479a-9962-7866c9fc7cd9.png)

-----
### Potree
Here is the result, taken from the Potree viewer. The coordinate is different.

![location](https://user-images.githubusercontent.com/21998080/131072569-41477f0e-b3a0-423a-87e9-68483cf1d61c.png)
![potree](https://user-images.githubusercontent.com/21998080/131072583-a563aba6-5626-451c-ac8c-518fc3245bca.png)


### How can I get the real coordinates of the points?

**Comment by HeadLessHUN** [comment]
Have you tried to convert las/laz files instead of ply?

![image](https://user-images.githubusercontent.com/10095691/131140109-130fed93-59db-4fa7-bb3f-60f887f1c8b6.png)
