### ISSUE TITLE
Resize 360 image spheres 

### ISSUE THREAD

**Issue by SiAryan** [potree/potree#1081]
![image](https://user-images.githubusercontent.com/46550818/134601178-47eb0efe-32a6-440b-a77a-42acecd9ae1e.png)
Is there a way to resize these spheres that represent the loaded 360 images ?

**Comment by HeadLessHUN** [comment]
yes there is. you will need to create a function to scale up/down the spheres in the 360 images class. possible solution is to add a default value. and create a getter/setter function. i'm not be able to show a solution because i'm not at home.

you will need to set the scale like this


```
this.images.map(image360=>{
      image360.mesh.scale.set(100,100,100)
}
```
