### ISSUE TITLE
Tree checkbox

### ISSUE THREAD

**Issue by Matthieu-Fontaine** [potree/potree#1082]
Hi, I'm starting to understand not too badly how the tree works however I would like your help on how inheritance works. Today if I uncheck the Cloud Points the child boxes uncheck but the point clouds remain them. If you have any ideas Thank you =)

![Capture](https://user-images.githubusercontent.com/73833231/135233661-36782826-da6f-4506-8a12-2bc076584376.PNG)

**Comment by Matthieu-Fontaine** [comment]
It works!

![soluc](https://user-images.githubusercontent.com/73833231/135283591-5457abda-76a5-4c8c-8a4b-cd4912e03294.PNG)

**Comment by NanBlanc** [comment]
can you give more details on how to implement your solution ?

i convert also the image to code because posting just an image is a bit useless for the community

```
tree.on("uncheck_node.jstree", (e, data) => {
            let object=data.node.data;
            if(object && object.Folder != "Folder"){
                object.visible = false;
            }else{
                for(let child of data.node.children_d){
                    let datachild=$.jstree.reference("pointclouds").get_node(child);
                    datachild.data.visible = false;
                }
            }
        });
                
        tree.on("check_node.jstree", (e, data) => {
            let object=data.node.data;
            if (object && object.Folder != "Folder"){ 
                object.visible = true;
            }else{
                for(let child of data.node.children_d){
                    let datachild = $.jstree.reference("pointclouds").get_node(child); 
                    datachild.data.visible = true;
                }
            }
        });
```
