### ISSUE TITLE
The measuring tools (i.e. distance measurement tool) work differently on different browsers

### ISSUE THREAD

**Issue by worlderland** [potree/potree#1088]
In Chrome, the distance measurement tool draws a line from A to B, but when you click on B to draw another line (another measurement) it actually moves the point B. Instead, if you click A again it will generate a new line (messing up the previous measurement).
Edge behaves like Chrome.

In Firefox it actually works correctly: you draw a line from A to B, then you click on B and it draws another line and so on.

**Comment by mrxder** [comment]
It may be related to these issues: #991 #996

**Comment by worlderland** [comment]
> It may be related to these issues: #991 #996

Thank you so much for pointing me to the solution!
What Nvernat suggested fixed the issue.
