### ISSUE TITLE
Adding volume clipping tool at given coordinates without using sidebar tool

### ISSUE THREAD

**Issue by naoya1999** [potree/potree#1096]
I'm potree beginner.
I want to use my own toolbar to do the clipping.
I don't know where to start.

**Comment by sdoughtie** [comment]
I'm new here also. I've found that if you can find an example that does what you are looking for, then you can read the html file and find out how it was done.

**Comment by mikepianka** [comment]
Inspect the HTML on this example, it shows what you need.

http://potree.org/potree/examples/clipping_volume.html

**Comment by naoya1999** [comment]
Thanks. it's helpful for me.
