### ISSUE TITLE
Images360 not loading in Firefox

### ISSUE THREAD

**Issue by worlderland** [potree/potree#1122]
Hello everyone,

Not sure whether anyone else encountered the same issue, but the images 360 do not appear in Firefox (I have tested the same image on Chrome, Edge and Brave and it appears in all of them).

Browser versions:
Firefox: 95.0 (64bit)
Chrome: 96.0.4664.93 (Official Build) (64-bit)
![chrome](https://user-images.githubusercontent.com/42766911/146313816-63e79b64-7f24-480a-a5b2-afc05ff506e5.jpg)
![firefox](https://user-images.githubusercontent.com/42766911/146313820-e3dfc2ef-e608-4e82-bbf2-f672065368d1.jpg)

**Comment by Matthieu-Fontaine** [comment]
Hi, firefox can be a little less powerful than other browser log the resolution of your photos before viewing and if the values are excess reduced their resolution and it should work =)

**Comment by worlderland** [comment]
Hi @KingTigrou , thank you for your reply.
In actual fact, because they are 360 deg images, they are 20xxx x 10xxx px, so we'll try optimising them so they appear in Firefox as well.

**Comment by Matthieu-Fontaine** [comment]
For each 360 image, my console show that
THREE.WebGLRenderer: Texture has been resized from (8069x4105) to (4096x4096).

the resolution that I display is 4096*4096 and it's already really good.

**Comment by worlderland** [comment]
This is the message in the console after I load an image:
THREE.WebGLRenderer: Texture has been resized from (20480x10240) to (16384x8192).

I had a separate test where I took an image, resized it from 20480x10240 to 10000x5000 and Firefox displayed it, plus I also run an optimiser to bring the size down to roughly 2MB and Firefox still displayed it.

In conclusion you were right about Firefox not being powerful enough (or as powerful as other browsers). =)
We'll be running a software to resize and optimise images from now on, so we won't have issues with them on different browsers.

**Comment by HeadLessHUN** [comment]
if you resizing images keep in mind that you will free up some resources if you keep them power of two sizes like
512,1024,2048,4096,8192,16384,etc...
because as you see in your log it will get resized everytime you load them.

if you want higher resolution then you should use cubemap instead of equirectangular, we loads 6x4096x4096 =100MPx it is somewhat comparable with the 16384x8192 image (because of the distortions maybe the cubemap will have better quality). we get this from our software and does not need any equirectangular images this is why we use that format.

**Comment by worlderland** [comment]
Thanks @HeadLessHUN .
We will be looking into what you said about using a cubemap.
We have built a software that extracts images from an .e57 file, but the result image is a sphere (20480x10240)... We'll have to look into libraries that can convert a sphere image into a cubemap, possibly resize it and definitely optimise it.
