### ISSUE TITLE
Potree continuously loading entire Octree file in server deployment

### ISSUE THREAD

**Issue by pe5er** [potree/potree#1142]
I'm trying to deploy Potree to an Ubuntu server (AWS EC2 T2.Micro: 1 CPU, 1GB RAM, 30GB SSD) and am having severe problems.

**Configuration**
Internet -> Apache Virtual Hosts -> Site 1  (subdomain1.site.com)
                                                     -> Potree Files (subdomain2.site.com)

The Potree files were generated by PotreeConverter 2.0 (in windows command line) and therefore include Potree version 1.8.0

**Issues**

- The point cloud can take several minutes to load, and often is missing large chunks for several minutes
- When the point cloud does load, it lacks detail
- The file works perfectly in the PotreeDesktop viewer, loading in a couple of seconds with full detail

_Point cloud running on my Ubuntu server; very slow to load and is missing most of the detail_
![image](https://user-images.githubusercontent.com/11816726/148928981-8b6464c6-b312-4d03-b8a1-304c795fd2cf.png)

_Same point cloud running in the Potree Desktop Viewer (for debugging purposes). Works perfectly with no errors_
![image](https://user-images.githubusercontent.com/11816726/148937734-3624ee07-1b33-484e-9ad6-7975ff01f8a7.png)

**Theories**

- Could this have anything to do with my low-spec cloud server? I couldn't find any system requirements for Potree, does anyone know about this?
- Any chance my apache virtual hosts config is causing any problems?
- Might I have somehow messed up my deployment of Potree?

**Comment by HeadLessHUN** [comment]
I don't think that low spec is the key here...
 
Ithink it is more likely to be settings issue in the viewer, for example very large point sizes and little bit low point count, but the 2million for thes scene should be enough the main issue is the point size. can you share your html file?

**Comment by pe5er** [comment]
> I don't think that low spec is the key here...
> 
> Ithink it is more likely to be settings issue in the viewer, for example very large point sizes and little bit low point count, but the 2million for thes scene should be enough the main issue is the point size. can you share your html file?

Thanks for your help. The file opens just fine with the PotreeDesktop viewer, and when hosted using Xampp on my Windows desktop

_Below screenshot shows the same point cloud running in XAMPP for debugging purposes. It works perfectly, although there are some errors in the console_
![image](https://user-images.githubusercontent.com/11816726/148936454-fd9c3e61-ca8e-41f1-bff4-239f60686de2.png)

That's with the same viewer settings as is configured on my ubuntu server, so I'm not sure if it could be a viewer settings problem.

**Comment by pe5er** [comment]
Here's my HTML file; I haven't touched it since it was generated from PotreeConverter --GeneratePage

[palestra-basement.html.txt](https://github.com/potree/potree/files/7846184/palestra-basement.html.txt)

**Comment by HeadLessHUN** [comment]
If it is opens fine in potree desktop maybe it can be related to network issues.

Is the server and the client on the same lan? if not that might be the root cause. not the performance of the machine.

**Comment by pe5er** [comment]
Server is in an Amazon data center, I've got gigabit fiber. I can't rule out a network issue, but it seems unlikely

**Comment by HeadLessHUN** [comment]
Don't you have somekind of bandwidth limiter on that AWS? I'd setup a webserver on your own lan, instead of AWS, and other solutions.That way you wouldn't have that 30GB file limit which is very low. Even for potree. 1cpu and 1 GB ram would be more than enough. 

We run our potree server on a truenas jail. it is barely using any resources.

**Comment by pe5er** [comment]
There's no bandwidth limit, and I need to host potree on a cloud provider because we don't have any on-prem web servers. I'm running out of ideas, might try a fresh ubuntu install on my other AWS account.

30GB isn't a limit, that's just what we're paying for at the moment. We pay per GB so can easily add storage in the future. 

Truenas jail is a decent idea, but I prefer not to host things at home when I can avoid it

EDIT: it's worth mentioning, we're looking to use Potree as a way of delivering point clouds directly to clients, so our deployment will need to be exposed to the internet either way

**Comment by midnight-dev** [comment]
Your AWS tier may be to blame after all if the viewer settings are identical. There's going to be some delay when on a remote server, but it shouldn't be *that* noticeable. For high detail point clouds, there's going to be a lot of disk thrashing as the viewer initializes. For lower end tiers, this could pose a problem if you reach your max SSD iops, especially if it's a burst limit. It'll be even worse if you are using legacy HDD storage. I've never checked how much IO potree uses, but it's worth considering. There's also the networking which has lower priority and lower speed at the cheap end, but that's probably less of an issue than the storage iops. 

There's some way to monitor AWS instance performance, but I can't give much advice as I'm well out of practice. By the way, the networking tab in your developer tools will provide better information than the console regarding performance issues.

**Comment by pe5er** [comment]
> Your AWS tier may be to blame after all if the viewer settings are identical. There's going to be some delay when on a remote server, but it shouldn't be _that_ noticeable. For high detail point clouds, there's going to be a lot of disk thrashing as the viewer initializes. For lower end tiers, this could pose a problem if you reach your max SSD iops, especially if it's a burst limit. It'll be even worse if you are using legacy HDD storage. I've never checked how much IO potree uses, but it's worth considering. There's also the networking which has lower priority and lower speed at the cheap end, but that's probably less of an issue than the storage iops.
> 
> There's some way to monitor AWS instance performance, but I can't give much advice as I'm well out of practice. By the way, the networking tab in your developer tools will provide better information than the console regarding performance issues.

Thanks for your help @midnight-dev !

The tip on the networking tab is very useful, but has raised quite a  few questions from me. OctreeLoader.js is listed with a size of 1.7GB (basically the size of my point cloud), and appears over and over again. It takes 2 minutes for it to load, and then it starts again with a new instance.

Task manager says that my Chrome tab is downloading at 250mbps, and the networking tab on chrome says it's 20000 MB transferred. Any idea what's going on here?

I'm afraid to admit that I don't really understand how Potree works :( Presumably it doesn't deliver the entire 1.7GB point cloud over the internet, but does some server side operations that allows it be rendered in a lightweight client?

I left my browser open for ages to see what would happen: slowly my model started loading in, bit by bit, but we're talking 10 minutes total load time before even 2/3 of the model shows.

_Here's a screenshot of that in-progress; you can see that many minutes have passed at this point_
![image](https://user-images.githubusercontent.com/11816726/149001120-f03131b3-bc1a-4e42-9525-6a36d7be39d6.png)

_Another screenshot after a few more minutes with the tab open_
![image](https://user-images.githubusercontent.com/11816726/149001884-b3475d02-f5dc-4cc9-8d60-7d3897a581c3.png)


As for my AWS tier; the storage is a gp2 SSD. They list a maximum throughput of 128 MiB/s, and max IOPS of 16,000. I don't know if that's fast enough, but my gut feeling is that it should be, if others are running Potree on spinning rust. 


I've probably been staring at this too long, but it seems to me that my potree sever is streaming 20GB+ of data to my client to serve a 1.7GB point cloud. I'm mightily confused!

**Comment by midnight-dev** [comment]
That's neat. Your client is downloading the entire 1.7 GB point cloud multiple times.

The JS loader is just the *initiator* and the file that it's fetching is the big boy, octree.bin. With the latest potree standard, partial chunks of the monolithic point cloud file are downloaded on demand. In theory, the loader will only fetch data it doesn't have, but something is going wrong here. It could very well be a bug with the browser or with the JavaScript. The partial range responses are not cache friendly like whole files, but here you've got the whole file being loaded several times.

Can you try a different browser, just for fun? I typically switch between the latest versions of Firefox and Chrome for testing.

By the way, did you specifically get a high throughput SSD? For a 30 GB allotment on a cheap micro tier, I would have expected a default closer to 300 iops. I haven't checked instance specs in a hot minute, so my expectations could be way out of date. If something is causing the loader to fetch the whole point cloud repeatedly, I doubt the hardware is the actual problem; I'm just curious if the default has dramatically changed or if you have an upgraded drive.

**Comment by HeadLessHUN** [comment]
Maybe on the server something is misconfigured or apache is baf and the range requests are sending the whole file?

What is the apache version? Can you see some apache logs/errors?

I'd check the request headers on those big files, to sort out javascript errors. If the rquest header contains a valid range request the javascript side is good. Then i'd look up the response headers, and crosschek them

**Comment by pe5er** [comment]
@midnight-dev 
> That's neat. Your client is downloading the entire 1.7 GB point cloud multiple times.
> 
> The JS loader is just the _initiator_ and the file that it's fetching is the big boy, octree.bin. With the latest potree standard, partial chunks of the monolithic point cloud file are downloaded on demand. In theory, the loader will only fetch data it doesn't have, but something is going wrong here. It could very well be a bug with the browser or with the JavaScript. The partial range responses are not cache friendly like whole files, but here you've got the whole file being loaded several times.

Thanks for the rundown, I appreciate it!

> Can you try a different browser, just for fun? I typically switch between the latest versions of Firefox and Chrome for testing.

Exact same problem on Firefox!

> By the way, did you specifically get a high throughput SSD? For a 30 GB allotment on a cheap micro tier, I would have expected a default closer to 300 iops. I haven't checked instance specs in a hot minute, so my expectations could be way out of date. If something is causing the loader to fetch the whole point cloud repeatedly, I doubt the hardware is the actual problem; I'm just curious if the default has dramatically changed or if you have an upgraded drive.

I went for their "General Purpose SSD (gp2)", which they quote for max 16,000 iops. They also offer high performance SSDs which go up to 64,000 iops. That being said, they do say that SSD performance is limited by volume size somewhat, so I wouldn't expect full performance out of my 30GB volume.

Initially I tried to use S3 to store the point clouds, as that storage is way cheaper. I used s3fs to mount an S3 bucket in my EC2 server, but it was painfully slow (although I now though it was also suffering from the same issue as we're discussing now).

@HeadLessHUN 
> Maybe on the server something is misconfigured or apache is baf and the range requests are sending the whole file?

> What is the apache version? 
* Apache Version 2.4.41 (Ubuntu)

> Can you see some apache logs/errors?
* Nothing notable in the apache error log

> I'd check the request headers on those big files, to sort out javascript errors. If the rquest header contains a valid range request the javascript side is good. Then i'd look up the response headers, and crosschek them

_Headers of octree.bin; it has a range request in it, but I don't know enough about the backend to see if it's valid or not_
![image](https://user-images.githubusercontent.com/11816726/149158700-4f046ea8-5965-4e82-b794-c8204f9722be.png)

_Response seems to be garbage, but again I'm lacking in expertise to know for sure!_
![image](https://user-images.githubusercontent.com/11816726/149159187-82561562-788c-4832-bef9-cde113855410.png)

**Comment by HeadLessHUN** [comment]
i've just looked around a little bit, it must be something in that apache, the javascript requested byte range seems valid (tries to download around 80kb)...

I've came across with this. Is the compression enabled in apache? If yes try to disable that.
https://stackoverflow.com/questions/53403529/apache-and-content-range

Or look for something like that in the apache configuration/htaccess, because this will disable the byte-range requests.
`Header set Accept-Ranges none`

**Comment by pe5er** [comment]
Sooooo...

I updated my SSL certificate and that fixed the problem. The clue to do that came from the following:

- I tried to take @HeadLessHUN 's suggestion; disabled compression (didn't help) then modified my htaccess file to include `Header set Accept-Ranges none`
- This threw an apache error, header command not found or something like that
- I then ran: `apache2ctl -M | grep headers_module` to check it exists, but this threw an error that it couldn't find my SSL certificate
- That prompted me to investigate my certificate, which had expired (but for some reason looked like it had renewed when looking in Chrome?). I did a manual update using DNS challenge (long story, will fix that at some point) and just like that: Potree is now working perfectly

I don't fully understand what the route cause of all this was, but here's my best guess:

- The apache2 headers module is needed to process a range request that loads part of the Octree file
- The headers module was upset / broken by my expired / broken SSL certificate, and therefore not working correctly
- This caused Apache to kindly ignore the range request, and load the whole file
- These requests happen continually, because OctreeLoader is supposed to only load the bit of the file you need at any one time


Thank you very much @HeadLessHUN and @midnight-dev for your extensive help, I really appreciate it. Also thanks to anyone who works on Potree, it's a brilliant project and I'm proud to now be contributing a little bit towards it every month.
