### ISSUE TITLE
Hop between 360 images (kind of like Google street view)

### ISSUE THREAD

**Issue by worlderland** [potree/potree#1145]
Hello everyone,

This may not be an issue but more of an improvement (if it doesn't exist), but I was wondering whether Potree has the ability of allowing the user to hop between 360 images (kind of what Google does with street view).

I could not find anything in the code and at the moment, once you enter an image, the other images around disappear (as in the red circles), and the user has to unfocus, leave the image, then click on another one.

Has anyone had this necessity, solved this issue or can anyone point me to the list of considerations for Potree 2.0 is held (in relation to this, just out of curiosity, what would be an ETA for Potree 2.0?).

Thanks in advance.

**Comment by skinkie** [comment]
Same as https://github.com/potree/potree/issues/887

**Comment by worlderland** [comment]
Thanks... I'll follow the other conversation (even if it hasn't gotten anywhere for the moment)
