### ISSUE TITLE
 360 sphere  Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by Munbc** [potree/potree#1146]
Hello
Currently, I'm trying to operate the 360 sphere shapefile function on the potree, but there was an error, so I checked and found this phrase.

Uncaught (in promise) TypeError: coordinates must be finite numbers  proj4.js:1 
at g (proj4.js:1:4846)
at St (proj4.js:1:22751)
at w (proj4.js:1:5221)
at A (proj4.js:1:5823)
at Object.forward (proj4.js:1:6540)
at Function.load (potree.js:25208:31)

In this case, how should we solve this?
And the current code for my 360 shape file function is like this:

async function run360(){
let pointcloudProjection = "+proj=utm +zone=52 +ellps=WGS84 +datum=WGS84 +units=m +no_defs";
proj4.defs("WGS84", "+proj=utm +zone=52 +datum=WGS84 +units=m +no_defs");
proj4.defs("pointcloud", pointcloudProjection);
let transform = proj4("WGS84", "pointcloud");

let params = {
transform:transform
};

Potree.Images360Loader.load("./photo/Record002/Record002/LB5/", viewer, params).then( images => {
viewer.scene.add360Images(images);
});

viewer.mapView.showSources(false);
}

**Comment by Munbc** [comment]
Now I have solved this problem and succeeded in correcting coordinates.txt to prevent errors, but this time we have a problem that 360sphere does not appear.
How can I make it visible?

![360image안보임](https://user-images.githubusercontent.com/96286203/151102092-c676c90e-9006-45f0-be14-6b2fda7849c9.png)

**Comment by tjbubbles** [comment]
Hi Munbc

May I ask what you did to your coordinates.txt file to fix the 'coordinates must be finite' error? I am currently having the same issue.

**Comment by Munbc** [comment]
> Hi Munbc
> 
> May I ask what you did to your coordinates.txt file to fix the 'coordinates must be finite' error? I am currently having the same issue.

https://github.com/potree/potree/blob/develop/examples/360.html
I checked the 360 image created by the Potree creator (same as http://147.135.204.133/examples/360.html) and confirmed that the coordinates.txt is referenced on this page, so I solved this problem by creating a new coordinates.txt in the same form.
(See http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/360/Drive2_selection/coordinates.txt)
