### ISSUE TITLE
Using the Camera as a Clipping Box

### ISSUE THREAD

**Issue by DaineGaming** [potree/potree#1151]
Is there any way to use the Camera Frustum as a clipping volume in addition to all other clipping volume preferably with a depth/distance control.

I understand this sort of defeats the purpose of using Potree to load an octree where the detail is based on your distance to a node but when we load High Density Point Clouds (30 Billion Points in a 60 meter Radius) there is a significant delay on any form of detail.

**Comment by HeadLessHUN** [comment]
Well in crowded spaces best is to subsample there ia no real reason to load 60billion point ever. So if you subsample that maybe you will have better results. And it is always better to use adaptive point size. And slightly higher point cloud.

To reach better frustrum culling can be a hard task. If you look for that in the commits Mark Shuetz put in a lot of effort to make it better. 

I think as users the only thing which we can do is subsample and load separated clouds for differents parts. Like load the point cloud in by floor, or by setup and only load what is really needed.

**Comment by DaineGaming** [comment]
> Well in crowded spaces best is to subsample there ia no real reason to load 60billion point ever. So if you subsample that maybe you will have better results. And it is always better to use adaptive point size. And slightly higher point cloud.
> 
> To reach better frustrum culling can be a hard task. If you look for that in the commits Mark Shuetz put in a lot of effort to make it better.
> 
> I think as users the only thing which we can do is subsample and load separated clouds for differents parts. Like load the point cloud in by floor, or by setup and only load what is really needed.

Typically I would agree with the requirement not to see 60 Billion Points at the same time but does the point budget that you set assist in bringing that number down, e.g., from the code I can see it uses the Point Budget * 2 to determine the max amount of points on screen, but when I move into a crowded space it takes an extremely long time to unload the points from higher octree nodes to the high detail octree nodes.

Is it possible to make Potree load these high detail, smaller point sizes load faster? We have seen issues when it comes to bandwidth of the points being delivered and the drives that the point clouds are stored on but it still seems to be the amount of time it is takng Potree to work through the hierarchy as a whole.

**Comment by HeadLessHUN** [comment]
> Is it possible to make Potree load these high detail, smaller point sizes load faster?

No, definitelly not. Set point budget to 5-10 million, set adaptive point size that is the most crucial one. It'll make the point cloud look like it is ugly, but at least you can identify geometries, walls, estc, more easily and way more faster. You can also enable high quality and EDL they will help you identif edges, etc but it will be more performance demanding (on the client side). 

This is an overview cloud with 10-15mm grid points. ()

![image](https://user-images.githubusercontent.com/10095691/153835114-fa76dff0-8b8e-4007-a0c6-fd8f886cafbb.png)

but as i've told you maybe you could convert separated clouds for every setups that way you will be able to load them separatelly to get similar result what you get in recap mirrirballs. That will always be the most cleaner most accurate loading...
and this is a 3-5mm grid resolution but only from one TLS setup. (So there won't be any color discrepancy, registration errors,significant noise,etc...) (2-3 million points /setup usually)
![image](https://user-images.githubusercontent.com/10095691/153835448-86f6b497-560f-4e13-9f49-a70d612e47e8.png)
