### ISSUE TITLE
Images 360 icon to be a plane geometry or an icon (i.e. annotation with buttons)

### ISSUE THREAD

**Issue by worlderland** [potree/potree#1156]
Hello Potree community,

I am currently banging my head against getting the images 360 icons (the white spheres) to look like the attached picture.

After some research I found a possible solution, plane geometry, however I'm founding it extremely hard to implement it the way I'd like (also to have the plane geometries to look at the camera the same way the annotations do).

In conclusion I was wondering whether anyone else has come across this issue and whether they have resolved it.

Thank you in advance.
![images 360 icons](https://user-images.githubusercontent.com/42766911/154427349-0a347423-6bc2-4f37-b19f-9d1567d9f3aa.jpg)

**Comment by HeadLessHUN** [comment]
Well, I wouldn't recmmend you to create annotations, because they are always visible so that might create a mess especially in crowded spaces like scan to bim projects.

If you really want a fancy button/ fancy element you can load a gltf/obj model as geometry for the mesh. which can have its own texture as well. 

just an example it is a THREE.ThorusGeometry and a THREE.ConeGeometry merged together.

```
let thorus=new THREE.TorusGeometry( .5, .1, 10, 10 );
let cone=new THREE.ConeGeometry( .5, 1.5, 10 );
cone.rotateX(-Math.PI/2);
cone.translate(0,0,.75);
let meshCone=new THREE.Mesh(cone);
let meshThorus=new THREE.Mesh(thorus);
var singleGeometry = new THREE.Geometry();
singleGeometry.merge(meshCone.geometry, meshCone.matrix);
singleGeometry.merge(meshThorus.geometry, meshThorus.matrix);
//cone.add(thorus);
let sg = singleGeometry;
```
![image](https://user-images.githubusercontent.com/10095691/154644111-37aa31a3-6a03-4841-814b-e21da2f880f9.png)

**Comment by HeadLessHUN** [comment]
Or if you really want to use planes instead of spheres, and you want it to be overlayed by the point clouds then, you should rotate the planes according to the camera. I think that can cause significant performance degradation over simple spheres.

**Comment by mikepianka** [comment]
A sprite might work well for this purpose as well since you don't need the icon to be actual 3D geometry.

**Comment by HeadLessHUN** [comment]
> A sprite might work well for this purpose as well since you don't need the icon to be actual 3D geometry.

Sprites are the same as the annotations, it works and you don't have to bother to rotate them according to the camera but they are just raycasted html elements so they will be shown all the time point cloud will not hide them. I think that is not a usable way. But it depends on the usecase, for scan to bim this is a nogo.

**Comment by mikepianka** [comment]
@worlderland did not mention anything about needing the pointcloud to hide the annotations. It sounds like he just wants a consistent flat symbol for each pano location and he is trying to achieve that with a plane geometry. A sprite will do exactly what he wants based on his question. If he wants them to be hidden by the pointcloud, that's a different scenario.

**Comment by worlderland** [comment]
Thank you for your responses.

We'll look at the code the @HeadLessHUN posted above and see whether it suits us, and if not we'll try different solutions, keeping in mind that planes may degrade performances.

In regards to hiding the annotations, we have solved the issue by writing a few functions into the Potree core. We are probably going to fork out and then submit a pull request for the Potree team to assess, because a "show/hide" annotations functionality is very much useful.

**Comment by worlderland** [comment]
Closing this issue now.

Thank you @HeadLessHUN and @mikepianka for pointing us to sprites. It fixed our issue and now we have the flat image that we wanted. :)

![image](https://user-images.githubusercontent.com/42766911/157146142-10a3f33d-0a3a-494e-acb2-e43cb58b0548.png)

We'll now move onto the harder feature of making a navigation between images.
