### ISSUE TITLE
360 positions disappearing

### ISSUE THREAD

**Issue by Vynikal** [potree/potree#1157]
Hello, I'm trying to use 360 images functionality of Potree.
Generally it is working, I can open the example page (360.html), I can open a pano position...
Then I click on 'unfocus' and when I click anywhere to rotate/move camera, ALL 360 positions disappear. It happens in the aforementioned example and my own created point cloud too. When I reload the page, it works again, but again only for the first position.
Not sure if this has already been reported. It is a nasty little bug in an otherwise excellent feature. Can someone help?

Before:
![obrazek](https://user-images.githubusercontent.com/7486998/154802166-5c06d825-7771-4759-bcc4-7eb69fb298a0.png)

After:
![obrazek](https://user-images.githubusercontent.com/7486998/154802187-fdee4e70-099b-4223-b46a-6e1969773098.png)

**Comment by HeadLessHUN** [comment]
#1027 i created a fix, but i think it should be fixed in the development branch as well. Apply that patch not mine. Or just run the latest development branch instead of the 1.8

https://github.com/potree/potree/commit/3a5aaac8c2f4314a7d09d026fc86ccbc23845dca

**Comment by HeadLessHUN** [comment]
please close it, if it is solved.

**Comment by Vynikal** [comment]
Yep, sorry
