### ISSUE TITLE
potree encountered an error

### ISSUE THREAD

**Issue by Munbc** [potree/potree#1160]
![image](https://user-images.githubusercontent.com/96286203/156318207-08173d75-91da-4fb9-814d-ecf41cee1714.png)

I tried to get a potree web from another external server, but I couldn't see it as the screen appeared.
I don't know what the problem is.
Can you help me with how I can solve it?
(FYI, the potree web works normally in the computer of the external server.)

**Comment by HeadLessHUN** [comment]
Hello, since it is an online viewer i was able to view that, maybe your pc has low amount of ram? Does it have webgl 2.0? If you have a laptop with  integrated and dedicated gpu, then you should use the dedicated one.

**Comment by Munbc** [comment]
@HeadLessHUN 

Unfortunately, I checked the problems you told me, but there were no problems.
Instead, I confirmed that my computer was not aware of the '( )' in the middle of the address, and I solved this problem by changing the folder name.
Thank you for your help.
