### ISSUE TITLE
Rendering pointclouds using a regular WebGLRenderer rather than PotreeRenderer

### ISSUE THREAD

**Issue by shiukaheng** [potree/potree#1161]
Hi, I'm trying to integrate Potree with other three.js libraries, and I found out that Potree now uses a PotreeRenderer to do its rendering (by calling gl.drawArrays manually) rather than WebGLRenderer. Is there any way to integrate Potree's rendering back to the main WebGLRenderer rendering loop? Thanks

**Comment by sebaFP** [comment]
Hi, how do you solved this?
Thanks
