### ISSUE TITLE
show/hide pointcloud

### ISSUE THREAD

**Issue by ataylor09** [potree/potree#117]
Hi there, I'm having trouble trying to show/ hide a point cloud using 

     pointcloud.visible = false

or

     pointcloud.visible = true

Where pointcloud is  a normal potree pointcloud, created using:

     pointcloud = new Potree.PointCloudOctree(pco, materials.rgb);

I am successfully changing the visible Boolean, but this isn't showing/hiding the point cloud. Is there a better way to do this?

Cheers
Adrian

**Comment by m-schuetz** [comment]
Hi!

I'm using the visible attribute to show and hide individual nodes of the point cloud which is most likely why you're unsuccessfull in trying to hide it yourself. Each call to pointcloud.update() will change the value of the visible attribute for point cloud nodes. 

I will add support for setting .visible to the TODO list. 
As a workaround for now you could try not to call pointcloud.update() when pointcloud.visible is set to false. And maybe you will also have to make every descendant of the pointcloud node invisible as well.

**Comment by m-schuetz** [comment]
Done: https://github.com/potree/potree/commit/33eeb7b1f9d147bbf3eb3c806100200bc296206d
