### ISSUE TITLE
Missing scene argument in update function ?

### ISSUE THREAD

**Issue by monodo** [potree/potree#118]
In <a href="https://github.com/potree/potree/blob/de3428e63e4164dd1916ccc1b0267bf490b5384f/src/PointCloudOctree.js#L94">update</a> function, should not be the *scene* passed as argument as it is required on this <a href="https://github.com/potree/potree/blob/develop/src/PointCloudOctree.js#L157">line</a> ?

**Comment by m-schuetz** [comment]
That was a bug. Scene should not be used in this case.
I'm attaching the bounding boxes to the PointCloudOctree instance instead of scene, now: https://github.com/potree/potree/commit/2a41147309adb508300b2f2038f1b7675ff2bb4e
