### ISSUE TITLE
Profile of multiple pointclouds downloads as split pointclouds

### ISSUE THREAD

**Issue by roy-mdr** [potree/potree#1193]
From example _"multiple pointclouds"_:
![01](https://user-images.githubusercontent.com/8226073/173083688-5445264b-8259-4a7f-a52e-ff5d40753e1f.PNG)

`.LAS` file:
![02](https://user-images.githubusercontent.com/8226073/173083708-210a2c4f-3153-4910-97bb-9a2daf27f218.PNG)

And `.CSV` coordinates are not matching either.

**Comment by mriedo** [comment]
Hi Markus @[m-schuetz](https://github.com/m-schuetz) It would be great if you could commit this correction of the export profile and new 2D & 3D DXF export function to potree 1.8. I think it's a great addition and of great interest for some of our users.

@roy-mdr did a great job on this and I tested it on our pointclouds https://github.com/potree/potree/pull/1178

It is live on (https://sitn.ne.ch/lidar/dev/) and [https://sitn.ne.ch/lidar/](url) for testing

**Comment by m-schuetz** [comment]
@roy-mdr Thanks for the PR! I plan to check and merge this week!

@mriedo Good to hear that this is a useful contribution, I will check it out this week!
