### ISSUE TITLE
Calculate the sum of measurements

### ISSUE THREAD

**Issue by jamatut** [potree/potree#1199]
Hi, is there a way to automatically Calculate the full length of each individual Measurement when they are connected? 
is there a setting to show it or does it have to be Implemented? 

![image](https://user-images.githubusercontent.com/17800283/175893177-fd1fac15-3f56-410c-b209-5dbb46f00253.png)

**Comment by zeonler** [comment]
you can find total length by selecting the measure in the scene section

**Comment by jamatut** [comment]
> you can find total length by selecting the measure in the scene section

Thanks a lot! This is what i looked for!
