### ISSUE TITLE
Classification re-rendering

### ISSUE THREAD

**Issue by okaforcj** [potree/potree#1213]
Hey guys, 

I was wondering if anyone knew how to re-render classifications. Basically, I want to change the classification of points within a box for quick visual feedback. I am able to get the attributes and change the attributes of certain points within a box volume. i.e. i change the classification attribute from being a ground( class 2) to vegetation (class 3) but i want to re-render the pointcloud or basically update the texture or material of that pointcloud to show the update colors. any ideas on how to do it or some targeted reading material on the section of the code that deals with material updates/re-renders

**Comment by kevjamco** [comment]
Hi @okaforcj, I am curious how you are changing the classification of points within a volume box. Do these changes then persist to the octree?

**Comment by okaforcj** [comment]
hey @kevjamco, sorry i wasnt paying attentition to this. it doesnt persist, i change it in the browser and then use pdal on the backend to persist any changes
