### ISSUE TITLE
Due to the recursive function loop, the page will soon crash due to memory exhaustion. But I found that running the examples in the source code will clean up the memory after a period of time, so the page can always run normally. How do you clean up the memory?

### ISSUE THREAD

**Issue by 3060935739** [potree/potree#1216]
Due to the recursive function loop, the page will soon crash due to memory exhaustion. But I found that running the examples in the source code will clean up the memory after a period of time, so the page can always run normally. How do you clean up the memory?

**Comment by ukarthik27** [comment]
what is the issue that you have faced here ?
