### ISSUE TITLE
How can i change the measurement tools function in potree

### ISSUE THREAD

**Issue by simsekibrahim** [potree/potree#1217]
How can i change the measurement tools function in potree. Now, i am using potree v.1.8..

Now, this function works as; When i start the measurement; firstly i am adding first point with left click after that i am moving that point measuriment second or next point with left click.

I would like to when i start the measuriment with left click for second and next point just add next point. when finish measuriment just right click.

as in the link

https://www.otago.ac.nz/surveying/potree/projects/16-007M001_QuarantineIsland_d001.html

**Comment by smcavoy12** [comment]
Pretty sure this is referring to a well known bug with chrome. Try with Firefox and see if it has the behavior you'd like.

You'll have to update the potree.js file with an unofficial fix. try this one. 
https://pointcloud.ucsd.edu/build/potree/potree.js

If it doesn't work for you look up "measurement bug chrome"

Duplicate: https://github.com/potree/potree/issues/991

**Comment by simsekibrahim** [comment]
Thank you @smcavoy12 ;

I used the potree.js file you suggested and the problem was solved.
