### ISSUE TITLE
[Question] Hardcoded position cesium_rets example

### ISSUE THREAD

**Issue by JonathanCallewaert** [potree/potree#1223]
I was looking into the code of cesium_retz.html to see how Potree renders with a map overlay (http://potree.org/potree/examples/cesium_retz.html) .
It really looks nice but there is one part of the code that I don't understand, It's the following code in particular:
```js
     scene.view.position.set(570975.577, 5398630.521, 1659.311);
     scene.view.lookAt(570115.285, 5400866.092, 30.009);
```
I understand why this code is is needed, but how where those numbers calculated that are passed to the function? What's the way do archive this without hardcoding? I'm using a custom point cloud format so it's not a file converted by Potree converter

**Comment by HeadLessHUN** [comment]
This is not related to cesium at all it's just set the initial view of the viewer. So it is not a requirement.

If you really need it, you can get these numbers from the camera element in the left side scene tree. There will be two coordinates (position, target).

**Comment by JonathanCallewaert** [comment]
Thank you :) 

There was also a mistake and my projection function, which also caused my pointcloud not rendering correctly. Now its' fine!
