### ISSUE TITLE
properties panel not displayed

### ISSUE THREAD

**Issue by crawld** [potree/potree#1233]
There are several panels not displayed in the sidebar, e.g., one for gamma/brightness/contrast that are defined in the code, but are not displayed in the web interface. How can these be enabled?

They are defined here:
https://github.com/potree/potree/blob/37dc46a25ca56683e216c973dd117bc68b75ab0f/src/viewer/PropertyPanels/PropertiesPanel.js#L83

**Comment by HeadLessHUN** [comment]
Gamma, brightness, contrast is a property of the cloud, so it will only show up, if a pointcloud is selected in the tree

**Comment by crawld** [comment]
How about the height range slider?

**Comment by HeadLessHUN** [comment]
Same answer select the point cloud and use elevation color then you will find the elevation slider. Everything is on the panel just fiddle with it.

**Comment by crawld** [comment]
The only tree I see is the export tree; a pointcloud is selected and I see no sliders.

![image](https://user-images.githubusercontent.com/7037909/189497394-a5694543-9cfa-41fb-9b4c-b7cb0f51f991.png)

**Comment by HeadLessHUN** [comment]
![image](https://user-images.githubusercontent.com/10095691/189497668-985158d6-58ca-4f8b-93c7-c6c30e148247.png)
select the point cloud and use elevation as attribute as i said.

**Comment by crawld** [comment]
I see, attribute needs to be elevation as well. Thanks!
