### ISSUE TITLE
Projected height profile data

### ISSUE THREAD

**Issue by m-schuetz** [potree/potree#124]
Coordinates are given in 3d scene coordinates. A helper function or tag that helps to get projected coordinates for 2d profile views is needed.

**Comment by potree** [comment]
Refactored getProfile() and getPointsInProfile().

getProfile(): returns all point attributes and a project() function which can be used to align point coordinates along the x-axis.

```
// usage example for the first single segment profile
var sg = new THREE.SphereGeometry(1);
var profile = profileTool.profiles[0];
var start = profile.points[0];
var end = profile.points[1];
var width = profile.width;
var points = pointcloud.getProfile(start, end, profile.width, 1);
for(var j = 0; j < points.numPoints; j++){
	var pos = points.position[j];
	pos = points.project(pos);

	var sm = new THREE.Mesh(sg);
	sm.position.copy(pos);
	scene.add(sm);
}
```


getPointsInProfile(): returns segments. Each segment contains start, width, points inside the segment and a project() function that can be used to transform this segments points to the x-axis.
Points of the second segment will be projected right after the first segment.

```
// usage example for a the first multi segment profile
var profile = profileTool.profiles[0];
var segments = pointcloud.getPointsInProfile(profile, 2);

var sg = new THREE.SphereGeometry(1);

for(var i = 0; i < segments.length; i++){
	var segment = segments[i];
	var points = segment.points;
	
	for(var j = 0; j < points.numPoints; j++){
		var pos = points.position[j];
		pos = segment.project(pos);
	
		var sm = new THREE.Mesh(sg);
		sm.position.copy(pos);
		scene.add(sm);
	}
}
```

Multi segment height profile:
![idbbceac](https://cloud.githubusercontent.com/assets/2094934/6526461/744f339c-c412-11e4-8030-3c5228ab3082.png)

Height profile unrolled and aligned on the x-axis and spheres created at the projected point positions:
![bdjbeiij](https://cloud.githubusercontent.com/assets/2094934/6526464/7b1daffa-c412-11e4-910f-22d0020a8d99.png)

**Comment by Zvyozdo4ka** [comment]
@potree How to do you change the color of the line? How are you getting the points? What is the definition of Profile?

**Comment by Zvyozdo4ka** [comment]
Do you have any documentation with algorithm description?
