### ISSUE TITLE
example 360 don't works anymore

### ISSUE THREAD

**Issue by bard0x** [potree/potree#1265]
Hi,

the example 360 don't works anymore...

The address http://5.9.65.151/ is not reacheable.

**Comment by HeadLessHUN** [comment]
hello, for me it is seems fine, if i lookup the exact url it works.

maybe you see some other issue?

http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/360/MLS_drive1/cloud.js
http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/360/Drive2_selection/coordinates.txt

**Comment by m-schuetz** [comment]
5.9.65.151 was done for a couple of days. It's up again.
