### ISSUE TITLE
How to transform longitude, latitude and altitude to Potree Scene coordinates?  

### ISSUE THREAD

**Issue by amc-ipetrov** [potree/potree#1282]
Hello everyone. I have one question related to transforming geo-coordinates (longitude, latitude, and altitude) to Potree Scene coordinates. 
I want to create one-way mapper like this:
(longitude, latitude, altitude) => { x, y, z }, and then I want to update Viewer.Scene.View via received (x, y, z). But unfortunately, I did not find a way how to do this.
Could please someone help me with this question?

**Comment by ElectricFiras** [comment]
@amc-ipetrov Did you find the solution?

**Comment by tiennguyen00** [comment]
same problem
