### ISSUE TITLE
How do I customize the point cloud colors

### ISSUE THREAD

**Issue by Koiandrop** [potree/potree#1289]
Hi everyone, I am using potree recently and have a question, I want to introduce a color picker in my project to change the color of the point cloud by selecting any color.What should I do?

**Comment by raycaster08** [comment]
You can do this directly in the sidebar
<img width="1433" alt="iShot_2023-02-15_17 53 41" src="https://user-images.githubusercontent.com/23043361/218994202-e1813c85-e21a-4f8a-adf9-61797cd653ae.png">
