### ISSUE TITLE
Potree.PointCloudOctree.prototype.update undefined 'scene' variable

### ISSUE THREAD

**Issue by okitu** [potree/potree#130]
When `showBoundingBox` is true for my pointCloud, the `Potree.PointCloudOctree.prototype.update` method tries to add a `boxHelper` to `scene`. This `scene`variable is undefined.

I think this normally works, because your examples are one-page demos. where everything kindof is globally defined. I'm currently implementing this in a larger AMD-based app.

**Comment by m-schuetz** [comment]
Hello okitu!

I've fixed this 2 days ago in the develop branch: https://github.com/potree/potree/commit/2a41147309adb508300b2f2038f1b7675ff2bb4e

You can try it out already but as it's still in the develop branch, there might be some other issues left.

**Comment by okitu** [comment]
nice, thank you
