### ISSUE TITLE
Resizing with quality = "Splats"

### ISSUE THREAD

**Issue by okitu** [potree/potree#131]
Hi there,

I'm just digging through the examples, and try to understand the bits and pieces. If you set the quality to "Splats" in one of the examples, you cannot resize the canvas without messing up the picture.

Because i don't have a clue yet, what's going on here, i have no idea how to fix this.

Maybe you can have a look at it.

Thanks

**Comment by m-schuetz** [comment]
There are probably some buffers that have to be resized.
I'll take a look at it!

**Comment by m-schuetz** [comment]
It seems like setSize() only works the first time the render targets are rendered.
```
rtDepth.setSize(width, height);
rtNormalize.setSize(width, height);
```

By disposing and recreating the render targets on resize, rendering works properly. 
Haven't comitted it yet because point picking still does not work after resize in splat quality mode.

**Comment by m-schuetz** [comment]
Picking after resizing didn't work for other rendering modes either. Also fixed it by disposing and recreating render targets after resize.

splat fix: https://github.com/potree/potree/commit/55c7a9c11f692746c9e0f53197de2bcc81074344
pick fix: https://github.com/potree/potree/commit/a76d5e85666c505a36dccd3fcccbfbd0ed0d4872

```
...
}else if(this.pickTarget.width != width || this.pickTarget.height != height){
	this.pickTarget.dispose();
	this.pickTarget = new THREE.WebGLRenderTarget( 1, 1, { minFilter: THREE.LinearFilter, magFilter: THREE.NearestFilter, format: THREE.RGBAFormat } );
}
this.pickTarget.setSize(width, height);
```

@mrdoob 
Do you know of any possible problems with resizing WebGLRenderTarget objects with setSize()?
After rendering to a target once, setSize() does not work for me but recreating the buffer and then setting the size of the fresh render target does.

**Comment by okitu** [comment]
Thanks for the quick fix =)

**Comment by mrdoob** [comment]
> Do you know of any possible problems with resizing WebGLRenderTarget objects with setSize()?
After rendering to a target once, setSize() does not work for me but recreating the buffer and then setting the size of the fresh render target does.

Yeah, I think this hasn't been implemented yet... :/

**Comment by m-schuetz** [comment]
Ah, I see. Maybe I'll give it a shot.

**Comment by benaadams** [comment]
Just came across this; glad there was this issue :)

**Comment by m-schuetz** [comment]
Great, I'll close this then.
