### ISSUE TITLE
Latest release (1.8.1) lacks package.json

### ISSUE THREAD

**Issue by gzotti** [potree/potree#1327]
The download package (Potree.zip from November 29, 2022) does not include the package.json required for installation (and maybe others from the root dir). Please fix ASAP.

**Comment by gzotti** [comment]
OK, I took the git instead.

**Comment by m-schuetz** [comment]
Hi, yeah, I'd recommend directly using the dev branch which is essentially the same. I'm currently not maintaining this Potree repo anymore because I'm working on a rewrite that is based on WebGPU.
