### ISSUE TITLE
Unable to Set Camera View in Potree with Reality Capture Data

### ISSUE THREAD

**Issue by SlavenSoldo** [potree/potree#1334]
I'm using Potree to visualize 3D models created with Reality Capture. I have camera parameter data from Reality Capture and I'm trying to set the camera view in Potree to match the original camera view when a particular photo was taken.

Here's a sample of the data 'Camera parametars': 
```
{
    "name": "DJI_20230228131209_0041.jpg",
    "x": 26.2941,
    "y": 32.3176,
    "alt": 24.1355,
    "heading": -112.0371,
    "pitch": -1.1162,
    "roll": 44.6601,
    "f": 35.9491,
    "px": -0.0018,
    "py": -0.0006,
    "k1": -0.0485,
    "k2": 0.046,
    "k3": -0.1316,
    "k4": 0.0,
    "t1": -0.0014,
    "t2": 0.0013
}
```
And here's the code I'm using to try to set the view:

```
const setCamera = (imageName: string) => {
        const imageData = camParam.find((image) => image.name === imageName);

        const boxGeometry = new THREE.BoxGeometry(0.1, 0.1, 0.1);
        const boxMaterial = new THREE.MeshBasicMaterial({ color: 0x00ff00 });
        const boxMesh = new THREE.Mesh(boxGeometry, boxMaterial);

        const position = new THREE.Vector3(imageData.x, imageData.y, imageData.alt);
        boxMesh.position.copy(position);
        
        function toRadians(degrees) {
            return (degrees * Math.PI) / 180;
        }

        function calculateDirection(yaw, pitch) {
            const direction = new THREE.Vector3();
            direction.x = Math.cos(pitch) * Math.cos(yaw);
            direction.y = Math.sin(pitch);
            direction.z = Math.cos(pitch) * Math.sin(yaw);
            return direction;
        }

        const euler = new THREE.Euler(
            toRadians(imageData.pitch),
            toRadians(imageData.heading),
            toRadians(imageData.roll),
            'XYZ' // This is the order of rotations
        );

        boxMesh.quaternion.setFromEuler(euler);
        viewer.scene.scene.add(boxMesh);

        const direction = calculateDirection(toRadians(imageData.heading), toRadians(imageData.pitch));
        const distance = imageData.f; // Assuming `f` is the focus distance
        const target = new THREE.Vector3().copy(position).add(direction.multiplyScalar(distance));

        // viewer.scene.view.direction = direction;
        viewer.scene.view.position.copy(boxMesh.position);
        viewer.scene.view.lookAt(target);
       
    };
```
The desired result is that when I enter this function, the view should go to the position where the image was taken and view the exact scene from the image in the 3D model. However, it's not working as expected.

What I've tried:

- Verified that the camParam array contains the correct image data.
- Assumed Reality Capture uses a right-handed coordinate system (Z up) and converted the coordinates to Potree's left-handed coordinate system (Y up).
- Converted the heading, pitch, and roll values from degrees to radians.
- Set the Potree camera's position, direction, pitch, yaw, and radius based on the image data.

Despite this, the camera view in Potree does not match the original photo.
 
I also have another file from Reality Capture with this kind of data:

```
{
    "R(0,0)": -0.254,
    "R(0,1)": 0.664,
    "R(0,2)": -0.703,
    "R(1,0)": 0.927,
    "R(1,1)": 0.375,
    "R(1,2)": 0.019,
    "R(2,0)": 0.277,
    "R(2,1)": -0.646,
    "R(2,2)": -0.711,
    "Tx": 2.172,
    "Ty": -36.962,
    "Tz": 30.78,
    "F(pix)": 3041.638,
    "Image": "DJI_20230228131209_0041.jpg"
}
```

In this R represents rotation matrix and T translation.

I haven't used this yet, but I'm wondering if it might help.

Could anyone point me in the right direction to solve this problem? Any help would be greatly appreciated.

**Comment by andrealowa** [comment]
Hi any news??

**Comment by SlavenSoldo** [comment]
**After some trial and error, I managed to solve the issue. The problem seemed to be due to the different conventions used by Reality Capture and Potree. I have made changes to the rotation order and applied a negative sign to the heading value. Here's the solution:**

```
const setCamera = (imageName: string) => {
    const imageData = camParam.find((image) => image.name === imageName);
    const position = new THREE.Vector3(imageData.x, imageData.y, imageData.alt);

    function toRadians(degrees) {
        return (degrees * Math.PI) / 180;
    }

    const quaternion = new THREE.Quaternion();
    quaternion.setFromEuler(
        new THREE.Euler(toRadians(imageData.pitch), toRadians(imageData.roll), toRadians(-imageData.heading), 'ZXY')
    );

    const cameraDirection = new THREE.Vector3();
    cameraDirection.set(0, 0, -1);
    cameraDirection.applyQuaternion(quaternion);

    const distance = imageData.f; // Assuming `f` is the focus distance
    const target = new THREE.Vector3().copy(position).add(cameraDirection.multiplyScalar(distance));

    viewer.scene.view.position.copy(position);
    viewer.scene.view.lookAt(target);
};
```

**This solved the issue of the camera view in Potree not matching the original photo.**

**Comment by andrealowa** [comment]
Wow, I'm glad you figured it out. did you put this code in the html file? or did you use it to convert the parameters that come out of Reality capture, can you give me some more info? Thank you.
Andrew
