### ISSUE TITLE
Empty filename when running in folder scanning mode

### ISSUE THREAD

**Issue by davestewart** [potree/potree#137]
When I ran this code:

```
PotreeConverter.exe ..\src -o ..\trg -l 3 --generate-page
```

Filenames in the output folder came out as ..html and ..js, rather than the name of the source file.

**Comment by martinheidegger** [comment]
As this is an issue with the PotreeConverter I moved it to the PotreeConverter issue tracker: https://github.com/potree/PotreeConverter/issues/258
