### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [potree/potree#1379]
.

**Comment by aycaramba1224** [comment]
If your cesium version is 1.10x or higher
The cesiumViewer.camera.setView part needs to be modified.

cesiumViewer.camera.setView({
	destination: cp,
	orientation: {
		heading: heading,
		pitch: pitch,
		roll: 0.0
	}
});

I'm also having a hard time synchronizing potree camera and cesium camera. Can you tell me the source code if you've solved it?

**Comment by ghost** [comment]
[aycaramba1224] Que has logrado hasta ahora con cesium y potree? 
 tal  puedas ayudarme a a solucionar un problema que tengo en con cesium

**Comment by aycaramba1224** [comment]
I'm trying to synchronize the cesium camera with the potree camera.
But the point cloud is still in the air.
![image](https://github.com/potree/potree/assets/60164178/37e7c609-a3dc-4b69-b581-4c66d8d931eb)

**Comment by DANIEL102210** [comment]
Tienes un medio de comunicación, correo electrónico o skype...

**Comment by aycaramba1224** [comment]
-

**Comment by DANIEL102210** [comment]
te envie un correo con el asunto **POTRE-CESIUM**

Tienes experiencia en desarrollo de software con .NET core ?

**Comment by jpbolano** [comment]
Hi, could you solve this issue?

**Comment by FirepadCN** [comment]
@aycaramba1224 sir,how to use basemap with potree?

**Comment by aycaramba1224** [comment]
> [@aycaramba1224](https://github.com/aycaramba1224) sir,how to use basemap with potree?

![Image](https://github.com/user-attachments/assets/a79a6be9-2f17-4563-817a-be3f19785109)

![Image](https://github.com/user-attachments/assets/4179a9ea-0b9c-46fe-aa9d-c655c1813117)

It's designated by cesium, but you'll have to adjust the coordinate system. I can't remember it because it's been a while.
