### ISSUE TITLE
How to change hue of background gradient?

### ISSUE THREAD

**Issue by justingrant** [potree/potree#1386]
How can I change the hue of the colors of the background gradient of potree? Currently it's a bluish hue and I'd like the gradient to use only pure grays with R=G=B, so that it will match other pure-gray UI in the existing app that I'm integrating with potree.

I've traced through the source looking for what happens when I click the "Gradient" button in the left pane, and it looks like the actual gradient rendering happens here: 

https://github.com/potree/potree/blob/6ab926f3b042f13d4662ff4ebfa8033a34c5612b/src/viewer/EDLRenderer.js#L228-L230

But I'm not sure how the color gets set in `viewer.scene.sceneBG` and `viewer.scene.cameraBG`.  Any idea where that color setting lives in the code?

**Comment by kyrylozharkovskyi** [comment]
Hi try change this value
let chroma = [1, 1.5, 1.7]; defoult
let chroma = [0.6, 1.8, 2.2]; change like screnshot below
![image](https://github.com/potree/potree/assets/108589852/0fb3d987-d3ef-4881-a3df-9486666e7183)


more darck
let chroma = [0.40, 0.5, 0.8];
![image](https://github.com/potree/potree/assets/108589852/442f1645-8572-4f63-bede-e36ab035604f)


`static createBackgroundTexture(width, height) {
                function gauss(x, y) {
                    return (1 / (2 * Math.PI)) * Math.exp(- (x * x + y * y) / 2);
                };

                // map.magFilter = THREE.NearestFilter;
                let size = width * height;
                let data = new Uint8Array(3 * size);

                let chroma = [1, 1.5, 1.7];
                let max = gauss(0, 0);

                for (let x = 0; x < width; x++) {
                    for (let y = 0; y < height; y++) {
                        let u = 2 * (x / width) - 1;
                        let v = 2 * (y / height) - 1;

                        let i = x + width * y;
                        let d = gauss(2 * u, 2 * v) / max;
                        let r = (Math.random() + Math.random() + Math.random()) / 3;
                        r = (d * 0.5 + 0.5) * r * 0.03;
                        r = r * 0.4;

                        // d = Math.pow(d, 0.6);

                        data[3 * i + 0] = 255 * (d / 15 + 0.05 + r) * chroma[0];
                        data[3 * i + 1] = 255 * (d / 15 + 0.05 + r) * chroma[1];
                        data[3 * i + 2] = 255 * (d / 15 + 0.05 + r) * chroma[2];
                    }
                }

                let texture = new DataTexture(data, width, height, RGBFormat);
                texture.needsUpdate = true;

                return texture;
            }`

**Comment by justingrant** [comment]
Perfect, thanks so much @kyrylozharkovskyi for the pointer. I ended up using `1.4, 1.4, 1.4` which looks great for my app.
