### ISSUE TITLE
Rotation between the 360 image and the Pointcloud

### ISSUE THREAD

**Issue by jpbolano** [potree/potree#1389]
Hi,
I am trying to integrate 360 images in a potree viewer that already is rendering a pointcloud, the pointcloud has EPSG: 32618 and is well located as well as the 360 images that are being located over the route on the pointcloud. The problem that I have is that when i open the 360 images the pointcloud are a little rotated in comparison to the 360 images.
![image](https://github.com/potree/potree/assets/147423726/5bd2abfc-4e2a-475e-a93d-5c4cd7da3611)
![image](https://github.com/potree/potree/assets/147423726/9c003ed3-775a-4f38-bd12-a7532e1b3503)
The file that has the information for each one of the images has the coordinates in easting and northing so i converted it to lat and long and also it has heading and not course but i assume this parameter as the same. 
This is a ss of my original data 
![image](https://github.com/potree/potree/assets/147423726/dd0454be-c4cd-4346-b911-7ffad8ecde1a)
and this is a ss of my coordinates.txt
![image](https://github.com/potree/potree/assets/147423726/ba777ef1-67af-49c1-ab4d-e04b5548e9f3)
Has anyone had this similar problem?

**Comment by MyosQ** [comment]
Yes, heading is the same as course in this context.

A few ideas that come to mind:
* There might be a "Boresight" offset between the camera and the sensor measuring the course, pitch, and roll. Often, they are mounted close together, but a small rotational offset can have a significant impact, as seen in your images.

* Grid north/True north distortion. See for example, https://github.com/bsb808/geonav_transform/issues/1.  
This issue is more prevalent if you're far from the center of your UTM zone. 

Are you sure it is a rotational issue only, and not translational as well?

**Comment by jpbolano** [comment]
After changing the values of the parameters for the orientation in the image360 class, I think that the issue is more related to a translational misalignment because I tried to fit the better alignment changing the values for the orientation but it did not work.
![image](https://github.com/potree/potree/assets/147423726/320f3345-1f8d-4bd4-9edc-2b0d885d5d26)
After a lot of tries, I think that the misalignment seems to be that the point cloud seems to be located closer to the screen than the 360 images.
![image](https://github.com/potree/potree/assets/147423726/3c3265b4-2127-4d4e-8a3a-7b303dc06994)
For this same image, in this orientation the car and truck  shapes in the point cloud are also located closer to the screen than these shapes in the 360 images. 
![image](https://github.com/potree/potree/assets/147423726/eb953002-225c-4637-bd38-57d38bbd91b3)
![image](https://github.com/potree/potree/assets/147423726/e2664d8b-650d-4f5d-b5e2-ee3c162d3b89)
I do not know if maybe you have any idea on how to solve this error?

**Comment by MyosQ** [comment]
I agree, it looks like the position of each images is a bit off. 

I don't understand how and why you converted easting/northing to lat/lon. 
You mentioned that the point cloud is in EPSG: 32618, which refers to the UTM zone 18N projection, but the coordinates in your coordinates.txt don't look like typical UTM coordinates. Are you sure you performed the conversion correctly?

**Comment by jpbolano** [comment]
My point cloud is in EPSG:32618 and also the coordinates for the 360 images are in this coordinates but I converted the easting and northing to lat/long for the 360 images for my inintial example but then I realized that this was not necessary. Yes the conversion was made correctly because I use a python library to perform it and I made a console log to see the easting and northing values that result of the conversion from the lot/lan values that i passed it. The difference between the converted values and the original values of my 360 images was of near  8 micrometers. However, I modified my coordinates.txt and the code so the lat and lon values are in utm and the same still happens
![image](https://github.com/potree/potree/assets/147423726/7e9ab440-f3ac-42a8-b595-bd877effc4d0)
![image](https://github.com/potree/potree/assets/147423726/31cb5bf8-d32d-4e66-9509-e27ced5a94a2)

**Comment by MyosQ** [comment]
Okay, I suggest looking into whether boresight offsets could be the issue. Check the hardware and see if the displacement between the IMU, camera, and Lidar is significant. Otherwise, I'm out of ideas.

Hope you figure it out! :)

**Comment by WuMianzhi** [comment]
Hi, im doing the same thing as u, combine the  pointcloud and the  panoramic image together, but in very first place, the position of panoramic and  pointcloud cant be together, and pointcloud looks like float in the panoramic :)

**Comment by jpbolano** [comment]
Hi, what do you mean with "the position of panoramic and pointcloud cant be together" ?, and yes i have a misalignment between the panoramic and the pointcloud due to a boresight and level arm effect that i have to fix

**Comment by WuMianzhi** [comment]
Thanks 4 u reply, now our team willing to generate a 360 pic from point cloud and then combine them together, beacause we even cant achieve the results like yours, by the way do u solve it?

**Comment by jpbolano** [comment]
If you can show me your code maybe, I can help you. Yes, I could solve it the problem of the misalignment was due to a boresight and level arm effect of the acquisition equipment.

**Comment by WuMianzhi** [comment]
Im sorry that cant show mine code, here is mine status, first we have a las file which had already been transform to wgs84 coordinate system,  some 360 pano pics that we take we have the location about this pics, this the all data we have, and we dont know how to do it like u, if you dont mind, would you  like to tell me about the way your archive that :)

**Comment by jpbolano** [comment]
What is the coordinate reference system for your pointcloud?. Also, your images have info about roll, pitch yaw? or omega, phi, kappa?

**Comment by WuMianzhi** [comment]
the coordinate reference system of mine pointcllud is EPSG:32650, and we have rool, pitch and yaw

**Comment by jpbolano** [comment]
Ok, have you made the coordinates.txt file? It should be something like this. And with this file you can make the load of the 360 images. See this example https://github.com/potree/potree/blob/6ab926f3b042f13d4662ff4ebfa8033a34c5612b/examples/360.html
![image](https://github.com/potree/potree/assets/147423726/818abe41-37db-477f-a668-98560639179d)

**Comment by WuMianzhi** [comment]
if we made this file, and the potree could auto match the pano pics, and we have the lng and lat which is wgs84 should we transform to the same coordinate with cloud point? and but we dont have alt info

**Comment by jpbolano** [comment]
It is not necessary to transform it because you can specify in potree the transform from WGS84 to your pointcloud projection. The altitude info is a problem because you need this to locate the sphere that contains the images but maybe you can try to set up a default value to the altitude that is on the surface of the point cloud so it can be located (i am not sure if this works).

**Comment by WuMianzhi** [comment]
ok, the source of ur data alt is what? and u just say u have solve the problem about misalignment between the panoramic and the pointcloud due to a boresight and level arm effect, how do u solve it plz tell me?

**Comment by jpbolano** [comment]
The source is a gps that it is integrated with the camera and it locates each image with the coordinates of each one using an imu. I could solve it but i had to use a software to correct these errors called orbit.

**Comment by WuMianzhi** [comment]
thank u very much, with your help we finanlly have the solution, if u dont mind i want to buy u a coffe would you leave your payment info?

**Comment by jpbolano** [comment]
No problem, It is not necessary, glad that you could solve it

**Comment by minhuan520** [comment]
Hello, I'm having a similar problem now, I myself am able to align the point cloud and panorama in the Y upward coordinate system, but not in the Z direction of the potree

**Comment by minhuan520** [comment]
我的camera数据是这样的
![Uploading image.png…]()

**Comment by minhuan520** [comment]
![image](https://github.com/potree/potree/assets/40617168/3bedbd66-6cea-4f28-9ec1-4a2cb921f8cd)
我的数据是这样的额

**Comment by minhuan520** [comment]
RPY  roll pitch yaw

**Comment by minhuan520** [comment]
![image](https://github.com/potree/potree/assets/40617168/2d4a595e-f673-4b6c-90e8-b9b73be1977a)
This is the result of the Y axis, the panorama and the point cloud match is still in line with my expectations, and the rest of the scene will perform better, but I rotated X and Z by 90 according to the potree, and the direction is always wrong.

**Comment by minhuan520** [comment]
![image](https://github.com/potree/potree/assets/40617168/032320f0-aef3-4792-9a2f-634fed5c14a8)
This is another scene with the Y-axis upwards.

**Comment by minhuan520** [comment]
![image](https://github.com/potree/potree/assets/40617168/91af4bd2-bfeb-4a4b-8ba9-aed6a4c9f1e4)
But in the potree example, the Z-axis goes up

**Comment by minhuan520** [comment]
this is focus
Code：
`
			{
				// orientation
				let { course, pitch, roll } = image360;

				this.sphere.rotation.set(
                    roll + Math.PI/2,
                    -pitch,
                    -course  + Math.PI/2,
                    'ZXY'
                );
		
			}
			// this.sphere.position.set(...image360.position);

			this.sphere.position.copy(image360.position);`

**Comment by minhuan520** [comment]
My data itself is radians, so I don't need to convert angles and radians

**Comment by WuMianzhi** [comment]
Author say :" I could solve it but i had to use a software to correct these errors called orbit." maybe u can try it

**Comment by minhuan520** [comment]
What do I need to do, what is the cause of this problem, I always thought it was a problem of my choice, not a problem with the data, because I was okay in a Y-axis up scenario

**Comment by minhuan520** [comment]
> Author say :" I could solve it but i had to use a software to correct these errors called orbit." maybe u can try it

What do I need to do, what is the cause of this problem, I always thought it was a problem of my choice, not a problem with the data, because I was okay in a Y-axis up scenario

**Comment by minhuan520** [comment]
> Author say :" I could solve it but i had to use a software to correct these errors called orbit." maybe u can try 
我看大佬是中国人，有其余的方式联系吗？

**Comment by WuMianzhi** [comment]
> > Author say :" I could solve it but i had to use a software to correct these errors called orbit." maybe u can try 
> 
> 我看大佬是中国人，有其余的方式联系吗？

lsy98wx

**Comment by wenjing0213** [comment]
> The source is a gps that it is integrated with the camera and it locates each image with the coordinates of each one using an imu. I could solve it but i had to use a software to correct these errors called orbit.

Hello, we directly assigned the IMU data in the acquisition process to the panoramic data through the timestamp, but there was an error in this way, so that the panoramic data and the point cloud data could not completely coincide. Do you have any good solutions? Thank you！

**Comment by minhuan520** [comment]
> > The source is a gps that it is integrated with the camera and it locates each image with the coordinates of each one using an imu. I could solve it but i had to use a software to correct these errors called orbit.
> 
> Hello, we directly assigned the IMU data in the acquisition process to the panoramic data through the timestamp, but there was an error in this way, so that the panoramic data and the point cloud data could not completely coincide. Do you have any good solutions? Thank you！
If you are using potree's built-in capabilities, you first need to confirm whether your data is consistent with the official data object. I now find that a large probability is that the data needs to be converted. If the panorama and point cloud are collected together, then the data is theoretically reasonable, which should require data conversion.

**Comment by minhuan520** [comment]
> > The source is a gps that it is integrated with the camera and it locates each image with the coordinates of each one using an imu. I could solve it but i had to use a software to correct these errors called orbit.
> 
> Hello, we directly assigned the IMU data in the acquisition process to the panoramic data through the timestamp, but there was an error in this way, so that the panoramic data and the point cloud data could not completely coincide. Do you have any good solutions? Thank you！

If you are using potree's built-in capabilities, you first need to confirm whether your data is consistent with the official data object. I now find that a large probability is that the data needs to be converted. If the panorama and point cloud are collected together, then the data is theoretically reasonable, which should require data conversion.

**Comment by wenjing0213** [comment]
已收到您的邮件,祝生活愉快~

**Comment by wenjing0213** [comment]
> > > The source is a gps that it is integrated with the camera and it locates each image with the coordinates of each one using an imu. I could solve it but i had to use a software to correct these errors called orbit.
> > 
> > 
> > Hello, we directly assigned the IMU data in the acquisition process to the panoramic data through the timestamp, but there was an error in this way, so that the panoramic data and the point cloud data could not completely coincide. Do you have any good solutions? Thank you！
> 
> If you are using potree's built-in capabilities, you first need to confirm whether your data is consistent with the official data object. I now find that a large probability is that the data needs to be converted. If the panorama and point cloud are collected together, then the data is theoretically reasonable, which should require data conversion.

Can we add a contact information and discuss it in detail?

**Comment by dyjandxy** [comment]
@jpbolano hello，I'm facing the same issue,
did you find a solution ?

**Comment by Decones80** [comment]
Same here, struggling to work this out. Thounsands of hours spent and still have big aligment issues between lidar and insta X4 spheres images

**Comment by wenjing0213** [comment]
已收到您的邮件,祝生活愉快~
