### ISSUE TITLE
Strange addScalar(1) in TransformationTool

### ISSUE THREAD

**Issue by chiccorusso** [potree/potree#139]
Hi Markus.
I found strange the presence of an addScalar(1) in TransformationTool.createScaleHandle.dragEvent().

The diff that is calculated at TransformationTool.js:341 is added to the original scale value, so the addScale(1) should not be needed. Actually, in my application it has the side effect to instantly grow the clip volume at the mouseDown on any scale handle. removing it, the TransformationTool works OK.

In the examples, its presence or absence seems to change anything. Is it ok to remove it?

**Comment by m-schuetz** [comment]
Sorry for the late reply, I always get carried away when working on things. 
You're right, the addScalar(1) is does not belong there.
Thanks the notice!

https://github.com/potree/potree/commit/127fcda3d78ba5b05c4c71ebae39c7c33c9575f0
