### ISSUE TITLE
intensity color customize

### ISSUE THREAD

**Issue by 01iePi** [potree/potree#1398]
When  
material.activeAttributeName = "intensity",  
the intensity color is white to black.
How to set custom color for intensity?
Classification is rough and not suitable when adding pointclouds sequentially as the data range changes.

**Comment by TBdt38** [comment]
did you find a way to control the color scaling? i have exact same need.

**Comment by 01iePi** [comment]
The following is example.

in potree.js　
  vec3 getColor(){
  #elif defined color_type_intensity
```javascript

    float w = getIntensity();
    float r=0.0;
    float g=0.0;
    float b=0.0;
    if (w>=1.0){
      r=1.0;
    }
    else if (w<=0.0){
      b=1.0;
    }
    else {     
      if (w <= 0.5) {
        r = 0.0;
        g = w * 2.0;
        b = 1.0;
      }
      else {
        r = 0.0;
        g = 1.0;
        b = 1.0 - (w - 0.5) * 2.0;
      }
    }
    color = vec3(r, g, b); 
```
