### ISSUE TITLE
How get latitude longitude from x,y,z point ?

### ISSUE THREAD

**Issue by NoeTeria** [potree/potree#1410]
Hello,
I would like to know if it is possible to know the gps latitude longitude position of a point rather than the x, y, z coordinates ?
Thank you

**Comment by wenjing0213** [comment]
u just need to convert the xyz in the point cloud coordinate system to wgs84 latitude and longitude.

**Comment by NoeTeria** [comment]
Thank you for your reply and your help.
That's what I've been trying to do, but without succes, the result is wrong, I must be making a mistake somewhere. 

When i'm using PotreeConverter, the source ".las" file uses the EPSG:2154 projection, so here's the option I use when converting the 3D model: 
`--projection "+proj=lcc +lat_0=46. 5 +lon_0=3 +lat_1=49 +lat_2=44 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs" `

In my file, I use this for the source projection:
`var firstProjection = '+proj=lcc +lat_0=46.5 +lon_0=3 +lat_1=49 +lat_2=44 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0 +units=m +no_defs +type=crs';`
And this for the destination projection:
`var secondProjection = "+proj=longlat +datum=WGS84 +no_defs";`

The result is not at all the expected coordinates.

Could the problem be linked to the fact that the OpenStreetMap on the top left doesn't position my 3D model correctly? I'm positioned in the sea, but I don't know how to correct this.

**Comment by NoeTeria** [comment]
The problem was with the .las file, but this has now been resolved.
