### ISSUE TITLE
Change minimap from Openstreetmap to own WMS

### ISSUE THREAD

**Issue by HolgerHerrmannGE** [potree/potree#1420]
Hello,

is there an easy way to change the Openstreetmap-URL of the minimap to my own WMS-Service-map? For example I would like to show this wms in minimap [https://gdi.gelsenkirchen.de/wss/service/WMSStadtkarten/guest?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=SK15_farb2024](url)

Any code or hints would be nice.

Best regards

**Comment by kyrylozharkovskyi** [comment]
Hi yes

That was defolut
`                let mapOSM = new ol.layer.Group({
                    layers: [

                        new ol.layer.Tile({
                            opacity: 0.8,
                            source: new ol.source.OSM({

                            })

                        }),

                        this.toolLayer,
                        this.annotationsLayer,
                        this.sourcesLayer,
                        this.sourcesLabelLayer,
                        this.images360Layer,
                        extentsLayer,
                        cameraLayer,
                        cameraLayerpoint
                    ]
                });`
                
                
                


                
                
                
                Example with WMS
                
                
                
                `                let gugik_ortofotomapa_HighResolution_WMS = new ol.layer.Group({
                    layers: [

                        new ol.layer.Image({
                            className: 'background',
                            opacity: 1,
                                source: new ol.source.ImageWMS({
                                url: 'https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution',
                                params: {
                                    layers: 'Raster'
                                }
                            })
                        }),


                        this.toolLayer,
                        this.annotationsLayer,
                        this.sourcesLayer,
                        this.sourcesLabelLayer,
                        this.images360Layer,
                        extentsLayer,
                        cameraLayer,
                        cameraLayerpoint
                    ]
                });`
                
                
                
                
![222](https://github.com/potree/potree/assets/108589852/d09c3953-92f8-4087-b3ce-0ebd1135a543)

**Comment by kyrylozharkovskyi** [comment]
@HolgerHerrmannGE 
Hre is your code 
`                        new ol.layer.Image({
                            className: 'background',
                            opacity: 1,
                                source: new ol.source.ImageWMS({
                                url: 'https://gdi.gelsenkirchen.de/wss/service/WMSStadtkarten/guest?request=GetLegendGraphic&version=1.3.0&format=image/png',
                                params: {
                                    layers: 'SK15_farb2024'
                                }
                            })
                        }),`

![333](https://github.com/potree/potree/assets/108589852/517d0385-26c5-4b8b-875a-4d0fb28e4a0f)
![222222](https://github.com/potree/potree/assets/108589852/a0aa5277-ab97-4514-a9fd-bb5a2f97eba0)




![image](https://github.com/potree/potree/assets/108589852/5b851b7b-9e25-4f16-81dd-96a9e9a84eb5)

**Comment by HolgerHerrmannGE** [comment]
Sorry for the late reply. Thank you for your code. Works perfect for me.
