### ISSUE TITLE
Make altitude gradient and classification colors changeable

### ISSUE THREAD

**Issue by potree** [potree/potree#143]
Both are hardcoded at the moment:
Altitude gradient: https://github.com/potree/potree/blob/master/src/materials/PointCloudMaterial.js#L538
classification color: https://github.com/potree/potree/blob/master/src/materials/PointCloudMaterial.js#L684

**Comment by potree** [comment]
Gradient done: https://github.com/potree/potree/commit/178e4c021a86a5fc680500804a5c46df863326be

**Comment by potree** [comment]
Classification done: https://github.com/potree/potree/commit/f44c830c09d0475da3554b558edc2fce2c2b157f

**Comment by potree** [comment]
Gradient can be set as follows:

```
pointcloud.material.gradient = Potree.Gradients.GRAYSCALE;
```

A custom gradient can be defined like this:

```
var customGradient = [
	[0, new THREE.Color(0.278, 0, 0.714)],
	[1/6, new THREE.Color(1, 0, 1)],
	[2/6, new THREE.Color(0, 1, 1)],
	[3/6, new THREE.Color(0, 1, 0)],
	[4/6, new THREE.Color(1, 1, 0)],
	[5/6, new THREE.Color(1, 0.64, 0)],
	[1, new THREE.Color(1, 0, 0)]
];
pointcloud.material.gradient = customGradient;
```

**Comment by potree** [comment]
A custom classification lookup table can be defined like this: 

```
var customClassification =  {
	0: 			new THREE.Color(0.2, 0.5,0.5),
	1: 			new THREE.Color(0.2, 0.5,0.5),
	2: 			new THREE.Color(0.3, 0.32, 0.18),
	3: 			new THREE.Color(1.0, 1.0, 0.0),
	4: 			new THREE.Color(0.0, 0.8, 0.0),
	5: 			new THREE.Color(0.6, 0.6, 0.0 ),
	6: 			new THREE.Color(1.0, 0.66, 0.0),
	7:			new THREE.Color(1.0, 0, 1.0   ),
	8: 			new THREE.Color(1.0, 0, 0.0   ),
	9: 			new THREE.Color(0.0, 0.0, 1.0 ),
	12:			new THREE.Color(1.0, 1.0, 0.0 ),
	"DEFAULT": 	new THREE.Color(0.3, 0.6, 0.6 )
}

pointcloud.material.classification = customClassification;
```

Color codes can be optionally set. DEFAULT must be set and specifies the color to use in case no color code has been specified.

**Comment by antoinebio** [comment]
Excuse me to open that post but i was wondering if we can add more class tags than 12 ?
IS Potree able to display more classes ?
thanks,
antoine

**Comment by adamsteer** [comment]
@antoinebio yes, I’ve used it for all the classes available in LAS1.4 - you could add as many as you have set in your point cloud `Classification`s.

I need to look back into the code, I think I had to set things in two places, which was a bit awkward. I’ll look this week. In the Potree viewer, you can still turn off classes which are not listed (eg 18 - high noise - but also sometimes bridge decks :/ ):

`viewer.setClassificationVisibility( 18, false);`

**Comment by antoinebio** [comment]
is it by changing something at potree convertor step ?
or directly in potree viewer ?
antoine
