### ISSUE TITLE
Compiling and running it in Linux

### ISSUE THREAD

**Issue by Madity** [potree/potree#146]
I have been trying to compile the code and run in Ubuntu 14.04 so that I can convert .las files to render object. I am unable to do that. Are there any instructions to do this or if there is any other way to convert .las files using potreeconverter?

**Comment by potree** [comment]
Hi!

Take a look at https://github.com/potree/PotreeConverter/issues/115 and https://github.com/potree/PotreeConverter/issues/128

There are some problems with platform independance but there are some workarounds described in these issues.,

**Comment by Madity** [comment]
The solution provided to this issue - https://github.com/potree/PotreeConverter/issues/115

This worked!

The executable file is created! But now every time I try to convert point cloud using potree, it ends up in segmentation fault!

**Comment by m-schuetz** [comment]
The latest develop branch works fine for me under debian. 
Do you still have this issue?

**Comment by martinheidegger** [comment]
I assume it worked out, closing this issue :+1:
