### ISSUE TITLE
Height of geopackage layers

### ISSUE THREAD

**Issue by sSeLeMaHs** [potree/potree#1463]
Hi,

Im quite new to Potree and am no expert in programming. 
I want to implement some geopackage layers (lines) into my webpage. I took the code from the example and managed to fit the geopackage well regarding latitude and longitude. 
I Wonder how the height of the depiction is determined. When i look at my pointcloud in comparison to the lines, i assume that maybe some sort of mean height value is calculated from the pointcloud and the geopackage is set to this height.

Is there a way to adjust the height so that it fits my pointcloud better?

**Comment by Hbm1g18** [comment]
Hi, 
Just checking, are all the lines in the geopackage layer loading at the same height? in this case, a Z value around 20?

**Comment by sSeLeMaHs** [comment]
Yes all the Lines have the same z value. I even tried to change them manualy by several meters, but the lines in the viewer always have the same height.

**Comment by Hbm1g18** [comment]
I believe the issue is in the potree.js file in libs/potree/

`static featureToSceneNode(feature, matLine, geopackageProjection, transform){
			let geometry = feature.geometry;
			
			let color = new Color(1, 1, 1);
			
			if(feature.geometry.type === "Point"){
				let sg = new SphereGeometry(1, 18, 18);
				let sm = new MeshNormalMaterial();
				let s = new Mesh(sg, sm);
				
				let [long, lat] = geometry.coordinates;
				let pos = transform.forward(geopackageProjection.forward([long, lat]));
				
				s.position.set(...pos, 20);
				
				s.scale.set(10, 10, 10);
				
				return s;
			}else if(geometry.type === "LineString"){
				let coordinates = [];
				
				let min = new Vector3(Infinity, Infinity, Infinity);
				for(let i = 0; i < geometry.coordinates.length; i++){
					let [long, lat] = geometry.coordinates[i];
					let pos = transform.forward(geopackageProjection.forward([long, lat]));
					
					min.x = Math.min(min.x, pos[0]);
					min.y = Math.min(min.y, pos[1]);
					min.z = Math.min(min.z, 20);
					
					coordinates.push(...pos, 20);
					if(i > 0 && i < geometry.coordinates.length - 1){
						coordinates.push(...pos, 20);
					}
				}
				
				for(let i = 0; i < coordinates.length; i += 3){
					coordinates[i+0] -= min.x;
					coordinates[i+1] -= min.y;
					coordinates[i+2] -= min.z;
				}
				
				const lineGeometry = new LineGeometry();
				lineGeometry.setPositions( coordinates );

				const line = new Line2( lineGeometry, matLine );
				line.computeLineDistances();
				line.scale.set( 1, 1, 1 );
				line.position.copy(min);
				
				return line;
			}else if(geometry.type === "Polygon"){
				for(let pc of geometry.coordinates){
					let coordinates = [];
					
					let min = new Vector3(Infinity, Infinity, Infinity);
					for(let i = 0; i < pc.length; i++){
						let [long, lat] = pc[i];
						
						let pos = transform.forward(geopackageProjection.forward([long, lat]));
						
						min.x = Math.min(min.x, pos[0]);
						min.y = Math.min(min.y, pos[1]);
						min.z = Math.min(min.z, 20);
						
						coordinates.push(...pos, 20);
						if(i > 0 && i < pc.length - 1){
							coordinates.push(...pos, 20);
						}
					}
					
					for(let i = 0; i < coordinates.length; i += 3){
						coordinates[i+0] -= min.x;
						coordinates[i+1] -= min.y;
						coordinates[i+2] -= min.z;
					}

					const lineGeometry = new LineGeometry();
					lineGeometry.setPositions( coordinates );

					const line = new Line2( lineGeometry, matLine );
					line.computeLineDistances();
					line.scale.set( 1, 1, 1 );
					line.position.copy(min);
					
					return line;
				}
			}else {
				console.log("unhandled feature: ", feature);
			}`

You can see here that the code is loading with ...pos, 20);
So all the loaded shapes (polygons, points, lines) are in the correct location, but with a height set at 20.

In my potree instances I've been loading contours where the elevation is in an attribute called 'elev' so I adjusted it all to load as follows:

`}else if(geometry.type === "LineString"){
				let coordinates = [];
				
				let min = new Vector3(Infinity, Infinity, Infinity);
				for(let i = 0; i < geometry.coordinates.length; i++){
					let [long, lat] = geometry.coordinates[i];
					let pos = transform.forward([long, lat]);
					
					min.x = Math.min(min.x, pos[0]);
					min.y = Math.min(min.y, pos[1]);
					min.z = Math.min(min.z, feature.properties.elev);
					
					coordinates.push(...pos, feature.properties.elev);
					if(i > 0 && i < geometry.coordinates.length - 1){
						coordinates.push(...pos, feature.properties.elev);
					}
				}
				
				for(let i = 0; i < coordinates.length; i += 3){
					coordinates[i+0] -= min.x;
					coordinates[i+1] -= min.y;
					coordinates[i+2] -= min.z;
				}`

If you have it as z, or pos[2] then you can use this in the potree.js file instead.
Odd that the original uses 20, seems to have been forgotten.

Hopefully this can help

**Comment by sSeLeMaHs** [comment]
Thank you very much, it works perfectly now. 
pos[2] doesn't work, but with the "feature.properties.elev" it works fine.
