### ISSUE TITLE
alter shapefile linewidth?

### ISSUE THREAD

**Issue by brsmaine** [potree/potree#1487]
is there some trick to controlling linewidth for shapefiles?  i've tried everything i can think of and have only been able to change the colors...

![image](https://github.com/user-attachments/assets/325c1c8a-39ec-45bf-9703-343c9171eb64)

http://brs-maine.com/ptdev/examples/test.html

you'll have to double-click the cloud or a layer to snap to the content...apologies in advance!

happy to provide whatever details may help...just think it has to be something simple i'm missing.

thanks!

**Comment by brsmaine** [comment]
may have a solution - investigating...

**Comment by kyrylozharkovskyi** [comment]
it will depend on how you use the option on three,js generally you can change the line width for a line. Probably need to update three,js and try to use this option https://threejs.org/examples/?q=line#webgl_lines_fat
