### ISSUE TITLE
Point picking / Measuring Tools Pointcloud flickering

### ISSUE THREAD

**Issue by davijo** [potree/potree#149]
Hi

The latest build introduced a new kind of issue regarding flickering after activating anything that has to do with real-time point picking from the pointcloud. 
The flickering comes with a warning message:
[.WebGLRenderingContext-23A84A40] GL ERROR :GL_INVALID_OPERATION : glDrawArrays: attempt to access out of range vertices in attribute 1

![image](https://cloud.githubusercontent.com/assets/8625487/7808600/20f86f7c-039d-11e5-9410-a8b9954f8cc3.png)

It seems to be somehow related to 3D objects (such as the picking sphere) in the scene.

Any ideas what might be causing this?

Btw, should this be scoped? https://github.com/potree/potree/blob/master/src/utils/MeasuringTool.js#L675

Thanks!

**Comment by potree** [comment]
You're right, this should be scoped. 
I'll look into the flicker issue.

**Comment by davijo** [comment]
Hi,

Just a quick comment on my findings.
It seems the issue might actually be originating from Potree.TextSprite()

If there are no text sprites in the scene then the problem does not show up.

I will continue testing.

Cheers

**Comment by potree** [comment]
My thoughts were that this comes from an activated normal attribute in a point cloud without normals.

**Comment by m-schuetz** [comment]
fixed in develop: https://github.com/potree/potree/commit/3abe4fde6591e77c9dcbde0a158c75bbc4a66937

Added [0,0,0] normal values to point clouds without normals. I'm no longer getting the error message and picking works smoothly for me. 
Does it work for you, too?

**Comment by davijo** [comment]
Yes, working again!

Many thanks.

**Comment by m-schuetz** [comment]
Great.
Scoping fixed as well: https://github.com/potree/potree/commit/b0c08afafac4693767b56178182730faf8c5b33f
