### ISSUE TITLE
Shader compilation error

### ISSUE THREAD

**Issue by Maartenvm** [potree/potree#150]
When using the something akin to the "Splats" quality setting ( setting "pointcloud.material.weighted = true;" ) this WebGL error happens:

THREE.WebGLShader: Shader couldn't compile.
(anonymous function) @ three.js:24702
(anonymous function) @ three.js:24559
initMaterial @ three.js:21968
setProgram @ three.js:22041
renderBufferDirect @ three.js:20304
renderObjects @ three.js:21241
render @ three.js:21106
<...>

THREE.WebGLShader: gl.getShaderInfoLog() ERROR: 0:159: 'w' : redefinition

**Comment by Maartenvm** [comment]
I've actually already tracked this down, it comes down to this piece of code in Shaders.js

 "	#if defined weighted_splats",
 "	    float w = pow(1.0 - (u*u + v*v), 2.0);",
 "		gl_FragColor.rgb = gl_FragColor.rgb * w;",
 "		gl_FragColor.a = w;",
 "	#endif",

Changing "w" to "wgt" fixes the issue.

 "	#if defined weighted_splats",
 "	    float wgt = pow(1.0 - (u*u + v*v), 2.0);",
 "		gl_FragColor.rgb = gl_FragColor.rgb * wgt;",
 "		gl_FragColor.a = wgt;",
 "	#endif",

**Comment by potree** [comment]
Thanks, I'll fix this shortly!

**Comment by m-schuetz** [comment]
Did you set material.interpolation to false? Weighted splats and interpolation are not meant to be used together.

**Comment by Maartenvm** [comment]
That seems to have been the issue indeed. Thanks.

But ... maybe it's a good idea to add a slightly more insightful error message? ;)

**Comment by thanmai95** [comment]
Hi, @m-schuetz  @potree 
I'm getting the following errors,please help me out in resolving this issues.

**1) THREE.WebGLShader: Shader couldn't compile.**

 **2) THREE.WebGLShader: gl.getShaderInfoLog() fragment WARNING: 0:4: 'GL_EXT_frag_depth' : extension is not supported
ERROR: 0:60: 'gl_FragDepthEXT' : undeclared identifier
ERROR: 0:60: 'assign' : l-value required (can't modify a const)**
