### ISSUE TITLE
Moved Origin of viewed points

### ISSUE THREAD

**Issue by dmercel** [potree/potree#153]
The origin in the .html viewer seems to be different to the originally converted data, which is very frustrating when trying to add new geometry to the scene in a specific location.  It appears to be a translation as well as a rotation, and it isn't obvious to me what is causing the issue.

After converting the data into the octree format I have reimported the segments into CloudCompare to see if it has moved.  However, it is in the same location as the original file.  Therefore, the change of origin is occurring when it is being rendered in the .html files.  

Any ideas as to how to stop this issue?  I really need to keep my data where I am expecting it to be, rather than some new, unknown location.  
I have tried different import formats and they all seem to have the same issue too.  I just can't quite figure out why it is happening.

Any feedback much appreciated.
Thanks,
Dave

**Comment by pinpointmapping** [comment]
It was my understanding that web mapping uses web Mercator auxiliary sphere coordinate system, perhaps your data is having an incorrect transformation applied by the reprojection.  Perhaps you should do all reprojection a via GIS software prior to use on the web?

**Comment by potree** [comment]
This is generaly necessary for 2 reasons:
- Georeferenced point clouds have very large coordinates which severely reduce precision. To preserve precision, point clouds are moved to the origin. 
- Most applications use z as up-vector. However, WebGL, three.js and subsequently potree use y as the up-vector. The rotation, or rather coordinate flipping, is necessary to fix this.

If you want to use the same coordinates as your point cloud, you can try to add your objects not to the scene but to the reference frame:

    referenceFrame.add(object);

The referenceFrame is the node that transforms everything to the origin.

Another possibility is to remove the transformations from the reference frame by deleting the respective lines like:

```
referenceFrame.position.copy(sg.center).multiplyScalar(-1); // remove transformation to origin
flipYZ(); // also remove all calls to flipYZ()
```

**Comment by dmercel** [comment]
The referenceFrame.add(object) was exactly what I needed.  Thank you for pointing that out.  I now understand what was happening.

Many thanks,

Dave
