### ISSUE TITLE
Switching to early loop termination to simulate dynamic loops in shaders

### ISSUE THREAD

**Issue by m-schuetz** [potree/potree#154]
You can help by checking this page and telling me if it works properly for you:
http://potree.org/demo/experimental/perf/r01/examples/test.html
This page has a vertex shader that loops from 0 to 1000 but exits early. 

Performance should be comparable to this old matterhorn demo:
http://potree.org/demo/potree_2014.12.30/examples/matterhorn.html

= Background = 

WebGL does not support dynamic loop ranges so at the moment, shader code is recompiled whenever the loop range changes.

I'd like to simplify this (and fix a bug with adaptive point sizes) by creating long loops and terminating early, for example:

```
for(int i = 0; i < 1000.0; i++){
    ...
    if(done){
        break;
    }
}
```

My GeForce GTX 860M and my samsung galaxy s4 active GPU both seem to support early loop termination. 
Waiting for some feedback from users with other devices(mac, iphone) before applying this change.

**Comment by m-schuetz** [comment]
There are 2 particular loops that would benefit from this.
The loop that calculates the local octree depth and the loop that iterates through all clip boxes.

**Comment by davijo** [comment]
Quadro K2000M seems to be working fine, though there is some flickering in the more distant pointcloud, maybe not even related to this.

**Comment by chiccorusso** [comment]
MacBook Pro with Retina Display and NVIDIA GeForce GT 650M 1024 MB works great!

**Comment by m-schuetz** [comment]
Thanks for the feedback!

I've now changed shader recompilation on range change to long range loops with early termination:
https://github.com/potree/potree/commit/709fc2ebca078039091083456f157dfca0df29cb
