### ISSUE TITLE
Hide points with certain properties / classification

### ISSUE THREAD

**Issue by m-schuetz** [potree/potree#157]
For example, only show points that are classified as buildings.

**Comment by gabrielwalton** [comment]
Only show points classified as buildings?

Is this possible? How can I implement this?

**Comment by monodo** [comment]
Have you tried to define a custom classification  and set other classes to transparent color ? I'm just not sure that THREE.Color supports RGBA for transparent color definition.

For instance: 

pointcloud.material.classification = customClassification:  {
        0:          new THREE.Color(1, 0, 0),
        1:          new THREE.Color(1, 0, 0),
        "DEFAULT":  new THREE.Color(0.3, 0.6, 0.6 ) => Define transparent color here
    }

**Comment by gabrielwalton** [comment]
So I can only set a particular colour as transparent?

I am attempting to replicate a neat function of CloudCompare but in CloudCompare it is implemented as a Layer function.

See the following video for what I am trying to achieve:
https://youtu.be/cW8J3dtBtJI

I would like to turn on and off different "layers". This allows the end user (in this particular data set) to turn on and off the schematics of the wreck to aid interpretation.

Is something like this possible with Potree?

Many thanks for your help so far.

**Comment by monodo** [comment]
Hmmm...I don't thinks this is possible "out of the box" with potree right now, but introducing the concept of layer in potree would be quite interesting for us and [PotreeViewer](https://github.com/PotreeViewer/PotreeViewer). Let see what @m-schuetz has to say about it.

**Comment by gabrielwalton** [comment]
My coding skills are very limited so implementing this "layer" principle is outside my knowledge base so I'm afraid I can't be too much help.

I could quite easily add an extra field to the separate point clouds and give them an ID number before merging them all into one large point cloud. This way the separate point clouds in the merged file could be "called" or told to be transparent if not needed.

Again, I'm non to slick on the coding.

I'm sure it would be a useful feature though so would be nice to see it implemented.

Thanks again for your help.

**Comment by stpsomad** [comment]
Is it finally possible to show classification? I see this in the showcases http://potree.org/demo/potree_1.3/showcase/tern_auscover_chowilla.html but I cant make it work

**Comment by JWGmeligMeyling** [comment]
It would be very useful to be able to "filter" by classification indeed. I would be interested in implementing this, but how?

**Comment by JWGmeligMeyling** [comment]
Update: nevermind, I see this was already implemented in https://github.com/potree/potree/pull/179/commits/08d7347d770c2861ccd6679ee26a049a83d42e7d . When will the develop branch be merged into master, and a new version released? @m-schuetz

**Comment by m-schuetz** [comment]
Currently working on another project. I hope to get back to potree in August and finish 1.4 by end of september.

**Comment by m-schuetz** [comment]
Possible in develop branch with the classification filter panel, or by setting the alpha component of the classification color table to zero.

```
// hide vegetation
viewer.pointclouds[0].material.classification = {
	0: 			new THREE.Vector4(0.5, 0.5,0.5, 1.0),
	1: 			new THREE.Vector4(0.5, 0.5,0.5, 1.0),
	2: 			new THREE.Vector4(0.63, 0.32, 0.18, 1.0),
	3: 			new THREE.Vector4(0.0, 1.0, 0.0, 0.0),
	4: 			new THREE.Vector4(0.0, 0.8, 0.0, 0.0),
	5: 			new THREE.Vector4(0.0, 0.6, 0.0, 0.0),
	6: 			new THREE.Vector4(1.0, 0.66, 0.0, 1.0),
	7:			new THREE.Vector4(1.0, 0, 1.0, 1.0),
	8: 			new THREE.Vector4(1.0, 0, 0.0, 1.0),
	9: 			new THREE.Vector4(0.0, 0.0, 1.0, 1.0),
	12:			new THREE.Vector4(1.0, 1.0, 0.0, 1.0),
	"DEFAULT": 	new THREE.Vector4(0.3, 0.6, 0.6, 0.5)
}
```
