### ISSUE TITLE
Add marker_move_stopped event to profileTool

### ISSUE THREAD

**Issue by monodo** [potree/potree#166]
The profile tool marker_moved fire on every maker move. This is fine on small datasets but on large ones it would useful to fire a marker_move_stopped when the user finishes dragging (on mouseup for instance).

**Comment by m-schuetz** [comment]
Next release will have a "marker_dropped" event, e.g.:

    measurement.addEventListener("marker_dropped", e => {
    	let index = e.index;
    	let location = e.measurement.points[index].position.toArray().join(", ");
    	console.log(`marker ${index} dropped at ${location}`);
    })

    // "marker 2 dropped at 589971.0792541504, 231398.54987335205, 743.7050007629394"

**Comment by m-schuetz** [comment]
Just committed event to develop.

For profiles, you'll have to drop the ".position" part in the code above, e.g.

    profile.addEventListener("marker_dropped", e => {
    	let index = e.index;
    	let location = e.profile.points[index].toArray().join(", ");
    	console.log(`marker ${index} dropped at ${location}`);
    })
