### ISSUE TITLE
Picking is inaccurate for adaptive point sizes

### ISSUE THREAD

**Issue by gribbet** [potree/potree#168]
Shader uniform octreeSize is not set which results in inaccurate picking.

Fix is here: https://github.com/Airphrame/potree/commit/cdbfda1eea8d2f89e2b34fbddfa3004c94eead5d

**Comment by m-schuetz** [comment]
Thanks! I'll add it as soon as I can!

**Comment by m-schuetz** [comment]
Merged your fix into develop branch.
Thanks again!
