### ISSUE TITLE
Clear drawings with measurement tools

### ISSUE THREAD

**Issue by wesweaver** [potree/potree#180]
Would be nice to be able to clear measurements made with the measuring tools from the rendering. Trying to track all of that down now, but if someone has advice... 

Correct me if there's a way to do this; I've only been at this for two days or so.

**Comment by m-schuetz** [comment]
Hi! 

There isn't an option in the GUI at the moment.
There is an alternative viewer by sitn which has that option, though:
* PotreeViewer: https://github.com/PotreeViewer/PotreeViewer/tree/master
* web demo: http://sitn.ne.ch/lidar/

You can also call the reset functions of the respective tools, (Also possible directly in the browser developer console)

Current master branch:
```
measuringTool.reset(); 
volumeTool.reset(); 
profileTool.reset()
```

Current develop branch:
```
viewer.measuringTool.reset(); 
viewer.volumeTool.reset(); 
viewer.profileTool.reset()
```

**Comment by wesweaver** [comment]
Perfect! Added this to viewer.js with a .png icon:

		elToolbar.appendChild(createToolIcon(
            "../resources/icons/reset.png",
            "reset measurements",
            function () {
                scope.measuringTool.reset();
                scope.profileTool.reset();
                scope.volumeTool.reset();
            }
            ));
