### ISSUE TITLE
Add event listeners to container and not globally to "window" 

### ISSUE THREAD

**Issue by dkastl** [potree/potree#181]
I think it's wrong to add the event listener to the window object, like here:
[FirstPersonControls#L369-L370](https://github.com/potree/potree/blob/e3104d70c1d47de4a5e6da73a8f286e53349e42b/src/FirstPersonControls.js#L369-L370)

Since you specify the DIV tag, which should be the container for the Potree viewer, the event listeners should be also limited to that container.

I think it should work like this:

```
document.getElementById("div").addEventListener("keydown", onKeyDown, false);
```

... where `div` is the container, that was specified at initialization.

Searching for occurrences of `addEventListener` there seem to be cases, where it was done right and some where the listeners applies to the whole document or window:
https://github.com/potree/potree/search?utf8=%E2%9C%93&q=addEventListener

**Comment by martinheidegger** [comment]
This code has been completely rewritten in the meantime. This problem shouldn't exist anymore, see [FIrstPersonControls#L95-L98](https://github.com/potree/potree/blob/58c289c707406224544fd216d1777b671250c9b9/src/navigation/FirstPersonControls.js#L95-L98)
