### ISSUE TITLE
bad orientation scene with multiple point cloud

### ISSUE THREAD

**Issue by jubru** [potree/potree#187]
Good job Markus, the new interface is really nice.

branch potree-develop 20.11.2015
problem: bad orientation scene with 2 point clouds.

![pc_1](https://cloud.githubusercontent.com/assets/12160142/11293327/83e2575e-8f59-11e5-896c-8981ae977f4b.PNG)
![pc_2](https://cloud.githubusercontent.com/assets/12160142/11293328/8785a9f6-8f59-11e5-857d-ac4a68513f15.PNG)
![pc_2 1](https://cloud.githubusercontent.com/assets/12160142/11293329/893d146e-8f59-11e5-8376-9b73a1598fe8.PNG)

**Comment by m-schuetz** [comment]
Thanks for the feedback. 
The problem with the flipping is that each time a point cloud is added, flipYZ() is called.
So theoretically, adding an odd amount of point clouds will result in the right orientation again.
Fill fix that later today.

**Comment by martinheidegger** [comment]
I am assuming this issue is fixed, closing this issue. Please reopen if that was premature.
