### ISSUE TITLE
snap only to visible point

### ISSUE THREAD

**Issue by jubru** [potree/potree#188]
with the option "clip outside" after the tool "clipping volume" or "height profile", the tool "Distance measurements" does not snap to the visible points of the clipped volume, but to all points of the point cloud, leading to misinterpretations..
This is a problem for complex point cloud in enclosed spaces. Can we limit the action of tools so it takes into account only for the points selected in the clip mode option ?

**Comment by jubru** [comment]
This is a real problem for measuring objects in a tunnel.
Example:
![capture d ecran 2015-12-16 a 11 43 59](https://cloud.githubusercontent.com/assets/12160142/11838919/50b873ae-a3ea-11e5-94bb-96cef77397cf.png)
![capture d ecran 2015-12-16 a 11 53 20](https://cloud.githubusercontent.com/assets/12160142/11839139/c35fab24-a3eb-11e5-96da-a63b8961b750.png)
![capture d ecran 2015-12-16 a 11 53 49](https://cloud.githubusercontent.com/assets/12160142/11839141/c6c1d63e-a3eb-11e5-8e21-a1314144fc3c.png)

The final distance is not taken on visible items:
![capture d ecran 2015-12-16 a 11 54 05](https://cloud.githubusercontent.com/assets/12160142/11839146/cbe03764-a3eb-11e5-82b2-ccd7e701dd97.png)

**Comment by m-schuetz** [comment]
Good point, will look into it.

**Comment by m-schuetz** [comment]
Done, in develop branch.
Exception is the profile tool to allow to modify the clip area.

**Comment by jubru** [comment]
very good Markus.
It's also ok with the navigation tools "Earth controls"
Thank you!

**Comment by jo-chemla** [comment]
May be related to this issue so I'm posting here: When selecting 'clip outside' setting, and using EDL, then the points outside the clipping volume re-appear as black instead of staying transparent.

**Comment by m-schuetz** [comment]
I've actually taken out HQ-Splats for now since it got a bit cumbersome to maintain 3 (Standard, EDL, HQ) render paths. I'll remember this issue when I bring HQ splats back in.

More importantly, it seems like measuring tools snap to points outside the clip area, again.
