### ISSUE TITLE
viewer.js JavaScript issues

### ISSUE THREAD

**Issue by sanak** [potree/potree#197]
I found the following issues in viewer.js.
* Invalid `Math.max` use:
<pre>
max = Math.max(array[i]);
</pre>
https://github.com/potree/potree/blob/1.4RC/src/viewer/viewer.js#L1137
* Nested(duplicated) counter `i`:
<pre>
for(var i = 0; i < scope.pointclouds.length; i++){
    :
    for(var i = 0; i < array.length; i++){
        :
</pre>
https://github.com/potree/potree/blob/1.4RC/src/viewer/viewer.js#L1125-L1138

**Comment by m-schuetz** [comment]
Thanks for the report.

Fixed in develop branch: 
https://github.com/potree/potree/blob/develop/src/viewer/viewer.js#L1167

**Comment by sanak** [comment]
Oh, the following fix is necessary on the next line.
[Before]
<pre>
max = Math.max(array[j]);
</pre>
[After]
<pre>
max = Math.max(max, array[j]);
</pre>
https://github.com/potree/potree/blob/develop/src/viewer/viewer.js#L1168

**Comment by m-schuetz** [comment]
This is one of the cases where I wonder why things ever worked. ^^

It seems like the correct maximum intensity is not a good measure, actually.
Just tried it on a pointcloud where maximum was 50.000 but most values were below 300, making the point cloud mostly black when using a linear scale between 0 and 50.000.

I'll try if something like median or 0.75 percentille is better suited than the max, to scale intensity to rgb.

**Comment by sanak** [comment]
Oh, I see.
Thanks for confirmation.

**Comment by m-schuetz** [comment]
Chosing intensity based on the 0.75 percentile of the root nodes intensity values now: https://github.com/potree/potree/blob/develop/src/viewer/viewer.js#L1167

Seems like a reasonable, albeit not perfect, choice to deal with outliers.
