### ISSUE TITLE
Mouse capture is preferable for pan operation

### ISSUE THREAD

**Issue by sanak** [potree/potree#198]
Currently, mouse capture is aborted if the mouse position is on another DOM element (like outside of the DOM or annotation DOM element).

Mozilla Firefox seems to support mouse capture API.
https://developer.mozilla.org/en-US/docs/Web/API/Element/setCapture
But, I don't know how to capture mouse for each modern browsers (like Chrome .etc).

OpenLayers 3 seems to support mouse capture.
(It can keep drag (pan) map when a mouse position is outside of the map div or browser window.)
http://openlayers.org/en/v3.2.1/examples/drag-rotate-and-zoom.html

**Comment by m-schuetz** [comment]
> In annotation example, mouse up on annotation doesn't work correctly after following operation.
1. Mouse drag (rotate) the scene, and mouse up when mouse position is on an annotation.
2. Click the annotation.
3. The scene is rotated although without mouse drag.

**Comment by m-schuetz** [comment]
During mouse-navigation, annotations will now be disabled.

Disable and enable annotations. 
(More specifically, the interaction of annotations with mouse)
https://github.com/potree/potree/blob/develop/src/viewer/viewer.js#L466-L478

Start and end events of all controlls will disable and enable annotations:
https://github.com/potree/potree/blob/develop/src/viewer/viewer.js#L1002-L1003

**Comment by sanak** [comment]
Sorry, I haven't been touching this library for a quite long time.
I couldn't remember the past discussion, so I close this issue. :bow:
