### ISSUE TITLE
Default Viewer Settings Using Converter or URL?

### ISSUE THREAD

**Issue by pihish** [potree/potree#199]
is there anyway to default the viewer's settings when I am converting a file using the converter or when opening up the HTML page using the URL (ie. adding GET values to end of URL)?

**Comment by potree** [comment]
Not yet but passing as get parameter sounds like a good idea.
Will defenitely add that.
Won't do that for the converter at the moment, however. Maybe for a future version.

**Comment by pihish** [comment]
Any chance you can point me in the right direction if I wanted to set settings using the URL right now?  What files / methods are doing the heavy lifting to change settings right now?

**Comment by m-schuetz** [comment]
You can use this to readl parameters from the URL: 
http://stackoverflow.com/questions/901115/how-can-i-get-query-string-values-in-javascript

For 1.4RC or the current develop branch (some bugs left but almost finished) you can then use the viewer.setXXX functions to set your options.

The viewer.setXX functions are defined in viewer.js starting here:
https://github.com/potree/potree/blob/develop/src/viewer/viewer.js#L214

You can call them in your viewer.html file, like here: 
https://github.com/potree/potree/blob/develop/examples/viewer.html#L103

**Comment by pihish** [comment]
I didn't generate my pages with 1.4RC or the current dev branch, but I was able to find the key value pairs to change under the ```sceneProperties``` object in ```/examples/myfilename.js``` and ```viewer.js``` starting on line 169.  Changing those did the trick.

**Comment by m-schuetz** [comment]
Glad you got it to work!

**Comment by m-schuetz** [comment]
Made some parameters modifieable by URL arguments in develop:
https://github.com/potree/potree/commit/05e7e2d0346986207e01228cae568b4f57475c95

Having others like camera position and target available would be nice, too.

**Comment by pihish** [comment]
Thanks.  Would you be open to accepting pull requests for new features here?  I was thinking of adding new parameters and also saving requested parameters in local storage so users can have their last known settings on a page preserved.
