### ISSUE TITLE
Any Way to Generate a POTree View Without Making Copies of JS Library Files?

### ISSUE THREAD

**Issue by pihish** [potree/potree#200]
Right now every time a file is converted into the POTree format, the library files that POTree uses (three.js, proj4, internal POTree library files, etc...) are copied into a new directory.  

Is there anyway to generate a new POTree view, but have the generated HTML pages look for the library files in a central location?

**Comment by m-schuetz** [comment]
Does the PotreeConverter version you use expect a name with the -p option?
If so, you can simply specify the same target directory with -o but a different page name with -p.
If you're using a PotreeConverter version that does not expect a name with -p or --generate-page, then you can still try it but the source files must have different names.
