### ISSUE TITLE
selected point cloud and 2d profil

### ISSUE THREAD

**Issue by jubru** [potree/potree#201]
When a single point cloud is on, the points of all clouds are drawing in 2d profile.
![capture d ecran 2016-01-07 a 17 35 37](https://cloud.githubusercontent.com/assets/12160142/12176024/ad6fa090-b565-11e5-9a8a-ede5a39546d4.png)
![capture d ecran 2016-01-07 a 17 35 48](https://cloud.githubusercontent.com/assets/12160142/12176025/ad729db8-b565-11e5-99e5-1c74a1ae72f0.png)
![capture d ecran 2016-01-07 a 17 35 56](https://cloud.githubusercontent.com/assets/12160142/12176026/ad73e8b2-b565-11e5-9452-e9d9ff7241c8.png)

**Comment by m-schuetz** [comment]
Thanks for the info, will take a look at it.
Nice point cloud, btw!

**Comment by jubru** [comment]
Nice Markus.
Where can I change the name of the point cloud in the group "Scene" (sceneList)?

**Comment by m-schuetz** [comment]
hidden point cloud in 2d profile and added names to scene list: https://github.com/potree/potree/commit/f33381b9481e0b7e6152db530b1f728e4596e2f1

To set the name, call pointcloud.setName("abc");

For example, like this:
```
viewer.addPointCloud("../resources/pointclouds/vol_total/cloud.js", function(e){
		e.pointcloud.setName("abc");
});
```
