### ISSUE TITLE
Measurement Tools crash point picking in dev branch

### ISSUE THREAD

**Issue by davijo** [potree/potree#202]
Not sure what could be going on, but the point picking while measuring crashes on the current dev branch with the error:
<img width="1083" alt="potree_dev_crash" src="https://cloud.githubusercontent.com/assets/8625487/12259837/e9ba20d4-b920-11e5-9ef0-ae2937ee7cd1.png">

For example with the distance tool it only makes one single measurement and point picking does not work after that.

Chrome OSX Version 47.0.2526.106 (64-bit)

**Comment by m-schuetz** [comment]
Can't reproduce that error with latest develop branch.
Could you upload your example and send me a link? (mschuetz@potree.org)

**Comment by davijo** [comment]
It was the viewer.html from examples that I tried running on a local linux VM https://github.com/potree/potree/blob/develop/examples/viewer.html

**Comment by m-schuetz** [comment]
Works fine for me. 
Only error I get is a sources.json not found but this file is not necessary.

How about the lion.html example? Does that one work for you?
Master branch? Potree 1.3?

**Comment by m-schuetz** [comment]
Hi @davijo, 
Did you resolve this issue? Seems like you're not the only one with this problem but I wasn't able to reproduce it myself.
