### ISSUE TITLE
Bower?

### ISSUE THREAD

**Issue by lavahot** [potree/potree#212]
Any chance this can be set up to be a bower listing? You'd have to take the libs out of the repo, but it makes it a lot easier to deploy.

**Comment by dkastl** [comment]
To register a new package a few requirements need to be met, see
http://bower.io/docs/creating-packages/#register

You're more than welcome to contribute some of the formal requirements, for example a valid `bower.json` file. A pull request makes it a lot easier to get this done.

**Comment by m-schuetz** [comment]
Unfortunately I don't realy know what bower is about and a quick search didn't really tell me why it's good to have. 

If you'd like to see bower support please tell my why it's good to have and what would need to be changed. I won't do these changes myself but as @dkastl mentioned, you're welcome to contribute them and if they're valuable and don't interfere with the rest of potree, I may merge them, though I can't guarentee it.

**Comment by lavahot** [comment]
Bower is a front-end package manager for web projects. It would make your software much easier to deploy into other projects. Unfortunately, I no longer work for the company that was interested in using your software, otherwise I'd gladly "bowerize" it for you.
