### ISSUE TITLE
What is unit of measurement tool?

### ISSUE THREAD

**Issue by mariczone** [potree/potree#214]
Hi I'm newbie here, 
I would like to know about unit of measurement tool.

Thank you.

**Comment by m-schuetz** [comment]
Hi, 

Potree does not assume any unit of measurement and therefore does not display meter/feet/etc.
The values you get are in the unit the coordinates are stored in. If your coordinates are stored in meters, then measurement results are in meter, too.

**Comment by mariczone** [comment]
Thank @m-schuetz
