### ISSUE TITLE
How I detect coordinate in potree viewer?

### ISSUE THREAD

**Issue by mariczone** [potree/potree#215]
Hi, I would like to know which coordinate is using in  example/lion.html or lion_las.html or lion_laz.html in default to know about unit of measure tool.

In Example/openLayers3.html in Configure Panel has coordinates check-box to show current coordinate system like "ESPG:21781".

Thank for helps.

**Comment by m-schuetz** [comment]
In the upcoming release:

To find the coordinate of a point, you can now use the coordinate measure tool. 
To find the projection (in proj4 format) you can call this code in your developer console:

    // Projection of the first point cloud
    viewer.scene.pointclouds[0].projection

    // Projections of all your point clouds (should be the same anyway)
    viewer.scene.pointclouds.map( (e, i) => [i, e.name, e.projection].join(", "))

**Comment by danilodelfio** [comment]
Sorry for my dumb question but I'm new in the potree world.
I would like to obtain the local coordinates from a double-clicked point on the cloud.
I need to use the coordinates to interrogate a db but 

viewer.scene.view.position

gives me the global coordinate of the clicked point. I tried to write 
viewer.scene.view.position.toLocal() 
but doesn't work.
Thank you

**Comment by skoslitz** [comment]
Use [getMousePointCloudIntersection](https://github.com/potree/potree/blob/develop/src/navigation/InputHandler.js#L538) within your InputHandler.onDoubleClick method to get the coordinates.
