### ISSUE TITLE
inserting a sphere in the scene at a global coordinate

### ISSUE THREAD

**Issue by jubru** [potree/potree#219]
Can we insert a three.js object to a 3D position by giving coordinates in the same system as the point cloud?

**Comment by m-schuetz** [comment]
Yes, you can by transforming from the point cloud coordinate system to scene coordiantes and using the scene coordinates for your objects.

```
var scenePos = viewer.toLocal(new THREE.Vector3(589541.5201, 231328.0400, 777.79500))
```

Likewise, you can use viewer.toGeo to transform from scene to point cloud coordinates.
