### ISSUE TITLE
Not displaying in Firefox 46.0.1

### ISSUE THREAD

**Issue by rmilner1** [potree/potree#229]
I have a range of point clouds that worked completely fine in Firefox 43 however, they do not work in Firefox 46.0.1. - the page loads as normal except the data is not visible.

The only error message in Firefox's debugging console is:
Error: WebGL: texImage2D: Uploading ArrayBuffers with FLIP_Y or PREMULTIPLY_ALPHA is slow.

**Comment by spatialhast** [comment]
@rmilner1 try change config in Firefox:

> about:config
> 
> webgl.force-enabled=true.
> webgl.msaa-force=true.
> layers.acceleration.force-enabled=true.
> gfx.direct2d.force-enabled=true.

https://github.com/potree/potree/issues/226

**Comment by rmilner1** [comment]
Thanks, it works! I hadn't noticed it was in the closed issues.
