### ISSUE TITLE
Open potree 1.4 at specific co-ordinate position

### ISSUE THREAD

**Issue by daviecahill** [potree/potree#230]
How can you open the point cloud at a specific XYZ position, as opposed to the far out view.

**Comment by daviecahill** [comment]
Can a variable be set in html file to set camera position/heading in version 1.42RC similar to 
       
        cameraPosition: null, 		// other options: cameraPosition: [10,10,10],
	cameraTarget: null, 		// other options: cameraTarget: [0,0,0],

in version 1.3

**Comment by m-schuetz** [comment]
You can set initial positions like this:

```
viewer.addPointCloud("http://5.9.65.151/mschuetz/potree/resources/pointclouds/opentopography/CA13_1.4/cloud.js", function(e){
	e.pointcloud.setName("CA13");
	viewer.camera.position.set(4032.572341682513, 362.07649293733874, 14037.010422605732);
	viewer.controls.target = new THREE.Vector3(4487.972917878704, 30.06198819344912, 13877.62507638037);
});
```

Position and name of the point cloud are set inside the callback that is executed once the point cloud metadata is loaded.
