### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by eVk2012** [potree/potree#233]
I have detected this detail in the line 11198 of potree.js:

`callback({type: "pointclouad_loaded", pointcloud: pointcloud});`

I'm thinking that it would be:

`callback({type: "pointcloud_loaded", pointcloud: pointcloud});`

Is correct? Also happend in viewer.js (line 164).

**Comment by m-schuetz** [comment]
You're right, fixed it now. 
Thanks!
