### ISSUE TITLE
Setting EDL mode at startup causes the interface to be out of sync

### ISSUE THREAD

**Issue by erich666** [potree/potree#237]
When converting a LAZ file using the converter, the converter produces an HTML file to display, which includes some settings:

		viewer.setEDLEnabled(false);
		viewer.setPointSize(3);
		viewer.setMaterial("RGB");
		viewer.setFOV(60);
		viewer.setPointSizing("Fixed");
		viewer.setQuality("Squares");
		viewer.setPointBudget(1*1000*1000);
		
		document.title = "PotreeViewer";
		viewer.setEDLEnabled(false);
		viewer.setShowSkybox(false);
		viewer.setMaterialID(Potree.PointColorType.RGB);
		viewer.setDescription('');
		
		viewer.loadSettingsFromURL();

First, note that setEDLEnabled is set twice - one of these could be deleted. Setting EDL to true here works as expected (on PCs), EDL rendering is performed (doesn't work on my iPhone, but I expect that's some platform limitation).

The problem is that the interface is a little bit out of sync at this point. Open up the menu and look at Appearance. The Eye-Dome-Lighting enable box will not be checked, even though EDL is in use. If you check the box, EDL is still on, unchecking turns it off, so things are fine after that. It's just the initial state that is not shown correctly.

**Comment by m-schuetz** [comment]
Fixed in develop: https://github.com/potree/potree/commit/cdefc62a2b40d4463c5019c53534221894b4c861

Please wait until the next push to master for this fix. 

> doesn't work on my iPhone, but I expect that's some platform limitation 
EDL is disabled if a device does not support the necessary extensions, which is most mobile devices at this time.

**Comment by jo-chemla** [comment]
> EDL is disabled if a device does not support the necessary extensions, which is most mobile devices at this time.  

Is there a plan to publish a working version of EDL for mobile devices? How is this handled right now? Thanks a lot for your help!

**Comment by m-schuetz** [comment]
Since you mention it, I just checked and it seems like I can drop an unnecessary extension that has zero support on mobile devices and isn't realy essential for EDL. 
The other extension that is required works on 75% of mobile devices according to webglstats.com, so there should be quite a lot of devices that will support EDL, soon. 

Follow #244 on updates for this.

**Comment by jo-chemla** [comment]
Thanks a lot for the update! Will stay tuned for this feature :)
