### ISSUE TITLE
potree in ie 11

### ISSUE THREAD

**Issue by KlemenSpruk** [potree/potree#238]
Hello!

I m trying to enble Potree Viewer in IE 11. I m getting Security error related to browsers blob support.
![image](https://cloud.githubusercontent.com/assets/8971677/17021968/b2726a7a-4f4b-11e6-90bb-4c698a38a1d7.png)

![image](https://cloud.githubusercontent.com/assets/8971677/17021970/b74858a2-4f4b-11e6-8a39-1f372ad2b311.png)

![image](https://cloud.githubusercontent.com/assets/8971677/17021978/c0d6f1c6-4f4b-11e6-8164-28f1a76bfe71.png)

Security error is related to this part of code:

Potree.utils.createWorker = function(code){
	 var blob = new Blob([code], {type: 'application/javascript'});
	 var worker = new Worker(URL.createObjectURL(blob));
	 
	 return worker;
};

Do you have any advice on how to tackle this? Will Potree be supported in IE?
I have noticed that potree works in some IE 11 versions.

Thanks Klemen!

**Comment by JWGmeligMeyling** [comment]
`Math.sign` is not included in the ES5 specification. See also: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sign

You can work around this issue by loading a bit of polyfill code first:
```js
Math.sign = Math.sign || function(x) {
  x = +x; // convert to a number
  if (x === 0 || isNaN(x)) {
    return x;
  }
  return x > 0 ? 1 : -1;
}
```

Please let us know if you run into further compatibility issues after this issue 😄

**Comment by m-schuetz** [comment]
Hi! Potree is no longer supported in IE11 since IE11 has stopped development. Edge may work but since it's not available for windows 7, it's not supported either. Please try Firefox, Chrome or Safari instead.
