### ISSUE TITLE
Opacity : pointcloud becoming white with opacity < 1

### ISSUE THREAD

**Issue by VioletteA** [potree/potree#248]
Hi Potree team!

I have a little issue with opacity. When i set it to a value under 1, the pointcloud becomes white. The transparency is good, but color seems to be lost.

![pbopacitefull](https://cloud.githubusercontent.com/assets/21361485/18908100/98f9899e-856e-11e6-8a99-47ce322e1f17.jpg)

I can't figure if it is a light problem, or shader, or ... ?

Anyway, thank you very much for this awesome work.

**Comment by m-schuetz** [comment]
That's because with a transparency of < 1.0, blending mode is set to additive which means that all the color channels are added up. A light red (e.g. 1.0 / 0.2 / 0.2) is mostly red but also partially green and blue. 
If 10 points with that color are added together, you'll end up with a color value of 10.0 / 2.0 / 2.0. Afterwards, each channel is clamped to 1.0 so the result will be 1.0 / 1.0 / 1.0 => white. 

This is more or less intented behaviour, or at least it's what GPUs can do without too much extra work and loss of performance.

**Comment by EloyAldao** [comment]
Dear Markus:

Regarding this same topic, I would like to ask you a question I didn't realize how to solve.
I have a custom tolbar to change the different render styles and one of them is to make transparency on the pointclouds.
As commented by @VioletteA the blending makes too bright everything.
I would like to try MultiplyBlending, but I can not achieve it using the console of the browser.

To put you in context, I share a page that contains a use case where I like to view better the rooms inside a building: [https://compassoluciones.synology.me/PoTree/repository/Edificio_Tabernas_20_LS.html#](url).

The tool is the third from the left. Here is a screenshot with the toolbar and the effect of additive blending:
![image](https://github.com/potree/potree/assets/12053667/cb9fb43d-091d-4908-bba0-b9466a395998)

Also the code for that button is the next (you can use the development tools to see the full script):

```
elToolbar.find("img[name=action_transparent]").click(() => {
        for (const pointcloud of viewer.scene.pointclouds) {
            pointcloud.material.size = 1.5;
            pointcloud.material.minSize = 1.5;
            pointcloud.material.pointSizeType = Potree.PointSizeType.FIXED;
            pointcloud.material.opacity = 0.02;
        }
        viewer.setEDLEnabled(false);
        viewer.setBackground("black"); // ["skybox", "gradient", "black", "white"];
        viewer.useHQ = false;
        transp = true;
    });
```

I would like to set the blending on this tool (maybe try all the standard options to see which looks better)

Thanks in advance

**Comment by raycaster08** [comment]
> Dear Markus:
> 
> Regarding this same topic, I would like to ask you a question I didn't realize how to solve. I have a custom tolbar to change the different render styles and one of them is to make transparency on the pointclouds. As commented by @VioletteA the blending makes too bright everything. I would like to try MultiplyBlending, but I can not achieve it using the console of the browser.
> 
> To put you in context, I share a page that contains a use case where I like to view better the rooms inside a building: [https://compassoluciones.synology.me/PoTree/repository/Edificio_Tabernas_20_LS.html](url).
> 
> The tool is the third from the left. Here is a screenshot with the toolbar and the effect of additive blending: ![image](https://private-user-images.githubusercontent.com/12053667/261794831-cb9fb43d-091d-4908-bba0-b9466a395998.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDkyMDAsIm5iZiI6MTcwMjU0ODkwMCwicGF0aCI6Ii8xMjA1MzY2Ny8yNjE3OTQ4MzEtY2I5ZmI0M2QtMDkxZC00OTA4LWJiYTAtYjk0NjZhMzk1OTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEwMTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NmNhMTA0NDZmNzFlNzQ3OGY0MjZhYWNmMjkzNzU3YTI4ZWNlYjMwZWVlY2U0Mjk2MWYzOGIzNmNjODc5NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bzxD8P-edZXgWWJ5uzxqhSnSoL1_61M_zZz_fv_juGg)
> 
> Also the code for that button is the next (you can use the development tools to see the full script):
> 
> ```
> elToolbar.find("img[name=action_transparent]").click(() => {
>         for (const pointcloud of viewer.scene.pointclouds) {
>             pointcloud.material.size = 1.5;
>             pointcloud.material.minSize = 1.5;
>             pointcloud.material.pointSizeType = Potree.PointSizeType.FIXED;
>             pointcloud.material.opacity = 0.02;
>         }
>         viewer.setEDLEnabled(false);
>         viewer.setBackground("black"); // ["skybox", "gradient", "black", "white"];
>         viewer.useHQ = false;
>         transp = true;
>     });
> ```
> 
> I would like to set the blending on this tool (maybe try all the standard options to see which looks better)
> 
> Thanks in advance

hi,

Is there a solution so far?
