### ISSUE TITLE
Hotspots on the point cloud

### ISSUE THREAD

**Issue by etnad77** [potree/potree#252]
Hi all, 
Im quite newbie to potree.
Is there anyway to add hotspots directly on the point cloud which allow to link external resources (i.e webpage) when clicked?
I went throug the issues but i couldnt find any advice.

Great job anyway
Thanks for any help

**Comment by m-schuetz** [comment]
If you use the develop branch then you can do it like in this demo:
https://github.com/potree/potree/blob/develop/examples/annotations.html

However, keep in mind that the develop branch is subject to frequent changes and incomplete stuff. 

![image](https://cloud.githubusercontent.com/assets/6705073/20409689/d59ee5f0-ad1a-11e6-9da5-08235ced3b93.png)

When you hover, the annotation content, which may include links and images, appears:
![image](https://cloud.githubusercontent.com/assets/6705073/20409704/e4f8a6c6-ad1a-11e6-938a-8dfcaafaa769.png)
