### ISSUE TITLE
offset with multiple cloud

### ISSUE THREAD

**Issue by giancan** [potree/potree#255]
Dear friends,
I manage to load multiple pointclouds in the same webpage (viewer.ad...) but although the two clouds are properly aligned in external program, when they are loaded into the webpage there is a slight offset between them (apparently only in one direction).
Any explanation and perhaps solutions?
Thanks,
G.

**Comment by giancan** [comment]
Any idea anybody?
Is there a possibility that the above issue is related to the center of the bounding box? I have the feeling that the offset is related to the small difference in the bounding box of the two loaded clouds. Is it a possibility?

**Comment by potree** [comment]
Do you have a link or a code snippet of how you're loading the point clouds?

**Comment by giancan** [comment]
I'm uploading the clouds to our website and to see an example, please check this link

http://photogrammetry.ims.forth.gr/siemens/?cloud=ValinteTsami_both&epsg=32635&wp=t&DCid=45&pl=3&a1=5&a2=3&a3=2

**Comment by potree** [comment]
Thanks. Having a hard time debugging this, though, since the chrome dev tools won't let me modify the source during startup. Probably because there is no html file that is being loaded here. 

In any case, if you're loading multiple point clouds, try to load the "main" one first and then load the other ones in the first point clouds callback, like this:

```
viewer.addPointCloud("pointclouds/"+cloud.substring(0,cloud.length-5)+"_laser/cloud.js", function(e) {
	e.pointcloud.setName(cloud.substring(0,cloud.length-5)+"_laser");
	
	viewer.addPointCloud("pointclouds/"+cloud.substring(0,cloud.length-5)+"_pg/cloud.js", function(e) {
		e.pointcloud.setName(cloud.substring(0,cloud.length-5)+"_pg");
	});
});
```

This ensures that the first point cloud is always loaded first, otherwise they may be loaded in random order since loading is done in parallel. Not sure if this fixes your issue, however.

**Comment by giancan** [comment]
Unfortunately this didn't fix it.
For your convenience the page name is index.php
so the link is 
http://photogrammetry.ims.forth.gr/siemens/index.php?cloud=ValinteTsami_both&epsg=32635&wp=t&DCid=45&pl=3&a1=5&a2=3&a3=2

**Comment by potree** [comment]
Manually setting the position with viewer.pointclouds[0].position.y = ... shows that position only changes in steps of around a meter. I suppose that it's a coordinate precision issue somewhere. 
Coincidentally, I'm working on fixing things like that right now but it's going to take a few more weeks to a release. 

A work around that may or may not work is to subtract the same value from the bounding box of both point clouds in your cloud.js files, e.g. subtract these values

```
x: 270566
y: 3916714
z: 8
```
from all the bounding box values in 

* http://photogrammetry.ims.forth.gr/siemens/pointclouds/ValinteTsami_laser/cloud.js
* http://photogrammetry.ims.forth.gr/siemens/pointclouds/ValinteTsami_pg/cloud.js

Your point clouds won't be georeferenced anymore if you do that, however.

**Comment by giancan** [comment]
Thanks for that test.
I also tried something else. I duplicated a cloud and load it twice to see if there was any issue related with multiple cloud loading, but in fact there is not.
So, as you suggested, there may be an error related with the decimals in the bounding boxes perhaps, so that different bounding boxes are rounded to the closes integers and therefore produce the offset. 
Does it make any sense to you?

**Comment by giancan** [comment]
Ok there, I found a solution to the problem.
Since the issue is related with the differences in the bounding boxes of the two clouds, I did the following:
1. check which cloud has the largest bounding box
2. copy the coordinates from cloud.js and import them as 3D points in CloudCompare
3. add these 3D points to each of the two pointclouds so that their final bounding box is exactly the same
4. re-process the clouds with potree-converter

Below I put two links to give you an idea of the final result with the alignment error

http://photogrammetry.ims.forth.gr/siemens/?cloud=IgoumenouGavriil_both&epsg=32635&wp=t&DCid=72&pl=3&a1=2&a2=2&a3=-4

and with this trick 

http://photogrammetry.ims.forth.gr/siemens/?cloud=IgoumenouGavriil2_both&epsg=32635&wp=t&DCid=72&pl=3&a1=2&a2=2&a3=-4

I hope that helps someone else, at least until the fix arrives :)

Cheers,
G.

**Comment by m-schuetz** [comment]
Hi @giancan,

It seems like this issue is now fixed in the develop branch. Very likely because of the switch to double precision transformations.

Thanks for providing the test cases, it made it a lot easier to do some testing.
