### ISSUE TITLE
access octreeDir from the AWS s3

### ISSUE THREAD

**Issue by shrikant-ror** [potree/potree#256]
Hi all,
We know cloud.js file stores information about the point cloud in JSON format. And in the colud.js file, we are mentioning **octreeDir**

If my Potree files are stored on AWS S3, then how can I access them. Anyone implemented this type of functionality, then please let me know your thoughts / solutions.

**Comment by dkastl** [comment]
You can just store the cloud.js file in the same AWS S3 bucket.

**Comment by shrikant-ror** [comment]
@dkastl I tried your solution. I kept cloud.js file in the AWS S3 bucket (In the in same bucket Potree files are present). 

But getting **Uncaught ReferenceError: url is not defined**  error.

**Comment by dkastl** [comment]
I'm using cloud.js on S3 and it works. 
However, I'm not using access keys in the URL and you shouldn't provide the path to the cloud.js file but to the data directory, I think.

**Comment by dkastl** [comment]
OK, sorry. You posted the Javascript configuration and not the content of the cloud.js file.
But maybe you're missing some setting for your S3 bucket, because it should work.

In my cloud.js file I set the full URL to the data directory.

**Comment by shrikant-ror** [comment]
@dkastl Sorry to trouble you. Can you please let me know how you set the **octreeDir** path (if simple example that would be great :) )

Also, I have few following doubts

- What permission did you provide to the octreeDir? 
- Did you use signed URL for accessing the cloud.js?  If yes, did you used signed URL while accessing the octreeDir?

Thanks in advance.

**Comment by dkastl** [comment]
I'm not suing anything special, just the S3 URL to the `cloud.js` with the bucket name and the permissions of the bucket are set to `public website`. There is no special restriction.

**Comment by shrikant-ror** [comment]
@dkastl Thanks for the reply.

**Comment by shrikant-ror** [comment]
If I have to fetch Potree files from the AWS S3 using signed URLs what changes I need to do?

**Comment by philip-firstorder** [comment]
@shrikant-ror Did you manage to do it using signed URLs?

**Comment by AlbionS** [comment]
@shrikant-ror  @philip-firstorder  did you manage to use cloud.js via signed URLs ? I have the same problem. I have my files uploaded on a S3 bucket, I dont want to be public (access  by everyone via url), so I use signed url for cloud.js but since my data is private it doesn't work. I have already tried with public bucket and it works, but I don't want to be public and with S3 bucket we can only generate signed url for objects( like png, js ..) and not for folders. Is there any solution for this ?

**Comment by philip-firstorder** [comment]
I didn't test it yet. But I saw this pull request that seems to fix it, maybe you can clone that fork and test it.
https://github.com/potree/potree/pull/184

**Comment by im-hamza-dev** [comment]
I worked on this issue recently to access octreeDir from aws-s3, I have used new format of potree where we have octree, hierarchy and metadata files only.
We got presigned urls of these files and as we know library is making a fetch request to the file url provided to it. We can override the fetch function and replace the argument (url) with the exact presign url.
Its just a workaround as library is currently not supporting presign urls approach.

Below is the actual implementation:

`let urls={
  octree: ".....",
  metadata:"......",
  hierarchy:"......",
}
 insertPresignedUrls(urls) {

    const nativeFetch = window.fetch;

    window.fetch = function (...args) {

      if (args[0].toString().includes('hierarchy.bin')) {

        args[0] = urls.hierarchy;

      } else if (args[0].toString().includes('octree.bin')) {

        args[0] = urls.octree;

      } else if (args[0].toString().includes('metadata.json')) {

        args[0] = urls.metadata;

      }

      return nativeFetch.apply(window, args);

    };

  }`

**Comment by yashwant-raut** [comment]
> I worked on this issue recently to access octreeDir from aws-s3, I have used new format of potree where we have octree, hierarchy and metadata files only. We got presigned urls of these files and as we know library is making a fetch request to the file url provided to it. We can override the fetch function and replace the argument (url) with the exact presign url. Its just a workaround as library is currently not supporting presign urls approach.
> 
> Below is the actual implementation:
> 
> `let urls={ octree: ".....", metadata:"......", hierarchy:"......", } insertPresignedUrls(urls) {
> 
> ```
> const nativeFetch = window.fetch;
> 
> window.fetch = function (...args) {
> 
>   if (args[0].toString().includes('hierarchy.bin')) {
> 
>     args[0] = urls.hierarchy;
> 
>   } else if (args[0].toString().includes('octree.bin')) {
> 
>     args[0] = urls.octree;
> 
>   } else if (args[0].toString().includes('metadata.json')) {
> 
>     args[0] = urls.metadata;
> 
>   }
> 
>   return nativeFetch.apply(window, args);
> 
> };
> ```
> 
> }`

can you provide live example on how you are using this

**Comment by im-hamza-dev** [comment]
@yashwant-raut can you elaborate your scenario, so I can guide better. I have just provided a overriding function where we can use our s3 presign urls

**Comment by yashwant-raut** [comment]
Thanks  @im-hamza-dev  for quick response. Debugged further and able to solve the issue and load the model from the Signed URLs. 

here is how I done it for reference 

``` js
async initPointCloud() {
    this.potree.pointBudget = 2_000_000;

//put presigned URL's here
  const urls = {
      hierarchy: 'https://example.com/path/to/hierarchy.bin',
       octree: 'https://example.com/path/to/octree.bin',
      metadata: 'https://example.com/path/to/metadata.json'
   };

  try {
      await this.loadPointCloudSignedURLs(urls, 'metadata.json');
      console.log('Point Cloud Loaded Successfully ');
    } catch (err) {
      console.error('Error in initializing the point cloud', err);
    }
  }
```
```js 
  insertPresignedUrls(urls: {
    hierarchy: string;
    octree: string;
    metadata: string;
  }): (url: string) => string {
    return (url: string): string => {
      if (url.includes('hierarchy.bin')) {
        return urls.hierarchy;
      } else if (url.includes('octree.bin')) {
        return urls.octree;
      } else if (url.includes('metadata.json')) {
        return urls.metadata;
      }
      throw new Error(`Unknown file requested: ${url}`);
    };
  }
 ```

```js 
  async loadPointCloudSignedURLs(
    urls: {
      hierarchy: string;
      octree: string;
      metadata: string;
    },
    fileName: string
  ) {
    try {
      const resolveUrl = this.insertPresignedUrls(urls);
      const pco = await this.potree.loadPointCloud(
        fileName,
        resolveUrl
      );

      pco.name = 'Point Cloud Mesh';
      this.scene.add(pco);
      this.pointClouds.push(pco);
      return pco;
    } catch (err) {
      console.error('Failed to load point cloud:', err);
      throw new Error('Error loading point cloud.');
    }
  }
 ```
