### ISSUE TITLE
Three.js logarithmic depth buffer not compatible.

### ISSUE THREAD

**Issue by Avocher** [potree/potree#259]
Hi,
It seems that Potree is not directly compatible with Three.js logarithmic depth buffer. Is there an easy way to get them working together? I'm using Potrees minimal example as a starting point.

**Comment by potree** [comment]
Fixed in develop branch by using standard depth buffer for depth testing and logarithmic depths for EDL shading.
I'll need to find a better way to improve depth buffer precision. 

![image](https://cloud.githubusercontent.com/assets/2094934/22062655/1a511606-dd7b-11e6-8b3a-4ab89bbebf8d.png)

**Comment by m-schuetz** [comment]
For now, depth buffer precision is somewhat improved by adapting the near clip plane to the spacing of the smallest visible octree node. That way, the near clip value essentially decreases as you zoom on and vice versa.
