### ISSUE TITLE
Avoid duplicate points in extracted profile

### ISSUE THREAD

**Issue by potree** [potree/potree#260]
Right now, consecutive profile segments overlap each other and return duplicate points, as shown here:
![image](https://cloud.githubusercontent.com/assets/2094934/21294166/07c087e4-c537-11e6-91d6-c9727fcfd383.png)

Something like this would be better:

![image](https://cloud.githubusercontent.com/assets/2094934/21294176/484f29be-c537-11e6-819e-9c6ed94d6f0d.png)

**Comment by m-schuetz** [comment]
Closing this because the orthographic projections of each segment are better off if they contain the duplicates.
