### ISSUE TITLE
Pass input as a directory to PotreeConverter command

### ISSUE THREAD

**Issue by shrikant-dm** [potree/potree#262]
As per the given in the documentation (http://potree.org/wp/potreeconverter-with-support-for-las-ply-and-xyz-files/), we are using following command for converting .las files to potree files
           `PotreeConverter  las_file -p output_directory`

In the command we are providing single input file.

In my case, there are more than one las files are present the folder. Is there any way so that I can pass input as folder. 

Please let me know your thoughts. Thanks.

**Comment by potree** [comment]
If you specify the folder, it will take all the las files in it as input.

**Comment by shrikant-dm** [comment]
@potree Thanks for the reply. It is working fine. 
Able to convert all the files by passing folder name.
