### ISSUE TITLE
Scene visibility issue

### ISSUE THREAD

**Issue by SimoTeru** [potree/potree#267]
Hi, i am a student from Politecnico di Milano and i am trying to set up a project which involves the use of potree for online visualization of different point clouds. I managet to have three different point clouds overlap in a viewer. I was thinking if it is possible to set up which is the default scene that has to be set to visible while the others must be turned of by default.

Thanks to anyone who could help.

Simone

**Comment by monodo** [comment]
Hi, 

This is not implemented as such for now, but you can easily edit the [initSceneList function](https://github.com/potree/potree/blob/develop/src/viewer/sidebar.js#L1130) so that it sets the first point cloud added as visible by default. For instance: 

```
function initSceneList(){

	var scenelist = $('#sceneList');
	
	var id = 0;
	// this works but it looks so wrong. any better way to create a closure around pointcloud?
	var addPointcloud = function(pointcloud){
		(function(pointcloud){
			var elLi = $('<li>');
			var elLabel = $('<label>');
			var elInput = $('<input type="checkbox">');
			if (id==0){
                elInput[0].checked = true;
            } else {
                pointcloud.visible = false;
            }
			elInput[0].id = "scene_list_item_pointcloud_" + id;
			elLabel[0].id = "scene_list_item_label_pointcloud_" + id;
			elLabel[0].htmlFor = "scene_list_item_pointcloud_" + id;
			elLabel.addClass("menu-item");
			elInput.click(function(event){
				pointcloud.visible = event.target.checked;
				if(viewer._2dprofile){
					viewer._2dprofile.redraw();
				}
			});
			
			elLi.append(elLabel);
			elLabel.append(elInput);
			var pointcloudName = " " + (pointcloud.name ? pointcloud.name : "point cloud " + id);
			var elPointCloudName = document.createTextNode(pointcloudName);
			elLabel.append(elPointCloudName);
			
			scenelist.append(elLi);
			
			pointcloud.addEventListener("name_changed", function(e){
				if(e.name){
					elPointCloudName.textContent = " " + e.name;
				}else{
					elPointCloudName.textContent = " point cloud " + id;
				}
			});
			
			id++;
		})(pointcloud);
	};
	
	for(var i = 0; i < viewer.pointclouds.length; i++){
		var pointcloud = viewer.pointclouds[i];
		addPointcloud(pointcloud);
	}
	
	viewer.addEventListener("pointcloud_loaded", function(event){
		addPointcloud(event.pointcloud);
	});
};
```
By the way, I think we should modify the addPointCloud function so that is take 3 arguments: path to point cloud, full point cloud name, and initial visibility.

Olivier

**Comment by SimoTeru** [comment]
Thank you a lot for the fast reply. I am new to programming in general and to potree but i can see what you mean. I 'll try to implement your suggestion and let you know.

Simone

**Comment by SimoTeru** [comment]
it seems i have a problem, ehiter i did something wrong or the script doesen't work.. i modified the html file of the sidebar as you said and rebuild potree. Problem is that when i open the html file in which i pot the two different pointclouds they are both still active. I even tried to open the file after deleating potree from my pc, still it opened without problems.. i wonder what i am missing.. i mean if i can open the html file without having potree at all does it make a difference having modified and built it agan? or maybe the cloud that will change are those created with potree converter after aving rebuilt the potree file?

Simone

**Comment by SimoTeru** [comment]
YES i did it. I was doing it wrong!!! Thank you 👍 :)
Simone

**Comment by m-schuetz** [comment]
As an fyi, in the upcoming release you can make the point cloud invisible in the load callback and then turn visibility on and off inside the Scene panel in the sidebar.

    Potree.loadPointCloud("../pointclouds/lion_takanawa/cloud.js", "lion", e => {
    	viewer.scene.addPointCloud(e.pointcloud);
    
    	e.pointcloud.visible = false;
    });

![image](https://cloud.githubusercontent.com/assets/6705073/22686544/c5d7e708-ed24-11e6-89a4-482316363706.png)

**Comment by Tofoillote** [comment]
Hi
Using the potree.json5 into the html _viewer.loadProject("./pointclouds/Assemblee_r-1/potree.json5");_

How can this visibility setting can be set into the json5 project file ?
