### ISSUE TITLE
Enhance colors of the point cloud

### ISSUE THREAD

**Issue by jo-chemla** [potree/potree#271]
It would be nice to modify the colors of the points by applying a function to the rgb channels, augmenting the brightness and contrast. 
To enhance the colors when they are not bright enough for examples, without having to change the big las file using cloud compare). An easy quickfix for now is to apply a css filter to the canvas like  filter: brightness(1.8) contrast(80%), but then the chlidren divs of the potree container are also impacted.

**Comment by m-schuetz** [comment]
Already done in develop, with many thanks to SITN ( @monodo @mriedo @kalbermattenm )

Targetting a new RC release ath the end of january.

![image](https://cloud.githubusercontent.com/assets/6705073/22075742/8849204a-ddad-11e6-99bc-6f83a23e3c93.png)

![image](https://cloud.githubusercontent.com/assets/6705073/22075748/8cff0866-ddad-11e6-83e7-77d8f6911efc.png)

![image](https://cloud.githubusercontent.com/assets/6705073/22075753/8fb0dcba-ddad-11e6-8708-e19be540df76.png)

![image](https://cloud.githubusercontent.com/assets/6705073/22075754/926f8ae6-ddad-11e6-98a2-3ba1c4ac92d9.png)

![image](https://cloud.githubusercontent.com/assets/6705073/22075756/949a2e7a-ddad-11e6-9e4d-ead4214d87dc.png)

**Comment by jo-chemla** [comment]
Perfect, that's brilliant! :)
