### ISSUE TITLE
Measures

### ISSUE THREAD

**Issue by jlmontes** [potree/potree#272]
Hello, Thanks for this amazing proyect.
Is posible make a  heigth measure tool which automatic detect base ground ? 
I need heigth measure in poles assests and is very dificult with current tools. We can pay for this development.

this tool is implemented in other library, this is the link  [http://demo.orbitgis.com/moma/]

Thanks.

**Comment by jo-chemla** [comment]
Why do you need automatic ground detection and don't measure Z directly using coordinates measurement?

**Comment by m-schuetz** [comment]
Height measurement tool will be included in the next release:

![image](https://cloud.githubusercontent.com/assets/6705073/22685531/f55263ea-ed20-11e6-9872-c0b0ae1d9c8a.png)
