### ISSUE TITLE
clipping volumes

### ISSUE THREAD

**Issue by jubru** [potree/potree#274]
Hi Markus,

The clipping volume tool is a little hard to use when the area is rotated.
After the rotation of a clipped area, the axes of functions "R" and "E" are not aligned.
![capture](https://cloud.githubusercontent.com/assets/12160142/22423608/b08eba3a-e6f2-11e6-8d40-c01d0e36c611.JPG)
![capture1](https://cloud.githubusercontent.com/assets/12160142/22423611/b2b9fc98-e6f2-11e6-9a0d-b8d9a9dc7fd2.JPG)
![capture2](https://cloud.githubusercontent.com/assets/12160142/22423613/b4771b74-e6f2-11e6-8a96-019ad5026a3e.JPG)

Best regards

Julien

**Comment by m-schuetz** [comment]
Coincidentally, I'm just thinking about how to improve the transformation tools. I think scale should always be aligned with the box. Should translate be aligned, too?

**Comment by jo-chemla** [comment]
Maybe the translate direction could be in the direction of the axes of the camera? (u, v), and the user can move the camera to drag in the 3rd direction (along the axis of the camera)

 Might be easier to keep the arrows to drag and drop the volume in the direction of the bounding box, and add a sphere at the intersection of the arrows, which would move the box along the axes of the camera when dragged.

**Comment by jubru** [comment]
Exactly jo. Drag and drop the volume in the same direction of the scale of the bounding box.
It's really nice to view/use indoor point cloud (building model).

**Comment by dannman939** [comment]
could you provide a brief tutorial on how to use the volume tool to produce a cut-and-fill calculation on a mound of dirt?
