### ISSUE TITLE
Framerate drop on iPhone.

### ISSUE THREAD

**Issue by phaseIV** [potree/potree#276]
I’m working with a local clone of the Potree1.3 codebase and recently upgraded to Threejs r84. When I applied the code changes from commit 252626bbaf3b8f1215aa55e20bcdd6bfcdcd0870 I noticed that the framerate on my iPhone dropped from 60 to 12. When I undo the changes done to the colorbuffer (ie. change Uint8Array back to Float32Array) in the worker and loader files, the framerate on the iPhone goes back to 60.

Now, while this behaviour might not apply to the develop branch of Potree and could very well be the result of the hacks done in my local Potree code, I thought to report it anyway in case this issue becomes apparent in future releases.

Thank you very much for your work on Potree, it's awesome!

**Comment by m-schuetz** [comment]
Thanks for the warning. Unfortunately, I don't own an iphone so I won't be able to test/debug there. On my galaxy s4, everything seems to be fine.

**Comment by m-schuetz** [comment]
Could you try this page on your iphone?
http://potree.org/work/mschuetz/potree_2017.02.05/examples/lion.html

It's just a very small scene but I can't upload new stuff right now.
You'll likely have to decrease the "min node size" option in the Other Settings panel to get some more details:

**Comment by phaseIV** [comment]
Thank you for the reply. The version you linked runs very smooth on the iphone, so it seems the issue I posted isn't affecting the latest developments. I'll close the issue, thanks for your time!
