### ISSUE TITLE
How can we add Zoom in / out buttons on the viewer.

### ISSUE THREAD

**Issue by shrikant-dm** [potree/potree#277]
This is not an issue. But as a functionality/improvement. 
I have to show + / - buttons on the viewer. So that we can zoom in and out using those buttons. Same as google map / mapbox?

Is there anyone who has implemented this type of functionality?

**Comment by monodo** [comment]
Have you tried the [Earth control](https://github.com/potree/potree/blob/master/src/EarthControls.js) ?

**Comment by shrikant-dm** [comment]
@monodo I tried to use Orbit Control. But it is not working. Here is the code

```
orbit = new Potree.OrbitControls(camera, renderer.domElement);
      $( "#zoomIn" ).click(function() {
        orbit.dollyIn(0.95);
      });
      $( "#zoomOut" ).click(function() {
        orbit.dollyOut(0.95);
      });
```

Is there anything I need to add.

**Comment by shrikant-dm** [comment]
By using [this](https://github.com/potree/potree/blob/master/examples/js/viewer.js#L729) method I am able to add zoom in / out functionality.

I used orbitControls for binding proper actions to zoom in / out buttons.

**Comment by cez2020** [comment]
> By using [this](https://github.com/potree/potree/blob/master/examples/js/viewer.js#L729) method I am able to add zoom in / out functionality.
> 
> I used **orbitControls** for binding proper actions to zoom in / out buttons.

Hello, do you still have the code available? I'm trying to implement something similar in my project
