### ISSUE TITLE
Add point (x,y,z)  on the pointcloud set by x,y coordinates

### ISSUE THREAD

**Issue by flombardet** [potree/potree#279]
Hi all,

Very often, i need to know a point's altitude that i have pick coordinates on a another map. To do that, i use the point measurement and i move the point until i find the same coordinates. This method could take a while.

I try to create a function to add a point on the pointcloud which is dinfine by x,y coordinate. The function below need the coordinates on the 3 axis and doesn't work...  My knowledge on JavaScript is close to zero...

SetAlt = function(sE, sN, sA){
PointA = viewer.toLocal(new THREE.Vector3(sE, sN, sA));
var p = new Potree.Measure();
p.addMarker(PointA);
viewer.MeasuringTool.addMeasurement(p);
console.log("new point defined");
}

If there is a lot of point on couple of coordinates the function should response with the lowest point and insert a coordinate in the measurements.

Is this function could be implement?

Thanks for the answer and for the job on Potree

**Comment by m-schuetz** [comment]
Hi, 

Finding the point in the point cloud that is closest to your x and y coordinates isn't possible at the moment. 
You can iterate through the coordinates of the point cloud to find the closest match but that requires some work. 

You'd have to traverse the octree towards the point location and check point coordinates in all containing and adjacent nodes.
For the root node, you can get the coordinates, stored in an [xyzxyz...] buffer like this:

    viewer.scene.pointclouds[0].root.geometryNode.geometry.attributes.position
