### ISSUE TITLE
Is it possible to add muliple three.js objects and make them load only if the users see them? Like the point clouds?

### ISSUE THREAD

**Issue by pogilon** [potree/potree#287]
Hello,

I am trying to add a lot of 3D objects created using three.js into the point cloud. However, I only want the data about these 3D points to be loaded only if they are seen by the user. Is it possible using potree? How? Thank you!

**Comment by m-schuetz** [comment]
You'll have to check three.js on how to do something like that.
You'd need to know about the locations/bounding Boxes of the objects and once you find that an objects bounding box becomes visible, you can start to do the loading.
