### ISSUE TITLE
how can I add an "action" to an added mesh or line? e.g., change camera view when clicked 

### ISSUE THREAD

**Issue by pogilon** [potree/potree#294]
how can I add an "action" to an added mesh or line? e.g., change camera view when clicked

**Comment by m-schuetz** [comment]
You'll need to add a click listener to viewer.renderer.domElement and then do a raycast to viewer.scene.scene (scene: potree scene, scene.scene: the threejs scene in a potree scene) to check whether a mesh has been hit.

Please refer to the three.js examples to see how to do this: https://threejs.org/examples/?q=raycast
