### ISSUE TITLE
Greyish point cloud in some use cases 

### ISSUE THREAD

**Issue by m-schuetz** [potree/potree#297]
On one machine, everything becomes greyish after the first profile pick:

From this:
![image](https://cloud.githubusercontent.com/assets/6705073/23161788/b993d67a-f82b-11e6-94ae-5b1b3866cc56.png)

To this:
![image](https://cloud.githubusercontent.com/assets/6705073/23161792/bc8843e8-f82b-11e6-89c6-e18da1e74fef.png)

On another machine, it works just fine.

**Comment by davijo** [comment]
Does it help if you reset the GL state before or after the pick? Probably not the best way but could give some ideas on why this happens.
-> renderer.resetGLState();

**Comment by m-schuetz** [comment]
For some reason I do not understand, I can't reproduce this issue today.

**Comment by m-schuetz** [comment]
Can't reliably reproduce this issue.
