### ISSUE TITLE
There is something wrong with 'Potree.PointCloudOctree.pick'

### ISSUE THREAD

**Issue by zouxianghong** [potree/potree#304]
mouse's position is different with that of the chosen point, namely, position obtained by the function 'Potree.PointCloudOctree.pick' is not accurate.

**Comment by ygeller** [comment]
Same here. There is an offset between the mouse position and selected point:
- The "point" of the mouse arrow doesn't report back the proper pointcloud coordinates
- When drawing a measurement, the measurement node sphere is not located at the "point" of the arrow. it drags in some distance from it, which changes from orientation to orientation.
- When a measurement node is placed, it does show correct coordinates (as it is placed on a pointcloud point)
- As mentioned by others, not all points in the pointcloud can be selected

I couldn't BTW find a function called Potree.PointCloudOctree.pick so I think the issue might benefit from a different name... perhaps a projection issue? this didn't happen in 1.4

**Comment by m-schuetz** [comment]
> As mentioned by others, not all points in the pointcloud can be selected
This has been fixed just now: 
https://github.com/potree/potree/issues/295
The dev branch has a new build that you can try. 

Does that fix the problem?
If not, can you provide a screenshot to illustrate the issue?

**Comment by m-schuetz** [comment]
Closing this since it's now working for me in chrome and firefox in the develop branch.
