### ISSUE TITLE
How can I convert and render the Kitti datasets use Potree?

### ISSUE THREAD

**Issue by yuwenhui** [potree/potree#308]
I've receive a task to convert and render the [Kitti datasets](http://www.cvlibs.net/datasets/kitti/raw_data.php), I'm new to Potree and what i can do first?

**Comment by m-schuetz** [comment]
Hi, please refer to the Getting Started section to find out how to display point clouds with potree:
https://github.com/potree/potree/blob/master/docs/getting_started.md
