### ISSUE TITLE
Change Elevation orientation

### ISSUE THREAD

**Issue by dgarciap** [potree/potree#311]
Hello!
I have a problem tying to visualize my pointcloud.
I'm customizing the camera, so probably because of my fault, when I load my pointcloud it is drawn vertically instead of horizontally.

So to fix this I do:
 pointcloud.rotation.x = -0.5*Math.PI;

The problem is that when I draw my pointcloud using a gradient to visualize the elevation, It applies the gradient horizontally instead of vertically. How can I change elevation orientation?

Edit: Notice that before changing rotation the gradient is applied correctly. But when I change X rotation, elevation keeps using the same orientation that was using before.

**Comment by m-schuetz** [comment]
In pointcloud.vs, the getElevation() function assumes that z is the up-vector
https://github.com/potree/potree/blob/master/src/materials/shaders/pointcloud.vs#L249

You could either make sure that your custom camera also uses z as the up-vector, which means that you likely won't need to rotate the point cloud in the first place, or you could change the shader to use y as the up-vector.
I'd recommend the first solution, to make sure that you use z as the up-vector. Some other stuff, including certain measurement tools, also rely on z as the up-vector.

**Comment by dgarciap** [comment]
Thank you very much!
I applied the shader change, because my camera is being use for another things and I cannot change the axis.
