### ISSUE TITLE
Potree 1.5RC not working on Safari (iphone-6)

### ISSUE THREAD

**Issue by dgarciap** [potree/potree#312]
I'm trying to run the examples on this Browser and they do not work.

The web examples (potree 1.3) run well.

**Comment by m-schuetz** [comment]
What about Safari on Mac? Does that work?
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.

**Comment by dgarciap** [comment]
I tested it on Safari 9 for Mac and It does not work. It is due to the use of ES6 javascript features.
It is problably the same problem with iphone 6 safaris (I need to check what version of safari is using).

**Comment by m-schuetz** [comment]
I was expecting Safari 9 to be obsolete since it's not even listed on the ECMA Script compatibility table anymore: http://kangax.github.io/compat-table/es6/

But yes, Safari 10 is a minimum requirement now because Safari 9 is missing a lot of ES6 features.

**Comment by OldSanSan** [comment]
I tested it on Safari  10.1.2 for Mac、iphone5s and iphone7  , but all failed..
Other platforms are working properly.

**Comment by stevenvachon** [comment]
Failing here on Safari 10.1.2 for OS X 10.12.6

**Comment by martinheidegger** [comment]
Seems to be an linting detail difference in safari.
![](https://i.gyazo.com/b14e49b65c3c241856e9b28c0bd8f692.png)

**Comment by m-schuetz** [comment]
Does this example work for you on safari? 
http://potree.org/subs/mschuetz/potree_safaritest/examples/viewer.html

**Comment by martinheidegger** [comment]
@m-schuetz works for me!

**Comment by m-schuetz** [comment]
Great. It really was just the redeclaration of i in a new scope. Safari is right in that it's a stupid thing to do but  unfortunately it seems to be valid syntax and it's supported by Edge, Firefox and Chrome. Going to fix that with the next release.

**Comment by stevenvachon** [comment]
You should probably be transpiling with [babel](https://npmjs.com/babel-core) anyway.

**Comment by m-schuetz** [comment]
You're free to do so if you need to.

**Comment by stevenvachon** [comment]
It's not about my needs, as I don't use this project anywhere, but it's about your ability to maintain standards code without it affecting a production environment.

**Comment by m-schuetz** [comment]
I believe it's better to expect a standard conform and up to date web browser, rather than transpiling to legacy browsers and I'm not keen on adding an extra step just to support outdated browsers, which may lack proper WebGL support anyway.

**Comment by martinheidegger** [comment]
@stevenvachon opened a separate issue: https://github.com/potree/potree/issues/397

**Comment by vadnart1** [comment]
HI @m-schuetz , works great in Safari !   is that code posted  anywhere that I can grab ?
