### ISSUE TITLE
Reason for not respecting Greyhound baseDepth?

### ISSUE THREAD

**Issue by elemoine** [potree/potree#317]
I am wondering why potree doesn't use the `baseDepth` advertized in Greyhound Info response. potree [uses](https://github.com/potree/potree/blob/master/src/loader/GreyhoundLoader.js#L194) `max(8, greyhoundInfo.baseDepth)` and I'd like to understand why? Why not using the advertized value?

**Comment by m-schuetz** [comment]
ping @connormanning 

I suspect because baseDepth 8 is similar to what the PotreeConverter does, i.e. it samples points with a grid size of 2^8 = 256 cells per axis. Might be interesting to try with baseDepth 7 instead, since the default for the newer converter is closer to 128 cells per axis.

**Comment by connormanning** [comment]
The reasoning by @m-schuetz is accurate.  Greyhound's base depth just means "the first octree depth where points were inserted".  It isn't meant as a suggestion for how to query the data - it's just a fact about the octree structure to tell clients where they can expect data to be present.

It's possible that it could be `0`, where the octree would look similar to [this](https://people.eecs.berkeley.edu/~demmel/cs267/lecture26/Quadtree1.gif).  In this case there would be only one point at the base depth.  A base depth of `2` would mean that the tree does not begin until the red-colored nodes - a minimum resolution of 4 cells per dimension.

Starting (and cube-splitting) from `8` means that we'll tend to get about 65k points for every HTTP request until the data density drops off.  That works well visually, and results in nicely sized buffers and a good amount of data received per RTT.
