### ISSUE TITLE
offset between mouse pointer and measurement markers

### ISSUE THREAD

**Issue by ygeller** [potree/potree#318]
As of version 1.5 I am encountering an odd issue of an offset between the mouse pointer and the positioning of measurement markers. Essentially, when drawing a new measurement, the red  marker sphere is offset from the mouse pointer, making it very hard to perform a measurement. 
I've tried to illustrate in the attached image:

![offset](https://cloud.githubusercontent.com/assets/18378946/24895910/4b39068c-1e9b-11e7-8396-19c62b76f639.png)

Note  - the marker has not been positioned yet by clicking, it simply trails behind the mouse while dragging in an offset. The distance and angle of the offset does not seem consistent and changes with zoom level and rotation.

**Comment by ygeller** [comment]
Did some additional testing. When using sample data from the Potree showcase - all works well. 
As soon as I use my own data (either potree converter 1.4 or 1.5) I start getting offsets.
So - this seems to be an issue related to the data (which worked fine in 1.4).
My only guess at this point is that this is a projection issue? My data uses EPSG:2039

**Comment by ygeller** [comment]
More info - confirmed: if I save a point cloud as "unitless" all works well. As soon as I save it as "projected" (e.g. EPSG:2039) I start getting offsets. I guess this is a projection error. I am happy to try and contribute a fix if someone can point in the right direction of where this has changed from the previous version.

**Comment by m-schuetz** [comment]
Same as #304

I believe this is fixed now in the develop branch.
