### ISSUE TITLE
LASDecoder RGB issue

### ISSUE THREAD

**Issue by davijo** [potree/potree#322]
Noticed an issue with LASDecoder.js where overblown (near 255,255,255) rgb colors resulted in cyan, magenta and blue noise.
Changing
https://github.com/potree/potree/blob/master/src/workers/LASDecoderWorker.js#L167

```
colors[3*i+0] = r / 255;
colors[3*i+1] = g / 255;
colors[3*i+2] = b / 255;
```

to

```
r /= 65535.0;
g /= 65535.0;
b /= 65535.0;
r *= 255.0;
g *= 255.0;
b *= 255.0;

colors[3*i+0] = r.toFixed(0);
colors[3*i+1] = g.toFixed(0);
colors[3*i+2] = b.toFixed(0);
```

fixed the problem. I'm guessing there is a more elegant solution available.

**Comment by m-schuetz** [comment]
Thanks for the report. 
I've comitted a fix where color values are divided by 256 instead of 255.
```65535 / 256 = 255.996 => 255```
