### ISSUE TITLE
Distance with HeightProfile

### ISSUE THREAD

**Issue by jorge-17** [potree/potree#324]
The height profile distance can be obtained?

**Comment by m-schuetz** [comment]
Only programmatically at the moment, like this:

```
for(let profile of viewer.scene.profiles){
	let distances = profile.points
		.map(v => new THREE.Vector3(v.x, v.y, 0))
		.map((v, i, a) => i === 0 ? 0 : a[i-1].distanceTo(a[i]))
	
	let totalDistance = distances.reduce((a, v) => a + v, 0);
	
	console.log(`distances: ${distances.join(", ")}`);
	console.log(`total distance: ${totalDistance}`);
	
}
```

This is for distances on the ground plane, ignoring the height of the elevation profile markers.
If you want to incorporate height differences into the distance calculation, just removethis line: 
```.map(v => new THREE.Vector3(v.x, v.y, 0))```

**Comment by IsraelAguilera** [comment]
Where should I put that segment of code?

**Comment by m-schuetz** [comment]
Open your browsers dev tools (ctrl+shift+i in chrome) and go to the "console" tab. 
Paste the code there and press enter. The result will be written into the console.
