### ISSUE TITLE
Height Profile display has wrong offset

### ISSUE THREAD

**Issue by potree** [potree/potree#327]
The hovered point is drawn twice, once with a wrong offset.
The whole profile itself is also shifted by an offset and starts before 0.

![image](https://cloud.githubusercontent.com/assets/2094934/25530403/6cc2838a-2c26-11e7-9f3e-56f5e07dbbc9.png)

**Comment by monodo** [comment]
You might want ot take a look at https://github.com/potree/pytree/blob/master/pytree/static/js/cpotreeProfile.js#L221 

The problem was solved there.

**Comment by potree** [comment]
Thanks for the hint!

**Comment by m-schuetz** [comment]
Fixed in develop branch
