### ISSUE TITLE
Race condition in adding a point cloud to the scene list

### ISSUE THREAD

**Issue by puzzlepaint** [potree/potree#330]
I think that in 1.5RC, there might be a race condition which sometimes prevents a point cloud from being added to the scene list. This happens if `initSceneList()` is called before `viewer.scene.addPointCloud()` adds the point cloud to `viewer.scene.pointclouds`. In this case, there seems to be no mechanism that adds the point cloud to the list (`addPointCloud` will dispatch a `pointcloud_added` event, but this will not do it). If however `initSceneList()` is called after the point cloud is added to `viewer.scene.pointclouds`, then it will take care of adding it to the list:

```js
	for(var i = 0; i < viewer.scene.pointclouds.length; i++){
		var pointcloud = viewer.scene.pointclouds[i];
		addPointcloud(pointcloud);  // (Note that this is a different addPointcloud().)
	}
```

I worked around this by:

* Removing the list initialization in `initSceneList()` quoted above
* Ensuring that `Potree.loadPointCloud()` is called after `initSceneList()` finishes
* Making the callback that gets called when the cloud finished loading manually dispatch a `pointcloud_loaded` event for the viewer.

**Comment by m-schuetz** [comment]
Right, seems like the callack mechanism doesn't work. Will fix this.

**Comment by m-schuetz** [comment]
Fixed: https://github.com/potree/potree/commit/47211fe4dc0a7552e5e5b6fb989303c1fb45d2a9
(among some other things)

Thanks for reporting this issue!
