### ISSUE TITLE
Custom render path for point clouds

### ISSUE THREAD

**Issue by potree** [potree/potree#332]
Last time I checked it wasn't possible to set individual uniform values for different objects sharing the same material. 

In case of adaptive point sizes, individual uniforms could significantly speed up rendering since the traversal could start at the currently rendered node, rather than always starting at the root.

It'd also be helpful for GPU picking.

**Comment by potree** [comment]
![image](https://cloud.githubusercontent.com/assets/2094934/25859469/ec63bc74-34de-11e7-8c97-ee87c8b60b2f.png)

**Comment by m-schuetz** [comment]
Found that threejs has a onBeforeRender callback that, paired with the now public setProgram call, can be used to set per-object uniforms. 
This is now used for adaptive point sizes and also to get rid of the custom gl calls in the picking code.

**Comment by jrodriguesimg** [comment]
My onBeforeRender callback is not being called :(
