### ISSUE TITLE
Classification filter is broken in viewer example

### ISSUE THREAD

**Issue by monodo** [potree/potree#333]
Looks like the classification filter got broken in viewer [example](https://github.com/potree/potree/commit/5af506737c62c30d6301cb451934cd1b0c0c60d6 )

**Comment by m-schuetz** [comment]
fixed: https://github.com/potree/potree/commit/1188dc0f789e5d366510e7ce996b46ebfc64568e

**Comment by monodo** [comment]
Thanks a lot @m-schuetz
