### ISSUE TITLE
export DXF / measure

### ISSUE THREAD

**Issue by jubru** [potree/potree#334]
The dxf exporter does not work for multiple objects. The dxf file is not built correctly.
I attach below a minimal dxf file for 2 points / 2 polylines / 2 surfaces.
![image](https://cloud.githubusercontent.com/assets/12160142/25998856/1d394148-3723-11e7-8e0c-266badf286e2.png)
![image](https://cloud.githubusercontent.com/assets/12160142/25998874/2e6ef1ce-3723-11e7-8e24-b826640b749b.png)

<details> 
  <summary>DXF File</summary>
<pre>
999
DXF created from potree
0
SECTION
2
HEADER
9
$ACADVER
1
AC1006
9
$INSBASE
10
0.0
20
0.0
30
0.0
9
$EXTMIN
10
589634.2898712158
20
231320.4200000763
30
729.2049998092651
9
$EXTMAX
10
590065.7591552734
20
231541.1996307373
30
762.7649983215332
0
ENDSEC
0
SECTION
2
ENTITIES
0
CIRCLE
8
layer_point
10
589934
20
231410
30
733
40
1.0
0
CIRCLE
8
layer_point
10
589702
20
231414
30
760
40
1.0
0
POLYLINE
8
layer_polyline
62
1
66
1
10
0.0
20
0.0
30
0.0
70
8
0
VERTEX
8
0
10
590046.1192626953
20
231380.31999969482
30
752.8849991607666
70
32
0
VERTEX
8
0
10
589912.1193847656
20
231320.4200000763
30
749.3249996948242
70
32
0
VERTEX
8
0
10
589698.2497558594
20
231370.87999725342
30
762.7649983215332
70
32
0
SEQEND
0
POLYLINE
8
layer_polyline
62
1
66
1
10
0.0
20
0.0
30
0.0
70
8
0
VERTEX
8
0
10
590065.6791381836
20
231541.1996307373
30
729.2049998092651
70
32
0
VERTEX
8
0
10
589864.6495056152
20
231531.74961853027
30
738.505
70
32
0
VERTEX
8
0
10
589634.2898712158
20
231482.70974731445
30
753.8450001525879
70
32
0
SEQEND
0
POLYLINE
8
layer_surface
62
1
66
1
10
0.0
20
0.0
30
0.0
70
9
0
VERTEX
8
0
10
590021.3392333984
20
231415.70987701416
30
747.2050007629394
70
32
0
VERTEX
8
0
10
590065.7591552734
20
231454.2297515869
30
739.7149990844727
70
32
0
VERTEX
8
0
10
590003.5992431641
20
231510.05975341797
30
731.7250002670288
70
32
0
VERTEX
8
0
10
589948.3999938965
20
231449.39999389648
30
729.9949997711182
70
32
0
SEQEND
0
POLYLINE
8
layer_surface
62
1
66
1
10
0.0
20
0.0
30
0.0
70
9
0
VERTEX
8
0
10
589837.5494995117
20
231397.26987457275
30
741.9649990844727
70
32
0
VERTEX
8
0
10
589892.1793823242
20
231470.24975585938
30
732.7750004577637
70
32
0
VERTEX
8
0
10
589829.5895080566
20
231515.48974609375
30
740.9749993133545
70
32
0
VERTEX
8
0
10
589790.8897399902
20
231437.3699951172
30
750.3249996948242
70
32
0
SEQEND
0
ENDSEC
0
EOF
</pre>
</details>

**Comment by potree** [comment]
Can you tell me some steps on how to reliably reproduce your issue? When I create some measurements and export them, I'm getting correct results.

**Comment by jubru** [comment]
With which software do you open the downloaded dxf file?
At home, in Autodesk Map3d and QGIS the data is not correct.
Maybe I'm not using the latest built, I work with the developp branch of this morning.

**Comment by potree** [comment]
Cloud Compare. But the dxf you've posted seems to be wrong in cloud compare, too.

**Comment by jubru** [comment]
The dxf that I've posted is correct, work in QGIS and Autocad. This is a potree export that I've manually edited with a text editor. This is the corrected version.

**Comment by potree** [comment]
Ah, I see. I'll check with QGIS, then.

**Comment by potree** [comment]
> This is a potree export that I've manually edited with a text editor

Can you help me out by describing the changes you've made? It already helps if you could provide the originally exported and the fixed measure.dxf files.

**Comment by jubru** [comment]
I've added a circle for "point" measurements too.
[DXF_mesure.zip](https://github.com/potree/potree/files/1001096/DXF_mesure.zip)

**Comment by gmiguelr87** [comment]
Hi Jubru! I'm really interested on this! I would like to get all measurements in DXF (not only one by one). Is this option available yet? If not... could you send me how to do it please?
Thank you!

**Comment by jubru** [comment]
Hi gmiguelr87!
The above DXF_mesure.zip file contains an original dxf file from portree and a modified version.

**Comment by potree** [comment]
Fixed, works for me in QGIS at least.

Thanks for the DXF_mesure.zip, that was very helpful!

Could you just give it a quick try here?
http://potree.org/work/mschuetz/measurements/examples/viewer.html

I'd like to do a release until end of the week, would be good to know if the exporter is fine now.

**Comment by jubru** [comment]
It's ok with Autocad Map3D.
