### ISSUE TITLE
Projection with PotreeConverter

### ISSUE THREAD

**Issue by jorge-17** [potree/potree#344]
How works Potree with the projection from PotreeConverter?

**Comment by jo-chemla** [comment]
Automatically takes into account the projection set up in the cloud.js file. If the coordinates of your cloud are given in geo referenced coordinate system (UTM 10N for example), and you tell PotreeConverter which projection you use, Potree will automatically add an openlayer widget which will show the extent of the cloud on the map and position of the camera.
