### ISSUE TITLE
potree.viewer depends on global viewer variable

### ISSUE THREAD

**Issue by adnan-wahab** [potree/potree#353]
i was runnig view-source:http://potree.org/showcase/santorini.html

and when i edit the source and make window.viewer undefined by making "viewer" a local variable, 

this line throws an error that viewer is undefined 

https://github.com/potree/potree/blob/master/build/potree/potree.js#L14112

did i do something wrong? if not then i can open a pr with a fix later this afternoon, thanks!

**Comment by ceciliaconsta3** [comment]
@adnan-wahab What are you trying to achieve by making "viewer" a local variable?

**Comment by martinheidegger** [comment]
During [linting](https://github.com/potree/potree/pull/366) there have been quite a few hard references to the global `viewer` variable removed. This should have fixed your issue _(can you test with the develop branch?)_.

There are still a few _(3?)_ places that are depending on a global viewer being present that could be removed as well.  It seems like it should be an optional default to have `viewer` as a global variable that can be switched off. Any further PR that removes the reliance on global variables is welcome.

**Comment by adnan-wahab** [comment]
i can take a look at this. thanks martin!

**Comment by martinheidegger** [comment]
Actually in #391 I think the last global references were extinguished

**Comment by adnan-wahab** [comment]
cool i'll close this issue then, thank you!
