### ISSUE TITLE
Move potree homepage to github.

### ISSUE THREAD

**Issue by martinheidegger** [potree/potree#355]
Currently the potree homepage seems to be a wordpress page. GIthub offers [hosting for projects](https://pages.github.com/) that comes with two advantages:

- People can contribute to the website
- Reduced hosting costs (presumably)

I would like to contribute to the potree webpage and was hoping to do so with - as a first step -
 moving the whole page to github. Would that be okay?

In case that is okay, I would need a little support:

- create a new repository: https://github.com/potree/potree.github.io
- write access to that repository for me

Optionally it might help to get access to the current source data to reduce the transition effort a little.

_Sidenote: I am posting this here, even though it doesn't really have to do with the potree javascript library, is this place okay for this sort of question?_

**Comment by potree** [comment]
Sounds good. I created the repository and added you as collaborator.

**Comment by martinheidegger** [comment]
Thank you! I followed the invitation. 

Any chance to get access to the wordpress data _(maybe backup data?)_

> Optionally it might help to get access to the current source data to reduce the transition effort a little.

**Comment by m-schuetz** [comment]
I'll get you a dump of images and resources as soon as I can

**Comment by dkastl** [comment]
I think you could rename the repository from `potree.github.io` to just `website` for example. 

In the end the website would be accessible by "www.potree.org" or just "potree.org", and these settings for Github Pages can be just made with some configuration file.

**Comment by martinheidegger** [comment]
Done.
