### ISSUE TITLE
Global variable name used in TransformationTool by mistake

### ISSUE THREAD

**Issue by potree** [potree/potree#364]
In TransformationTool.js:

```
let sphere = new THREE.Mesh(sg, sm);
sphere.name = name + "_sphere";
```

```name``` is not defined in the scope of TransformationTool. As a result, ```window.name``` is used instead, which holds an empty string.

**Comment by martinheidegger** [comment]
Fixed in #fc2bd9fe45c67cf31705f6dd318bd4c98d8dd7e0
