### ISSUE TITLE
Replace old jshint with eslint

### ISSUE THREAD

**Issue by martinheidegger** [potree/potree#371]
There is still code that uses the old jshint specification in the gulpfile https://github.com/potree/potree/blob/5e67da40419aa9b6eb3dad4a640ef4d613d773fc/gulpfile.js As part of the cleanup it would be good to delete this and simply rely on the npm lint script.

**Comment by potree** [comment]
Is the  jshint part is completely superseded by the travis build doing ```npm test``` and and ```npm run lint``` ?

**Comment by martinheidegger** [comment]
Yes

**Comment by potree** [comment]
done in develop branch
