### ISSUE TITLE
Linux build: link potreeconverter to already-installed laszip

### ISSUE THREAD

**Issue by adamsteer** [potree/potree#373]
linking potreeconverter to a system laszip would be convenient - for example, I have an existing stack which uses laszip from here:

https://github.com/LASzip/LASzip

Could potreeconverter link to that (eg /usr/lib/liblaszip.so)  instead of pulling a new LAStools version?

Not urgent - essentially a feature/tidy request.

**Comment by potree** [comment]
I'm not experienced enough with linux to take this on. In any case, if someone does this, it should be an up-to-date version of laszip that also supports las 1.4.

I'm closing this here since it is in the wrong repo but you're welcome to reopen it in https://github.com/potree/PotreeConverter
