### ISSUE TITLE
Intensity Colors

### ISSUE THREAD

**Issue by jimmyfishbean** [potree/potree#382]
Hi,

Versions: Potree 1.5 / PotreeConverter_1.5_windows_64.

Please could someone point me in the right direction.  I have checked online resources but to no success thus far.

I am experimenting with Potree, and must admit it is easily the best library out there IMO.  I have taken existing compressed LiDAR data, as LAZ format, and converted this using the PotreeConverter.  The output is displayed smoothly when loading in a browser.

The issue I have is that the LAZ data does not contain RGB values.  From reading online (as per Markus Schütz recommendation) I believe an alternative is to use Intensity, especially as the LAZ data contains an intensity value per point.  When I display the LAZ tile in the broswer, I am getting what appears to be just black/grey/white color shades - there is no rainbow color shades (such as blue, green etc).

When checking one of the LAZ files, there were 2266 unique intensity values, with the lowest value being 2 and the highest value being 7908.  When converting the source LAZ using PotreeConverter (Windows version) from a command line, I have tried each of the following:

1) `PotreeConverter.exe sourcefile.laz -o C:/IBI/xampp/htdocs/potree/converted -p example1 - -output-format LAZ`

2) `PotreeConverter.exe sourcefile.laz -o C:/IBI/xampp/htdocs/potree/converted -p example2 -r 7908 -output-format LAZ -a INTENSITY`

I am attempting to display the data using a PointColorType of INTENSITY.  Snippet of code from the generated HTML file is below:

```javascript
window.viewer = new Potree.Viewer(document.getElementById("potree_render_area"));
		
viewer.setEDLEnabled(true);
viewer.setFOV(60);
viewer.setPointBudget(1*1000*1000);
document.title = "";
viewer.setEDLEnabled(false);
viewer.setBackground("gradient"); // ["skybox", "gradient", "black", "white"];
viewer.setDescription(``);
viewer.loadSettingsFromURL();
		
viewer.loadGUI(() => {
	viewer.setLanguage('en');
	$("#menu_tools").next().show();
	//viewer.toggleSidebar();
});
		
Potree.loadPointCloud("pointclouds/example1/cloud.js", "example1", e => {
	let pointcloud = e.pointcloud;
	let material = pointcloud.material;
	viewer.scene.addPointCloud(pointcloud);
	material.pointColorType = Potree.PointColorType.INTENSITY;
	material.size = 1;
	material.pointSizeType = Potree.PointSizeType.ADAPTIVE;
	material.shape = Potree.PointShape.SQUARE;
	viewer.fitToScreen();
});
```

Questions
1. How can I configure Potree so that the intensity colors are rainbow colors as opposed to black/grey/white?  I know I can change the Classficiation colors by declaring my own THREE.Color custom collection and calling pointcloud.material.classification = customCollection.  Is there something similar for intensities?

2. Is this relevant?  Can I upscale the RGB colours using las2las.exe even when there are no RGB colors in the source LAZ (I would think this is not possible).  The command I used was: las2las -i sourcefile.laz -o upscaled.laz -scale_rgb_up

Many thanks in advance, and apologies for asking anything obvious.

![potree](https://user-images.githubusercontent.com/4130571/29410731-cd9dc8ac-8349-11e7-8d9c-dd1faf916cdf.PNG)

**Comment by jimmyfishbean** [comment]
Anyone got any advice / suggestions on this post please?

**Comment by martinheidegger** [comment]
.laz output doesn't support colors as far as I remember. Not sure about it. If your questions are urgent it might be easier to catch me at https://gitter.im/potree/Lobby

**Comment by Giedrius1991** [comment]
Im having kinda similar problem. It would be great to get solution.

**Comment by jimmyfishbean** [comment]
This was not an issue.  The LiDAR data I was using did not have any RGB values recorded, hence the lack of colors in the viewer!

.LAZ does support color.  I was using 1.2 data.
