### ISSUE TITLE
potree for meshes?

### ISSUE THREAD

**Issue by foobarbecue** [potree/potree#39]
I know that part of the idea of using potree is that you don't need to mesh your points to surfaces. But there are still some reasons to use surfaces; for example if you want to have the user click on a surface to define a point (usually you handle this by calculating which mesh triangle is intersected by a ray from the camera).

So, my question is: could potree be adapted for meshes, so that the mesh first loads extremely simplified and then triangles are added? This seems mathematically more difficult than doing it with point clouds -- I'm not even sure if the same algorithms apply. It seems that Google Earth does something like this for when you zoom in on their 3D terrain.

**Comment by tldv** [comment]
Would Harvest4D's Floating Scale Surface Reconstruction be an integratable solution?
Demo here (second one): https://harvest4d.org/?page_id=860
