### ISSUE TITLE
load potree with preset settings values

### ISSUE THREAD

**Issue by Giedrius1991** [potree/potree#393]
Hello,

is it possible to load potree data with preset settings values?

In particular i need to load preset intensity and gamma. Intensity range slider set at 0-65536 and gamma at 0.5.

Thank you in advance.

**Comment by Giedrius1991** [comment]
Any suggestions how to do it?

**Comment by martinheidegger** [comment]
You can simply load a second, meta-data, file that holds the gamma and intensity before you load the pointcloud? Wouldn't that work?

**Comment by Giedrius1991** [comment]
Im quite new to these things. Could you explain me more detailed how to do that?

**Comment by martinheidegger** [comment]
Currently you can request data with: `Potree.loadPointCloud`. Loading meta-data additionally could look like _(using [jquery api](https://api.jquery.com/jQuery.getJSON/))_:

```javascript
jQuery.getJSON('path/to/your/metadata.json', function (metaData) {
   Potree.loadPointCloud(metaData.pointCoudUrl, ...); // Follow the example from the potree webpage
   // Apply other configuration from metadata.
})
```

right now there is no clear pattern for all configuration; need to look up for each of the values :D

**Comment by Giedrius1991** [comment]
I cant figure it out how to use this. Probably too advanced for me.

Anyways, thanks for your help.

**Comment by Giedrius1991** [comment]
Is it not possible to add support to load those settings preset (range, gamma, brightness, contrast) like for example there is::

viewer.setFOV(60); 

or

material.size = 1;

so it could be for example viewer.setIntensityGamma(0.5)  or something like this?

**Comment by Giedrius1991** [comment]
And after more experimentation i managed to load my potree with preset intensity range sliders:

material.intensityRange = [[0],[65536]];
