### ISSUE TITLE
Area tool reporting incorrect values

### ISSUE THREAD

**Issue by corymsmith** [potree/potree#403]
I have a triangle with 3 sides (`665.21`, `728.29`, and `235.03`). 

The total area should be `77744.495` which is `278.8269989²` but the area tool says `973.1²`.

<img width="272" alt="screenshot 2017-09-07 10 17 06" src="https://user-images.githubusercontent.com/7315/30173674-b726e51e-93b5-11e7-9856-8653775e4aba.png">

**Comment by m-schuetz** [comment]
Not sure what's going on here, unless I've got a typo, the area shouldn't be any of that but 82,202.5.
I've tried with some of the examples on potree.org and there, the result of potree matches exactly with the area reported by ```Area[Polygon[...]]``` in mathematica.

Can you send me a link to your page?

**Comment by m-schuetz** [comment]
Here is what I got in mathematica. Please note that height is ignored in the area measurements but that shouldn't have that much of an impact in thise case since heights are very similar.

![image](https://user-images.githubusercontent.com/6705073/30203842-bfbb80bc-9483-11e7-966e-21ff6e3f7f45.png)

**Comment by corymsmith** [comment]
This was due to an old version of Potree.
