### ISSUE TITLE
Display of profile points

### ISSUE THREAD

**Issue by efac-fb** [potree/potree#406]
Hi everyone,

I have an issue with the 1.5 release : no points are dsplayed in the profile tool (see image).
![bug_profile](https://user-images.githubusercontent.com/7057636/30275833-fe27bff6-9702-11e7-96a8-83bbddbd1c8e.png)

I think the bug comes from the cloud itself, because when I change the point cloud to vol_total everything is OK. did I miss an option in the converter ? Or is it a bug ?

Thank you very mutch.

**Comment by JJ-Alvtech** [comment]
i have the same bug, it come from to big coordinate (x,y) of the cloud.

**Comment by martinheidegger** [comment]
@efac-fb Is there an error shown in the [developer console](https://developers.google.com/web/tools/chrome-devtools/console/)?

**Comment by jorge-17** [comment]
i have the same issue and it's no error in the developer console:
![2017-10-24_10h21_24](https://user-images.githubusercontent.com/16123655/31952215-b93705e0-b8a5-11e7-99e6-d867d7ae629b.png)

**Comment by monodo** [comment]
Similar error here: http://sitn.ne.ch/lidar/

**Comment by jorge-17** [comment]
Problem solved, thanks!

**Comment by monodo** [comment]
Perfect, thanks!

**Comment by efac-fb** [comment]
Thanks !

**Comment by Giedrius1991** [comment]
Is it possible to view height profile with composite attributes?

**Comment by Giedrius1991** [comment]
Is it possible to display profile coloured with elevation colors, when composite attributes are used?

**Comment by arnaldoasneto** [comment]
I still have this problem... no solution with latest build... different lines to solve in this issue solution.. does anyone can help?
