### ISSUE TITLE
Add support to send credentials with xhr requests to render content that is protected

### ISSUE THREAD

**Issue by cherukumilli** [potree/potree#408]
Currently there is no way to send credentials like cookies and authorization headers with the xhr requests.

Adding support for sending credentials when making xhr requests will enable potree library to render `content that is protected/secured`.

I see calls like:
```
		let xhr = new XMLHttpRequest();
		xhr.open('GET', url, true);
```

Changing xhr calls by setting `withCredentials` to true should send the credentials to the secured CDN that is hosting the potree data files
```
		let xhr = new XMLHttpRequest();
		xhr.withCredentials = true;
		xhr.open('GET', url, true);
```

I understand that the code needs to be refactored better to accomplish this. Is the potree team willing to entertain a PR to `Add support for sending credentials`? I will work on the PR.

**Comment by DanielSmon** [comment]
Hi @cherukumilli, we've come across this issue as well. In our case we need to send two custom authentication headers containing an API key and another value. I was thinking about an approach that would be a bit more flexible and potentially cater for other future unknown scenarios. For this reason I'm not terribly keen on just adding a parameter to supply request headers. Perhaps some kind of IoC for the consumer to supply a callback that performs the request? What are peoples thoughts?

I'll have a better think and read through the codebase over the next few days and try to refine my thinking.

**Comment by cherukumilli** [comment]
@DanielSmon 
A little more about my solution...
1. Expose an object called Potree.xhrConfig to the clients with usage like:
```
        Potree.xhrConfig = {withCredentials: true};
        Potree.loadPointCloud("https:mycdn.com/path/to/cloud.js", "modelname", e => {
        ...
        });
```
2. Add `Potree.xhrConfig` to `Potree.js`
```
Potree.xhrConfig = {
	withCredentials: false,
        customHeaders: null
        // add more if you would like to extend this
};
```
3. Create a wrapper class for XMLHttpRequest
```
Potree.XMLHttpRequest = class XHR {
	constructor () {
		this.xhr = new XMLHttpRequest();
	}
        open(method, url, async, user, password) {
                this.xhr.open();
		this.xhr.withCredentials = Potree.xhrConfig.withCredentials;
                if (Potree.xhrConfig.customHeaders) {
                   this.xhr.setRequestHeader(Potree.xhrConfig.customHeaders);
                }
                // set more props as per the requirements 
        }
};
```
4. Replace all occurrences of `XMLHttpRequest` with `Potree.XMLHttpRequest`. For example:
Replace the following:
```
	var xhr = new XMLHttpRequest();
	xhr.open('GET', url, true);
	xhr.responseType = 'arraybuffer';
```
with:
```
	var pxhr = new Potree.XMLHttpRequest();
	pxhr.open('GET', url, true);
	pxhr.xhr.responseType = 'arraybuffer';
```

**Comment by DanielSmon** [comment]
Hi @cherukumilli, that seems like a reasonable approach. I've gone back and forth in my head about more generic abstraction, but I think that would just be complicating things. Do you have that in a fork/branch that I could cherry-pick? If not I'd be happy to do the implementation in our fork as we need this fairly soon.

@m-schuetz would you be happy for this as a PR following the contribution guidelines?

**Comment by martinheidegger** [comment]
@DanielSmon @cherukumilli as I am working on #391 i think it would be awesome if a PR would use [`martinheidegger:browserify`](https://github.com/martinheidegger/potree/tree/browserify) as a base.

The solution @cherukumilli proposed in https://github.com/potree/potree/issues/408#issuecomment-330217420 is certainly a step into the right direction, however thinking about that for a bit now in #356 and #184 I think It would be good to have a [template](http://www.dofactory.com/javascript/template-method-design-pattern) configuration in the [`context.js`](https://github.com/martinheidegger/potree/blob/browserify/src/context.js) following the [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) API:

```javascript
{
  load: {
     fetchJSON: (url) => fetch(url).etc. ,
     fetchBinary: (url) => fetch(url).etc.
  }
}
```

This way the API could be simplified and any credential or what-not support could be implemented by simply having a different loader in the context.
