### ISSUE TITLE
Reduce file sizes / load things only when needed

### ISSUE THREAD

**Issue by m-schuetz** [potree/potree#414]
Some files are way too large, others are loaded even though they're not used.
Output from the chrome network tracker:

![image](https://user-images.githubusercontent.com/6705073/31044369-6bd763ba-a5ce-11e7-9327-e3e0a3cd6825.png)

* The skybox (nx, ny, nz, px, py, pz) is loaded even though the gradient background is shown. That's around 1.5MB for unused resources. Should be loaded on demand.
* cloud_icon.svg is 761kb, even though it's just a small icon. Should be replaced with something else in any case.

This would reduce the size of the page from around 5.4MB to around 3.1MB.

**Comment by m-schuetz** [comment]
A page with minified potree is now around 3MB and if the webserver automatically gzips, then it's down to around 1.1MB.

**Comment by martinheidegger** [comment]
Referencing commit:  ef2637739a6cdfb4524760f795c7bd7a47762023
