### ISSUE TITLE
Remove inline onclick handlers ( e.g. <a onclick=..." >)

### ISSUE THREAD

**Issue by m-schuetz** [potree/potree#416]
```<a href="javascript:viewer.setLanguage(" fr');"="">FR</a>```

These handlers currently access the global "viewer" variable. Users may assign a different name, however. 
It's probably better to assign handlers afterwards when the true viewer object is already known, e.g. in initSidebar:

```javascript
$("#a_french").click(e => {
	viewer.setLanguage("fr");
})
```

**Comment by SuyashDeshmukh** [comment]
May I take this one?

**Comment by martinheidegger** [comment]
@SuyashDeshmukh go for it!

**Comment by m-schuetz** [comment]
Going to do this now.

**Comment by m-schuetz** [comment]
fixed: https://github.com/potree/potree/commit/eaf230a67b1f0f16a20767c2ca2553850fc81578
(branch not ready to use)
