### ISSUE TITLE
Revert to before browserify

### ISSUE THREAD

**Issue by m-schuetz** [potree/potree#429]
I'll have to revert to before browserify. I've waited to do some things until it's done but due to some ongoing debugging/profling issues I still can't work on it.

**Comment by m-schuetz** [comment]
Reverted develop to 5a5079a5a1f4191bb9ddbe92d660ab96359200fe

The browserify version is still at develop_2017.10.10

**Comment by martinheidegger** [comment]
This is a non-issue. It can't be fixed.
