### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by emqiongwu** [potree/potree#432]
I am a newbie to web development. I modified src/utils/Measure.js, so I suppose I need to rebuild potree.js in order to have changes in effects. However, I am getting a build error for "sudo gulp build" as below. Any ideas?

```
/opt/lampp/htdocs/potree/gulpfile.js:132
	for(let workerName of Object.keys(workers)){
	    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

**Comment by martinheidegger** [comment]
Your Node.js version is too old. Please update your node.js version 😉
