### ISSUE TITLE
Coordinates measurements

### ISSUE THREAD

**Issue by SimonGeom** [potree/potree#437]
Hi all,
I have a question about coordinates measurements:
Is it possible to invert the order of appearence to ensure that the last point picked appears first in the
 <div.measurement details>

![issue_potree](https://user-images.githubusercontent.com/23637230/32216047-296a4b0a-be24-11e7-856e-f196d95ac3c6.JPG)

Thanks,

Simon

**Comment by m-schuetz** [comment]
You could try to prepend the elements instead of append them: https://github.com/potree/potree/blob/develop/src/viewer/sidebar.js#L2201

```mlist.append(panel.elPanel);``` 
=> 
```mlist.prepend(panel.elPanel);```

**Comment by SimonGeom** [comment]
Thanks a lot for your quick reply, it's work fine!
