### ISSUE TITLE
Classification show/hide bug when loading multiple point clouds?

### ISSUE THREAD

**Issue by tomomano** [potree/potree#448]
I was using classification filter in Potree to show/hide particular sets of points.
This works pretty nicely, as long as I have only one point cloud loaded.
However, if I load multiple point clouds, it seems that the filter works only on the "first" (or 0th) point cloud.
You can check this behavior in the [multiple point cloud example](http://potree.org/demo/potree_1.5/examples/multiple_pointclouds.html). Here again, the classification only applies to background field, but not to the lion.

I believe the relevant code is [src/viewer/viewer.js](https://github.com/potree/potree/blob/develop/src/viewer/viewer.js), particularly in the following lines
```
// update classification visibility
for (let pointcloud of this.scene.pointclouds) {
	let classification = pointcloud.material.classification;
	let somethingChanged = false;
	for (let key of Object.keys(this.classifications)) {
		let w = this.classifications[key].visible ? 1 : 0;

		if (classification[key]) {
			if (classification[key].w !== w) {
				classification[key].w = w;
				somethingChanged = true;
			}
		} else if (classification.DEFAULT) {
			classification[key] = classification.DEFAULT;
			somethingChanged = true;
		} else {
			classification[key] = new THREE.Vector4(0.3, 0.6, 0.6, 0.5);
			somethingChanged = true;
		}
	}

	if (somethingChanged) {
		pointcloud.material.recomputeClassification();
	}
}
```

For me, the logic presented in the code seems fine, and I do not understand why this does not work.
But it seems that "somethingChanged" becomes true only once at the first iteration?

Thanks in advance for your help.

**Comment by m-schuetz** [comment]
Even though point clouds have different material instances, they all point to the same classification instance. This means that ```somethingChanged ``` only works on the first point cloud. Subsequent point clouds in the loop will have their classification value applied from the first point cloud in the loop and therefore somethingChanged remains false.

Best solution is probably to create a different instance of the classification object for each material.

**Comment by m-schuetz** [comment]
fixed: https://github.com/potree/potree/commit/7ebe89a664346af9cf9d099b081aab7afff04260
