### ISSUE TITLE
Bug in TransformationTool.js (branch 120c6ef)

### ISSUE THREAD

**Issue by tomomano** [potree/potree#450]
I found a very small, but critical bug in TransformationTool.js (branch 120c6ef  on Sep 7).
```
{ // size
	let camera = scene.getActiveCamera();
	let pr = 0;
	if(scene.cameraMode == Potree.CameraMode.PERSPECTIVE) {
		let distance = camera.position.distanceTo(pivot);
		let pr = Potree.utils.projectedRadius(1, camera.fov * Math.PI / 180, distance, domElement.clientHeight);
	} else {
		pr = Potree.utils.projectedRadiusOrtho(1, camera.projectionMatrix, domElement.clientWidth, domElement.clientHeight);
	}
	let scale = (120 / pr);
	this.sceneTransform.scale.set(scale, scale, scale);
}
```
The *let* declaration should be removed in the *if(scene.cameraMode == Potree.CameraMode.PERSPECTIVE)* block. Otherwise, *pr* remains 0, causing scale to go *INFINITY*. Because of this, transformation tool is not visible in the browser.

I hope it helps.

**Comment by m-schuetz** [comment]
Already experienced this issue but didn't have the time to debug, so thanks for the help!
https://github.com/potree/potree/commit/ac02c07921193556b21dcab7ccef2db70889e63c
