### ISSUE TITLE
 Point measurement(x,y,z) and horizontal measurement

### ISSUE THREAD

**Issue by kozka** [potree/potree#453]
in Point measurement, how to change to see the coordinates x, y, z ??

and could you give me an idea of how to add the horizontal measurement tool only?

Thank you :)

**Comment by m-schuetz** [comment]
Horizontal Measurement tool: 
![image](https://user-images.githubusercontent.com/6705073/33891936-b9dd4f26-df57-11e7-8ef2-b90758234941.png)

The coordinates of a point measurement are listed in the Measurement Panel:
![image](https://user-images.githubusercontent.com/6705073/33891971-d6a31eb0-df57-11e7-8ed3-3bf7c070ed7a.png)

**Comment by m-schuetz** [comment]
Oh, sorry, missunderstood that. There is no horizontal meassuring tool atm. You'd have to use the regular distance measurement tool and calculate horizontal distance from the coordinates in the measurement panel yourself.
