### ISSUE TITLE
Adaptive Point Size issue - Help Request

### ISSUE THREAD

**Issue by m-schuetz** [potree/potree#458]
I'm looking for help to track and fix a bug with adaptive point sizes. On some systems, adaptive sizes fail spectacularly with large points sprinkled in between small points. 

I've uploaded four pages, one without a fix and three more with different fixes that work with Google SwiftShader. At least one of the versions did not work on a mac with a Intel HD 4000 GPU, however and I did not have the chance to test the other ones, yet.

I'd appreciate if people who experience point size issues with the unfixed version could test the other versions, and let me know whether it works or not. Please also let me know which GPU, OS and Browser you're using.

[without fix](http://mschuetz.potree.org/adaptive/without_fix/test/adaptive_ca13.html)
[fix 1](http://mschuetz.potree.org/adaptive/with_fix/test/adaptive_ca13.html)
[int fix](http://mschuetz.potree.org/adaptive/with_int_fix/test/adaptive_ca13.html)
[LUT fix](http://mschuetz.potree.org/adaptive/with_LUT_fix/test/adaptive_ca13.html)

This is what it should look like:
![image](https://user-images.githubusercontent.com/6705073/33989960-a9af7c82-e0c9-11e7-8b7e-94f6bae94e5d.png)

This is wrong:
![image](https://user-images.githubusercontent.com/6705073/33989958-a643f0a0-e0c9-11e7-967c-07d968faae17.png)

Template for reports:
```
<table>
	<tr>
		<td>OS</td>
		<td>Windows 10</td>
	</tr>
	<tr>
		<td>GPU</td>
		<td>Software</td>	
	</tr>
	<tr>
		<td>Renderer</td>
		<td>Google SwiftShader</td>	
	</tr>
	<tr>
		<td>Browser</td>
		<td>Chrome</td>	
	</tr>
	<tr>
		<td>without fix</td>
		<td>:x:</td>	
	</tr>
	<tr>
		<td>fix 1</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>int fix</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>LUT fix</td>
		<td>:white_check_mark:</td>	
	</tr>
</table>
```

The renderer is shown in the unmasked renderer line on [WebGL Report](http://webglreport.com/).
This will usually be ANGLE on Windows, probably OpenGL everywhere else.

(Related to: #454)

**Comment by m-schuetz** [comment]
<table>
	<tr>
		<td>OS</td>
		<td>maxOS High Sierra</td>
	</tr>
	<tr>
		<td>GPU</td>
		<td>Intel HD 4000</td>	
	</tr>
	<tr>
		<td>Renderer</td>
		<td>-</td>	
	</tr>
	<tr>
		<td>Browser</td>
		<td>Chrome</td>	
	</tr>
	<tr>
		<td>without fix</td>
		<td>:x:</td>	
	</tr>
	<tr>
		<td>fix 1</td>
		<td>:x:</td>	
	</tr>
	<tr>
		<td>int fix</td>
		<td>not tested</td>	
	</tr>
	<tr>
		<td>LUT fix</td>
		<td>not tested</td>	
	</tr>
</table>

**Comment by monodo** [comment]
<table>
	<tr>
		<td>OS</td>
		<td>Windows 10</td>
	</tr>
	<tr>
		<td>GPU</td>
		<td>NVIDIA Quadro K620</td>	
	</tr>
	<tr>
		<td>Renderer</td>
		<td>WebGL ?</td>	
	</tr>
	<tr>
		<td>Browser</td>
		<td>Fiferfox 57.0.2 (64 bits)</td>	
	</tr>
	<tr>
		<td>without fix</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>fix 1</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>int fix</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>LUT fix</td>
		<td>:white_check_mark:</td>	
	</tr>
</table>

**Comment by monodo** [comment]
<table>
	<tr>
		<td>OS</td>
		<td>Windows 10</td>
	</tr>
	<tr>
		<td>GPU</td>
		<td>NVIDIA Quadro K620</td>	
	</tr>
	<tr>
		<td>Renderer</td>
		<td>WebGL ?</td>	
	</tr>
	<tr>
		<td>Browser</td>
		<td>Version 63.0.3239.84 (Build officiel) (64 bits)</td>	
	</tr>
	<tr>
		<td>without fix</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>fix 1</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>int fix</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>LUT fix</td>
		<td>:white_check_mark:</td>	
	</tr>
</table>

**Comment by uomben** [comment]
<table>
	<tr>
		<td>OS</td>
		<td>Windows 10</td>
	</tr>
	<tr>
		<td>GPU</td>
		<td>Intel(R) HD Graphics 520</td>	
	</tr>
	<tr>
		<td>Renderer</td>
		<td>Microsoft Edge(?)</td>	
	</tr>
	<tr>
		<td>Browser</td>
		<td>Edge/15.15063</td>	
	</tr>
	<tr>
		<td>without fix</td>
		<td>:x:</td>	
	</tr>
	<tr>
		<td>fix 1</td>
		<td>:x:</td>	
	</tr>
	<tr>
		<td>int fix</td>
		<td>:x:</td>	
	</tr>
	<tr>
		<td>LUT fix</td>
		<td>:x:</td>	
	</tr>
</table>

**Comment by danilosalvati** [comment]
<table>
	<tr>
		<td>OS</td>
		<td>Kubuntu 17.04</td>
	</tr>
	<tr>
		<td>GPU</td>
		<td>Intel integrated Graphics Controller</td>	
	</tr>
	<tr>
		<td>Renderer</td>
		<td>WebGL</td>	
	</tr>
	<tr>
		<td>Browser</td>
		<td>Chrome</td>	
	</tr>
	<tr>
		<td>without fix</td>
		<td>:x:</td>	
	</tr>
	<tr>
		<td>fix 1</td>
		<td>:x:</td>	
	</tr>
	<tr>
		<td>int fix</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>LUT fix</td>
		<td>:x:</td>	
	</tr>
</table>

**Comment by danilosalvati** [comment]
<table>
	<tr>
		<td>OS</td>
		<td>Kubuntu 17.04</td>
	</tr>
	<tr>
		<td>GPU</td>
		<td>Intel integrated Graphics Controller</td>	
	</tr>
	<tr>
		<td>Renderer</td>
		<td>WebGL</td>	
	</tr>
	<tr>
		<td>Browser</td>
		<td>Firefox 57</td>	
	</tr>
	<tr>
		<td>without fix</td>
		<td>:x:</td>	
	</tr>
	<tr>
		<td>fix 1</td>
		<td>:x:</td>	
	</tr>
	<tr>
		<td>int fix</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>LUT fix</td>
		<td>:x:</td>	
	</tr>
</table>

**Comment by connormanning** [comment]
<table>
	<tr>
		<td>OS</td>
		<td>MacOS Sierra</td>
	</tr>
	<tr>
		<td>GPU</td>
		<td> Intel Iris Pro 1536 MB </td>	
	</tr>
	<tr>
		<td>Renderer</td>
		<td> AMD Radeon R9 M370X OpenGL Engine</td>	
	</tr>
	<tr>
		<td>Browser</td>
		<td>Chrome</td>	
	</tr>
	<tr>
		<td>without fix</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>fix 1</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>int fix</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>LUT fix</td>
		<td>:white_check_mark:</td>	
	</tr>
</table>

**Comment by pedroscaff** [comment]
<table>
	<tr>
		<td>OS</td>
		<td>MacOS Sierra</td>
	</tr>
	<tr>
		<td>GPU</td>
		<td>NVIDIA GeForce GT 750M 2048 MB / Intel Iris Pro 1536 MB</td>	
	</tr>
	<tr>
		<td>Renderer</td>
		<td>NVIDIA GeForce GT 750M OpenGL Engine</td>	
	</tr>
	<tr>
		<td>Browser</td>
		<td>Firefox Nightly</td>	
	</tr>
	<tr>
		<td>without fix</td>
		<td>✅</td>	
	</tr>
	<tr>
		<td>fix 1</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>int fix</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>LUT fix</td>
		<td>:white_check_mark:</td>	
	</tr>
</table>

**Comment by martinheidegger** [comment]
<table>
	<tr>
		<td>OS</td>
		<td>MacOS High Sierra 10.13.2</td>
		<td>MacOS High Sierra 10.13.2</td>
		<td>MacOS High Sierra 10.13.2</td>
		<td>MacOS EL Capitan 10.11.4</td>
		<td>Window 10 Home - 1703</td> 
	</tr>
	<tr>
		<td>GPU</td>
		<td>Intel Iris Graphics 540 1536 MB</td>
		<td>Intel Iris Graphics 540 1536 MB</td>
		<td>Intel Iris Graphics 540 1536 MB</td>
		<td>Intel HD Graphics 5000 1536 MB</td>
		<td>Intel HD Graphics Family 2122 MB</td>
	</tr>
	<tr>
		<td>Renderer</td>
		<td>WebKit WebGL - Intel(R) Iris(TM) Graphics 540</td>
		<td>Mozilla - Intel(R) Iris(TM) Graphics 540</td>
		<td>WebKit WebGL - Intel(R) Iris(TM) Graphics 540</td>
		<td>WebKit WebGL - Intel HD Graphics 5000 OpenGL Engine</td>
		<td>WebKit WebGL - ANGLE (intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)</td>
	</tr>
	<tr>
		<td>Browser</td>
		<td>Chrome/63.0.3239.84</td>
                <td>Firefox/57.0</td>
                <td>Safari/11.0.2</td>
		<td>Chrome/62.0.3202.94</td>
		<td>Chrome/63.0.3239.84</td>
	</tr>
	<tr>
		<td>without fix</td>
		<td>:x:</td>	
		<td>:x:</td>	
		<td>:x:</td>
		<td>:white_check_mark:</td>
		<td>:white_check_mark:</td>
	</tr>
	<tr>
		<td>fix 1</td>
		<td>:white_check_mark:</td>
		<td>:white_check_mark:</td>
		<td>:white_check_mark:</td>
		<td>:white_check_mark:</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>int fix</td>
		<td>:white_check_mark:</td>
		<td>:white_check_mark:</td>
		<td>:white_check_mark:</td>
		<td>:white_check_mark:</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>LUT fix</td>
		<td>:white_check_mark:</td>
		<td>:white_check_mark:</td>
		<td>:white_check_mark:</td>
		<td>:white_check_mark:</td>
		<td>:white_check_mark:</td>	
	</tr>
</table>

**Comment by dkastl** [comment]
<table>
	<tr>
		<td>OS</td>
		<td>Ubuntu 17.10</td>
		<td>Ubuntu 17.10</td>
	</tr>
	<tr>
		<td>GPU</td>
		<td>Intel® HD Graphics 620 (Kaby Lake GT2)</td>	
		<td>Intel® HD Graphics 620 (Kaby Lake GT2)</td>	
	</tr>
	<tr>
		<td>Renderer</td>
		<td>-</td>	
		<td>-</td>	
	</tr>
	<tr>
		<td>Browser</td>
		<td>Chrome 63.0.3239.108</td>	
		<td>Firefox 57.0.1</td>	
	</tr>
	<tr>
		<td>without fix</td>
		<td>:white_check_mark:</td>	
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>fix 1</td>
		<td>:white_check_mark:</td>	
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>int fix</td>
		<td>:white_check_mark:</td>	
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>LUT fix</td>
		<td>:white_check_mark:</td>	
		<td>:white_check_mark:</td>	
	</tr>
</table>

**Comment by mriedo** [comment]
<table>
	<tr>
		<td>OS</td>
		<td>Windows 7</td>
	</tr>
	<tr>
		<td>GPU</td>
		<td>Software</td>	
	</tr>
	<tr>
		<td>Renderer</td>
		<td>-</td>	
	</tr>
	<tr>
		<td>Browser</td>
		<td>Chrome</td>	
	</tr>
	<tr>
		<td>without fix</td>
		<td>:x:</td>	
	</tr>
	<tr>
		<td>fix 1</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>int fix</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>LUT fix</td>
		<td>:white_check_mark:</td>	
	</tr>
</table>

<table>
	<tr>
		<td>OS</td>
		<td>Windows 7</td>
	</tr>
	<tr>
		<td>GPU</td>
		<td>Software</td>	
	</tr>
	<tr>
		<td>Renderer</td>
		<td>-</td>	
	</tr>
	<tr>
		<td>Browser</td>
		<td>Firefox</td>	
	</tr>
	<tr>
		<td>without fix</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>fix 1</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>int fix</td>
		<td>:white_check_mark:</td>	
	</tr>
	<tr>
		<td>LUT fix</td>
		<td>:white_check_mark:</td>	
	</tr>
</table>

**Comment by m-schuetz** [comment]
Looks like the "int fix" version is the one that works on all systems. I've commited it here: https://github.com/potree/potree/commit/145ef2d3cb8e286840e71a279afd297b98d70234
and it's already part of develop.

Thanks for the tests, that was very helpful!
