### ISSUE TITLE
Chrome/FF crash if too many loading operations are in progress

### ISSUE THREAD

**Issue by rwfrenz20** [potree/potree#464]
I have a large dataset (~200 LAS files, 30GB bin) that causes problems upon loading.  Chrome crashes after a few seconds with little info.  Firefox works most of the time, but occasionally hangs, emitting messages about too many workers.

Looking in the code (WorkerPool.js) I notice that there is no guard on the number of loading operations, and in fact the crash in Chrome happens after about 20 workers are running at once.  I'm not sure if the actual limit here is about web workers or AJAX/HTTP requests, but the issue (in my dataset, at least) goes away if I limit the number of simultaneous operations to 16.

I will create a PR with my approach to fixing this, feel free to incorporate it.

For reproduction - I'm not sure I can share my dataset, but it should be observable in any sufficient large dataset (or number of pointclouds).  I'm testing w/ python SimpleHTTPServer and the data on a USB3 external drive.

-Ryan

**Comment by m-schuetz** [comment]
Too many loading workers should usually be implicitly prevented due to a limit on how many nodes are loaded in parallel at any given time.

See: https://github.com/potree/potree/blob/develop/src/PointCloudOctreeGeometry.js#L112

I get at most 4 workers, which matches with the line above that aborts loading if there are already four nodes which are being loaded.

**Comment by rwfrenz20** [comment]
Interesting.  I'll debug further but that's not what I'm seeing at the WorkerPool level.

I instrumented WorkerPool.getWorker and WorkerPool.returnWorker to increment/decrement a counter.  I see it get very large (over 60) with a large dataset.  Chrome only runs stably when I limit it to < 16.

Is this 'numNodesLoading' tracked for the entire scene, or is it only per-scan?

**Comment by rwfrenz20** [comment]
It appears this numNodesLoading counter is unique for each point cloud.  In my case, I have 203 point clouds, which causes the issue even though numNodesLoading stays < 4 in any one point cloud.  At the extreme I have 203 pcoGeometry objects, each with numNodesLoading of 1.

**Comment by m-schuetz** [comment]
Good catch, it shouldn't be ```this.pcoGeometry.numNodesLoading``` but something like ```Potree.numNodesLoading```.

I'll fix that in develop.

**Comment by rwfrenz20** [comment]
That should be fine, and simpler than my solution.  Please consider raising the limit to match - my example performs quite nicely with a limit of 16.

**Comment by m-schuetz** [comment]
fixed: https://github.com/potree/potree/commit/4bb1364369996b870878608ed413c0426c570880

You can set the max number of nodes that are loaded in parallel to, for example 20, with ```Potree.maxNodesLoading = 20```;
