### ISSUE TITLE
JS error rendering intensity material

### ISSUE THREAD

**Issue by rwfrenz20** [potree/potree#465]
potree.js:17452 Uncaught TypeError: First argument to DataView constructor must be an ArrayBuffer
    at new DataView (<anonymous>)
    at PotreeViewer.update (potree.js:17379)
    at PotreeViewer.loop (potree.js:17776)

Data was created with --output-attributes INTENSITY and --material INTENSITY

**Comment by m-schuetz** [comment]
Do you have a link I can check?

**Comment by rwfrenz20** [comment]
Actually...I can't seem to reproduce now, sorry.  Possibly a corrupt point cloud.  I will close this and re-open if I see again.
