### ISSUE TITLE
Adjustable Point size

### ISSUE THREAD

**Issue by yonasteodros** [potree/potree#466]
I have changed two Ply files clouds with 40901and 67894 vertices  using Potree 1.5RC and I was trying to experiment by changing the size using "Min node size" slider, for the one with 40901 vertices  I can't see any changes but for the other one  works. Is there a possible way of having the "Point size" slider  just like Potree 1.4RC in 1.5RC ?

Picture for 40901 vertices

![screenshot-2017-12-31 admin page](https://user-images.githubusercontent.com/3707570/34460756-3275bcce-ee18-11e7-9ac7-0b54883c81ab.png)

Picture for 67894 vertices

![screenshot-2017-12-31 admin page 1](https://user-images.githubusercontent.com/3707570/34460737-bc61721c-ee17-11e7-83ca-3e701558faaf.png)

**Comment by GinaVulpes** [comment]
I have the same problem; I cannot adjust the size of the points. Any solutions for this?

**Comment by m-schuetz** [comment]
Point sizes and other material properties are now adjustable per-point-cloud. You can therefore find the point size slider and other settings inside the "Scene" panel, when you click on the point cloud.

**Comment by bejucoo** [comment]
Hello, is it possible to change the point size programmatically?
