### ISSUE TITLE
Add object to potree without adding point cloud

### ISSUE THREAD

**Issue by Dmarcoux111** [potree/potree#483]
General question,

Is there a way to initialize a potree scene and add a threejs object to it without adding a point cloud first?

The examples only show how to add meshes after a pointcloud has been added.

**Comment by mghildiy** [comment]
I also want to add geometric objects to a potree scene, like boxes,cylinders,circles etc. Is it possible?

**Comment by Dmarcoux111** [comment]
viewer.scene.scene.add( THREE.Mesh() )
