### ISSUE TITLE
Clarify point cloud coordinate system when using Cesium

### ISSUE THREAD

**Issue by danallen26** [potree/potree#484]
Hello,

Thanks in advance for anybody who can help me out!

I am using potree alongside Cesium to render pointclouds that (hopefully) are geo-aligned with the world. There are a couple of examples of this in the potree develop branch (https://github.com/potree/potree/blob/develop/examples/cesium_ca13.html and https://github.com/potree/potree/blob/develop/examples/cesium_sorvilier.html) which do exactly what I want. 

The problem is that I don't quite understand how the projection of coordinates onto the map work. My point clouds are in their own arbitrary local reference frame, which I wish to display in the north-east-down (NED) coordinate frame by applying rotation, scaling and translation. I am currently defining the pointcloudProjection as:

```pointcloudProjection = '+proj=some_model +lat_0=$latitude +lon_0=$longitude +k_0=1 +x_0=0 +y_0=0 +ellps=bessel +towgs84=0.0,0.0,0.0,0,0,0,0 +units=m +no_defs'```

I would have thought that this should place the origin of my point cloud on the surface of the earth at the specified $latitude and $longitude on the WGS84 model. This appears to be true for one of my models, however when I made a point cloud representing the x, y and z axes (to investigate rotations) the point cloud floats far away from the earth in the scene. This is confusing to me as I now do not understand how potree is rendering my point clouds relative to the earth.

If someone could explain to me how this works I would be very grateful :)

Cheers,
Dan.

**Comment by nikste** [comment]
how did you solve this issue ?
