### ISSUE TITLE
Index not refreshed

### ISSUE THREAD

**Issue by aleksandrmelnyk** [potree/potree#488]
hi all,

We have run entwine build, it successfully generated index. Then we have run build with extended source data into same folder as previous. But greyhound still provides extent from previous  index, new data/tiles not visible.

Any ideas what could it be?

**Comment by m-schuetz** [comment]
Have you tried flushing the cache? If that doesn't work, the greyhound guys may be better able to answer this: https://github.com/hobu/greyhound
