### ISSUE TITLE
1.6 release has a error at the builded potree.js file

### ISSUE THREAD

**Issue by wemamawe** [potree/potree#496]
hello sir,

when i use the lastest potree1.6, i found that there are some mistakes.

1. Stats not defined
![stats](https://user-images.githubusercontent.com/29365634/37750227-e6ac78fc-2dc6-11e8-869e-b77272c25c05.png)

2. there is no potree.css file in Potree/build/potree/ folder, when i use examples.

**Comment by potree** [comment]
I couldn't find "this.stats = new Stats()" in the latest source code or its build.
This is the location in viewer.js where it's previously been: https://github.com/potree/potree/blob/develop/src/viewer/viewer.js#L90

Are you certain you've got the latest version of potree?

**Comment by wemamawe** [comment]
i used git to pull a lastest virsion from https://github.com/wemamawe/potree.git, and i checked your .gitingnore file, you set some file ignored.

**Comment by m-schuetz** [comment]
I can't find any occurance of new Stats() in the release or in the develop branch.

**Comment by m-schuetz** [comment]
> i used git to pull a lastest virsion from https://github.com/wemamawe/potree.git, and i checked your .gitingnore file, you set some file ignored.

You need to pull from https://github.com/potree/potree.git
