### ISSUE TITLE
Potree & Cesium

### ISSUE THREAD

**Issue by antoinebio** [potree/potree#500]
Here is an open discussion started on Gitter
the idea is to use CESIUM streaming maps background Pointcloud in Potree.
Based on example such as 
http://www.potree.org/potree/examples/cesium_sorvilier.html
http://potree.org/potree/examples/cesium_retz.html
I tried to copy paste these codes keeping only what is referring to my poincloud (Potree.loadPointCloud("pointclouds/ ... )
Please note that I have explicitly defined my pointcloud proj when I've converted it with potree converter ( in proj4 format)
In potree viewer setup i used I recall it like that "let pointcloudProjection = e.pointcloud.projection;"
First issue noticed:
the map focus its position at the same location than examples/cesium_sorvilier.html
second issue noticed:
also potree is not reacting (no map interaction) and pointcloud is not displayed....
in POTREE sorvilier example there is that sentence
let cp = new Cesium.Cartesian3(4303414.154026048, 552161.235598733, 4660771.704035539);
these coord refer to sorvilier location in geocentric coord. 
So I've transformed my pt cloud location in geocentric coord and updated the code so that CESIUM is focused on my project location....but Potree doesn't like it... (still frozen)
But what I don't catch is that 
in view-source:http://www.potree.org/potree/examples/cesium_sorvilier.html
in view-source:http://www.potree.org/potree/examples/cesium_ca13.html
and in view-source:http://www.potree.org/potree/examples/cesium_retz.html
the same geocentric coordinates are used, even if pointcloud isn't located at that place...

**Comment by adamsss92** [comment]
Did you solve your problem? I've got exactly the same issue :(

**Comment by loicroybon** [comment]
Up ! I've the same issue... Hope there's someone to explain us how to proceed

**Comment by antoinebio** [comment]
copy/paste that below html file and update the line #92 Potree.loadPointCloud(....) with your pointcloud created from PotreeConverter.

[cesium_enable.txt](https://github.com/potree/potree/files/2380937/cesium_enable.txt)
