### ISSUE TITLE
Potree requires 'window.viewer' variable?

### ISSUE THREAD

**Issue by rfrenz-avio** [potree/potree#502]
Is it required to set window.viewer after creating a Potree Viewer object?  It appears to be, at least in the version (1.5) that I'm using.

Or is it something I'm doing wrong?  I'm trying to implement a feature where I use a second Viewer object and a dialog window, and managing this global variable is quite error prone.

Thanks in advance!
-Ryan

**Comment by potree** [comment]
Might be some accidental usage of global viewer variable. Shouldn't happen, at least not with 1.6.
Creating two viewer instances is not really supported. It may or may not work but probably not. You could try to embedd multiple viewers in iframes, though.

**Comment by rfrenz-avio** [comment]
By 'unsupported' - is there any specific known or suspected problem?  I could have a try to improve it.

And thank you, 1.6 does not appear to behave any differently with or without window.viewer set.

-Ryan
