### ISSUE TITLE
Loading data as a straight line along the top grid edge

### ISSUE THREAD

**Issue by belrion** [potree/potree#52]
Hi,

Love the demo using distance measuring. Try to use with my data but did not seem to work correctly. Here are my steps:
1. Converted my LiDAR.las file to binary using PotreeConverter command:
   potreeConverter -o examples -l 15 --source examples/FusedLidar_Lidar34.las
2. Output:
   == params ==
   source[0]: examples/FusedLidar_Lidar34.
   outdir: examples
   spacing: 1
   levels: 15
   format: xyzrgb
   range: 255
   output-format: BINARY

AABB:
min: [-76.6152, 39.2969, -15.823]
max: [-76.6135, 39.2985, 13.492]
size: [0.00163842, 0.00154115, 29.315]

reading examples/FusedLidar_Lidar34.las
1m points processed
duration: 20.264s
2m points processed
duration: 113.698s
722,679 points written
duration: 154.632s
closing writer
duration: 155.036s
1. I had edited the distance_measure.html to include the new point clouds
2. When run, it displayed the grid with everything except the point clouds data: however, if you pan the camera to the top you can see the data lined up against one of the edge

Can you please tell me what had gone wrong with the above process? I suspect that my AABB box is not matching my data but don't know enough to fix anything.

Thanks,
Chi

**Comment by lyaunzbe** [comment]
@belrion Can you let me know what tool you used for the successful conversion? I am encountering a similar issue. Thank you!

**Comment by belrion** [comment]
Hi Ben,
The conversion tool and potree are working fine. The fact that we are seeing a straight line is because of the pointcloud setup.
I'd ended up changing the rotation.set, scene.add with bigger grid and moving/removing the position.y to the appropriate the location.
You have to play around it so the grid can cover your pointcloud then you can see all of them. The straight line means the grid is outside of the pointcloud formation (too low, too high or too far away.)
-Chi

**Comment by lyaunzbe** [comment]
Ahh okay, that makes sense. But my las file is still in latlon (wgs84) when I give it to the potreeconverter. I'm trying to figure out what tool to use to convert it to xyz (Cartesian) or UTM. 

Thanks

**Comment by belrion** [comment]
There isn't a good tool that will convert from Lat/Lon to XYZ. I have to use an internal developed tool to do that before using PoTree successfully.
You can use some public lib (e.g. liblas) to write your own conversion tool.
-Chi
