### ISSUE TITLE
Access to image texture from shader 

### ISSUE THREAD

**Issue by jo-chemla** [potree/potree#527]
I am trying to use a texture directly in the vertex shader, through `color = texture2D(textureUniform, uv).rgb;`. I have ported an old version of a demo code of mine which was working with Potree 1.5, but does not work on 1.6 - yet. I followed the gradient or classificationLUT textures models, copying generation, storing the three texture in the PotreeMaterial of the pointcloud, and updating the uniform texture value. The generation code is basically the following: 

```
generateCustomTexture(filepath) {
  let texture = new THREE.TextureLoader().load( new URL(Potree.resourcePath + "/textures/" + filepath).href, function(tex) {console.log(tex);} );
  return texture;
}
```

It seems that the way textures are handled in the material shader have recently changed, am I right ? If so, it seems like the image texture type is not yet handled. 

Update : 
The texture is visible when setting it as the map for a plane : 
```
material = new THREE.MeshLambertMaterial({ map : viewer.scene.pointclouds[0].material.uniforms.textureUniform.value }); 
plane = new THREE.Mesh(new THREE.PlaneGeometry(300, 300), material); 
viewer.scene.scene.add(plane)
```
There seems to be no big changes between Threejs Versions of Potree 1.5 (r83) and 1.6RC (r85) as seen here https://github.com/mrdoob/three.js/wiki/Migration-Guid

I supsect this comes from the portion of code 
```
let gradientTexture = this.textures.get(material.gradientTexture); 
shader.setUniform1i("gradient", currentTextureBindingPoint); 
gl.activeTexture(gl.TEXTURE0 + currentTextureBindingPoint); 
gl.bindTexture(gradientTexture.target, gradientTexture.id); 
currentTextureBindingPoint++;
```
or from the setUniform method, where Potree.WebGLTexture does not yet handle image textures. Am I correct ? 

All the best,

**Comment by jo-chemla** [comment]
Hi @m-schuetz , sorry to bother, any news concerning this issue ? Just posted to gitter as well. All the best, Jonathan

**Comment by jo-chemla** [comment]
Hi @m-schuetz , sorry to bother, any news concerning this issue ? Here are the ways I am trying to load the custom image in the material shader gradient texture : 
```
texture1=ImageUtils.loadTexture (url), 
texture2=TextureLoader().load(url), 
texture3: Texture(base64_image)
```
All of tehse work when applied to the material of a mesh or of the background with `viewer.scene.sceneBG.children[0].material.map = viewer.scene.pointclouds[0].material.uniforms.matcapTextureUniform.value`

I've progressed a bit, and found out that the
Potree.WebGLTexture::update() function only handles THREE.DataTexture and THREE.CanvasTexture instances, while my texture is a simple THREE.Texture, with an image stored as src (url or base64 URI). Trying to play around with these gl.texImage2D parameters, inspired from the other instances examples, I could not find a way to use my custom texture in the shader material. Would love a hint, thanks!

**Comment by ua4192** [comment]
Hi 

I have tried to use a DataTexture built with a Uint8Array( 1024*1024*4 ) as material uniform in order to remap the point vertext color using this texture, but I get always ffffff ( white color) from texture2D command in the potree shader.

I have tried to access the texture data from VexterShader and from Fragment Shader both with same result.

I have used the same DataTexture in a THREE.Mesh without any issue.

best regards

**Comment by TBusan** [comment]
> 你好
> 
> 我尝试使用使用 Uint8Array（ 1024_1024_4 ） 构建的 DataTexture 作为材质均匀，以便使用此纹理重新映射点垂直文本颜色，但我总是从 potree 着色器中的 texture2D 命令中获得 ffffff（白色）。
> 
> 我尝试从 VexterShader 和 Fragment Shader 访问纹理数据，结果相同。
> 
> 我在 THREE 中使用了相同的 DataTexture。网格没有任何问题。
> 
> 此致敬意



> Hi
> 
> I have tried to use a DataTexture built with a Uint8Array( 1024_1024_4 ) as material uniform in order to remap the point vertext color using this texture, but I get always ffffff ( white color) from texture2D command in the potree shader.
> 
> I have tried to access the texture data from VexterShader and from Fragment Shader both with same result.
> 
> I have used the same DataTexture in a THREE.Mesh without any issue.
> 
> best regards

@ua4192    Hi   are  you resolved??

**Comment by ua4192** [comment]
Hi.
I have partialy got what I pretended to get. The texture is being used by the shader. I am using a RGBA UNISIGNED_BYTE texture 4 * side * side and the mapping is not accurate at all.
So, I has not custom texture working working yet.
It seems that potree has no support at all from the developers, I guess too much busy withother topics, I openened multiple tickets without answer
