### ISSUE TITLE
Can't see shp file on render area

### ISSUE THREAD

**Issue by Raquel0** [potree/potree#532]
Hello! I'm web-dev noobie and i'm trying to modify potree examples to get some things. I achieved viewing my point cloud over base map like cesium retz example. The problem comes when i try to use the same pointcloud with the shapfile example. I can see the shapefile into the layer tree but no shapefile showed into the render area. I was careful with projections in every step and no error is showed. I would be infinitely grateful if somebody helps me. Thank your very much in advance.
 
![image](https://user-images.githubusercontent.com/40294955/42262168-b62f1fc2-7f6a-11e8-9f7d-c3d99020a535.png)

here can be seen the shapefile into scene but it is not shown anywhere in render area

**Comment by zwnk** [comment]
take a look at: https://github.com/potree/potree/issues/375

**Comment by Rakel00** [comment]
@zwnk than you very much, I achieved loading data using geojson and the code you told me but it would be useful for my project to mantain data in shapefile.
