### ISSUE TITLE
Improve the initialization of controls in Viewer

### ISSUE THREAD

**Issue by chuxiaonan** [potree/potree#537]
As we has known, `Potree` loads a specific `cloud.js` file from remote server, which, by all means, delays the callback codes when a point cloud is about to load into the scene, because it is asynchronous. Error would be thrown when I change the loading way synchronously, however. There is `TypeError: Cannot read property 'stop' of undefined` shown on console panel.

As deep as I can investigate, there's no initializer for `this.controls` in [constructor of `Viewer`](https://github.com/potree/potree/blob/32ca9f782d3b2e944a16a3cb15de9c4388bb85f5/src/viewer/viewer.js#L31-L252), located in `src/viewer/viewer.js`. In deed, `this.controls` is initialized in `this.update()`, which is invoked by `this.loop()` every `requestAnimationFrame`'s time span. Imagine what will happen if we instantiate a `viewer` by `const viewer = new Potree.Viewer()`, and fit it to screen by `viewer.fitToScreen()` immediately? *`this.controls` will be `undefined` and error would be  thrown!*

So how can this occur? As I mentioned above, **load point cloud in a synchronous way**. 
```js
const viewer = new Potree.Viewer();

// As you see, it is synchronous
Potree.loadPointCloudSync(pointCloud, () => {
  viewer.scene.addPointCloud(pointCloud);
  // some actions here

  viewer.fitToScreen(); // Oh! Error here!
});
```

Why should I load point cloud synchronously? Because I have got it already. All should I do is to load it into the scene and render it correctly. It is not necessary to load it from a remote server asynchronously. There is a limitation, truly; however, I don't think I'm the one to solve it, in my humble option.

**Comment by m-schuetz** [comment]
Hello chuxiaonan,

One of the main reason things are asynchronous is to make sure that potree remains responsive at all times. If connection is slow then potree will stall if you do it synchronously, so there is no advantage in doing it synchronously. You could get a slight improvement if you'd put the cloud.js data directly into the html file but that improvement won't be significant compared to the time it takes to load the actual point cloud data afterwards.

**Comment by chuxiaonan** [comment]
Thanks for your kind help @m-schuetz . You are right, it doesn't count because everything is stalled. So, as a potential solution, do not try to use `this.controls` when it is not initialized, and after all, it will be ready some time (usually after a `requestAnimationFrame`'s time span).
