### ISSUE TITLE
How to download all points inside a volume as las file.

### ISSUE THREAD

**Issue by joki0924** [potree/potree#549]

**Comment by joki0924** [comment]
I want to download all points inside a volume as a las file.
I am not sure how to iterate all nodes and its points.
Please somebody help me.

**Comment by mariczone** [comment]
https://github.com/potree/potree/blob/develop/src/PointCloudOctree.js

Method: getPointsInBox will help you to get all points in side a volume box

*You may need to modify code that read geometry from buffer to read from geometry attribute of that node instead.

**Comment by luisebenkert** [comment]
I would like to do the same, without the import to a las file, though. So I pretty much just want to use the volume measurement tool and have all points inside of the volume box returned. I looked at @mariczone 's reply and also answers to other similar questions, but I can't seem to figure it out. Unfortunately, the getPointsInBox method is never used, so maybe someone can provide a simple example for it?

**Comment by joki0924** [comment]
Hi, everyone, sorry for late reply.

I checked getPointsInProfile() method and made a similar function that returns all points inside a given box.
It works pretty well, but it is not good enough.
The method is async and I can't estimate time for getting all points.
If anyone wants, I can share my code.

**Comment by joki0924** [comment]
Finally, I have made a server-side program to make a clipped box.
It's using laszip and lastools source code and works like lasmerge or las2las programs.
I am sure it's much better to let users download clipped las file made on server-side.

**Comment by luisebenkert** [comment]
@joki0924 if you could share your code, that would be amazing!

**Comment by adamsteer** [comment]
Hi all

There’s some prototyping work here: https://github.com/adamsteer/pointWPS

…using PyWPS + PDAL to do lots of things with points server-side. But LAStools is another way (or libLAS). It’s not operational at the moment, we’ll re-implement it soon :)

**Comment by julienbaudry** [comment]
Hi @joki0924 
I'm really interested to see your similar function to getPointsInProfile() allowing to return all points inside a given box.
If you could share your code, it would be really great !

**Comment by joki0924** [comment]
Hi, everyone. I am sharing my code for it.
But please don't laugh at my low-quality code.

`
// this needs to be placed where the download request is necessary.
let doSomeWork = () => {

    let clipBox = new THREE.Box3();

    let curPoint = new THREE.Vector3().copy(this.measurement.points[0].position);
    curPoint.z = -99999;
    let width = 200, length = 200;
    let maxDepth = 6;

    clipBox.expandByPoint(curPoint);
    clipBox.expandByPoint(curPoint.add(new THREE.Vector3(width, length, 99999999)));

    let points = new Points();

    this.requests = [];

    for (let pointcloud of this.viewer.scene.pointclouds.filter(p => p.visible)) {
        let request = pointcloud.getPointsInBox3(clipBox, maxDepth, {
            'onProgress': (event) => {

                console.log('working...', event.points);
                points.add(event.points);
                //

            },
            'onFinish': (event) => {
                console.log(points);


                let buffer = LASExporter.toLAS(points);

                let blob = new Blob([buffer], {type: "application/octet-binary"});
                $('#hhhhhhh').attr('href', URL.createObjectURL(blob));

                console.log('finished');

            },
            'onCancel': () => {

            }
        });

        this.requests.push(request);
    }
}

//getPointsInBox3() method on PointCloudOctree.js

getPointsInBox3(box, maxDepth, callback) {
        let request = new Potree.DownloadRequest(this, box, maxDepth, callback);
        this.downloadRequests.push(request);

        return request;
    }

// DownloadRequest.js file

import {Points} from "./Points";


export class DownloadRequest {
	constructor (pointcloud, box, maxDepth, callback) {
		this.pointcloud = pointcloud;
		this.box = box;
		this.maxDepth = maxDepth || Number.MAX_VALUE;
		this.callback = callback;
		this.temporaryResult = new Points();
		this.pointsServed = 0;
		this.highestLevelServed = 0;

		this.priorityQueue = new BinaryHeap(function (x) { return 1 / x.weight; });

		this.initialize();
	}

    nodeIntersectsBox (node, box){

        let bbWorld = node.boundingBox.clone().applyMatrix4(this.pointcloud.matrixWorld);

        return bbWorld.intersectsBox(box);

    }

	initialize () {
		this.priorityQueue.push({node: this.pointcloud.pcoGeometry.root, weight: Infinity});
	};

	// traverse the node and add intersecting descendants to queue
	traverse (node) {
		let stack = [];
		for (let i = 0; i < 8; i++) {
			let child = node.children[i];
			if (child && this.nodeIntersectsBox(child, this.box)) {
				stack.push(child);
			}
		}

		while (stack.length > 0) {
			let node = stack.pop();
			let weight = node.boundingSphere.radius;

			this.priorityQueue.push({node: node, weight: weight});


			// add children that intersect the cutting plane
			if (node.level < this.maxDepth) {
				for (let i = 0; i < 8; i++) {
					let child = node.children[i];
					if (child && this.nodeIntersectsBox(child, this.box)) {
						stack.push(child);
					}
				}
			}
		}
	}

	update(){
		if(!this.updateGeneratorInstance){
			this.updateGeneratorInstance = this.updateGenerator();
		}

		let result = this.updateGeneratorInstance.next();
		if(result.done){
			this.updateGeneratorInstance = null;
		}
	}

	* updateGenerator(){
		// load nodes in queue
		// if hierarchy expands, also load nodes from expanded hierarchy
		// once loaded, add data to this.points and remove node from queue
		// only evaluate 1-50 nodes per frame to maintain responsiveness

		let start = performance.now();

		let maxNodesPerUpdate = 1;
		let intersectedNodes = [];

		for (let i = 0; i < Math.min(maxNodesPerUpdate, this.priorityQueue.size()); i++) {
			let element = this.priorityQueue.pop();
			let node = element.node;

			if(node.level > this.maxDepth){
				continue;
			}

			if (node.loaded) {
				// add points to result
				intersectedNodes.push(node);
				exports.lru.touch(node);
				this.highestLevelServed = Math.max(node.getLevel(), this.highestLevelServed);

				let doTraverse = (node.level % node.pcoGeometry.hierarchyStepSize) === 0 && node.hasChildren;
				doTraverse = doTraverse || node.getLevel() === 0;
				if (doTraverse) {
					this.traverse(node);
				}
			} else {
				node.load();
				this.priorityQueue.push(element);
			}
		}

		if (intersectedNodes.length > 0) {

			for(let done of this.getPointsInsideBox(intersectedNodes, this.temporaryResult)){
				if(!done){
					//console.log("updateGenerator yields");
					yield false;
				}
			}
			if (this.temporaryResult.numPoints > 100) {
				this.pointsServed += this.temporaryResult.numPoints;
				this.callback.onProgress({request: this, points: this.temporaryResult});
				this.temporaryResult = new Points();
			}
		}

		if (this.priorityQueue.size() === 0) {
			// we're done! inform callback and remove from pending requests

			if (this.temporaryResult.numPoints > 0) {
				this.pointsServed += this.temporaryResult.numPoints;
				this.callback.onProgress({request: this, points: this.temporaryResult});
				this.temporaryResult = new Points();
			}

			this.callback.onFinish({request: this});

			let index = this.pointcloud.downloadRequests.indexOf(this);
			if (index >= 0) {
				this.pointcloud.downloadRequests.splice(index, 1);
			}
		}

		yield true;
	};

	* getAccepted(numPoints, node, matrix, points){
		let checkpoint = performance.now();

		let accepted = new Uint32Array(numPoints);
		let acceptedPositions = new Float32Array(numPoints * 3);
		let numAccepted = 0;

		let pos = new THREE.Vector3();
		let svp = new THREE.Vector3();

		let view = new Float32Array(node.geometry.attributes.position.array);

		for (let i = 0; i < numPoints; i++) {

			pos.set(
				view[i * 3 + 0],
				view[i * 3 + 1],
				view[i * 3 + 2]);
		
			pos.applyMatrix4(matrix);

			if (this.box.containsPoint(pos)) {

				accepted[numAccepted] = i;
                points.boundingBox.expandByPoint(pos);


                acceptedPositions[3 * numAccepted + 0] = pos.x;
				acceptedPositions[3 * numAccepted + 1] = pos.y;
				acceptedPositions[3 * numAccepted + 2] = pos.z;

				numAccepted++;
			}

			if((i % 1000) === 0){
				let duration = performance.now() - checkpoint;
				if(duration > 4){
					//console.log(`getAccepted yield after ${duration}ms`);
					yield false;
					checkpoint = performance.now();
				}
			}
		}

		accepted = accepted.subarray(0, numAccepted);
		acceptedPositions = acceptedPositions.subarray(0, numAccepted * 3);

		//let end = performance.now();
		//let duration = end - start;
		//console.log("accepted duration ", duration)

		//console.log(`getAccepted finished`);

		yield [accepted, acceptedPositions];
	}

	* getPointsInsideBox(nodes, target) {
		let checkpoint = performance.now();

		for (let node of nodes) {
			let numPoints = node.numPoints;
			let geometry = node.geometry;

			if(!numPoints){
				continue;
			}

			{ // skip if current node doesn't intersect current box
				let intersects = this.nodeIntersectsBox(node, this.box);

				if(!intersects){
					continue;
				}
			}

			let points = new Points();

			let nodeMatrix = new THREE.Matrix4().makeTranslation(...node.boundingBox.min.toArray());

			let matrix = new THREE.Matrix4().multiplyMatrices(
				this.pointcloud.matrixWorld, nodeMatrix);

			let accepted = null;
			let acceptedPositions = null;
			for(let result of this.getAccepted(numPoints, node, matrix, points)){
				if(!result){
					let duration = performance.now() - checkpoint;
					//console.log(`getPointsInsideProfile yield after ${duration}ms`);
					yield false;
					checkpoint = performance.now();
				}else{
					[accepted, acceptedPositions] = result;
				}
			}

			let duration = performance.now() - checkpoint;
			if(duration > 4){
				//console.log(`getPointsInsideProfile yield after ${duration}ms`);
				yield false;
				checkpoint = performance.now();
			}

			points.data.position = acceptedPositions;

			let relevantAttributes = Object.keys(geometry.attributes).filter(a => !["position", "indices"].includes(a));
			for(let attributeName of relevantAttributes){

				let attribute = geometry.attributes[attributeName];
				let numElements = attribute.array.length / numPoints;

				if(numElements !== parseInt(numElements)){
					debugger;
				}

				let Type = attribute.array.constructor;

				let filteredBuffer = new Type(numElements * accepted.length);

				let source = attribute.array;
				let target = filteredBuffer;

				for(let i = 0; i < accepted.length; i++){

					let index = accepted[i];

					let start = index * numElements;
					let end = start + numElements;
					let sub = source.subarray(start, end);

					target.set(sub, i * numElements);
				}

				points.data[attributeName] = filteredBuffer;
			}

			points.numPoints = accepted.length;

			target.add(points);
		}

		//console.log(`getPointsInsideProfile finished`);
		yield true;
	};

	finishLevelThenCancel () {
		if (this.cancelRequested) {
			return;
		}

		this.maxDepth = this.highestLevelServed;
		this.cancelRequested = true;

		//console.log(`maxDepth: ${this.maxDepth}`);
	};

	cancel () {
		this.callback.onCancel();

		this.priorityQueue = new BinaryHeap(function (x) { return 1 / x.weight; });

		let index = this.pointcloud.profileRequests.indexOf(this);
		if (index >= 0) {
			this.pointcloud.profileRequests.splice(index, 1);
		}
	};
}


// on Potree_update_visibility.js
// update updatePointClouds() method

for (let profileRequest of pointcloud.profileRequests) {
			profileRequest.update();

			let duration = performance.now() - start;
			if(duration > 5){
				break;
			}
		}

        for (let downloadRequest of pointcloud.downloadRequests) {
            downloadRequest.update();

            let duration = performance.now() - start;
            if(duration > 5){
                break;
            }
        }

		let duration = performance.now() - start;


// on potree.js
add this line.
export * from "./DownloadRequest.js";



`

**Comment by joki0924** [comment]
If you have any questions, I am always ready on skype.
skype id id liangjongai@126.com.

**Comment by tolsac** [comment]
@joki0924 You're not taking in account the Volume possible rotations

**Comment by pewixg3** [comment]
> @ joki0924 Vous ne tenez pas compte du nombre de rotations possibles

It's true !
I wonder how I can apply the rotation of my volume on the box3

**Comment by LCGsystems** [comment]
I still don't understand how you implement those codes.
What do you mean by "// this needs to be placed where the download request is necessary.
let doSomeWork = () => {"? Is it in your HTML index file or in a separate file?
How do you call the three other functions PointCloudOctree.js, DownloadRequest.js and Potree_update_visibility.js? Don't you need to call them in the HTML file like "<script src="libs/extra/PointCloudOctree.js"></script>"?

**Comment by m-schuetz** [comment]
Closing this here since it won't make it into the 1.7 release and 2.0 will be a rewrite where things will be very different. Feel free to keep discussing though, if you've got solutions/ideas on how to manually add this feature to 1.6.

**Comment by MaxymShtoyko** [comment]
@m-schuetz  any updates?

**Comment by MaxymShtoyko** [comment]
@joki0924 did you manage to find any solution?

**Comment by Zvyozdo4ka** [comment]
> https://github.com/potree/potree/blob/develop/src/PointCloudOctree.js
> 
> Method: getPointsInBox will help you to get all points in side a volume box
> 
> *You may need to modify code that read geometry from buffer to read from geometry attribute of that node instead.

Hello. Only inside the box? is it those points, which have been intersected with the box and points? Is in possible to get points of any other polygon?

**Comment by Zvyozdo4ka** [comment]
> Hi, everyone. I am sharing my code for it. But please don't laugh at my low-quality code.
> 
> ` // this needs to be placed where the download request is necessary. let doSomeWork = () => {
> 
> ```
> > `

Could you share the real example, please? I am newcomer in potree. Thanks for sharing code too. What is the difference of your code and existing Method: getPointsInBox, which has been mentioned before

**Comment by okaforcj** [comment]
for any one looking to just see the points inside a box volume this is the modified code that i had 

because to add a timer variable in VolumePanel class if youre 

`pointsInBox() {
      const pointCloud = window.viewer.scene.pointclouds[0];
      const measurement = this.measurement;
      console.log(measurement, pointCloud.visibleNodes);

      const pointNodes = pointCloud.visibleNodes.map((node, index) => {
        return node.getPointsInBox(measurement);
      });

      const flatNodes = pointNodes.flat();

      const groupedMap = flatNodes.reduce(
        (entryMap, e) => entryMap.set(e.classification, [...entryMap.get(e.classification)||[], e]),
        new Map()
    );

      console.log(groupedMap);
    }

    debounce(func, timeout = 1000) {
      return () => {
        if (this.timer) clearTimeout(this.timer);
        this.timer = setTimeout(() => {
          func();
        }, timeout);
      };
    }

    update() {
      this.debounce(() => this.pointsInBox(), 3000)();
      }`

**Comment by okaforcj** [comment]
then the modified code for points in the box
      ``` 
    getPointsInBox(boxNode) {
      if (!this.sceneNode) {
        return null;
      }

      const attributes = this.geometryNode.geometry.attributes;
      const position = attributes.position;
      const worldToBox = boxNode.matrixWorld.clone().invert();
      const objectToBox = new Matrix4().multiplyMatrices(
        worldToBox,
        this.sceneNode.matrixWorld
      );
      let inBox = [];

      for (let i = 0; i < position.count; i++) {
        const pos = new Vector3();
        const arr = position.array;
        const x = arr[3 * i];
        const y = arr[3 * i + 1];
        const z = arr[3 * i + 2];
        pos.set(x, y, z);
        pos.applyMatrix4(objectToBox);

        // console.log(point)

        if (-0.5 < pos.x && pos.x < 0.5) {
          if (-0.5 < pos.y && pos.y < 0.5) {
            if (-0.5 < pos.z && pos.z < 0.5) {
              const classification = attributes.classification.array[i];
              let point = new Vector3(x, y, z);
              point.applyMatrix4(this.sceneNode.matrixWorld);
              inBox.push({
                classification,
                point,
              });
            }
          }
        }
      }

      return inBox;
    }```
