### ISSUE TITLE
CPU/GPU usage is constant even after loading complete

### ISSUE THREAD

**Issue by rfrenz-avio** [potree/potree#561]
Hi,

I'm looking at various optimizations for my application, and noticed that Potree 1.6 is causing the page to use a significant amount of CPU and GPU even after the point cloud is fully loaded and without any user interaction.  Debugging a bit, I see that Potree.Viewer.update and Potree.Viewer.render are being called continuously.

This can be seen simply by loading any example from Potree.org and watching Windows Task Manager.

![image](https://user-images.githubusercontent.com/35305009/46631675-19f4e900-cb16-11e8-8439-12b324b364d3.png)

This image is taken after loading [lion_laz](http://www.potree.org/potree/examples/lion_laz.html) and letting it render for several minutes.

Of course a static scene should be refreshed when the browser requests, but otherwise there should be a way to avoid doing a full render if nothing has changed (i.e. all points loaded for current view and no camera change).

Is this possible?  Or, if not, is there a way to access information about loading progress (so I could use Potree.Viewer.freeze or similar to control performance)?

Any advice is appreciated.
-Ryan

**Comment by m-schuetz** [comment]
Hi Ryan,

You could try to replace the Potree render loop with your own.
To do this, create a PotreeViewer and pass the ```useDefaultRenderLoop``` argument set to false.

```
let viewer = new Potree.Viewer(
	document.getElementById("potree_render_area"),
	{useDefaultRenderLoop: false}
);
```

(see https://github.com/potree/potree/blob/develop/src/viewer/viewer.js#L243)

As a result, viewer.loop won't be executed anymore and you can do whatever it does by yourself.
(see https://github.com/potree/potree/blob/develop/src/viewer/viewer.js#L1747)

Most importantly, call viewer.update and viewer.render as you need it.

**Comment by rfrenz-avio** [comment]
Thank you Markus, this is very helpful.  Is there a way to know the progress of point loading at the top level?  Ideally we would only update/render if there are new points to display or the scene/camera has changed.

**Comment by justingrant** [comment]
> Is there a way to know the progress of point loading at the top level? 

@rfrenz-avio were you able to find this info?
