### ISSUE TITLE
Profile extraction in 2D

### ISSUE THREAD

**Issue by ghost** [potree/potree#569]
Hello,
The profile tool is great because it displays a straightened view of the points along the axis. This type of view is essential for professional applications (eg rockfall trajectories). It would be really nice to be able to export this view in a scaled and straightened vector format. Currently the CSV export lists the points with their 3D coordinates and therefore does not meet this need. It would take a CSV export on both X and Z axes, following the path of the profile.
Is that possible ? What function should be changed to achieve this?
At a minimum, would it be possible to allow 3D DXF extraction of profiles in the same way as distance measurements?
Thank you very much and congratulations for your work.

**Comment by potree** [comment]
Hi,

You can get the straightened profile from the csv by plotting the milage (last column) and z (elevation) attributes. Only thing that's missing would be the depth within the profile.

**Comment by loicroybon** [comment]
Thanks for the tip! Would it be possible to directly generate a DXF profile from Potree based on this information? The existing professional modules propose to define a step (say every 20 centimeters in X for example) and to return the average / high / low altitude (with the choice) of the points in this interval. I will have to be able to create an Excel macro to do that but as a Potree improvement suggestion I think this feature is expected by many people.
Thanks again.
