### ISSUE TITLE
points in pointcloud after conversion don't have same accuracy as in ply file

### ISSUE THREAD

**Issue by shaymaatarek** [potree/potree#597]
I use potreeConverter 1.6 to convert my ply file to view it in potreeViewer. I get the mouse point using this method
`var intersection = Potree.utils.getMousePointCloudIntersection(mouse, viewer.scene.getActiveCamera(), viewer, viewer.scene.pointclouds);
var point=intersection.point.position; `
but this point hasn't same accuracy as point in ply file ?! I don't know why?

**Comment by fgilic** [comment]
Have you defined `--scale` parameter? It defines coordinates precision of the output point cloud. If you don't define it, PotreeConverter determines the precision of the output point cloud based on the size of the input point cloud. So, the precision of input and output point clouds don't have to be the same. 
If you have input point cloud with coordinates defined in meters with centimeter-level precision and want to be sure that the output cloud has the same precision then you need to use `--scale 0.01`.

**Comment by shaymaatarek** [comment]
thanks  @fgilic , @potree the issue has been solved by change scale in potree conversion  while i need .000001 as scale .
