### ISSUE TITLE
Fix elevation slider range clamping bug

### ISSUE THREAD

**Issue by rjpals** [potree/potree#606]
Initially reported here: hobu/usgs-lidar#2
Using elevation range slider causes bounds to default to 0-1000, regardless of the actual range of the data.

**Comment by sunapi386** [comment]
I just saw the same issue, was going to file a ticket as well. 

![out](https://user-images.githubusercontent.com/1029022/52456200-8ace0100-2b08-11e9-91f8-991d231a7c35.gif)
