### ISSUE TITLE
EPT Support and different versions of 1.6

### ISSUE THREAD

**Issue by TaylorDale** [potree/potree#615]
If you convert a LAS file with PotreeConverter and get it to generate the page for you, the resultant Potree JS library has support for loading EPT-based data. Potree.Version() returns 1.6. 

However, release 1.6 from this repo (Which returns 1.6 with Potree.Version()) does not have the ability to have a ept.json url as input. I can't find any documentation on this, is this intended?

**Comment by TaylorDale** [comment]
Any updates on this?

**Comment by chrislcs** [comment]
The 1.6 release does not contain the ept loader yet. It will probably be part of the next release. For now you will have to build potree yourself to get potree with the ept loader. Clone the repository and follow [the build steps in the README](https://github.com/potree/potree#build). The potree library will be generated in the `build/` folder.

**Comment by TaylorDale** [comment]
Cheers for that.

**Comment by thomaspingel** [comment]
Bumping an old thread, but does it look like 1.7 is going to have support for EPT loading?
