### ISSUE TITLE
Have tiles off by default in minimap

### ISSUE THREAD

**Issue by ianh88** [potree/potree#640]
Hi,

Sorry couldn't find an answer to this. Using much larger datasets I am seeing performance issues by having the tiles on by default in the minimap. Everything runs fine once they're off. 

Wondering if anyone knows how to ensure they're off by default. Is this somewhere in the potree.js file?

Thanks.

**Comment by ianh88** [comment]
Figured it out.

Anyone else interested I added a line into the potree.js

`// TOGGLE TILES
			let btToggleTiles = document.createElement('button');
			btToggleTiles.innerHTML = 'T';
                        **_this.showSources(false);**
			btToggleTiles.addEventListener('click', () => {
				let visible = sourcesLayer.getVisible();
				_this.showSources(!visible);
			}, false);
			btToggleTiles.style.float = 'left';
			btToggleTiles.title = 'show / hide tiles';
`

**Comment by HolgerHerrmannGE** [comment]
This did it for me:

``` javascript
viewer.mapView.showSources(false);
```
