### ISSUE TITLE
PotreeDesktop Version Not working on Windows 10

### ISSUE THREAD

**Issue by nizamuddinsyed** [potree/potree#645]
Hey everyone,

I am not able to use PotreeDesktop verison on my Windows 10 machine, Could some one look into my issue and help me out please. (I can run Potree web verison without any difficulty)

Well, I did follow the below steps to download PotreeDesktop version (referring to this website https://github.com/potree/PotreeDesktop)

**Step 1:** Downloading and Installing Node.js
**Step 2:** Downloading the git repository
>git clone https://github.com/potree/PotreeDesktop.git  C:/PotreeDesktop

**Step 3:** Move into the PotreeDesktop folder and install dependencies
>cd C:/PotreeDesktop
>npm install

**Step 4:** Start the application

![PotreeDesktop_cmd](https://user-images.githubusercontent.com/44087478/56926786-d0301800-6ad2-11e9-9d9c-b24f16a66a4a.PNG)

**After starting I am getting the below screen with error details**

![Potree_Desktop_error](https://user-images.githubusercontent.com/44087478/56926764-c60e1980-6ad2-11e9-818e-6f5f628c28bf.PNG)

**Please find below System details:**

**OS : Windows 10 64-bit
Graphics Card : AMD Radeon R5 M330**
![amd_radeon_graphicsCard](https://user-images.githubusercontent.com/44087478/56927042-695f2e80-6ad3-11e9-9897-26de0f50b31e.PNG)

**Browser : Google Chrome (Version : 74.0.3729.108 (Official Build) (64-bit))**

**Comment by aleskou** [comment]
Hello,

Have you tried opening it from Firefox ?

I had the same problem latelyand it was all right. It wouldnt work on chrome if not hosted on a web server (apache).
I dont precisely know why...

**Comment by syed05** [comment]
Dear Leskou, 

I really appreciate for your time and effort.
Well, i can use web based potree(both chrome and firefox).  But while spinning up potree desktop application iam encountering the above mentioned error. 

Thanks in advance.

Regards, 
Nizam Uddin Syed

**Comment by HeadLessHUN** [comment]
Did you just copy over the html file from the web server directory? If yes then don't do it, because the desktop version it is different just copy the pointclouds and the pointcloud loading part from the html file. It is working on windows 10 and i think you dont need node, because it has a built in electron.exe.
