### ISSUE TITLE
Automated testing (and builds)

### ISSUE THREAD

**Issue by dkastl** [potree/potree#65]
It could be interesting to do automated testing for "develop" branch and then run builds with Travis CI: https://travis-ci.org/

**Comment by martinheidegger** [comment]
Travis has been setup with #367 though for the moment it _only_ does linting _(no automated tests yet)_? Since this issue mixes various tasks _(build, deployment, tests, ci)_ I will close this issue and look split it up in follow up issues for tests & deployment.

**Comment by alesage** [comment]
@martinheidegger was an issue created for "more tests"?  I'd like to pitch in some mocha-style tests.
