### ISSUE TITLE
individual - distance measure tool

### ISSUE THREAD

**Issue by Raquel0** [potree/potree#654]
Hi all!

I wonder if anybody could help me with this.

I'm traying to build on v1.6 a menu that looks like the old simple one with few tools, but i cannot make it work. For example: when i build onclick function for distance measure icon, i use

`viewer.measuringTool.startInsertion({showDistances: true, showArea: false, closed: false})`

and nothing happens but error in console.I've also tried other unsaccessful ways to solve this.

Any kindly helpufll idea? 😄

**Comment by Raquel0** [comment]
This is what i get:
> scriptTest.js:15 Uncaught TypeError: Cannot read property 'startInsertion' of undefined

**Comment by Raquel0** [comment]
Got it 😄

**Comment by coupster74** [comment]
Raquel0.. not the best form to just say "Got it".. what did you do? I'm having the same issue
