### ISSUE TITLE
Shader couldn't compile error with Chrome 75

### ISSUE THREAD

**Issue by DylanWard14** [potree/potree#657]
Hi,

I have been using Potree with the latest versions of Google Chrome and Firefox for the past few months. However the most recent update of Chrome (75) seems to not work with Potree, is anybody able to help with this? Potree still appears to be working with Firefox. The issue is that pointclouds are not loading (The background, sidebar and annotations all appear but the pointcloud does not). I have tried rebuilding Potree from the latest source but the issue still occured. The errors are below: 

`THREE.WebGLShader: Shader couldn't compile.`

`THREE.WebGLProgram: shader error:  0 gl.VALIDATE_STATUS false gl.getProgramInfoLog invalid shaders` 

The errors indicate a problem with Three.js, however, Three.js scenes seem to work fine. I have tried to use different versions of Three.js with no luck. The examples on the potree webpage also seem to work correctly, however, the Potree version the website uses seems to be behind the current version.

I am running Ubuntu 18.04 but am also experiencing the issue on MacOS, I don't have a windows machine to test on.

**Comment by damian66** [comment]
I experience the same issue on Chrome 75 and MacOS 10.14.5 - it was working well on previous versions.
This happens only on the develop branch.

**Comment by m-schuetz** [comment]
This is a bit tough to debug for me since everything works fine on chrome 75 on windows. If anyone with that issue could find the problem, it'd be highly appreciated.

**Comment by m-schuetz** [comment]
Someone reported chrome 75.0.3770.80 may have been the problem and chrome 75.0.3770.90 seems to work again.

**Comment by damian66** [comment]
@m-schuetz sure, I updated chrome to the newest version (75.0.3770.90) and it works. Thanks!

**Comment by DylanWard14** [comment]
Thanks for the responses! I wont be able to check if chrome 75.0.3770.90 fixes the problem on Ubuntu until I am back at work on Monday. I will keep you posted.

**Comment by DylanWard14** [comment]
Hey guys, Thanks for all your help. Chrome 75.0.3770.90 fixes the issue on Ubuntu also.
