### ISSUE TITLE
Three.js & Potree: 3D Model Flickering

### ISSUE THREAD

**Issue by benjdel** [potree/potree#663]
Hey everyone,

As part of a project, i am trying to add some informations to a point clouds.

So basicaly to understand the context of my problem, the purpose of my project is that a user :
- 1. When using one of the measurements tools, he can add some description to the object measure. Then send it and register it into a posgresql database in the geojson format.
- 2. By using a form, he can next choose which object he want to make appear on the potree scene based on the type of geometry or the description that he add before.

I manage to create some three.js object based on my geojson file (measured by the user and register in the postgresql database). But my problem is that when i am moving trough the scene, the pointcloud is stable but the objects created are like shaking for a few seconds (As you can see on the video).
![20190627_161027](https://user-images.githubusercontent.com/49481908/60273958-82c7ff80-98f7-11e9-86af-98ff8c28e1a5.gif)

The function, to create three.js object(point, line and polygon only).
[MydrawThreeGeoJSON.zip](https://github.com/potree/potree/files/3335186/MydrawThreeGeoJSON.zip)

If anyone have a clue why, it would be very usefull.

Thanks :)

**Comment by m-schuetz** [comment]
Hi, 

Are you working with large coordinates? Did you create the 3D Vertex Buffer of the Polygon with those large coordinates? If so, then that's the problem since the vertex buffers have float precision. 

To fix this, compute the minimum value of all coordinates. Use this minimum value as the position of the THREE.Object3D scene node, and subtract the min value from the coordinate before you store the coordinate in the vertex buffer.

**Comment by benjdel** [comment]
Thank you for your answer !

I am using those coordinates to create the 3D vertex from  geojson files, like this one for example : 
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [
                            494403.19999980927,
                            5419840,
                            309.28900051116943
                        ],
                        [
                            494354.7989997864,
                            5419884,
                            305.60900020599365
                        ],
                        [
                            494408.39999961853,
                            5419913,
                            299.51900005340576
                        ],
                        [
                            494403.19999980927,
                            5419840,
                            309.28900051116943
                        ]
                    ]
                ]
            },
            "properties": {
                "name": "Area",
                "type": "polygone",
                "description": "polygone"
            }
        },

So if i understand correctly : 

1. Compute the minimum value of ALL coordinates : 
For the polygon in my example,
- I have to find the OVERALL minimum value of my coordinates ? -->  299.51900005340576
- Or i have to find the minimum values of all  X, Y and Z coordinates ?--> (494354.7989997864, 5419840, 299.51900005340576)

2. Use this minimum value as the position of the THREE.Object3D scene node
When i create a object 3D with "new THREE.Object3D", i fix the position with "Object3D.position.set(x,y,z)"? So i need the minimum value in X, Y and Z?

3. Subtract the min value from all vertex coordinates before you store the coordinate in the vertex buffer

**Comment by benjdel** [comment]
Works perfectly !! Thanks a lot :).

**Comment by rsouthon** [comment]
@benjdel could a similar solution fix the problem with large coordinates causing a jitter in the shaders for clipping boxes? See [https://github.com/potree/potree/issues/733](url)
