### ISSUE TITLE
Building potree project

### ISSUE THREAD

**Issue by Ingsayyad** [potree/potree#671]
I am trying to build potree-project.
I have followed the following instructions:
Make sure you have node.js installed

Install all dependencies, as specified in package.json, then, install the gulp build tool:

    cd <potree_directory>
    npm install --save
    npm install -g gulp
    npm install -g rollup

But getting error...on gulp watch..
Any idea? It is + gulp@4.0.2, I tried also gulp@3.8.8, gulp@3.9.xx as well.

        C:\Users\SS\Downloads\potree>gulp watch
    assert.js:339
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Task function must be specified
        at Gulp.set [as _setTask] (C:\Users\SS\Downloads\potree\node_modules\und
    ertaker\lib\set-task.js:10:3)
        at Gulp.task (C:\Users\SS\Downloads\potree\node_modules\undertaker\lib\t
    ask.js:13:8)
        at Object.<anonymous> (C:\Users\SS\Downloads\potree\gulpfile.js:85:6)
        at Module._compile (internal/modules/cjs/loader.js:776:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:690:17)
        at require (internal/modules/cjs/helpers.js:25:18)

**Comment by rjpals** [comment]
Did you make sure that gulp was version <4.0 both globally and local to the project? That was the problem I ran into.

What is the output of these commands?
`npm list --depth=0 | grep gulp`
`npm list -g --depth=0 | grep gulp`

**Comment by Ingsayyad** [comment]
H:\Potree>npm install --save
added 356 packages from 215 contributors and audited 1344 packages in 17.166s
found 28 vulnerabilities (4 low, 2 moderate, 22 high)
  run `npm audit fix` to fix them, or `npm audit` for details

H:\Potree>npm audit fix
+ gulp-connect@5.7.0
added 10 packages from 9 contributors, removed 25 packages and updated 36 packag
es in 5.557s
fixed 21 of 28 vulnerabilities in 1344 scanned packages
  1 package update for 7 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm aud
it` for steps to fix these manually)

H:\Potree>
H:\Potree>npm audit fix --force
npm WARN using --force I sure hope you know what you are doing.

> fsevents@1.2.9 install H:\Potree\node_modules\fsevents
> node install

+ gulp@4.0.2
added 212 packages from 107 contributors, removed 46 packages, updated 29 packag
es and moved 4 packages in 23.948s
fixed 7 of 7 vulnerabilities in 1341 scanned packages
  1 package update for 7 vulns involved breaking changes
  (installed due to `--force` option)

H:\Potree>npm install -g gulp@3.8.8
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, follo
wing the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for comp
atibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compa
tibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and
 will break at some point. Do not use it, and update to graceful-fs@4.x.
C:\Users\sayyad\AppData\Roaming\npm\gulp -> C:\Users\sayyad\AppData\Roaming\npm\
node_modules\gulp\bin\gulp.js
+ gulp@3.8.8
updated 1 package in 3.371s

H:\Potree>npm install  gulp@3.8.8
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for comp
atibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compa
tibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and
 will break at some point. Do not use it, and update to graceful-fs@4.x.
+ gulp@3.8.8
added 33 packages from 31 contributors, removed 281 packages, updated 22 package
s, moved 3 packages and audited 370 packages in 23.13s
found 13 vulnerabilities (2 low, 2 moderate, 9 high)
  run `npm audit fix` to fix them, or `npm audit` for details

H:\Potree>npm install -g rollup
C:\Users\sayyad\AppData\Roaming\npm\rollup -> C:\Users\sayyad\AppData\Roaming\np
m\node_modules\rollup\bin\rollup
+ rollup@1.17.0
updated 1 package in 0.847s

H:\Potree>npm list --depth=0 | grep gulp
Der Befehl "grep" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
