### ISSUE TITLE
Wrong sidebar

### ISSUE THREAD

**Issue by Raquel0** [potree/potree#701]
HI!

I've built potree to check the new features but i noticed that some of the html files in examples have strange looking sidebar. But not all of them. Does this happen to someone else?
Notice that i didn't change any file, just navigated through example files. I tried this using Windows 10, Chrome and Firefox; Ubuntu, Chrome and Firefox as well.
![image](https://user-images.githubusercontent.com/40294955/64676686-62c7c700-d476-11e9-92ef-3589905b0895.png)

Thx!

**Comment by m-schuetz** [comment]
I've recently changed the sidebar to fix an issue in Oculus Quest Browser. Maybe some changes weren't properly applied to all html files. Can you tell me one where this issue occurs?

**Comment by Raquel0** [comment]
Sure!
From examples folder

Strange sidebar:
- annotation_hierarchy.html
- ca13.html
- cesium_ca13.html
- ept.html
- features_ca13.html
- light_ca13.html
- lion_las.html
- lion_laz.html

No pointcloud shown:
- lasmap.html
- ept_zstandard.html
- ept_binary.html
- entwine_greyhound.html
- arena4d.html

Meshes have no texture:
- meshes.html
- features_sorvilier.html
