### ISSUE TITLE
converted point cloud using potreeconverter is not viewed in browser

### ISSUE THREAD

**Issue by Ahmedmouri** [potree/potree#705]
Hello,

I converted a point cloud using PotreeConverter successfully. After havníng the html file; itried opening it , I got only a blank layer without the rendered point cloud.

The Error is:

document.title = "";viewer.setEDLEnabled(false);viewer.setBackground("gradient"); // ["skybox", "gradient", "black", "white"];viewer.setDescription(``); 

![potree](https://user-images.githubusercontent.com/55276569/64864985-981c1280-d638-11e9-9f2c-59608046357f.PNG)

html code:

![code](https://user-images.githubusercontent.com/55276569/64865401-7707f180-d639-11e9-8400-27f6ea53d319.PNG)

Can you help me in solving this matter1

Best regards
Amori

**Comment by m-schuetz** [comment]
Hi Amori,
Internet Explorer doesn't support the necessary Javascript and WebGL functionality. You could try Firefox or Chrome instead.

**Comment by Ahmedmouri** [comment]
Hi,

I tried in Firfox and Chrome, please see the screen; I got the same blank layer:

![potree-screen](https://user-images.githubusercontent.com/55276569/64871496-a6bcf680-d645-11e9-8124-3c70fcc123e2.PNG)


Best regards

**Comment by Raquel0** [comment]
Try to read documentation and opened and closed issues in detail. Your problem seems to be that you are not executing a local server to call the html webpage. I'm sure you can find a solution dedicating some time to read answers given before 😄

**Comment by Ahmedmouri** [comment]
This issue has been solved and closed. The problem is not as you noted as executing a local server, please see the issue 706. Thanks a lot.
