### ISSUE TITLE
View two point clouds in Potree

### ISSUE THREAD

**Issue by Ahmedmouri** [potree/potree#711]
Hi,

I converted two point clouds using PotreeConverter, and for each one I got the related folders and files: like libs folder, html, etc. My question is: how can I view them in potree viewer with the posibility to switch between them. 

Here it is an example I found, but unfortunatley, I could not do it for my data:
http://potree.org/potree/examples/multiple_pointclouds.html 

Thnaks for your supporting

Best reagrds

**Comment by HeadLessHUN** [comment]
Copy the pointcloud to the same pointcloud directory tgen edit the html file. To load the another pointcloud. You just have to create an another instance of the pointcloud loader 
(Potree.loadPointCloud(){} ) function with the other parameters.... You can copy it from the other html if you want.

You should analyze the sources of the examples... You could learn these things very easyly.

**Comment by Ahmedmouri** [comment]
Thanks for the feedback. I tried it and it works!

Regards
