### ISSUE TITLE
.las file loses classifications en route from PotreeConverter to potree

### ISSUE THREAD

**Issue by lightheaded** [potree/potree#752]
I've been struggling to get classification to be displayed in potree and I've ran out of things to try. What I'm trying to do is:

1. convert a classified .las/.laz file using `PotreeConverter <las file> --output-attributes RGB CLASSIFICATION`
2. open potree and toggle classes

What happens is that all points are under the "never classified" filter. What I would expect to happen is that I could toggle the classes I can see via `lasinfo UAV_SnoopySeriesA_A2.laz`:
```
histogram of classification of points:
         3764128  unclassified (1)
         1710013  ground (2)
```

Here's a repository to reproduce the whole thing, including a sample .laz file. NB! it uses Docker for running PotreeConverter. If you have local PotreeConverter, then edit `converter/convert.sh` file to remove all the docker stuff and run PotreeConverter (i.e. just leave lines 3 and 10): https://github.com/lightheaded/potree-playground

**Comment by adamsteer** [comment]
Hi Toomas

Set potreeconverter to output LAS/LAZ

The native bin format doesn't keep classes.

**Comment by lightheaded** [comment]
Indeed, https://github.com/lightheaded/potree-playground/commit/fe4866f7e22caebd8f2b203473f0ba1cf94bd96f fixed it. I'm still unable to process my files as they are left transparent while small .las chunks are visible in the network tab, but this particular issue has been solved by setting output to LAS. Thanks!
