### ISSUE TITLE
hierarchy / folder-structure / order data in scene section

### ISSUE THREAD

**Issue by geoplanteam** [potree/potree#755]
Hi everybody,
how can I structure my data in the scene section of my potree-html?
Right now it looks like this:
![Image of Yaktocat](https://3d.geoplanteam.ch/potree_1-6/potree_scene.jpg)
The pointclouds' order depends on the loading speed, don't they?
How can I freeze the order of the date? And, moreover, can I create my own hierarchy?
Something like this:
```
- Point Clouds <folder>
-- EG 2019-07 <folder>
--- EG pqr 2019-07-25 <layer>
-- EG 2019-10 <folder>
--- EG xyz 2019-10-17 <layer>
--- EG xyz 2019-10-17 <layer>
--- EG stu 2019-10-18 <layer>
-- EG 2019-11 <folder>
--- EG abc 2019-11-26 <layer>
- Machines <folder>
-- Maschine ZE1 <layer>
-- Maschine ZE2 <layer>
-- ...
- Measurements <folder>
- Annotations <folder>
- Other <folder>
-- Camera <layer>
```

**Comment by m-schuetz** [comment]
Yes, the entries are ordered according to load speed. There is currently no mechanism to specify/control this order, unfortunately, other than loading the next point cloud after the previous one is loaded. You could check if jstree has some means of sorting, e.g. something like this: https://old.jstree.com/documentation/sort
