### ISSUE TITLE
Unable to view Cesium maps 

### ISSUE THREAD

**Issue by abhishek202206** [potree/potree#757]
Hi All,
I have been struggling to integrate potree and cesium. I am using the potree examples and had downloaded the git repo. I am using gulp to run the application. When I run the example cesium_retz.html I am able to see the pointclouds but maps isn't loaded. I investigated the html and found that osm tiles as well as bing tiles are getting downloaded but couldn't be stitched on the page. Some screenshots of the problem are shown below:

![Screenshot from 2020-01-15 15-33-01](https://user-images.githubusercontent.com/22738612/72447523-60230880-37ad-11ea-9926-f77705035bc6.png)

![image](https://user-images.githubusercontent.com/22738612/72447553-7204ab80-37ad-11ea-9f42-afa675649627.png)

I have been able to convert georeferenced pointclouds into cesium tiles and render it on cesium viewer but I want to test the same on Potree. Any help would be greatly appreciated

**Comment by Just5D** [comment]
Hi  I meet the same problem，How do you solve it?

**Comment by abhishek202206** [comment]
I was using the wrong repo, so I  downloaded the correct repo from release and then it worked for me. Kindly use the updated repo from the release and then  test.
