### ISSUE TITLE
360 image Example

### ISSUE THREAD

**Issue by Ingsayyad** [potree/potree#764]
The question is quite selfexplaning. Can someone upload/link/hint a working example (html) of 360 images implemented in potree.
I cannot figured out how to import 360 images in cloud.

**Comment by ToHold** [comment]
I've done it on a self-developped fork of Potree
You need to have access to your trajectory file. The one that is produced by mobile-mapping equipment.
In this file there is photo's positions and orientation.

**Comment by Ingsayyad** [comment]
Can you share part of your HTML where you added images?
Also:
The file containing image positions and orientation

**id(image name or number??) PositionX  PositionY PositionZ Orientation (Omega,phi,Kappa ???, unit ??)**

**Comment by ToHold** [comment]
I can't give you my code, it is private.

But I just can tell you that you can do it with THREE.js, you just have to texture a sphere with your 360image.

**Comment by ToHold** [comment]
Here is an old example of what you can do.
https://youtu.be/3uDQbLW0aKc

**Comment by m-schuetz** [comment]
Working example: http://potree.org/potree/examples/oriented_images.html

Camera parameters: http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/epalinges/img_selected/IXM35_190522_nodistortion.xml";

Images: http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/epalinges/img_selected/Calib190522_MN95_NF02_cam.txt";

one of the image files: http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/epalinges/img_selected/47549.jpg

Code to load 360 images:

```
    const cameraParamsPath = "http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/epalinges/img_selected/IXM35_190522_nodistortion.xml";
    const imageParamsPath = "http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/epalinges/img_selected/Calib190522_MN95_NF02_cam.txt";
    
    Potree.OrientedImageLoader.load(cameraParamsPath, imageParamsPath, viewer).then( images => {
    	viewer.scene.addOrientedImages(images);
    });
```

see: https://github.com/potree/potree/blob/develop/examples/oriented_images.html

**Comment by m-schuetz** [comment]
Uh sorry, I confused oriented images with 360 images. For 360 images, a demo is in the making.

**Comment by Ingsayyad** [comment]
Thank you. Have you seen 
https://youtu.be/3uDQbLW0aKc.
The mouse (circle) changes at corners and helps the user to know where is a corner. Do you know or plan to integrate it into Portree.

**Comment by HeadLessHUN** [comment]
> Uh sorry, I confused oriented images with 360 images. For 360 images, a demo is in the making.

if you need anything, just tell me. If you need sorce files with images for example, i can share it with you. And i can give you the scan(laz)/scan position/quaternion if its needed. in any format.

**Comment by m-schuetz** [comment]
Hi, there is a somewhat of a demo here now: https://github.com/potree/potree/commit/b845e49bdabb0a455df56bc792eed0062cf88449#commitcomment-37472780

I also got permission to host a georeferenced demo, I just need to prepare it for upload.

**Comment by HeadLessHUN** [comment]
Hi!

Do you plan to support cubemap panorama as well? because i have mixed panorama images cube and equirectangular as well.. And i have never used georeferenced point cloud, we just export it from cyclone reister 360, without any reference. lat, long, height means x,y,z coords, or there will be missalingnments.

**Comment by CHARLY9090** [comment]
> Ejemplo de trabajo: http://potree.org/potree/examples/oriented_images.html
> 
> Parámetros de la cámara: http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/epalinges/img_selected/IXM35_190522_nodistortion.xml ";
> 
> Imágenes: http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/epalinges/img_selected/Calib190522_MN95_NF02_cam.txt ";
> 
> uno de los archivos de imagen: http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/epalinges/img_selected/47549.jpg
> 
> Código para cargar imágenes 360:
> 
> ```
>     const cameraParamsPath = "http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/epalinges/img_selected/IXM35_190522_nodistortion.xml";
>     const imageParamsPath = "http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/epalinges/img_selected/Calib190522_MN95_NF02_cam.txt";
>     
>     Potree.OrientedImageLoader.load(cameraParamsPath, imageParamsPath, viewer).then( images => {
>     	viewer.scene.addOrientedImages(images);
>     });
> ```
> 
> ver: https://github.com/potree/potree/blob/develop/examples/oriented_images.html


Hi, can you help me on how to calculate the focal length for your example? Thanks for the help and thanks for potree.

**Comment by midnight-dev** [comment]
> I also got permission to host a georeferenced demo, I just need to prepare it for upload. 

@m-schuetz Any update on a georeferenced demo? Would it be compact enough to package in the repo as a local asset?

**Comment by m-schuetz** [comment]
Georeferenced 360 image demo is in dev branch here: https://github.com/potree/potree/blob/develop/examples/360.html

**Comment by govem002** [comment]
I have point cloud data which I want to superimpose on another layer of imagery. Is there functionality within to potree to load and make visible this Imagery Layer?

**Comment by govem002** [comment]
I have point cloud data which I want to superimpose on another layer of imagery. Is there functionality within the Potree Viewer to load and make visible this Imagery Layer?

**Comment by duongduong24** [comment]
> > Ejemplo de trabajo: http://potree.org/potree/examples/oriented_images.html
> > Parámetros de la cámara: http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/epalinges/img_selected/IXM35_190522_nodistortion.xml ";
> > Imágenes: http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/epalinges/img_selected/Calib190522_MN95_NF02_cam.txt ";
> > uno de los archivos de imagen: http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/epalinges/img_selected/47549.jpg
> > Código para cargar imágenes 360:
> > ```
> >     const cameraParamsPath = "http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/epalinges/img_selected/IXM35_190522_nodistortion.xml";
> >     const imageParamsPath = "http://5.9.65.151/mschuetz/potree/resources/pointclouds/helimap/epalinges/img_selected/Calib190522_MN95_NF02_cam.txt";
> >     
> >     Potree.OrientedImageLoader.load(cameraParamsPath, imageParamsPath, viewer).then( images => {
> >     	viewer.scene.addOrientedImages(images);
> >     });
> > ```
> > 
> > 
> > ver: https://github.com/potree/potree/blob/develop/examples/oriented_images.html
> 
> Hi, can you help me on how to calculate the focal length for your example? Thanks for the help and thanks for potree.

Hi. Have you known how to calculate the focal lenth yet? I have the same problem

**Comment by VivekSri006** [comment]
Can you share  file structure that containing image positions and orientation

id(image name or number??) PositionX PositionY PositionZ Orientation (Omega,phi,Kappa ???, unit ??)

**Comment by MattiasTancred** [comment]
> > Uh sorry, I confused oriented images with 360 images. For 360 images, a demo is in the making.
> 
> if you need anything, just tell me. If you need sorce files with images for example, i can share it with you. And i can give you the scan(laz)/scan position/quaternion if its needed. in any format.

[HeadLessHUN](https://github.com/HeadLessHUN) Do you have the posibility to share a working example? image(s) / pointcloud and coordintes.txt file that would be very helpful. Version of Potree/potreeconverter and if any changes have been made to the code.
