### ISSUE TITLE
Point Cloud Interactions in VR

### ISSUE THREAD

**Issue by hudsonchase** [potree/potree#765]
Has anyone had any success with Potree VR interaction? Or would know a direction in which to head? 

Essentially I'm wanting to create a UI for selection and changing of the attributes of the point cloud (i.e. classification), along with other natural VR modalities (navigation, teleportation, intuitive controls). So that selection and manipulation can be accomplished in VR and ultimately exported out as a new point cloud (.las, json, etc.). 

Much love to the open source community 👍

**Comment by quanhongtran** [comment]
I am trying to do the same thing but via the web and not VR....... not sure how we can manage converted las to potree files.. i think that is the main problem

**Comment by m-schuetz** [comment]
Closing this for now since I don't have resources to work on VR development in Potree right now.
