### ISSUE TITLE
Updating point cloud?

### ISSUE THREAD

**Issue by vuoriov4** [potree/potree#766]
Hey, I'm new to potree and trying to figure out what is the best way to update point cloud data.
I want to add a few additional points to my old point cloud in the most convenient (fastest) way without reloading the page.

A naive way would be to generate an entirely new octree with PotreeConverter, delete the outdated point cloud and replace it with the new one. (but how?)

 I'm willing to modify the source code to make it possible.

**Comment by quanhongtran** [comment]
I am also having the same issues, would love to be able to update / merge / edit / or even run PDAL functions on the converted point cloud. At the moment, I am converting -> potree, run command on laz file then re-update with --overwrite command. This is quite a slow process! 

Let me know how you guys go1

**Comment by smcavoy12** [comment]
If you're just adding points you can isolate the new additions and then do **--incremental** instead of **--overwrite**.
https://github.com/potree/PotreeConverter/issues/138

**Comment by m-schuetz** [comment]
Atm, the cleanest way is to reconvert a new point cloud, then reload the page. There is the incremental option mentioned by @smcavoy12, but it wasn't maintained/tested in a while, and there is no proper way to update without reloading.
