### ISSUE TITLE
Will not load pointcloud, cannot read byteSize error

### ISSUE THREAD

**Issue by CarlBromell** [potree/potree#770]
Hi guys, 

I´m fairly new to this, but i´ll try to make sense of it. 
I´m having issues with reading my pointcloud, i get this message: 

Uncaught TypeError: Cannot read property 'byteSize' of undefined
    at new Potree.PointAttributes (potree.js:4211)
    at XMLHttpRequest.xhr.onreadystatechange (potree.js:3978)

![byteSize Error potree](https://user-images.githubusercontent.com/61231357/74826873-9b64aa00-530c-11ea-9369-ce7218ec35b4.JPG)

I´ve seen similar issues on the forum but not quite, hope you can help me out!
I´m on Win10, Google Crome, Potree Version 1.6

Cheers

**Comment by m-schuetz** [comment]
Hi, are you using the PotreeConverter 1.7 pre-release with the Potree 1.6 release? If so, you can either fall back to the PotreeConverter 1.6 release and use it with Potree 1.6, or you can use the potree develop branch rather than the Potree 1.6 release.

**Comment by CarlBromell** [comment]
Yes, that was my problem, it´s working fine now!

Thanks!

**Comment by guylevin** [comment]
Didn't solve the problem for  me, tried many convertors versions
