### ISSUE TITLE
HIDDDEN TOOLS

### ISSUE THREAD

**Issue by mihapajnic** [potree/potree#772]
Hello,

@m-schuetz 

i have one question about the tools in the online point cloud viewer. The POTREE.jpg image shows the ordinal row you have generated on your web site, while the MY.jpg image shows my toolbar, which I did with a 1.7 version of the potreeconverter. I wonder what I need to do to have the same tools as you?

![MY](https://user-images.githubusercontent.com/60388504/75115718-9df33680-5661-11ea-9686-666e829f7a82.JPG)

![POTREE](https://user-images.githubusercontent.com/60388504/75115720-a0ee2700-5661-11ea-9828-3d4fefc4cfe8.JPG)

Thank you very much for the answer

**Comment by m-schuetz** [comment]
The tools are in the develop branch of potree. A 1.7 release will follow soon.
