### ISSUE TITLE
Zoom in while start draging - Earth Controls

### ISSUE THREAD

**Issue by pnowakaero** [potree/potree#775]
Hello.
I have an issue with Earth controls enabled. When I start dragging with left mouse button camera automatically zooms in by a small factor. This issue can be reproduced in basic potree demo http://potree.org/potree/examples/viewer.html
Any ideas?

Thanks for any reply and sorry for my english.

**Comment by m-schuetz** [comment]
Fixed: https://github.com/potree/potree/commit/d8abe2721f1bc794d46010fd14990941f22c47ef
