### ISSUE TITLE
blank page in browser - ionos install

### ISSUE THREAD

**Issue by sebk60** [potree/potree#778]
Hello,

sorry for english but i preferred to use google translator.

I unzipped the zip on my 1 & 1 server, I am trying to view the example "lio_las.html" but I have a blank page, can someone help me to run potree?

Thank you

Seb

**Comment by Yongho-VIRNECT** [comment]
hello,
potree example need server. 

do you used chrome? 
i recommend this chrome app

https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb/reviews

If you run a chrome app, choose folder 
![image](https://user-images.githubusercontent.com/58449745/76063690-93bf2980-5fcb-11ea-9f4c-f0ede3dbca69.png)

![image](https://user-images.githubusercontent.com/58449745/76063913-f9abb100-5fcb-11ea-9b52-a9289737f1ec.png)

select example > lion_las.html
![image](https://user-images.githubusercontent.com/58449745/76063955-11833500-5fcc-11ea-9ce3-f5db15089aa6.png)

**Comment by m-schuetz** [comment]
Are there any errors in the developer tools? (press F12)
