### ISSUE TITLE
Hide sidebar on start

### ISSUE THREAD

**Issue by safibet** [potree/potree#779]
Hi,

It is possible to setup hide state to the sidebar by default?

Thanks

**Comment by HeadLessHUN** [comment]
just edit the generated html file.

you just have to comment out the toggle line... like this


`//viewer.toggleSidebar();`

**Comment by safibet** [comment]
Thanks.

Where is it?

I tried to find it without success.


`<body>
	<script src="libs/jquery/jquery-3.1.1.min.js"></script>
	<script src="libs/spectrum/spectrum.js"></script>
	<script src="libs/perfect-scrollbar/js/perfect-scrollbar.jquery.js"></script>
	<script src="libs/jquery-ui/jquery-ui.min.js"></script>
	<script src="libs/three.js/build/three.min.js"></script>
	<script src="libs/other/BinaryHeap.js"></script>
	<script src="libs/tween/tween.min.js"></script>
	<script src="libs/d3/d3.js"></script>
	<script src="libs/proj4/proj4.js"></script>
	<script src="libs/openlayers3/ol.js"></script>
	<script src="libs/i18next/i18next.js"></script>
	<script src="libs/jstree/jstree.js"></script>
	<script src="libs/potree/potree.js"></script>
	<script src="libs/plasio/js/laslaz.js"></script>
	
	
		document.title = "";
		viewer.setEDLEnabled(false);
		viewer.setBackground("gradient"); // ["skybox", "gradient", "black", "white"];
		viewer.setDescription(``);
	
	<div class="potree_container" style="position: absolute; width: 100%; height: 100%; left: 0px; top: 0px; ">
		<div id="potree_render_area"></div>
		<div id="potree_sidebar_container"> </div>
	</div>
	
	<script>
	
		window.viewer = new Potree.Viewer(document.getElementById("potree_render_area"));
		
		viewer.setEDLEnabled(true);
		viewer.setFOV(60);
		viewer.setPointBudget(4000000);
		document.title = "";
		viewer.setEDLEnabled(false);
		viewer.setBackground("gradient"); // ["skybox", "gradient", "black", "white"];
		viewer.setDescription(``);
		viewer.loadSettingsFromURL();
		
		viewer.loadGUI(() => {
			viewer.setLanguage('en');
			$("#menu_appearance").next().show();
			$("#menu_tools").next().show();
			$("#menu_scene").next().show();
			viewer.toggleSidebar();
		});
		
		Potree.loadPointCloud("pointclouds/taravella/cloud.js", "taravella", e => {
			let pointcloud = e.pointcloud;
			let material = pointcloud.material;
			viewer.scene.addPointCloud(pointcloud);
			material.pointColorType = Potree.PointColorType.RGB; // any Potree.PointColorType.XXXX 
			material.size = 1;
			material.pointSizeType = Potree.PointSizeType.ADAPTIVE;
			material.shape = Potree.PointShape.SQUARE;
			viewer.fitToScreen();
		});
		
	</script>
	
	
  </body>
</html>`

**Comment by m-schuetz** [comment]
It's right there in the code you posted...
