### ISSUE TITLE
overview map

### ISSUE THREAD

**Issue by HeadLessHUN** [potree/potree#780]
Hello @m-schuetz!

i'd like to create a mini map like you created based on images, but i'd like to create it based on an "overview" cloud (not so dense), i'll need to create a clipping box, because of multiple levels of building. I have scan location spheres in my project and i'll need to link  those with the original cloud. it's like a sitemap, and if click on the scan you can view it in 360 image and simple and dense pointcloud as well in the main screen. like walking in cod you can see where you are where you see and click targets...

So i'll need a different viewer or at least a scene with a different render area somewhere maybe in the top right corner.

i know that the easier would be that, to just create an iframe and load a different site completelly, but i don't want to go that route, because later it will need much more work, every time i'd create a viewer,  i'd need to create to different html files... 

Do you think that two different viewer for 1 html is possible or i should go the other way with different html and iframe...

**Comment by HeadLessHUN** [comment]
i went for a hacky solution i'm not proud of it, but i load a secondary potree with iframe and then after load i connect them together. i had to control the fps because it was a litle bit laggy on mid gpus.  i had to write a different control which is a helicopter with mouse control. i based it on earth control and removed the rotation control. because i wanted to get only a sitemap from top view.

**Comment by Matthieu-Fontaine** [comment]
Hi, I'll try to do the same thing as you would have any advice? Ah and I will add in the minimap the images360 so that at the click on it we arrive in the image of the main potree.
