### ISSUE TITLE
Potree not shown in web host

### ISSUE THREAD

**Issue by ivansipiran** [potree/potree#781]
Hello,

I succesfully configured Potree in my local web server to show my point cloud using the setup guidelines.

![Captura de pantalla de 2020-03-12 21-02-03](https://user-images.githubusercontent.com/13351925/76582792-45b39580-64a5-11ea-9fcb-1f04f8e34d08.png)

However, when I upload the page (included pointclouds and libs) to a web host, I could not see the visualization. 

![Captura de pantalla de 2020-03-12 21-07-59](https://user-images.githubusercontent.com/13351925/76582898-a773ff80-64a5-11ea-8583-1e5adcc0ff2c.png)

Maybe I am missing something, but is there some configuration do I need to do to deploy Potree in a web host?

Thanks in advance.

**Comment by HeadLessHUN** [comment]
hello, show us a console log. i think there is a path issue... the loader can't find the uploaded cloud.js file

**Comment by ivansipiran** [comment]
Hi, thanks for the response. In Chrome, the console showed the message: 

Uncaught RangeError: byte length of Float32Array should be a multiple of 4
   at new Float32Array (<anonymous>)
   at onmessage (BinaryDecoderWorker.js:62)

After googleing this error and lookking Issue #68 , it seems FileZilla uploaded the files in ascii mode. I changed the transfer to binary mode, and now it is working.

Thanks a lot.
