### ISSUE TITLE
Get local min/max of region

### ISSUE THREAD

**Issue by cammei** [potree/potree#782]
I'm currently loading a point-cloud and clipping it with a Volume Clip (as shown below). From there, I'll use it to control my elevation gradient scheme. I've got the second part working, but I'm stumped at how I would go about getting the min/max x,y, and z co-ordinates enclosed in a clipped volume. 

I've tried treating it as both a volume and as a very fat height profile to no avail. (In particular, the suggested code in the documentation doesn't seem to work:

```javascript
var maxOctreeDepth = 1;
var segments = pointcloud.getPointsInProfile(profileTool.profiles[0], maxOctreeDepth);


```
Is there a way that I can find the min/max (x,y,z) coordinates of points enclosed in that volume?

![co-ordinates](https://user-images.githubusercontent.com/56857035/76592266-cc13ba00-652d-11ea-83d4-9bf84fe7b222.PNG)

**Comment by m-schuetz** [comment]
getPointsInProfile is for elevation profiles, not for volumes. There is a pointcloud.getPointsInBox function, but it's not used anywhere and chances are that it doesn't work anymore.

**Comment by Shumzi** [comment]
Any update with this? 
Could you take advantage of how ClipTask.SHOW_INSIDE works? looks like it very quickly changes visibility of the region, should be simple to augment it to return min/max.
Only can't find where the visibility changes in the code...
