### ISSUE TITLE
Interactive pointcloude

### ISSUE THREAD

**Issue by fucik2013** [potree/potree#786]
Hi to everybody. I have got a question related to this sample https://jsfiddle.net/kep3ofhz/1/ and Potree. As I am a land surveyor I use potree for presentation of our measured data I mean point cloud but I would like to have part of this pointcloud to be interactive in a same way like in the mentioned sample and because I am not a programmer its hard to say if its possible or not or how to do that. Havent you got any experiences with that?

**Comment by fucik2013** [comment]
Or maybe there is an easier way how to sort this problem. All I need is to be able in potree rotate model around central line 
![Heliport](https://user-images.githubusercontent.com/56881555/78117810-66b53980-7406-11ea-9185-645688e5374a.JPG)

**Comment by m-schuetz** [comment]
Unfortunately, that is not possible. Potree currently only supports visualization and measurement, but not modifications.
