### ISSUE TITLE
A full data load is possible?

### ISSUE THREAD

**Issue by gmiguelr87** [potree/potree#792]
Hello!

Potree's project is fascinating! Congratulations! The more I use it and work on it, the more I like it!

I have a doubt, I know it goes a bit against the philosophy of the viewer itself "Do not load full data: Low-resolution data when far and gradually higher resolution data when closer", but I'm looking for a utility. Is there any way to force a full load of the data?

Thank you very much!

**Comment by smcavoy12** [comment]
Hi, in the html page change 

viewer.setPointBudget(1*1000*1000);

to the number of points in your full set. if 100 million set to

viewer.setPointBudget(100*1000*1000);

Just a note, with a Nvidia 1080ti I usually start to lag pretty badly after 80 million points. 

I have crashed windows entirely with 10 million points on a crummy old PC with onboard graphics.

**Comment by m-schuetz** [comment]
What @smcavoy12 suggests is currently the only way of doing it.
