### ISSUE TITLE
Error in getNorthVec without projection (utils.js)

### ISSUE THREAD

**Issue by ilisalis** [potree/potree#796]
Without projection information, the vector should simply be the direction multiplied by the distance.

In place of : `const vec = p1.clone().add(new THREE.Vector3(0, 1, 0).multiplyScalar(distance));`
It should be : `const vec = new THREE.Vector3(0, 1, 0).multiplyScalar(distance);`

Original code: 
![Capture d’écran (6)](https://user-images.githubusercontent.com/54713132/80053505-6566c080-851d-11ea-9c78-ea12f2c2acfc.png)

Correction
![Capture d’écran (5)](https://user-images.githubusercontent.com/54713132/80053500-64ce2a00-851d-11ea-904e-5dd5eb5e7db1.png)

**Comment by m-schuetz** [comment]
Thanks for the fix! Applied it in develop now.
