### ISSUE TITLE
Crash in Examples: Pointclouds with Fixed Point Sizing and LOD attribute

### ISSUE THREAD

**Issue by mokargas** [potree/potree#798]
Currently, all Potree examples with point-clouds crash the browser (Chrome or Firefox latest) when:

- A point-cloud is selected. e.g sigeom.sa in the [Annotations example](http://potree.org/potree/examples/annotations.html)
- Under properties, the point sizing is set to Fixed
- Under Attribute, Level of Detail is selected   

The problem seems to lie in the shader code (see screenshot)
![image](https://user-images.githubusercontent.com/236984/80454384-4c22a180-896d-11ea-934d-5f86c89099f6.png)
![image](https://user-images.githubusercontent.com/236984/80454481-74aa9b80-896d-11ea-9d2f-85bafc1642e8.png)

**Comment by midnight-dev** [comment]
@m-schuetz  Sorry about the duplicate references. Built two other branches from the rebased commit. The PR that fixes this uses 54edcbcac0bf6af790711e69a1d6d575ab2589da whose parent is the most recent commit in this repo.

**Comment by m-schuetz** [comment]
Merged fix by @midnight-dev into dev branch.
