### ISSUE TITLE
Measuring Leaves Phantom Angle

### ISSUE THREAD

**Issue by easilyBaffled** [potree/potree#803]
[Measure's `removeMarker`](https://github.com/potree/potree/blob/72748db38fd46a98c4d0800a70b1fe2570365152/src/utils/Measure.js#L464) removes the point, dot, edge, and measurement label. But it neglects to remove the `angleLabel`, if `showAngles: true` leaving a phantom label in the UI.

I have found adding 
```js
this.remove(this.angleLabels[index]);
this.angleLabels.splice(index, 1);
```
to `removeMarker` resolves the issue. As of yet I have not found any negative ramifications. 
I can open a PR with the change. 

#### Two Points
![angle-remains-two-points](https://user-images.githubusercontent.com/4247680/81424446-f8117d00-9123-11ea-99aa-31c7b9f9a601.gif)

#### Multiple Points
![angle-remains-many-points](https://user-images.githubusercontent.com/4247680/81424453-fb0c6d80-9123-11ea-9980-3ef3e35eb804.gif)

**Comment by m-schuetz** [comment]
Thanks, for the info. If you can provide a PR towards the develop branch within the next days, I'll be happy to merge it. Otherwise I'll just integrate your suggested fix. Planning to release 1.7 by the end of the week.

**Comment by Yongho-VIRNECT** [comment]
> Thanks, for the info. If you can provide a PR towards the develop branch within the next days, I'll be happy to merge it. Otherwise I'll just integrate your suggested fix. Planning to release 1.7 by the end of the week.

Potree 1.7 support  latest three.js ?

**Comment by midnight-dev** [comment]
> Potree 1.7 support latest three.js ?

I can't speak for @m-schuetz but there's always going to be a cat and mouse game of trying to get the latest version of something. There's already been a huge uplift from 1.6 using r85 and the develop branch using r109. I would like to get something between r110 - 119 for my own satisfaction, but the bleeding edge isn't exactly necessary. There's going to have to be some thorough testing of many examples across different browsers to ensure a major graphics engine update won't bork anything.

What's the latest version that introduces the feature or fix that you need?

@easilyBaffled Would you be able to submit that PR before the weekend?

**Comment by m-schuetz** [comment]
fixed, thanks @easilyBaffled !

**Comment by vishnuaheadrace** [comment]
how to rotate 180 degree angle potree map not below the ground level.
