### ISSUE TITLE
Export Volume in potree 1.6

### ISSUE THREAD

**Issue by LCGsystems** [potree/potree#804]
It is still unclear how we can implement the codes to export the points that are included in a volume box. There are many sources giving examples such as 
https://github.com/potree/potree/issues/549, or
https://github.com/potree/potree/issues/457, or even in
https://gitter.im/potree/Lobby?at=5ca7a5ae8148e555b25548ce at the date of the 4th of March 2020 but none of them offers clear instructions on where to put the code and how to call the download volume function as shown in the youtube video: "https://www.youtube.com/watch?v=hvrE5RL5nrQ". 
Can anyone describe precisely how to create this function?

**Comment by m-schuetz** [comment]
The video was done with https://github.com/potree/PotreeServer running, which would then filter the points and prepare a downloadable file. This server never made it out of the prototype stage, and won't in the near future. That means that there is no way to download all points within a volume at this time, unortunately.

**Comment by upendrakolte** [comment]
Any update on this .. ? is it possible now to get all the points within a volume ?

**Comment by MaxymShtoyko** [comment]
@m-schuetz Any update on this?

**Comment by okaforcj** [comment]
did any of you find an alternate solution? @upendrakolte @MaxymShtoyko
