### ISSUE TITLE
Impossible d'executer le potreeConverter

### ISSUE THREAD

**Issue by nova360-cloud** [potree/potree#805]
Thank you for your interest! In an effort to make it easier to respond to your problem we would like
for you to consider a few things:

- Can you try to phrase it as a task?
    Instead of "What unit is used in the cut view?" ask for "Clarify unit in cut view".

- Can you make a screenshot or a screencast?
    Some graphic errors are hard to describe, a screenshot helps to get your problem accross.
    A service like [Gyazo Gif](https://gyazo.com/download) makes it possible to keep the link up for a long time.
    Please don't link to a url that could be gone in a month or two (like dropbox).  

- Did you reach out on Gitter?
    We have a gitter [channel for potree](https://gitter.im/potree/Lobby). Did you try to ask about your issue there?
    
- Is all information accessible for us?
    A cryptic error message like "Doesn't work on my computer" will not help us much. It would be awesome if
    you could provide a permalink or code sample to the problematic section. What OS, potree and browser version you are
    you using? How can we reproduce the issue? Logs can help too and
    [Gists](https://help.github.com/articles/creating-gists/) are a good idea as well.

Thank you for your consideration, please delete this text after you read it.

**Comment by nova360-cloud** [comment]
Hello
Maybe someone can help me, after installing the potreeconverter, I still have this same message: "impossible to execute the code because MSVCP140.ddl cannot be found, reinstalling the program can correct this problem" what is wrong please, 
_
My window 10 version is the 1909

**Comment by midnight-dev** [comment]
For reference, `MSVCP140.dll` is part of the Microsoft Visual C++ redistributable package from 2015. Many programs use it, and it's typically installed automatically. 

Sometimes, you may want to install it separately to fix or prevent dependency errors like this.

Here is the official page for the Windows library: https://www.microsoft.com/en-us/download/details.aspx?id=48145

Select your language, download, and install. For 64-bit systems, both x86 and x64 versions should be installed. For (old) 32-bit systems, only x86 should be installed.

You can also download and install newer & older versions of Visual C++ runtime libraries while you're at it, but programs will only use the specific version that they were built for. **Important: Only download and install these libraries from the official Microsoft website.** If you install packages from third-party websites, you may accidentally install malware.

Cheers o/
