### ISSUE TITLE
Issue first time using potree

### ISSUE THREAD

**Issue by jrjdavidson** [potree/potree#811]
Hi all, 

Using potree for the first time, very excited about the possibilities. I'm having trouble getting started and wondering if you could point me in the right direction.

I'm trying to test PotreeConverter on datasets downloaded from opentopography. I downloaded this dataset:

https://ot-data2.sdsc.edu/appLasSelectService1589161025233231940838/points.las

processed it using Potreeconverter using the example command:

PotreeConverter.exe C:/data.las -o C:/potree_converted -p pageName

when attempting to load the page, I get the following error in the console.log

Uncaught TypeError: Cannot read property 'byteSize' of undefined
    at new Potree.PointAttributes (potree.js:4211)
    at XMLHttpRequest.xhr.onreadystatechange (potree.js:3978)

I've tried adding projection tag when converting, tried playing with the inputs tags, but I can't seem to get it right.. Any help would be appreciated.

Also sorry if this isn't the right place to post this!

**Comment by smcavoy12** [comment]
[https://github.com/potree/potree/issues/770]

Hi, See this previous post, try using the 1.6 version of potreeconverter if you're using 1.7

**Comment by jrjdavidson** [comment]
That's looks like its almost certainly it. Thanks - and I promise I tried to search the fault in here and didn't find anything.  I guess I need to hone my git search skills!
