### ISSUE TITLE
Potree access to data stored on a cloud

### ISSUE THREAD

**Issue by ludpt** [potree/potree#812]
Hi all,
I starting with Potree and I managed to display a model in local using xampp. Meanwhile, my project need to work with data stored on a cloud. Is there a header that would let me query pointcloud data with login and password?
Thanks a lot

**Comment by TaylorDale** [comment]
You can use a basic auth header, simple and effective

**Comment by m-schuetz** [comment]
Closing this since I don't know about cloud hosting behind user authentication, and can't help with this.
