### ISSUE TITLE
Discussion: Default Port - localhost:1234

### ISSUE THREAD

**Issue by midnight-dev** [potree/potree#819]
Hi all. I'd like to get a small discussion going regarding the default port that's used for localhost servers spawned by the gulp / npm task `start`.

_TL;DR: Port 1234 (`localhost:1234`) has been causing browser suggestion issues for me. Would anyone be opposed to switching the server port to 80 so just `localhost` can be used instead?_

I noticed the port number while skimming through the docs a long time ago, yet I never gave it any thought, because why should it matter? Then I started developing more on my local machine and using the localhost server. Everything was fine for a while, until I synced my Firefox history between my workstation and laptop. Every time I wanted to go to localhost on my desktop, Firefox had the neat idea of autofilling the port.

![image](https://user-images.githubusercontent.com/47105073/82147272-40abf300-9814-11ea-9a5d-87cc90e9a757.png)

### So, what's the BFD, mate?

The deal is browsers are terrible with suggestions. I cleared cache & removed every single reference to the port in my history and it still showed up. Checked for bookmarks, no dice. It _knew_ that I visited `localhost:1234` a handful of times and figured I must want to default to that.. on every machine... always. I **cannot** type "local" without it filling in "localhost:1234" every time.

I did finally fix behavior by manually removing _all_ localhost histories. Doing that every time is painful, and the majority of my history is precious research and resources, so I can't run a full history wipe every time. I'd like to think most developers like having their history intact for future reference.

Ultimately, this is an oversight in browser suggestion mechanics. It should never get a port _stuck_ in suggestions when there's no history of it. Until that gets patched, it's private window all the time so nothing gets stuck.

Lately, I've been working with a modified gulp config that just defaults to port 80 and makes the web server reachable without specifying a port 👌  Though I have to stash and reapply this every time I switch branches or checkout a pull request.

### This got me thinking... 

Has anyone else run into this annoyance or something related? Would it be an improvement to use port 80 as the default? Sure, there could be a collision with another dev server, but that's true for any port config, be it 80, 1234, 8080, or 20000. The only real issue I see is if someone runs the server NPM script on the same device that's hosting a typical HTTP server already. I've never done that, and neither have the colleagues whom I've asked. I also don't usually run more than one dev server at a time, and Node will let your know if there's a collision anyway. 

So, is port 1234 still a necessity? I'm in favor of swapping to the conventional port 80, but there are plenty devs who spin up a Potree build on a regular basis, so this deserves community discussion.

**Comment by m-schuetz** [comment]
Not using 80 or 8080 was a conscious choice, because it was interfering with other applications.

**Comment by hunkyu** [comment]
// For development, it is now possible to use 'gulp webserver'
// from the command line to start the server (default port is 8080)
gulp.task('webserver', gulp.series(async function() {
	server = connect.server({
		host:'192.168.0.xx', 
		port: 80,
		https: 'false',
	});
}));


[15:35:02] 'webserver' errored after 45 ms
[15:35:02] 'watch' errored after 47 ms
[15:35:02] The following tasks did not complete: build, pack, <anonymous>, <parallel>, shaders, icons_viewer, examples_page
[15:35:02] Did you forget to signal async completion?

**Comment by hunkyu** [comment]
[15:37:22] Error: listen EACCES: permission denied 192.168.0.196:89
    at Http2SecureServer.setupListenHandle [as _listen2] (node:net:1298:21)
    at listenInCluster (node:net:1363:12)
    at doListen (node:net:1501:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[15:37:22] 'webserver' errored after 48 ms
[15:37:22] 'watch' errored after 49 ms
[15:37:22] The following tasks did not complete: build, pack, <anonymous>, <parallel>, shaders, icons_viewer, examples_page
[15:37:22] Did you forget to signal async completion?

ufw :
-                          --          --
82                         ALLOW       Anywhere                  
7070                       ALLOW       Anywhere                  
89                         ALLOW       Anywhere                  
82 (v6)                    ALLOW       Anywhere (v6)             
7070 (v6)                  ALLOW       Anywhere (v6)             
89 (v6)                    ALLOW       Anywhere (v6)

**Comment by midnight-dev** [comment]
Not really related to the port 1234 issue... However, you may be running into problems with a program already using your preferred port. You need to make sure you close previous instances of your webserver task. The easiest way is to tap Ctrl + C in the terminal where the watch/start/webserver task is running until you see the context fully shutdown to the vanilla terminal. If you have any other program bound to that port, initialization will fail because the port cannot be claimed by more than one program at a time.
