### ISSUE TITLE
Clipping and Point Budget

### ISSUE THREAD

**Issue by smcavoy12** [potree/potree#825]
My understanding is that clipping functions are merely visual masks, keeping the invisible points in memory. I understand the utility of this method for the majority of cases, but is there a way to reallocate the point budget to only those sections shown in the clipping region? It seems like a useful feature for exploring interiors with multiple layers of points in view.

Example: seeing carvings on this cave wall (video below). From the inside it's impossible to see the whole thing, so you clip away the opposite wall, but you're still sharing the point budget with that now invisible wall until you zoom back inside the cave.

https://youtu.be/oJQHF-3ZbC0

I can get my desired effect by simply uploading each carving as a separate pointcloud aligned with the rest of the cave and unchecking the main cave. I was hoping though, has anyone implemented a clipping feature like I've described?

Thanks very much.

**Comment by m-schuetz** [comment]
Potree already does this per-node. All nodes fully outside the clip region will not be considered in the point budget.
