### ISSUE TITLE
Getting error while trying to run 360.html example

### ISSUE THREAD

**Issue by Ingsayyad** [potree/potree#826]
Here is the detail:

Uncaught ReferenceError: cv is not defined
    at onmessage (BinaryDecoderWorker.js:314)

			**const getter = getterMap[pointAttribute.type.name].bind(cv);**
![error](https://user-images.githubusercontent.com/17673805/82808275-f2d56180-9e89-11ea-9e38-2ad30c27fbac.PNG)

**Comment by m-schuetz** [comment]
Fixed: https://github.com/potree/potree/commit/47edbce440603d1eaa9a720c8451bc8422217332

Thanks for the report!
