### ISSUE TITLE
Make navigation easier.

### ISSUE THREAD

**Issue by tigerfoot** [potree/potree#83]
It would be nice to have a combined mode between orbitcontrol and FirstPersonControl.
Expected feature is use mouse scroll to zoo in/out, left click moving around (obit) and right click allow to is defining a point and then around the picked point.
Also a way should exist to keep right clic to pan lef-right, top-bottom 

This show that the project will need to define an HID in the long term.

**Comment by m-schuetz** [comment]
I'm thinking about adding a navigation that is similar to google earths

**Comment by martinheidegger** [comment]
This has been added as [`EarthControls`](https://github.com/potree/potree/blob/master/src/navigation/EarthControls.js) a while back. I am closing this issue as I assume this implementation reflects the ideas described by @tigerfoot. Please reopen the issue if I am mistaken.
