### ISSUE TITLE
Incomplete function of the toolbar on the left of multiple point clouds

### ISSUE THREAD

**Issue by WenBinPan** [potree/potree#834]
When the potree loads multiple point clouds, some functions of the left toolbar are not displayed (Properties section). It is possible to load only one point cloud.
![image](https://user-images.githubusercontent.com/45220025/84623568-2566fd00-af12-11ea-9a68-800b2110a7a0.png)

**Comment by midnight-dev** [comment]
It works fine on my local version with multiple point clouds. I just have to click on the point cloud in the Scene section to get the properties panel of the specific point cloud. There is a problem with the multi point cloud example linked out from the project's readme.

I'm not sure why, but [PropertiesPanel.js](http://potree.org/potree/src/viewer/PropertyPanels/PropertiesPanel.js) on potree.org is inconsistent with the current version of the repository. It's missing the minimum size field, for instance. This appears to be the case regardless of the example selected.
