### ISSUE TITLE
 FlipYZ in viewer

### ISSUE THREAD

**Issue by smcavoy12** [potree/potree#835]
Would someone be able to tell me how to call flipYZ in the viewer? Doing e.pointcloud.rotation.set();  is moving my clouds off center.

This doesn't work, but is it something like:

```
window.viewer = new Potree.Viewer(document.getElementById("potree_render_area"));
--
  |  
  viewer.setFOV(60);
  viewer.setPointBudget(10*1000*1000);
  document.title = "";
  viewer.setEDLEnabled(false);
  viewer.setBackground("gradient"); // ["skybox", "gradient", "black", "white"];
  viewer.setDescription(``);
   viewer.loadSettingsFromURL();
   viewer.flipYZ();
    
```

Thanks very much!

**Comment by midnight-dev** [comment]
Unfortunately, the `flipYZ()` method hasn't been implemented yet. In theory, your example is indeed how it would be called, as it's part of the viewer. It changes a bool that is meant to keep track of YZ flipping, but I don't see it referenced anywhere in the current build of potree.js. But maybe I've missed a worker script that checks that bool.

@m-schuetz I noticed a TODO log in this method. Is this on a near-term milestone checklist?

**Comment by m-schuetz** [comment]
This isn't supported atm. There might be a way to do it, but it might now work reliably and break tools that did not expect a flip.
