### ISSUE TITLE
Black Background Issue

### ISSUE THREAD

**Issue by colinmacrae** [potree/potree#836]
Clicking option for a black background shows no background.
![No Background Selected](https://user-images.githubusercontent.com/53214385/85114164-73307d80-b210-11ea-8e50-06d34ded82ed.png)
![Black Background selected](https://user-images.githubusercontent.com/53214385/85114167-7461aa80-b210-11ea-8a7e-2fb8acb349bd.png)

**Comment by m-schuetz** [comment]
Works for me. Please describe how to reproduce your issue.
