### ISSUE TITLE
problema na visualização

### ISSUE THREAD

**Issue by gabrielmancilla** [potree/potree#840]
hello, I uploaded my first model and the browser returns me a line just like the figure below

the link is: http://genesis.coletor.com.br/las_paulo/webpageName.html 

I am grateful for the help

![image_las](https://user-images.githubusercontent.com/2414363/85333478-a6406e80-b4a7-11ea-8634-d9c8e2a0b99c.JPG)

**Comment by malamutekid** [comment]
Hi Gabriel- Have you tried looking at your developer tools console in your web browser? When I clicked your link, it's giving me an error message saying that your point cloud file is not found.

**Comment by m-schuetz** [comment]
This is because the point cloud coordinates are in lat/long, rather than euclidean coordinates. You'll have to project your point cloud from a lat/long coordinate reference system to a euclidean map projection.
see issues #52 #383
