### ISSUE TITLE
How can I show the grid?

### ISSUE THREAD

**Issue by gmiguelr87** [potree/potree#842]
Hello,

I am trying to show the grid, as you could see in the example of the lion in version 1.4 (attached example image), but I am not able to do it in the current version.

![image](https://user-images.githubusercontent.com/20948392/86102007-4c4d3380-babb-11ea-8e6a-a84cd0fe2a51.png)

I would be very grateful if someone could guide me in doing so. Thank you very much in advance.

Best regards!

**Comment by m-schuetz** [comment]
This grid was created using three.js. I suggest to take a look at the line rendering demos of three.js in order to learn how to do this: https://threejs.org/examples/?q=line
