### ISSUE TITLE
Mobile browsing problems

### ISSUE THREAD

**Issue by WenBinPan** [potree/potree#843]
I can already browse on my iPhone and Android. However, the mobile terminal starts EDL（ viewer.setEDLEnabled (true))。 When rotating a certain angle, there are fringe spots on the surface of the point cloud. Is there a solution?
![Screenshot_2020-06-30-17-27-49-773_com tencent mo](https://user-images.githubusercontent.com/45220025/86109770-50974200-baf7-11ea-941e-ce0a860ad99f.jpg)
![Screenshot_2020-06-30-17-28-04-072_com tencent mo](https://user-images.githubusercontent.com/45220025/86109803-5ab94080-baf7-11ea-96b6-de66200f361e.jpg)

**Comment by Haris487** [comment]
I am also facing same problem when I set viewer.setEDLEnabled(false); then example 360.html works. otherwise it does not works.

**Comment by m-schuetz** [comment]
> there are fringe spots on the surface of the point cloud. Is there a solution?

This sounds like either a precision issue or a general problem with floating point textures on the mobile device. Unfortunately I have no means to debug this and work on it, so to avoid this you'll have to disable EDL by default.
