### ISSUE TITLE
Potreee Desktop upload in ftp server

### ISSUE THREAD

**Issue by patrimoniodigitale** [potree/potree#845]
Hi, im a new user of potree..

im testing a potree desktop 1.7

how i can upload my file converted in my ftp?

with potree converter is very simple because the cmd comand generate a html page, but in desktop version how it is possible?

thanks 

sorry for my bad ensglish

**Comment by m-schuetz** [comment]
Hi,

If you want to upload something, use Potree instead of PotreeDesktop and once it runs localy (test with npm start, see readme.md), you can upload it on the webserver.
