### ISSUE TITLE
Bad vertical scale on profile

### ISSUE THREAD

**Issue by poagliati** [potree/potree#846]
Hi,
It looks like the commit b3c4b618477fc1bfe326375dcdaaf4b850e5e4fd named "some promisifications; fix coordinate precision in profile window" performed the 4th of February introduced some errors on the profile vertical scale.
In fact, the position of the point cloud has been substracted in the ProfileRequest for the sake of precision, but I don't think all the stuff necessary to the coordinate shifting has been performed on notification of addPoints in profile.js.
As a result, the profile window shows the shifted profile, and the vertical scale is erroneous.
Best regards

**Comment by m-schuetz** [comment]
Do you have some details on how to reproduce this issue? Seems to work fine for me.

**Comment by poagliati** [comment]
Hi Markus,
Thank you for your feedback.
Starting from a fresh 1.7beta, if you run the elevation-profile example and look at the profile, you can see that the range covered on the Z axis scale is approximatively [ 20, 65] but if you look at the z coordinate in the info window the elevation is rather between approximatively 745 and 790 (see the attached snapshot).
I believe this comes from the quoted commit, the z-axis is probably associated to the translated cloud.
Best regards and many thanks for your great work.
![2020-07-23_17h29_59](https://user-images.githubusercontent.com/1236227/88307135-df206d00-cd0b-11ea-980d-b4ebb19c762b.png)

**Comment by m-schuetz** [comment]
Good catch, thanks!

**Comment by loicroybon** [comment]
Hello, I have a similar error on a model with two pointclouds. The two pointclouds should be perfectly aligned. 
![Z error on profile](https://user-images.githubusercontent.com/43131515/89016756-8bb8ab00-d319-11ea-8014-8e102d3d2d79.png)
And on mouse hover on profile, the good Z value is displayed on properties panel, but, scale is wrong and alignement too.
Thanks in advance for your help to solve this problem.

**Comment by poagliati** [comment]
Hello,
Yes it sounds logical considering the problem raised because each cloud has been substracted from its own reference position which is somewhat different between your both clouds.
I guess things have to be translated again in the addPoints method of profile.js to go back to the global (common) coordinate frame.
Cheers

**Comment by m-schuetz** [comment]
fixed in develop branch: https://github.com/potree/potree/commit/f9d94d18408a187825bfe482d83bd248025a3c64

Let me know if you still run into issues.

**Comment by loicroybon** [comment]
Hello, 
The previous solution fixed the bad alignment when two profiles are present, but now the LAS export is broken : real coordinates are lost. Any idea ?
