### ISSUE TITLE
How do you set distance measurement precision?

### ISSUE THREAD

**Issue by afr-git** [potree/potree#849]
Apologies for the simple question but I couldn't find this searching through existing issues or documentation. I've got a small private test deployment of Potree (1.7 beta) that uses terrestrial laser scans (units are meters which is great, but the distance precision is to two decimal places, i.e. cm). 

As the precision and accuracy tolerances for this data are in the order of mm, I'd like to add an extra decimal place into the mix, and change the default precision from cm to mm. Is this possible/easily adjustable? Thanks

**Comment by m-schuetz** [comment]
Hi,

* Distance displays in the sidebar already have 3 decimal places.
* To adjust the display in the 3D View, change ```let txtLength = Utils.addCommas(distance.toFixed(2));``` to ```let txtLength = Utils.addCommas(distance.toFixed(4));``` in Measure.js
* To adjust the display in the sidebar, change ```toFixed(3)``` to ```toFixed(5)``` in DistancePanel.js

**Comment by afr-git** [comment]
Hi Markus,

Thanks for your help, apologies I did spot the measurements in the sidebar with 3 decimal places afterwards but it was the 3D view displayed measurements I was referring to. 

I couldn't find the Measure.js file you're referring to but I found that line in Potree.js and updated to `let txtLength = Utils.addCommas(distance.toFixed(3));` which works perfectly.

**Comment by m-schuetz** [comment]
Great!
