### ISSUE TITLE
Webpage not loading points (compiled in linux ubuntu)

### ISSUE THREAD

**Issue by fpirotti** [potree/potree#850]
I managed to compile Potree 1.8 for linux - at first it did not find the "page_template" - I had to copy the parent folder "resources" directly in root path and everything worked - but points are not loaded. Checking the page debugger it shows that the attributes seem not to be assigned correctly. I tried to fiddle changing the "let pointAttributeName = pointAttributes[i];" to "let pointAttributeName = pointAttributes[i].name;" but without success. Is there a workaround for this or am I doing something wrong? 
 
![immagine](https://user-images.githubusercontent.com/1391292/87872647-d0a81d80-c9ba-11ea-8d26-6ccfb8534909.png)

**Comment by smcavoy12** [comment]
Hi, page_template and the resources folder are related to PotreeConverter, I wonder, are you using a version of potree converter not compatible with your version of the viewer?

**Comment by fpirotti** [comment]
Yes! My bad, I will move this issue to Potree converter.
