### ISSUE TITLE
SaveProject/LoadProject Issues with material ranges

### ISSUE THREAD

**Issue by ilisalis** [potree/potree#851]
In pointcloud material, ranges (for different range names like elevation or intensity) are not generalize and use specific variables. They are therefore currently not correctly save and reload.

Proposition: 
In SaveProject.js (line 8)

	for(let [name, value] of material.ranges){
		ranges.push({
			name: name,
			value: value,
		});
	}
	if(pointcloud.material.activeAttributeName === 'elevation'){
		ranges.push({
			name: pointcloud.material.activeAttributeName,
			value: pointcloud.material.elevationRange,
		});
	} else if(pointcloud.material.activeAttributeName === 'intensity'){
		ranges.push({
			name: pointcloud.material.activeAttributeName,
			value: pointcloud.material.intensityRange,
		});
	}	

And in LoadProject.js (line 19):

	if(data.material.ranges != null){
		for(let range of data.material.ranges){
			if(range.name === 'elevation'){
				target.elevationRange = range.value;
			} else if(range.name === 'intensity'){
				target.intensityRange = range.value;
			} 
			
			target.setRange(range.name, range.value);
		}
	}

**Comment by m-schuetz** [comment]
Thanks for the report/suggestion - integrated here: https://github.com/potree/potree/commit/467fd8733d56c49f1fb7cd8d1729356836b3a757

* The exporter now always exports elevationRange and intensityRange.
* Switched to JSON5 because JSON sucks. Now supports +-Infinity values for the ranges.
