### ISSUE TITLE
SaveProject/LoadProject Issues with EDL use

### ISSUE THREAD

**Issue by ilisalis** [potree/potree#852]
When we load a Potree Project, the EDL state is correctly sent to viewer.js, but not to the sidebar. This change is correctly dispatch (use_edl_changed) in viewer.js; but there is no correct listener in sidebar.js.

Proposition of adding in sidebar.js (near line 1320):
```
this.viewer.addEventListener('use_edl_changed', (event) => {
	$('#chkEDLEnabled')[0].checked = this.viewer.getEDLEnabled();
});
```

**Comment by m-schuetz** [comment]
Thanks, added your suggested fix: https://github.com/potree/potree/commit/fee8cac946cfd830369ec41808802bef360c30a4
