### ISSUE TITLE
Cant get 2.0 format to Load in Browser

### ISSUE THREAD

**Issue by smcavoy12** [potree/potree#864]
Hi, I've been having some trouble getting the new format to load in browser, pointing to the metadata.json file.

Here's the viewer, from the "Basic Viewer" example, with the new 2.0 readme loader snippet pasted in:
https://pointcloud.ucsd.edu/potree2/bathy2.html

Here's the JSON file
https://pointcloud.ucsd.edu/potree2/pointclouds/bathy/metadata.json

I've tried it with a couple of different clouds, tried with the latest 1.7 release, the 1.7beta, and 1.6, and the latest desktop release.

Thanks very much!

**Comment by potree** [comment]
Hi, it seems like the Potree version you're using is not the lattest one. It's missing the metada.json condition: https://github.com/potree/potree/blob/develop/src/Potree.js#L164 
```} else if (path.indexOf('metadata.json') > 0) {```

Did you get this release? https://github.com/potree/potree/releases/tag/1.7

**Comment by smcavoy12** [comment]
Ah! It was the "../" in the script path, loading from my 1.6 repository, Thanks for pointing that out,  it's working great now, much appreciated!

**Comment by potree** [comment]
You're welcome, thanks for signing up for a github sponsorship/license!
