### ISSUE TITLE
Intensity Value Display

### ISSUE THREAD

**Issue by smcavoy12** [potree/potree#867]
I upgraded to the newest Potree1.7 build, I noticed that when I specify "intensity" or "intensity gradient" as the active attribute the pointcloud loads black and I have to actually click on the pointcloud title in the scene window before it'll load the color scheme.

Here's a short video showing the behavior
https://youtu.be/HfbFDv9orAc

The site
https://pointcloud.ucsd.edu/intense.html

Thanks very much!

**Comment by smcavoy12** [comment]
I found that it works if I manually specify the range, apparently the range isn't automatically populated until clicking on the title to load attribute options. 

```
material.activeAttributeName = "intensity";   
pointcloud.material.intensityRange = [1,6];
```

**Comment by midnight-dev** [comment]
@m-schuetz Think this is related to the conundrum of trying to use reasonable defaults for the shaders before the min & max attributes are known to Potree? Particularly for gradients? It sounds like it, because when a range is specified, it's easy to create a gradient from black to white.

**Comment by m-schuetz** [comment]
Might be a regression from integrating the 2.0 format, which already has precomputed min and max values.

**Comment by potree** [comment]
And yes, it's because of trying to find reasonable defaults for the gradients, which have to be computed in javascript for formats before 2.0, but with PotreeConverter 2.0, min and max are already precomputed during conversion. Bringing both together into Potree 1.7 may have caused this issue.

**Comment by AlbionS** [comment]
@potree is it possible to display automatically the Intensity if rgb values are 0 ? activeAttributeName = "depending if scan has color or not"
Or we have to check the metadata.json of Potreeconverter2.0  if the values are 0 and than  switch to intensity activeAttributeName = "intensity";

**Comment by m-schuetz** [comment]
Cause: 

Potree now initializes the intensity range with the min/max values reported in the Potree 2 format, or with [Infinity, -Infinity] for older formats that do not report min/max values. This is why things start out as black with models up to format 1.7. Once the properties panel is opened/selected, the range is initialized with an estimate that's stored in attribute.range:

```
if(pointcloud.material.intensityRange[0] === Infinity){
	pointcloud.material.intensityRange = attribute.range;
}
```

TODO: immediately apply the estimate, if the model doesn't provide absolute values.

**Comment by m-schuetz** [comment]
@AlbionS 
I won't be able to work on an automatic detection for WebGL based Potree, but I've added it to the considerations for Potree 2.

**Comment by m-schuetz** [comment]
I've re-added intensity range estimation for up to Potree 1.7 format, but it's a bit whacky because the estimated values undergo huge changes as more data is loaded in: https://github.com/potree/potree/commit/fe2e4d2a43f66c6476f8eaa8cd1ae207a2b79a63#diff-404685ceda9fba1c8960e0af13f519131ed50c34f6fef14c89290d97380de0a9R1590-R1595

So, it has some issues but solving these will be postponed to Potree 2.0.
