### ISSUE TITLE
local rendering pipeline

### ISSUE THREAD

**Issue by kittles** [potree/potree#893]
ive spent a couple days with potree now, and its just about as good a javascript library as i have seen. so thank you! id like to describe what i am working towards below, just to see if anyone has thoughts or suggestions.

i have a dataset that has a datapoint for each km squared of the continental united states, which is about 13 million points. there is one of these per hour, and id like to animate a full day of data. basic idea is to generate intermediate data sets between each of the hours (60 or so) and render each to a png, and then create a movie out of the pngs. ive done this in the past with smaller datasets using 3d geometry, but with 13 million points it seems like pointclouds are much faster and sacrifice almost nothing in terms of quality.

as a fallback im thinking could run a bunch of instances in the cloud to do this, but im curious if there are some ways around this. the first hurdle is that converting las to octree for each dataset adds about 20 seconds. since im using a point budget greater than 13 million, and running a local server, i wonder if there is any point in an octree for my case? i havent looked to deeply into potree source yet, but would it be a PITA to handle las files directly? i love the way it renders pointclouds with the enhanced depth perception via borders, and i am fairly versed in THREE.js, hence my attachment to this particular project.

my second question is predicated on the first being answered yes- in that case, where in the source would be a good place to apply transformations to the data set being rendered? in my case, i think id probably want to load two las datasets in memory and create an interpolation function which modified the visible dataset. 

supposing thats all a no-go, im curious if anyone knows of other nice ways of rendering point clouds for such an animation. ive tried using blender but i inevitably give up because im not convinced enough that its the right enough tool for the job to warrant the apparently vast amount of learning required to do basic stuff there. an idea program would simply be a cli that accepts a dataset and camera position, and renders to a png. thank you for the wonderful library, and any help or suggestions with this project!

**Comment by smcavoy12** [comment]
Ok, like an animated histogram over each square km? 13 million doesn't sound too crazy big, I'd try without Octrees.

If it were me I'd convert the two point clouds to raster DEMs. Use a video editing program to animate a color gradient change between the two frames, save the clip as an animated GIF. Then use that GIF as a displacement map on a plane, or maybe a grid of points.

Here's an example of an animated displacement map in three.js.

**Comment by kittles** [comment]
thats a very cool idea. so cool... that i will give it a try!
