### ISSUE TITLE
2.0 format Hosting, Pointclouds and Viewers on Different Servers.

### ISSUE THREAD

**Issue by smcavoy12** [potree/potree#900]
Hello,

With the 1.7 format I can host a viewer on one server, but load the pointcloud from another server. I can use this loader to pull my cloud (below), though the viewer itself is on a local xampp server.

`Potree.loadPointCloud("https://pointcloud.ucsd.edu/pointclouds/seuss/cloud.js", "Dr. Seuss Statue, UC San Diego Library ", e => {`

I can't seem to do this with 2.0 format pointclouds, this wont load unless I'm hosting the viewer and pointcloud on the same server:

`Potree.loadPointCloud("https://pointcloud.ucsd.edu/pointclouds/Pompeii/metadata.json", "Pompeii, Italy", e => {`

**Comment by midnight-dev** [comment]
Are you seeing CORS errors in the console log? Or any other errors for that matter?

**Comment by smcavoy12** [comment]
Thanks Ben,

I added:
```

Header set Access-Control-Allow-Headers "*"
Header set Access-Control-Allow-Origin "*"

```
to the .htaccess file, its working fine just fine now.
