### ISSUE TITLE
Volumes block the Earth Control navigation from working properly

### ISSUE THREAD

**Issue by mikepianka** [potree/potree#904]
When using Earth Control navigation and there are volumes in the scene, the volumes block mouse clicks from reaching the point cloud and as a result the Earth Controls do not work. If you zoom in far enough to be "within" the volume, then the mouse clicks will reach the point cloud and you can navigate as expected.

Tested on 1.7.1 develop branch. To reproduce, open the Clipping Volume example and set the navigation mode to Earth Control. Try clicking on the point cloud within one of the volumes to navigate - it doesn't work and mouse clicks on the point cloud are ignored. Now, zoom in close to the point cloud so you are within the volume. Now you can navigate as expected.

![image](https://user-images.githubusercontent.com/47948499/94447168-8344eb00-0177-11eb-8783-01c2ad73a27e.png)

![image](https://user-images.githubusercontent.com/47948499/94447361-aa9bb800-0177-11eb-96c5-69473cc604bd.png)

**Comment by mikepianka** [comment]
To add to the above, I just noticed that setting visibility on the volume to false will also let Earth Control work as expected. So it seems that when the volume is visible, it is intercepting the mouse events and blocking them from reaching the point cloud within.

`viewer.scene.volumes[0].visible = false`

**Comment by m-schuetz** [comment]
Hi, although that behaviour is not entirely intuitive/desirable, it's not something that will be fixed for Potree 1.7 since I'd rather like to concentrate on the rewrite.
