### ISSUE TITLE
Point cloud quality of mobile phone version 1.7 decreases

### ISSUE THREAD

**Issue by Paweled** [potree/potree#905]
On my mobile phone, I used the same configuration to browse the point cloud of version 1.6 and version 1.7, and found that the quality of point cloud of version 1.7 has deteriorated,
material.size = 0;
viewer.setEDLEnabled(false);
viewer.useHQ = false;

This is version 1.6:
![image](https://user-images.githubusercontent.com/45220025/94526588-515f8180-0268-11eb-9d4b-5bc4eab5577b.png)

This is version 1.7:
![image](https://user-images.githubusercontent.com/45220025/94526657-663c1500-0268-11eb-9238-643e0116ab55.png)

Do you need to configure anything else?

**Comment by potree** [comment]
Are you using the same point budget and minNodeSize in both cases? 
![image](https://user-images.githubusercontent.com/2094934/94527992-15acc380-0238-11eb-9ab1-fbc3def6b9bf.png)

**Comment by potree** [comment]
Also check 
- dev console for errors (F12)
- Enable the bounding box (right under min node size slider) in both cases to check whether a similar amount of nodes are rendered
- Does this only happen on mobile? Desktop too?

**Comment by Paweled** [comment]
using the same point budget and minNodeSize
viewer.setPointBudget(=2*1000*1000);

Desktop 1.7 has also declined,

viewer.setEDLEnabled (true); viewer.useHQ =True; not obvious,

viewer.setEDLEnabled (false); viewer.useHQ =False; version 1.7 is a little fuzzy

**Comment by midnight-dev** [comment]
> viewer.setEDLEnabled (true); viewer.useHQ =True; not obvious,
> 
> viewer.setEDLEnabled (false); viewer.useHQ =False; version 1.7 is a little fuzzy

@Paweled Does this part of your comment mean that 1.7 is set to no EDL & standard quality while 1.6 is set differently? Or is that about desktop? I'm confused about what you're referring to here since you're giving two different configurations. 

For what it's worth, capital "True" and "False" are not in spec for JavaScript. Lowercase "true" and "false" should be used for boolean values.

To me, it looks like point size may be the issue here. Can you check the point size, minimum size, and if the points are set to adaptive / fixed sizes. The shape may also have an impact on appearance (square / paraboloid / circle points), but it's less noticeable while the camera is far away from the points.

**Comment by m-schuetz** [comment]
Please upload a 1.6 and 1.7 online that I can look at to figure out the issue.

**Comment by Paweled** [comment]
Oh, I'm sorry, it's my fault; I forgot that I added anti aliasing to version 1.6, so my version 1.6 looks better. 
I'm very sorry for the trouble. 
I added: this.renderer.setPixelRatio ( window.devicePixelRatio );

![image](https://user-images.githubusercontent.com/45220025/94636881-cbdfde00-0308-11eb-9956-bab3f08bea83.png)

**Comment by midnight-dev** [comment]
Anti-aliasing alone shouldn't be able to do that. Fine detail like the pathways among foliage is completely obscured in the second screenshot, so smoothing the color deltas would just blend the different shades of green better, similar to using the high quality splats. 

The pixel ratio is an interesting difference though. If your smartphone typically scales pixels by 3x for better readability, then 9px in a square (3x3) would represent 1px, and that could affect which points are loaded in. In theory, if you have min node size set to a default of 30, any node that is smaller than 90x90 (at current camera position) _will not_ load. Hence, the more granular points making up the pathways wouldn't be loaded or rendered. Essentially, only very sparse points closest to the camera would be visible when using a high DPI/PPI screen like on modern smartphones.

To some degree, it still looks like point size to me, but setting the pixel ratio properly according to the device is something I've never tested. I'll give it a poke this weekend. Need to verify if the display ratio actually matters while node size is evaluated. Whatever the ultimate reason is, the first screenshot looks more professional while the second one looks kind of amateur. Glad you found that snippet, by the way. I wouldn't have guessed that pixel ratio was involved. 👌

**Comment by potree** [comment]
> Anti-aliasing alone shouldn't be able to do that. 

Device pixel ratio probably acts like supersampling so coupled with smaller less occluding points, that's a nice way to improve quality.
