### ISSUE TITLE
One Potree works, the other doesn't.

### ISSUE THREAD

**Issue by alexandramclarty** [potree/potree#913]
Hi there,

I have a client who produces 3D Lidar scans and would like to host them on his site as Potrees.

I've uploaded one for him here the works beautifully: https://www.thegeonavgroup.com/potree/private-residence/private-residence.html

Since then, he's sent me a few more, none of which display the point map: http://thegeonavgroup.com/potree/airplane-hangar/airplant-museum.html

I don't see any obvious differences between the files, but am wondering if the experts here might have an idea what's gone wrong. I can share the original files if that's more useful - they're just large.

Thank you!

**Comment by m-schuetz** [comment]
Second one works because the link to the cloud.js file is invalid: https://www.thegeonavgroup.com/potree/airplane-hangar/pointclouds/Airplant%20Museum/cloud.js
404, page not found.

**Comment by alexandramclarty** [comment]
There's no cloud.js file in the one that works either:

https://www.thegeonavgroup.com/potree/private-residence/pointclouds/Private%20Residence/cloud.js

**Comment by alexandramclarty** [comment]
The cloud.js file for the Airplant Museum potree is at this location: https://www.thegeonavgroup.com/potree/airplane-hangar/pointclouds/Airplant%20Museum/datascan/scan/cloud.js

**Comment by m-schuetz** [comment]
For some reason, the first one loads a valid cloud.js file, while the second one tries to load from the invalid link.
* https://www.thegeonavgroup.com/potree/private-residence/pointclouds/Private%20Residence/datascan/scan/cloud.js
* https://www.thegeonavgroup.com/potree/airplane-hangar/pointclouds/Airplant%20Museum/cloud.js

I don't know why but maybe the developer tools (F12 or ctrl + shift + i) will help you find the reason.

**Comment by m-schuetz** [comment]
From the dev tools: 

![image](https://user-images.githubusercontent.com/6705073/96737783-54a8e180-13be-11eb-97bd-5ffa9363faff.png)

"Access to fetch at 'https://www.thegeonavgroup.com/potree/airplane-hangar/pointclouds/Airplant%20Museum/cloud.js' (redirected from 'http://thegeonavgroup.com/potree/airplane-hangar/pointclouds/Airplant%20Museum/cloud.js') from origin 'http://thegeonavgroup.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
"

**Comment by alexandramclarty** [comment]
Thanks so much for tracking that down! Clearly there's more to dig into for me here.
