### ISSUE TITLE
Possibility to "move" pointclouds

### ISSUE THREAD

**Issue by Donald1212** [potree/potree#933]
Is it possible to move pointclouds? 
For example, I have a pointcloud at the position X, Y, Z and want to move it 10 meters along the X-axis. 
I´ve tried the pointcloud.position.set() method, but that´s not really what i want. It set´s the pointcloud to a specific coordinate, but doesn´t "move" it.

**Comment by Donald1212** [comment]
> Is it possible to move pointclouds?
> For example, I have a pointcloud at the position X, Y, Z and want to move it 10 meters along the X-axis.
> I´ve tried the pointcloud.position.set() method, but that´s not really what i want. It set´s the pointcloud to a specific coordinate, but doesn´t "move" it.

**Comment by smcavoy12** [comment]
Hi Donald,

I'd use pointcloud.translateX()

**Comment by midnight-dev** [comment]
Think you're looking good tween

**Comment by midnight-dev** [comment]
Think tween is relevant here. It can smoothly move objects from one location to another.
