### ISSUE TITLE
Annotation actions are not exported

### ISSUE THREAD

**Issue by garrettluu** [potree/potree#940]
Annotations with actions are not properly exported; the `actions` property is completely missing from the exported JSON

To reproduce this bug:
1. Go to http://potree.org/potree/examples/features_sorvilier.html (or any other example that has actions within annotations)
2. Under "Scene" and "Export", click "Potree" and download the exported file

If we look at the file, the annotation with actions is stored as such, missing the `actions` field completely.
```json
{
	"uuid": "F091305C-ABC2-4E34-9A3D-43A5A9412A45",
	"title": "Actions:&nbsp;",
	"description": "This annotation has actions that switch between elevation and color rendering modes.",
	"position": [
		589769.27,
		231236.83,
		783.89
	],
	"offset": [
		0,
		0,
		0
	],
	"children": []
}
```

**Comment by potree** [comment]
Hi, 

This was a conscious choice because storing executable code in a distributable data file is a safety concern. If someone handed you a project file with code in it and you'd open it in PotreeDesktop, they'd have native access to your system and could delete files or transfer sensitive data.
