### ISSUE TITLE
How to load a previously exported existing camera animation in .json5?

### ISSUE THREAD

**Issue by Alfonsso786** [potree/potree#945]
I am trying to load a camera animation for a point cloud that I am currently hosting on my computer, I have tried using the camera_animation.html method and it works on localhost but when accessing with the external ip the animation doesn't load and doesn't appear in the scene panel.
I only tried the camera_animation.html method copying the json5 coordinates that i obtained from potree desktop but i suppose that there must to be a way to import this exported files.
Does anyone know how I could do it?

**Comment by midnight-dev** [comment]
Quick question. Are you using the exact same browser & Potree version in both the export and import attempt? 

There could be a problem if you're exporting on Chrome and importing on Firefox, as Firefox doesn't play nicely with the camera animation feature. Likewise, if you're exporting from the latest version of Potree and importing to an older version, it's possible that camera animation isn't fully implemented.

**Comment by Alfonsso786** [comment]
I'm using chrome for exporting and importing, also i tried to export with PotreeDesktop.
I tried to use the camera_animation.html script before load the pointcloud script but doesn't work, also when i tried to load the pointcloud in my smartphone the camera animation was loaded but i can´t use it.
Finally, I tried to reduce the amount of point that it´s loaded but it doesn´t work.
I leave the html code for you to take a look.


`<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
	<meta name="description" content="">
	<meta name="author" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	<title>Potree Viewer</title>

	<link rel="stylesheet" type="text/css" href="libs/potree/potree.css">
	<link rel="stylesheet" type="text/css" href="libs/jquery-ui/jquery-ui.min.css">
	<link rel="stylesheet" type="text/css" href="libs/perfect-scrollbar/css/perfect-scrollbar.css">
	<link rel="stylesheet" type="text/css" href="libs/openlayers3/ol.css">
	<link rel="stylesheet" type="text/css" href="libs/spectrum/spectrum.css">
	<link rel="stylesheet" type="text/css" href="libs/jstree/themes/mixed/style.css">
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="description" content="">
	<meta name="author" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	<title>Potree Viewer</title>

	<link rel="stylesheet" type="text/css" href="./libs/potree/potree.css">
	<link rel="stylesheet" type="text/css" href="./libs/jquery-ui/jquery-ui.min.css">
	<link rel="stylesheet" type="text/css" href="./libs/openlayers3/ol.css">
	<link rel="stylesheet" type="text/css" href="./libs/spectrum/spectrum.css">
	<link rel="stylesheet" type="text/css" href="./libs/jstree/themes/mixed/style.css">
</head>

<body>
	<script src="./libs/jquery/jquery-3.1.1.min.js"></script>
	<script src="./libs/spectrum/spectrum.js"></script>
	<script src="./libs/jquery-ui/jquery-ui.min.js"></script>
	<script src="./libs/three.js/build/three.min.js"></script>
	<script src="./libs/three.js/extra/lines.js"></script>
	<script src="./libs/other/BinaryHeap.js"></script>
	<script src="./libs/tween/tween.min.js"></script>
	<script src="./libs/d3/d3.js"></script>
	<script src="./libs/proj4/proj4.js"></script>
	<script src="./libs/openlayers3/ol.js"></script>
	<script src="./libs/i18next/i18next.js"></script>
	<script src="./libs/jstree/jstree.js"></script>
	<script src="./libs/potree/potree.js"></script>
	<script src="./libs/plasio/js/laslaz.js"></script>
	
	
	
	
	<div class="potree_container" style="position: absolute; width: 100%; height: 100%; left: 0px; top: 0px; ">
		<div id="potree_render_area" style="background-image: url('../build/potree/resources/images/background.jpg');"></div>
		<div id="potree_sidebar_container"> </div>
	</div>
	
	<script>
	
		window.viewer = new Potree.Viewer(document.getElementById("potree_render_area"));
		
		viewer.setEDLEnabled(true);
		viewer.setFOV(60);
		viewer.setPointBudget(1_000_000_000);
		
	
		
		viewer.setDescription("");
		
		viewer.loadGUI(() => {
			viewer.setLanguage('es');
			$("#menu_appearance").next().show();
			$("#menu_tools").next().show();
			$("#menu_clipping").next().show();
			viewer.toggleSidebar();
		});
		
		

		Potree.loadPointCloud("./pointclouds/arco_converted/metadata.json", "Espinete", e => {
			let scene = viewer.scene;
			let pointcloud = e.pointcloud;
			
			let material = pointcloud.material;
			material.size = 1;
			material.pointSizeType = Potree.PointSizeType.ADAPTIVE;
			material.shape = Potree.PointShape.SQUARE;
			material.activeAttributeName = "rgba";
			
			scene.addPointCloud(pointcloud);
			
			viewer.fitToScreen();
		});

	</script>
	
	<script>
	
		const animation = new Potree.CameraAnimation(viewer);


		const positions = [
			[-5386.137, -1541.951, -4.547],
			[-5381.322, -1532.432, -7.817],
			[-5372.912, -1521.576, -8.922],
			[-5373.849, -1509.892, -8.320],
			[-5364.985, -1497.690, -9.879],		
			[-5358.245, -1492.310, -12.301],		
			[-5360.269, -1487.985, -14.007],		
			[-5370.428, -1493.837, -9.681],		
			[-5378.058, -1495.782, -10.179],
			[-5385.080, -1501.522, -12.201],
			[-5390.741, -1503.457, -12.957],
			[-5394.033, -1503.221, -13.235],
			[-5396.585, -1498.678, -13.141],
			[-5401.578, -1491.968, -13.405],
			[-5400.070, -1482.858, -14.535],
			[-5392.990, -1477.482, -14.781],
			[-5396.171, -1468.597, -15.375],
			[-5390.915, -1463.146, -14.828],
			[-5381.338, -1463.183, -15.490],
			[-5375.655, -1458.082, -17.210],
			[-5371.888, -1460.356, -16.768],
			[-5368.672, -1456.113, -16.382],
			[-5359.420, -1460.692, -16.984],
			[-5349.065, -1462.068, -20.263],
			[-5337.792, -1468.267, -20.353],
			[-5349.065, -1462.068, -20.263],
			[-5358.442, -1449.051, -19.820],
			[-5363.113, -1449.507, -19.352],
			[-5361.287, -1443.656, -18.385],
			[-5358.340, -1435.900, -18.179],
			[-5358.123, -1431.002, -20.009],
			[-5355.364, -1431.232, -19.942],
			[-5352.138, -1434.454, -20.729],
			[-5339.953, -1426.401, -23.988],
			[-5329.888, -1419.001, -23.984],
			[-5311.916, -1426.287, -25.180],
			[-5309.542, -1426.962, -25.779],
			[-5310.066, -1432.313, -24.355],
			[-5307.985, -1437.347, -23.707],
			[-5301.255, -1444.584, -26.116],
		];

		const targets = [
			[-5373.838, -1503.886, -18.257],
			[-5386.652, -1491.149, -15.261],
  	 		[-5379.298, -1491.422, -8.443],   
			[-5366.423, -1479.982, -9.045],
      	   		[-5343.394, -1476.657, -16.343], 
			[-5362.241, -1465.756, -27.442],    
			[-5366.327, -1460.989, -27.602],    
			[-5370.428, -1493.837, -9.681],    
			[-5403.585, -1511.933, -16.330],    
			[-5383.877, -1532.192, -15.066],    
			[-5421.408, -1505.252, -15.533],    
			[-5406.925, -1475.256, -11.797],    
			[-5387.884, -1469.139, -11.703],    
			[-5398.287, -1461.666, -18.016],    
			[-5378.296, -1461.037, -14.268],    
			[-5411.573, -1452.899, -15.597],    
			[-5418.363, -1447.377, -18.125],    
			[-5360.108, -1463.832, -13.949],    
			[-5358.758, -1442.414, -18.502],    
			[-5348.838, -1472.861, -13.646],    
			[-5352.320, -1436.631, -14.643],    
			[-5341.531, -1470.290, -12.818],    
			[-5351.202, -1431.254, -21.005],    
			[-5318.455, -1463.541, -23.607],    
			[-5307.072, -1469.658, -22.505],    
			[-5318.455, -1463.541, -23.607],    
			[-5388.984, -1446.118, -16.833],    
			[-5357.459, -1420.118, -11.963],    
			[-5348.887, -1415.481, -16.750],    
			[-5375.842, -1412.036, -26.811],    
			[-5327.396, -1433.370, -19.261],    
			[-5329.517, -1447.345, -24.696],    
			[-5326.888, -1418.470, -28.292],    
			[-5314.236, -1409.443, -25.153],    
			[-5299.901, -1426.098, -24.817],    
			[-5283.432, -1436.255, -31.473],    
			[-5300.718, -1456.454, -27.412],    
			[-5296.737, -1458.687, -15.578],    
			[-5283.220, -1455.521, -26.294],    
			[-5302.129, -1475.268, -28.958],
		];

		for(let i = 0; i < positions.length; i++){
			const cp = animation.createControlPoint();

			cp.position.set(...positions[i]);
			cp.target.set(...targets[i]);
		}

		viewer.scene.addCameraAnimation(animation);


	</script>

	
  </body>
</html>`


And this is the .json5:
`{
	type: 'Potree',
	version: 1.7,
	settings: {
		pointBudget: 3000000,
		fov: 60,
		edlEnabled: true,
		edlRadius: 1.4,
		edlStrength: 0.4,
		background: 'gradient',
		minNodeSize: 0,
		showBoundingBoxes: false,
	},
	view: {
		position: [
			-5287.281695530408,
			-1426.1999899604946,
			-27.384510002869696,
		],
		target: [
			-5300.952339751534,
			-1432.418988527208,
			-37.669923311144245,
		],
	},
	classification: {
		'0': {
			visible: true,
			name: 'never classified',
			color: [
				0.5,
				0.5,
				0.5,
				1,
			],
		},
		'1': {
			visible: true,
			name: 'unclassified',
			color: [
				0.5,
				0.5,
				0.5,
				1,
			],
		},
		'2': {
			visible: true,
			name: 'ground',
			color: [
				0.63,
				0.32,
				0.18,
				1,
			],
		},
		'3': {
			visible: true,
			name: 'low vegetation',
			color: [
				0,
				1,
				0,
				1,
			],
		},
		'4': {
			visible: true,
			name: 'medium vegetation',
			color: [
				0,
				0.8,
				0,
				1,
			],
		},
		'5': {
			visible: true,
			name: 'high vegetation',
			color: [
				0,
				0.6,
				0,
				1,
			],
		},
		'6': {
			visible: true,
			name: 'building',
			color: [
				1,
				0.66,
				0,
				1,
			],
		},
		'7': {
			visible: true,
			name: 'low point(noise)',
			color: [
				1,
				0,
				1,
				1,
			],
		},
		'8': {
			visible: true,
			name: 'key-point',
			color: [
				1,
				0,
				0,
				1,
			],
		},
		'9': {
			visible: true,
			name: 'water',
			color: [
				0,
				0,
				1,
				1,
			],
		},
		'12': {
			visible: true,
			name: 'overlap',
			color: [
				1,
				1,
				0,
				1,
			],
		},
		DEFAULT: {
			visible: true,
			name: 'default',
			color: [
				0.3,
				0.6,
				0.6,
				0.5,
			],
		},
	},
	pointclouds: [
		{
			name: 'arco_converted',
			url: 'C:\\Users\******\*******\*************\******************\arco_converted/metadata.json',
			position: [
				-5447.088,
				-1630.6200000000001,
				-32.611000000000004,
			],
			rotation: [
				0,
				0,
				0,
				'XYZ',
			],
			scale: [
				1,
				1,
				1,
			],
			material: {
				activeAttributeName: 'intensity gradient',
				ranges: [
					{
						name: 'elevationRange',
						value: [
							-32.61,
							10.575000000000001,
						],
					},
					{
						name: 'intensityRange',
						value: [
							0,
							65535,
						],
					},
				],
				size: 1,
				minSize: 2,
				pointSizeType: 'ADAPTIVE',
				matcap: 'matcap.jpg',
			},
		},
	],
	measurements: [],
	volumes: [],
	cameraAnimations: [
		{
			uuid: '6F7EA4DF-D71A-4A82-9647-8EB68B078DF1',
			name: 'Camera_Animation',
			duration: 5,
			t: 0,
			curveType: 'centripetal',
			visible: true,
			controlPoints: [
				{
					position: [-5386.137, -1541.951, -4.547,],
					target: [-5373.838, -1503.886, -18.257,],
				},
				{
					position: [-5381.322, -1532.432, -7.817,],
					target: [-5386.652, -1491.149, -15.261,],
				},
				{
					position: [-5386.652, -1491.149, -15.261,],
					target: [-5347.215, -1501.865, -7.184,],
				},
				{
					position: [-5372.912, -1521.576, -8.922,],
					target: [-5379.298, -1491.422, -8.443,],
				},
				{
					position: [-5373.849, -1509.892, -8.320,],
					target: [-5366.423, -1479.982, -9.045,],
				},
				{
					position: [-5364.985, -1497.690, -9.879,],
					target: [-5343.394, -1476.657, -16.343,],
				},
				{
					position: [-5358.245, -1492.310, -12.301,],
					target: [-5362.241, -1465.756, -27.442,],
				},{
					position: [-5360.269, -1487.985, -14.007,],
					target: [-5366.327, -1460.989, -27.602,],
				},{
					position: [-5370.428, -1493.837, -9.681,],
					target: [-5370.428, -1493.837, -9.681,],
				},{
					position: [-5378.058, -1495.782, -10.179,
					],
					target: [-5403.585, -1511.933, -16.330,
					],
				},{
					position: [-5385.080, -1501.522, -12.201,
					],
					target: [-5383.877, -1532.192, -15.066,
					],
				},{
					position: [-5390.741, -1503.457, -12.957,
					],
					target: [-5421.408, -1505.252, -15.533,
					],
				},{
					position: [-5394.033, -1503.221, -13.235,
					],
					target: [-5406.925, -1475.256, -11.797,
					],
				},{
					position: [-5396.585, -1498.678, -13.141,
					],
					target: [-5387.884, -1469.139, -11.703,
					],
				},{
					position: [-5401.578, -1491.968, -13.405,
					],
					target: [-5398.287, -1461.666, -18.016,
					],
				},{
					position: [-5400.070, -1482.858, -14.535,
					],
					target: [-5378.296, -1461.037, -14.268,
					],
				},{
					position: [-5392.990, -1477.482, -14.781,
					],
					target: [-5411.573, -1452.899, -15.597,
					],
				},{
					position: [-5396.171, -1468.597, -15.375,
					],
					target: [-5418.363, -1447.377, -18.125,
					],
				},{
					position: [-5390.915, -1463.146, -14.828,
					],
					target: [-5360.108, -1463.832, -13.949,
					],
				},{
					position: [-5381.338, -1463.183, -15.490,
					],
					target: [-5358.758, -1442.414, -18.502,
					],
				},{
					position: [-5375.655, -1458.082, -17.210,
					],
					target: [-5348.838, -1472.861, -13.646,
					],
				},{
					position: [-5371.888, -1460.356, -16.768,
					],
					target: [-5352.320, -1436.631, -14.643,
					],
				},{
					position: [-5368.672, -1456.113, -16.382,
					],
					target: [-5341.531, -1470.290, -12.818,
					],
				},{
					position: [-5359.420, -1460.692, -16.984,
					],
					target: [-5351.202, -1431.254, -21.005,
					],
				},{
					position: [-5349.065, -1462.068, -20.263,
					],
					target: [-5318.455, -1463.541, -23.607,
					],
				},{
					position: [-5337.792, -1468.267, -20.353,
					],
					target: [-5307.072, -1469.658, -22.505,
					],
				},{
					position: [-5349.065, -1462.068, -20.263,
					],
					target: [-5318.455, -1463.541, -23.607,
					],
				},{
					position: [-5358.442, -1449.051, -19.820,
					],
					target: [-5388.984, -1446.118, -16.833,
					],
				},{
					position: [-5363.113, -1449.507, -19.352,
					],
					target: [-5357.459, -1420.118, -11.963,
					],
				},{
					position: [-5361.287, -1443.656, -18.385,
					],
					target: [-5348.887, -1415.481, -16.750,
					],
				},{
					position: [-5358.340, -1435.900, -18.179,
					],
					target: [-5375.842, -1412.036, -26.811,
					],
				},{
					position: [-5358.123, -1431.002, -20.009,
					],
					target: [-5327.396, -1433.370, -19.261,
					],
				},{
					position: [-5355.364, -1431.232, -19.942,
					],
					target: [-5329.517, -1447.345, -24.696,
					],
				},{
					position: [-5352.138, -1434.454, -20.729,
					],
					target: [-5326.888, -1418.470, -28.292,
					],
				},{
					position: [-5339.953, -1426.401, -23.988,
					],
					target: [-5314.236, -1409.443, -25.153,
					],
				},{
					position: [-5329.888, -1419.001, -23.984,
					],
					target: [-5299.901, -1426.098, -24.817,
					],
				},{
					position: [-5311.916, -1426.287, -25.180,
					],
					target: [-5283.432, -1436.255, -31.473,
					],
				},{
					position: [-5309.542, -1426.962, -25.779,
					],
					target: [-5300.718, -1456.454, -27.412,
					],
				},{
					position: [-5310.066, -1432.313, -24.355,
					],
					target: [-5296.737, -1458.687, -15.578,
					],
				},{
					position: [-5307.985, -1437.347, -23.707,
					],
					target: [-5283.220, -1455.521, -26.294,
					],
				},{
					position: [-5301.255, -1444.584, -26.116,
					],
					target: [-5302.129, -1475.268, -28.958,
					],
				},
			],
		},
	],
	profiles: [],
	annotations: [
		{
			uuid: 'C7043B48-3F5D-4F52-A8E4-862EA7C569A8',
			title: 'Annotation Title',
			description: 'Annotation Description',
			position: [
				-5358.593001617432,
				-1454.878000114441,
				-18.560000358581547,
			],
			offset: [
				0,
				0,
				0,
			],
			children: [],
		},
	],
	orientedImages: [],
	geopackages: [],
}`

Somebody had loaded a prexisting file with the camera animation?

**Comment by HeadLessHUN** [comment]
hi!

based on your description your issue is that you added the camera path loading before a pointcloud loaded. 
I think you should put your codes inside the pointcloud loaded callback.

i already loaded back json5 projects with camera paths.
you can load projects by

`viewer.loadProject("path_to_json.json5")`

**Comment by Alfonsso786** [comment]
Hello, 
Finally I tried with viewer.loadProject("path_to_json.json5") and it worked, lot of thanks.
