### ISSUE TITLE
Map Projection

### ISSUE THREAD

**Issue by smcavoy12** [potree/potree#957]
I've got a HUGE pointcloud of the Spanish province of Catalonia
https://pointcloud.ucsd.edu/Catalonia_Spain.html

Have the projection set as I have in other projects 
`"projection": "+proj=utm +zone=31 +ellps=GRS80 +datum=NAD83 +units=m +no_defs",`

but it's just not showing up. I'm wondering if I broke the projection by having more points outside of the UTM 31 zone, see them here:
![catalonia](https://user-images.githubusercontent.com/13354749/105109433-6196a900-5a71-11eb-957a-d25e3a4516f5.PNG)

Does that sound like a reason it might break? Is there a way enable the map overlay, or do I need to rerun it without this section from another UTM zone?

Thanks!
-Scott

**Comment by potree** [comment]
Hi Scott,

"projection" is set twice, and the second time it overrides it to "":

```
	"projection": "+proj=utm +zone=31 +ellps=GRS80 +datum=NAD83 +units=m +no_defs",
	"points": 37658130283,
	"projection": "",
```

**Comment by smcavoy12** [comment]
Ooph! Thankyou, absolutely right, that fixed it.

**Comment by JiahaoXia** [comment]
Hi, where can i set projection information for the point cloud data?
