### ISSUE TITLE
Two or more textures

### ISSUE THREAD

**Issue by pawellm96** [potree/potree#958]
Hello everyone! Help my please add several textures to one .obj model. I loaded the model itself perfectly, added one texture as in the examples. But I have no idea how to add at least 2 textures. There are files in .obj, .mtl format and a folder with textures .jpg

**Comment by m-schuetz** [comment]
Hi,

This is more of a three.js question since mesh rendering is done using three.js. Try checking the three.js examples: https://threejs.org/examples/?q=obj

**Comment by SBCV** [comment]
See https://github.com/potree/potree/issues/1167
