### ISSUE TITLE
How to convert value from preciseBuffer to value from arrayBuffer?

### ISSUE THREAD

**Issue by bmichalowski** [potree/potree#966]
Hi,

I have a pointcloud with gps-time.
After clicking on the point, I read the gps value (e.g. 174100 - like other preciseBuffer). Then I create a Profile that passes through this area.
My goal is to get all points with the same gps-time as the point you clicked.

However, ProfileWindow.addPoints gets points as `Float32Array` and they are <1, for example 0.5082387924194336
0.5081834197044373
0.5088375806808472

I thought it was calculated as:
arrayBufforValue = (preciseValue - rangeMin) / rangeMax

I checked for both range and initialRange.
Unfortunately, they don't get exactly the same value as in array. After calculating, in addition to looking for the calculated value, I also measured the difference between the values. The smallest difference is 0.0010439721691332116.

What is missing from this formula or my way of reasoning?
![image](https://user-images.githubusercontent.com/3858803/106010740-15bfb180-60ba-11eb-9745-c51c0f39eff1.png)

**Comment by m-schuetz** [comment]
Hi, which version are you using? I believe that was fixed at some point, could you give it a try with the latest PotreeDesktop 1.8 or Potree 1.8? https://github.com/potree/PotreeDesktop/releases/tag/1.8

**Comment by bmichalowski** [comment]
I'm using 1.7.

In fact, since the calculation is based on floating point, error could be the result of the precision of rounding in JS.

My mistake, it's been a long day;)

So I try the other way and it looks like it works.
Currently, I only have access to the values from the screen shoot. I'll check it out tomorrow for the entire collection.

// From array to preciseValue:
var arrayValue = array [1]; // 0.00005207197682466358
var preciseValue = (arrayValue * range [1]) + range (0) // 21901.05707142793
var roundedValue = Math.round (preciseValue / 100) * 100 // 21900

**Comment by bmichalowski** [comment]
I create a `Profile` to get points from the selected area.
I am in the `ProfileWindow.addPoints` function, where I have access to `data` from a given request and to the `pointcloud` itself.

I have values from `Float32Array`, but I am looking for a value from `preciseBuffer`.
How to calculate them?

The following method works only for initial values:

> preciseValue = (arrayValue * rangeMax) + rangeMin;

![image](https://user-images.githubusercontent.com/3858803/106114632-1014ab00-6150-11eb-92e6-99814b732287.png)


Here on higher values

![potree_gps_time_range](https://user-images.githubusercontent.com/3858803/106109504-e789b280-6149-11eb-8b97-e50ab1033bc9.png)

I found another formula in the shader:
> time = (gpsTime + uGpsOffset) * uGpsScale

but with that:
![image](https://user-images.githubusercontent.com/3858803/106113999-5cabb680-614f-11eb-8c6d-fc993e63c5bb.png)
I got values like 
0.00048003072760330334 instead of 30300, so probably not what i'm looking for.

**Comment by bmichalowski** [comment]
To get a precise value:
`value = value * (initialRange [1] - initialRange [0]) + initialRange [0]`

This mechanism is in PointCloudOctree. ProfileWindow uses ProfileFakeOctree.

Therefore, we do not have exact values for GPS_TIME.
![image](https://user-images.githubusercontent.com/3858803/107039029-ac2c5b00-67bd-11eb-9e94-33e67651b0dc.png)

PR will be appreciated
