### ISSUE TITLE
Example 'multiple_pointclouds' missing name values in sidebar

### ISSUE THREAD

**Issue by marckassay** [potree/potree#972]
If the string value set on this line:
https://github.com/potree/potree/blob/c4ecc8c02adb8b711ba01d04246ef97b5a5a375f/examples/multiple_pointclouds.html#L80

... is used to set the values of items under Point Clouds section of sidebar, than it seems to be not working as seen here:
![image](https://user-images.githubusercontent.com/459665/107360756-5d740f00-6aa4-11eb-90e2-01c2777ec2da.png)

**Comment by mikepianka** [comment]
This works in Potree 1.7. Recent commits must have broken it.

**Comment by marckassay** [comment]
@monodo posted a while back demonstrating a successful multi load here: https://github.com/potree/potree/issues/226#issuecomment-225788349

Below is a condensed version of JS from that link, for anyone who is interested:
```javascript
		window.viewer = new Potree.Viewer(document.getElementById("potree_render_area"));
		
		viewer.setEDLEnabled(true);
		viewer.setFOV(60);
		viewer.setPointBudget(7*1000*1000);
		viewer.loadSettingsFromURL();
		
		viewer.setDescription("");
		
		viewer.loadGUI(() => {
			viewer.setLanguage('fr');
			$("#menu_scene").next().show();
			viewer.toggleSidebar();
		});

		async function loadDatasets(){

			let scene = viewer.scene;

			{
				let result = await Potree.loadPointCloud("https://sitn.ne.ch/lidar/potree_data/clouds/2016/pointclouds/lidar2016_14levels/cloud.js");
				let pointcloud = result.pointcloud;
				let material = pointcloud.material;

				pointcloud.name = "SITN LiDAR 2016";
				material.size = 1.5;
				material.pointSizeType = Potree.PointSizeType.FIXED;
				material.shape = Potree.PointShape.CIRCLE;
				scene.addPointCloud(pointcloud);
				viewer.fitToScreen();
				pointcloud.visible = false;
			}
		        // omitted repetitive anonymous blocks
			{
				let result = await Potree.loadPointCloud("https://sitn.ne.ch/lidar/pointclouds/aerial/2010/metadata.json");
				let pointcloud = result.pointcloud;
				let material = pointcloud.material;

				pointcloud.name = "SITN LiDAR 2010";
				material.size = 1.5;
				material.pointSizeType = Potree.PointSizeType.FIXED;
				material.activeAttributeName = "rgba";
				material.shape = Potree.PointShape.CIRCLE;
				scene.addPointCloud(pointcloud);
				viewer.fitToScreen();
				pointcloud.visible = false;
			}

		};

		loadDatasets();
```

**Comment by mikepianka** [comment]
I think the `pointcloud.name` syntax should still be fine. If you inspect the pointcloud objects in the scene, the name attribute is being assigned. I think it's a problem with the sidebar. 

![image](https://user-images.githubusercontent.com/47948499/107699720-79cea200-6c84-11eb-9bed-e2445d676726.png)

**Comment by m-schuetz** [comment]
Might be some sort of "race condition". Sometimes the names show up, sometimes they don't. I guess they show up if the GUI is initialized after the points are added to the scene. The GUI basically doesn't register if you change pointcloud.name.

**Comment by m-schuetz** [comment]
As a workaround, you can try to set the name of the pointcloud before adding it to the scene. In the case of multiple_pointclouds.html, you'd simply have to do the callback, which sets the name, before calling addPointCloud:

Change this:

```
viewer.scene.addPointCloud(pointcloud);
pointclouds[i].callback(pointcloud);
```

to this:

```
pointclouds[i].callback(pointcloud);
viewer.scene.addPointCloud(pointcloud);
```

Seems to work for me, but hard to say for certain since it also ocasionally worked before.
