### ISSUE TITLE
THREE.PlaneGeometry transparency rendering issue

### ISSUE THREAD

**Issue by cojeffj** [potree/potree#985]
I'm playing with threejs planes and they render, but there's an issue when transparency is set:
```javascript
let material = new THREE.MeshBasicMaterial( {color: 0xff2b2b, transparent:true,opacity: .5} );
```
The plane renders fine, and transparency works - but the transparency looks "through" the point cloud - but sees the cesium layer behind it. Is this something that can be fixed by changing the order that elements are rendered? Right now the plane is being rendered inside the function that is passed as an argument to Potree.loadPointCloud(), so I believe that will cause the plane to be rendered before the point cloud - but I'm not sure how to render them in reverse. I'll keep playing with it an will post an update if I find a solution.
![potree_NDVI_plane](https://user-images.githubusercontent.com/70295778/109175186-2875e680-774b-11eb-89cf-7590944d0424.png)

**Comment by cojeffj** [comment]
Fixed the issue. Disabling EDL takes care of the problem.

**Comment by JiahaoXia** [comment]
Hi, I am also working on adding planes to loaded point cloud space, the plane has the same Z value.
```js
window.viewer = new Potree.Viewer(document.getElementById("potree_render_area"));
let scene = viewer.scene;
const geometry = new THREE.PlaneGeometry( 100, 100 );
const material = new THREE.MeshBasicMaterial( {color: 0xffff00, side: THREE.DoubleSide} );
const plane = new THREE.Mesh( geometry, material );
scene.add(plane);
```
I have the error: "TypeError: scene.add is not a function", could you please give some suggestions?
