### ISSUE TITLE
animation

### ISSUE THREAD

**Issue by niallrobinson** [potree/potree#99]
Hi Potree people - I've just been exploring this and it seems like a great tool.

I'm really interested in trying to develop animation capabilities for Potree.
1. Has this been done
2. Do you think it would be possible
3. Can you give me any tips on where to start

Thanks
Niall

**Comment by m-schuetz** [comment]
Hello Niall!

There is no animation in potree, yet. What kind of animation do you have in mind? 
Different point clouds at different points in time?

**Comment by jo-chemla** [comment]
I think he meant being able to define a path for the camera to follow. Maybe an easy way to add keyframes, and then launch the animation - and store it for later use - would be feasible. 
I know you can use `viewer.annotations[0].moveHere(viewer.camera);` to move your camera. @niallrobinson  maybe you can just try to set several annotations as keyframes, and then call these methods - no control onduration between keyframes though.

**Comment by m-schuetz** [comment]
Could be, let's continue this in #281 then.
