### ISSUE TITLE
Measuring bug in Chrome 89.0.4389.72

### ISSUE THREAD

**Issue by runetvilum** [potree/potree#991]
After updating to Chome 89.0.4389.72 the measuring tools are not working.
Trying to measure distance or height will only add one marker and then stops the measuring.

**Comment by midnight-dev** [comment]
Are there any console warnings or errors? Have you checked if measurements still work as expected under Chrome 88 or current stable/beta versions of Firefox?

**Comment by runetvilum** [comment]
There are no console warnings or errors. Measurements works in current
Firefox and Chrome 88

Den 3. mar. 2021 kl. 17.09 skrev Ben Arnett <notifications@github.com>:

﻿

Are there any console warnings or errors? Have you checked if measurements
still work as expected under Chrome 88 or current stable/beta versions of
Firefox?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/potree/potree/issues/991#issuecomment-789828237>, or
unsubscribe

**Comment by krooole** [comment]
I am facing the same issue, and it also affects other tools that require more than one point (distance, height)

Found a difference between Chrome 89 and Firefox that may provide a clue:
Enable logging in InputHandler through console
`viewer.inputHandler.logMessages= true
`
Activate measuring tool and place the cursor somewhere to start the profile
You will get a sequence of multiple console messages 
```
InputHandler: drag: 
InputHandler: onMouseMove; hovered: ''
```
Click to select the starting point for the profile. You will get
```
InputHandler: onMouseDown
InputHandler: startDragging: ''
InputHandler: onMouseUp
InputHandler: drop 
InputHandler: onMouseClick
```
So far, this is the same in both Firefox and Chrome 89

However, in Chrome, additional events are shown 
```
InputHandler: onMouseMove; hovered: ', '
InputHandler: mouseleave:
```
Which do not show up in Firefox
After that point, chrome stops "expecting" a second point, whereas Firefox keeps registering new sequences of
```
InputHandler: onMouseMove; hovered: ', ' 
InputHandler: drag: 
```
as you move the cursor to place the second point

**Comment by Nevernat** [comment]
maybe the sequence of events in chrome has changed.

Firefox
```
InputHandler: onMouseDown
InputHandler: onMouseUp 
InputHandler: drop
InputHandler: click
InputHandler: startDragging:
InputHandler: onMouseClick
```

Chrome:
```
InputHandler: onMouseDown
InputHandler: startDragging: ''
InputHandler: onMouseUp
InputHandler: drop 
InputHandler: onMouseClick
```

now the drag object to the InputHandler is not assigned correctly?

**Comment by Nevernat** [comment]
My proposal to solve the problem:
in ProfileTool.js and MeasuringTool.js replace every:
```
domElement.addEventListener('mouseup', insertionCallback, true);
domElement.removeEventListener('mouseup', insertionCallback, true);

```
with:
```
domElement.addEventListener('mouseup', insertionCallback, false);
domElement.removeEventListener('mouseup', insertionCallback, false);

```
in my tests it seems to work

**Comment by runetvilum** [comment]
@Nevernat perfect, this solves my problems

**Comment by krooole** [comment]
Works for me as well, in both Chrome 89 and Firefox. 
Thanks @Nevernat !

**Comment by midnight-dev** [comment]
Good diagnosis, @Nevernat @krooole 

However, I wonder why the capture option was set to `true` to begin with. If there are no side effects in event bubbling, then I guess it doesn't matter. Anyway, `false` is the default, so the `false` at the end of add/remove methods _shouldn't_ be necessary.

**Comment by m-schuetz** [comment]
@Nevernat  Thanks! I'll just need to figure out why the third parameter was set to false before applying the fix. There probably was a reason, like avoiding conflicts with other events.

**Comment by joskojaksic** [comment]
Hi everyone, I'm new to Potree and I've uploaded my point cloud on web and have trouble finding files where to replace the code. I'm sorry, I'm not a programmer and I'm not really familiar how everything works. I've made the changes in potree.js.map which seems to create "src" directory. I believe that problem is in potree.js located in libs\potree that is created again after refreshing the web page so manual changing the code doesn't work. Can someone please tell me where to change the code for measurement tool to work on web?

**Comment by midnight-dev** [comment]
@joskojaksic You don't want to modify a _.map_ file because that's a generated file based on the exact code structure of all the separate JavaScript files which are combined to form the final, built JavaScript. It's something that the browser uses to map concatenated or minified code to the original source.

What you should do is modify a couple of lines in two source files as described above. These two files are both located in `src/utils/` - one for the measuring tools, and one for the profile tool. You need to modify the lines referenced above, which appear around line 90 in both files. One line adds an event listener, another removes it. Just need to change the _true_ to _false_ in those 4 places. 

After that is done, rebuild the Potree.js file by running `npm run build`.

I'm assuming that the author will merge this change into the repo after he checks that this doesn't have negative consequences. So you may not need to make the changes yourself if you don't need to use the measure tools immediately. Alternatively, just use Firefox or the previous version of Chrome in the meantime since it seems to only malfunction in Chrome 89 and above.

**Comment by mriedo** [comment]
these 2 lines correct the problem with the measures
domElement.addEventListener('mouseup', insertionCallback, false);
domElement.removeEventListener('mouseup', insertionCallback, false);

You still need to change these two additional lines to get the profile to work

			cancel.callback = e => {
				profile.removeMarker(profile.points.length - 1);

domElement.removeEventListener('mouseup', insertionCallback, **false**);
domElement.addEventListener('mouseup', insertionCallback, **false**);

**Comment by joskojaksic** [comment]
@midnight-dev Thanks for the answer and help. This solves it.

**Comment by robosinghai** [comment]
All - thank you for the suggestion above. Managed to fix this!

**Comment by Gerardg8** [comment]
Hello

Don't get the problem solved.
In existing potree projects I cannot find the ProfileTool.js and MeasuringTool.js.
Made projects with PotreeConverter version 1.6 or 1.8.

**Comment by midnight-dev** [comment]
@Gerardg8 That's due to the already-built version being used in the converter template.

You'll have to try to find the relevant location in the large _potree.js_ file that's somewhere in the _libs_ directory. Thankfully, the project uses many small classes, so you should be able to easily confirm the proper locations match up to the measuring & profile tools. 

Alternatively, if you make the changes in the source files in this main repo, you can build a new _potree.js_ file & replace the one in the converter libs with it. Some forks may already have a correctly built file that you can download.

**Comment by Solsviken** [comment]
Have this error resurfaced again ? 
The above fix, doesnt seem to work in edge/chrome lastest version anymore. Opera is no problem.

**Comment by mriedo** [comment]
On my side, with last Chrome version, measuring and profile still works  
Version 90.0.4430.212 (Build officiel) (64 bits) Google Chrome est à jour

**Comment by mriedo** [comment]
You can test here [Street Lidar Vevey](https://www.cartoriviera.ch/3d/rues_vevey_2020/) and [Lidar SITN](https://sitn.ne.ch/lidar)

**Comment by Solsviken** [comment]
Definitly something wrong on my end. Suddenly it worked. Sorry for the trouble

**Comment by VerenaV** [comment]
I have a problem with the annotation tag where I cannot change the default annotation title nor the description. The problem is in Chrome + FF. Am I missing here?

**Comment by bblammo** [comment]
> After updating to Chome 89.0.4389.72 the measuring tools are not working.
> Trying to measure distance or height will only add one marker and then stops the measuring.

This one seems to be back with Chrome Version 91.0.4472.114, Anything requiring more than one point, Measure, Profile maker, only the first point is recorded, and also used in subsequent picks.  Works in FireFox 89.X.  Marker locations are listed out in the side menu, but only the first point is displayed in the 3D model space . . .

**Comment by bblammo** [comment]
> > After updating to Chome 89.0.4389.72 the measuring tools are not working.
> > Trying to measure distance or height will only add one marker and then stops the measuring.
> 
> This one seems to be back with Chrome Version 91.0.4472.114, Anything requiring more than one point, Measure, Profile maker, only the first point is recorded, and also used in subsequent picks. Works in FireFox 89.X. 

Marker locations are listed out in the side menu, but only the first point is displayed in the 3D model space . . .

Same thin in Edge Version 91.0.864.59 . . .

**Comment by VerenaV** [comment]
@bblammo 
I can confirm that it works in FireFox 89.X.

**Comment by tmvtool** [comment]
> @joskojaksic You don't want to modify a _.map_ file because that's a generated file based on the exact code structure of all the separate JavaScript files which are combined to form the final, built JavaScript. It's something that the browser uses to map concatenated or minified code to the original source.
> 
> What you should do is modify a couple of lines in two source files as described above. These two files are both located in `src/utils/` - one for the measuring tools, and one for the profile tool. You need to modify the lines referenced above, which appear around line 90 in both files. One line adds an event listener, another removes it. Just need to change the _true_ to _false_ in those 4 places.
> 
> After that is done, rebuild the Potree.js file by running `npm run build`.
> 
> I'm assuming that the author will merge this change into the repo after he checks that this doesn't have negative consequences. So you may not need to make the changes yourself if you don't need to use the measure tools immediately. Alternatively, just use Firefox or the previous version of Chrome in the meantime since it seems to only malfunction in Chrome 89 and above.



> @joskojaksic You don't want to modify a _.map_ file because that's a generated file based on the exact code structure of all the separate JavaScript files which are combined to form the final, built JavaScript. It's something that the browser uses to map concatenated or minified code to the original source.
> 
> What you should do is modify a couple of lines in two source files as described above. These two files are both located in `src/utils/` - one for the measuring tools, and one for the profile tool. You need to modify the lines referenced above, which appear around line 90 in both files. One line adds an event listener, another removes it. Just need to change the _true_ to _false_ in those 4 places.
> 
> After that is done, rebuild the Potree.js file by running `npm run build`.
> 
> I'm assuming that the author will merge this change into the repo after he checks that this doesn't have negative consequences. So you may not need to make the changes yourself if you don't need to use the measure tools immediately. Alternatively, just use Firefox or the previous version of Chrome in the meantime since it seems to only malfunction in Chrome 89 and above.

i applied the modifications in these two file Measuring tool.js and Profile.js but didn't solve the problem.
I needed to apply these changes into the potree.js and now it works. My question is : how to run the command npm on my server to do a npm run build and what is the goal to run this command ? Do i need to install node .js on my server ? My potree app is deploy on a server with a xampp web server. Thanks for the help

**Comment by midnight-dev** [comment]
@tmvtool If you modified your potree.js file directly, then you don't need to do anything more. Running the npm build task just combines everything together (which is needed if you only make changes to the small, individual files). If you don't plan on making further changes, you don't need to worry about npm or node, as it only applies to development work. Potree works completely with or without node.

**Comment by tmvtool** [comment]
> @tmvtool If you modified your potree.js file directly, then you don't need to do anything more. Running the npm build task just combines everything together (which is needed if you only make changes to the small, individual files). If you don't plan on making further changes, you don't need to worry about npm or node, as it only applies to development work. Potree works completely with or without node.

Thanks a lot for your answer. So what is the step to install node.js on my server and run npm build ?

**Comment by midnight-dev** [comment]
@tmvtool You'll have to lookup the exact details on https://nodejs.org as some systems need to have a node repo added to their sources. For Windows and Mac, just download and install the binary installer. Again, you don't need this on your server if you aren't going to be *developing* potree on your server. It's a pretty small package when built, so it's quicker for me to code changes & build locally, then send the JS to a server when I have everything finalized. No node is used on servers.

**Comment by BigEyePuna** [comment]
Same problem exists using Brave. The measurement tools work in potree desktop but after running the potree converter and viewing in my local host webserver the measurement tools do not work. Is there a newer/alternative fix than what was suggested a couple years ago (changing the code to "false" instead of "true" in those two lines of code)?
