### ISSUE TITLE
Measuring tools not working on the latest Chrome version

### ISSUE THREAD

**Issue by jmdollosa** [potree/potree#996]
Chrome version: **Version 89.0.4389.82 (Official Build) (x86_64)**
Operating System: **Mac OSX Big Sur**
Potree version: **1.7.1**

Hi, I tried playing around with the Measuring tools today and it seems the Area tool doesn't work. The other points doesn't display when I click around the pointcloud.

Tried the online demo but it's the same.

![image](https://user-images.githubusercontent.com/43800694/110575713-3563e400-8114-11eb-8644-da57a6a44d2d.png)

**Comment by m-schuetz** [comment]
Duplicate of: #991
Proposed solution: https://github.com/potree/potree/issues/991#issuecomment-790531335
Pull Request with proposed solution: #992

**Comment by jmdollosa** [comment]
Closing this issue now as the solution worked. Thank you @m-schuetz
