### ISSUE TITLE
measuring tool issue

### ISSUE THREAD

**Issue by coupster74** [potree/potree#997]
in MeasuringTool.js, there is an issue on line 261:

```
updateAzimuth(viewer, measure);
```

results in an exception as viewer undefined. This needs to be updated to 

```
updateAzimuth(this.viewer, measure);
```

**Comment by midnight-dev** [comment]
In the latest version? I see on line 262 that the correct object is passed in.

**Comment by mikepianka** [comment]
Make sure you are using the latest version, this was fixed in January with https://github.com/potree/potree/pull/952:

https://github.com/potree/potree/blob/37dc46a25ca56683e216c973dd117bc68b75ab0f/src/utils/MeasuringTool.js#L262

**Comment by boxel0** [comment]
Sorry am I being silly cause I search for MeasuringTool.js and there is no file found?
